src/readFromStore.ts
src/watchedQueries.ts
test/tests.ts
test/watchedQueries.ts
typings.json

This is a class that takes a set of queries and a store, and broadcasts the results to all of the queries.

Query watching class

---

src/QueryManager.ts
src/store.ts
test/QueryManager.ts

Until now we've been faking it in all of the tests

Implement the actual store

---

package.json

This removes the duplicated lodash deps

remove duplicate lodash

---

src/storeUtils.ts

We now define ScalarValue as an union type of all the acceptable scalar types.

Better type usage for scalar values

---

.npmignore

Include test directory through npm to make installing easier

---

src/diffAgainstStore.ts
src/writeToStore.ts
test/readFromStore.ts
test/writeToStore.ts

This includes adjustments for writing null values in lists to the store, and also reading them back out (per discussion in #68).

Store support for null values in a list

---

src/middleware.ts
src/networkInterface.ts
test/middleware.ts
test/networkInterface.ts
test/tests.ts

So this PR has two parts, sorry about that. I can break it apart if you like.
1) Adds support for middleware in general.
2) Adds a middleware for including token headers.
Thanks!

Middleware

---

.travis.yml
src/index.ts
test/client.ts

Fixes #82 
It turns out the only real change was making ApolloClient a default export!

Breaking changes

---

package.json
test/networkInterface.ts
test/tests.ts

Mock fetch() in tests to use local SWAPI API

---

src/index.ts

export usable parts of the library

---

src/QueryManager.ts
src/actions.ts
src/index.ts
src/store.ts
test/client.ts

Instead of passing the store in the constructor. Still need to figure out what to do about tests that pass a store directly into `NetworkInterface`.
Fixes #102

Integrate with Redux via middleware

---

test/QueryManager.ts
test/client.ts
test/mocks/mockNetworkInterface.ts

From Martijn: improve network interface mocking

---

.npmignore
CHANGELOG.md

Ignore a bunch of stuff from NPM

---

src/data/resultUtils.ts
src/data/store.ts
src/data/storeUtils.ts
src/data/writeToStore.ts
src/queries/store.ts

Minor refactor

---

CHANGELOG.md
src/data/diffAgainstStore.ts
src/queryPrinting.ts
test/QueryManager.ts
test/diffAgainstStore.ts

Fixes:
1. https://github.com/apollostack/react-apollo/issues/45
2. #184 
TODO:
@mattiasewers this is the fix about your issue, should be done soon!

Make sure diffing and printing works with multiple root queries

---

CHANGELOG.md
src/QueryManager.ts
src/data/readFromStore.ts
test/QueryManager.ts

Fix returnPartialData

---

CHANGELOG.md
src/data/storeUtils.ts

Suggest workaround of using variables for non-scalar arguments

---

CHANGELOG.md
src/data/writeToStore.ts
test/roundtrip.ts

GraphQLJSON scalar value support

---

gql.js

Drop gql.js into the root and reference to lib so people can npm link without crying

---

README.md

Add payload size to the readme

---

CHANGELOG.md
package.json
src/networkInterface.ts

add whatwg-fetch to fix promise problems that occurs in special browser (eg. Wechat browser in China )

---

CHANGELOG.md
package.json

prepare version 0.3.13 for publishing

---

CHANGELOG.md
package.json

Bump version to 0.3.16

---

src/index.ts
test/scheduler.ts~

Added the `shouldBatch` option to `ApolloClient` so that people can actually use the batching.
TODO:

Removed a useless file and added the shouldBatch option to ApolloClient

---

CHANGELOG.md
package.json

Prepare 0.3.18

---

README.md

Improve NPM badge

---

CHANGELOG.md
src/index.ts
src/networkInterface.ts

- Export `addTypenameToSelectionSet` as `addTypename`
- Network interfaces created with `createNetworkInterface` support batching by default
TODO:

Streamline API

---

CHANGELOG.md
package.json

Bump version for 0.3.20

---

CHANGELOG.md
gql.js
package.json
scripts/deploy.sh

Fixes #327 
(Already published to npm as 0.3.24)
TODO:

Fix apollo-client/gql import

---

CHANGELOG.md
gql.js

Deprecation warning

---

CHANGELOG.md
src/index.ts
test/client.ts

Don't mutate options

---

CHANGELOG.md
package.json

Published 0.3.25

---

CHANGELOG.md
package.json

To fix https://github.com/apollostack/apollo-client/issues/346
TODO:

Bump version to 0.3.26

---

package.json
scripts/dev.sh
scripts/test_and_lint.sh

Add npm run dev command that watches files and runs tests

---

CHANGELOG.md
package.json

Bump version to 0.3.28

---

.vscode/launch.json

Makes it a bit easier to manage :)

Don't time out tests when a debugger is attached

---

CHANGELOG.md
package.json

TODO:
Probably last version before 0.4

Bump version to 0.3.30

---

src/QueryManager.ts
src/actions.ts
src/mutations/store.ts

Adds a missed action that is dispatched when a mutation errors.

Add action APOLLO_MUTATION_ERROR

---

test/QueryManager.ts

A work-in-progress solution to #334.
TODO:

Extra test, attempted to repro 334

---

.travis.yml
appveyor.yml

**Travis-CI Total time**
before ~ 5 min 00 sec
after ~  3 min 30 sec

Add caching node_modules to TravisCI and AppVeyor

---

src/ObservableQuery.ts
src/QueryManager.ts
src/batching.ts
src/data/mutationResults.ts
src/index.ts
src/scheduler.ts
src/watchQueryOptions.ts
test/QueryManager.ts
test/scheduler.ts

Moved ObservableQuery and WatchQueryOptions out of QueryManager

---

CHANGELOG.md
src/QueryManager.ts
src/data/mutationResults.ts
src/index.ts
test/optimistic.ts

Failing mutation test

---

CHANGELOG.md
ambient.d.ts
package.json
src/index.ts
test/client.ts
typings/browser/globals/apollo-client/index.d.ts
typings/browser/globals/apollo-client/typings.json
typings/browser/modules/lodash/index.d.ts
typings/main/globals/apollo-client/index.d.ts
typings/main/globals/apollo-client/typings.json
typings/main/modules/lodash/index.d.ts

Added fragment definition flattening as per the discussion in #421 and a test for it.
(also, this branch's name is misspelled). 
TODO:

Added the fragment flattening

---

CHANGELOG.md

Changelog formatting

---

CHANGELOG.md
src/QueryManager.ts
src/errors.ts
test/QueryManager.ts
test/errors.ts

Fix error issues

---

.gitignore
tsconfig.json

Just small config changes to be compatible. http://alm.tools/
TODO:

Set up alm

---

src/queries/getFromAST.ts

Don't use bracket cast

---

CHANGELOG.md
src/QueryManager.ts
test/client.ts
test/optimistic.ts

Added the apollo mutation error handling

---

CHANGELOG.md
src/queries/queryTransform.ts
test/QueryManager.ts
test/client.ts
test/queryTransform.ts

Don't add fields to the root mutation/query

---

CHANGELOG.md
src/QueryManager.ts
src/queries/getFromAST.ts
test/getFromAST.ts

Fixed the update queries bug with fragments

---

src/batching/queryMerging.ts
src/data/writeToStore.ts
test/client.ts
test/mocks/mockNetworkInterface.ts
test/queryMerging.ts

Named fragments issue within query merging

---

CHANGELOG.md

Added changelog entry for #509.
TODO:

Added back changelog entry for #509.

---

test/QueryManager.ts

Made significant progress on #151. No update to changelog since this is not an application-facing change.
TODO:

Refactored the QueryManager tests

---

README.md

Add contributing link

---

CHANGELOG.md
src/ObservableQuery.ts
src/watchQueryOptions.ts
test/graphqlSubscriptions.ts

Change subscriptions API to updateQuery instead of updateFunction

---

CHANGELOG.md
src/ObservableQuery.ts
src/QueryManager.ts
src/index.ts
test/graphqlSubscriptions.ts

Subscription that returns an observable

---

CHANGELOG.md
src/networkInterface.ts
test/networkInterface.ts

Merge bryanchriswhite 547 fix

---

src/data/store.ts

Simple fix that adds undefined to the domain of StoreValue.

---

package.json
src/data/readFromStore.ts
src/data/store.ts
src/data/writeToStore.ts
src/index.ts
src/networkInterface.ts
src/queries/getFromAST.ts
src/store.ts
src/watchQueryOptions.ts

Thanks to https://github.com/zakhenry/typedoc/tree/ts-2.0, I got typedoc working w/ TS2.0! (At least for our purposes, AFAICT).
This PR is the comments from https://github.com/apollostack/apollo-client/pull/557 without the code changes.

Typedoc ts 2.0

---

AUTHORS
src/data/store.ts

Fix `undefined` as a type

---

package.json
src/util/Observable.ts

Now we can use it with the latest RxJS.

Update to symbol-observable@1

---

CHANGELOG.md

Fix changelog for #619

---

CHANGELOG.md

Add bigger note to changelog

---

CHANGELOG.md
src/index.ts
test/client.ts

Add back reduxRootKey for backcompat

---

CHANGELOG.md

Add note to changelog about 0.4.16/17

---

src/index.ts
test/client.ts

set reduxRootKey for backwards compatibility

---

CHANGELOG.md
package.json
src/index.ts
test/client.ts

Fix root key

---

package.json
src/scheduler.ts

TODO:
Fix for issue https://github.com/apollostack/apollo-client/issues/703

delete interval from intervalQueries when is empty to create interval on new subscription

---

AUTHORS
CHANGELOG.md
src/transport/afterware.ts
src/transport/batchedNetworkInterface.ts
src/transport/networkInterface.ts

- Bugfix for afterwares (did not wait for promise)
- Change response of afterware to GraphQLResult (more reasonable)
** this approach also aligned with the batching network interface **

fix: afterware network interface aligment

---

AUTHORS
CHANGELOG.md
src/transport/afterware.ts
src/transport/batchedNetworkInterface.ts
src/transport/networkInterface.ts

Reverts apollostack/apollo-client#749

Revert "fix: afterware network interface aligment"

---

CHANGELOG.md
src/data/writeToStore.ts
src/index.ts
test/writeToStore.ts

[WIP] Refactor normalization

---

CHANGELOG.md

Add 0.4.21 to the changelog

---

CHANGELOG.md
src/data/writeToStore.ts
test/roundtrip.ts

Test and fix for #776

---

test/client.ts

Test for #736

---

CHANGELOG.md
package.json
src/data/storeUtils.ts
test/roundtrip.ts
test/writeToStore.ts

Add enum support

---

src/data/mutationResults.ts
src/data/writeToStore.ts
test/writeToStore.ts

Introduce write context

---

test/client.ts
test/getFromAST.ts

Test for #763

---

src/core/ObservableQuery.ts

Move all of the observable query stuff out of the closure

---

CHANGELOG.md
package.json

First preview of 0.5.0: 0.5.0-0

---

test/ObservableQuery.ts

Add test that passes

---

src/core/QueryManager.ts
src/data/mutationResults.ts

Undo accidental breaking change to updateQueries

---

README.md

Add back file size

---

CHANGELOG.md
src/transport/networkInterface.ts
test/networkInterface.ts

Fixes: https://github.com/apollostack/apollo-client/issues/806
TODO:

Add backcompat for old net interface function

---

src/index.ts

add a few exports for external query merging

---

src/actions.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/watchQueryOptions.ts
src/queries/store.ts
src/scheduler/scheduler.ts
src/store.ts
test/ObservableQuery.ts
test/QueryManager.ts
test/client.ts
test/mutationResults.ts
test/store.ts
test/subscribeToMore.ts

WIP Network Status

---

CHANGELOG.md
package.json

0.5.0 preview.3

---

scripts/deploy.sh

revert mistake in deploy script

---

.travis.yml
appveyor.yml
package.json
src/transport/batchedNetworkInterface.ts
tsconfig.json
typings.d.ts

@helfer @tmeasday Works with `typedoc` but you should check it, just to be sure

Use typescript/libs instead of es6-shim

---

CHANGELOG.md
src/core/ObservableQuery.ts
test/ObservableQuery.ts

Make sure `currentResult` uses optimistic store

---

CHANGELOG.md
src/core/QueryManager.ts
src/queries/store.ts
test/QueryManager.ts

Fix resetStore bug

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/core/watchQueryOptions.ts
test/subscribeToMore.ts

TODO:
Minimal docs update in this PR: https://github.com/apollostack/react-docs/pull/103

provide simple error callback in subscribeToMore

---

CHANGELOG.md
src/transport/batchedNetworkInterface.ts
test/client.ts

sanity-check server response in batching NI

---

CHANGELOG.md
src/core/QueryManager.ts

watchQuery should respect addTypename

---

AUTHORS
CHANGELOG.md
package.json
src/core/QueryManager.ts
src/queries/getFromAST.ts
test/getFromAST.ts
typings.d.ts

Continuing #906 (thanks @jnwng)
TODO:

Unique fragments

---

package.json

Add back lodash.isequal

---

README.md

Added polymer integration.

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/scheduler/scheduler.ts
test/QueryManager.ts
test/scheduler.ts

Let's hope the tests are decent...

refactor polling queries

---

CHANGELOG.md
src/ApolloClient.ts
src/core/QueryManager.ts

convenience method for Initial state

---

ROADMAP.md

Here it is, the roadmap for Apollo Client 1.0!
It's neither complete nor guaranteed to be right. To make it better, I need **your** help! Yes, **you**! Apollo Client is built by the community and for the community. For this particular document it means that if you're interested or have a stake in Apollo Client 1.0, consider doing one or more of the following:
1. Providing feedback on the planned features + improvements (which ones are important, which ones are not, which ones are missing?)
2. Making PRs to this document to reference currently open issues and PRs where applicable. If there are none, please open an issue/PR and link it!
3. Volunteering to help with or be responsible for one or more of the items in the list of 1.0 goals. It can also be an item you propose!
What we've built …

Apollo 1.0 Roadmap

---

CHANGELOG.md
src/index.ts

Added export for NetworkInterface and HTTPFetchNetworkInterface

---

ROADMAP.md

Properly format list in ROADMAP.md

---

package.json

chore: Add @types/chai and typed-graphql to optionalDependencies.

---

src/store.ts

As suggested by @glasser
TODO:

Add comment about query IDs

---

CHANGELOG.md
src/ApolloClient.ts

Devtools hook

---

CHANGELOG.md
package.json

Drop 0.5.14 in changelog

---

CHANGELOG.md
package.json
src/ApolloClient.ts
src/store.ts
test/client.ts

Add tests and make sure it works with self-made store

---

CHANGELOG.md
package.json
src/store.ts
test/client.ts

Make devtools enhancer last maybe?

---

CHANGELOG.md
package.json
src/ApolloClient.ts

Make sure to actually run the reducers before getting the state

---

CHANGELOG.md
package.json
src/actions.ts
src/core/QueryManager.ts

Make sure query result client has requestId

---

scripts/deploy.sh

Remove tag in deploy script

---

src/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/data/mutationResults.ts
src/data/replaceQueryResults.ts
src/data/store.ts
src/data/writeToStore.ts
src/mutations/store.ts
src/optimistic-data/store.ts
src/queries/getFromAST.ts
src/queries/store.ts
src/scheduler/scheduler.ts
src/store.ts

This will convert all Object assigns to ES6 spreads.

WIP: use spread

---

src/ApolloClient.ts
src/core/QueryManager.ts
src/store.ts
test/QueryManager.ts

Broadcast a bit less

---

CHANGELOG.md
src/data/store.ts

Write to ROOT_SUBSCRIPTION for subscription results

---

src/ApolloClient.ts
src/core/types.ts
src/data/extensions.ts
src/data/writeToStore.ts
src/store.ts
test/QueryManager.ts
test/diffAgainstStore.ts
test/writeToStore.ts

Remove extensions.ts

---

rollup.config.js

@helfer About https://github.com/apollostack/apollo-client/pull/1095#issuecomment-270566932

Suppress rollup warnings

---

test/mutationResults.ts

This is a test reproducing https://github.com/apollostack/apollo-client/issues/1094. Either the issue has been fixed, or this is not reproducing the original error.

Add test for reducer error swallowing

---

package.json
scripts/deploy.sh

`jsnext:main` hasn't been updated so I made an adjustment

Fix jsnext:main

---

src/ApolloClient.ts
src/core/QueryManager.ts
src/data/readFromStore.ts
src/util/environment.ts
src/util/maybeDeepFreeze.ts
test/environment.ts
test/tests.ts

Avoid using process.env.NODE_ENV direcly

---

CHANGELOG.md
src/core/QueryManager.ts
src/core/types.ts
test/QueryManager.ts

TODO:
PR on docs: https://github.com/apollostack/react-docs/pull/146

change refetchQueries to allow 'pure' refetch

---

CONTRIBUTING.md

In preparation for [contributor week](https://dev-blog.apollodata.com/save-the-date-apollo-contributor-week-eef66d09f0e6), we're updating CONTRIBUTING.md and README.md on a our main repos. If you have ideas for what to put in these, please share them here!

WIP update CONTRIBUTING.md

---

README.md

badges: apollostack -> apollographql

---

CHANGELOG.md
src/core/QueryManager.ts

Closes https://github.com/apollographql/apollo-client/issues/1249

End flow after promise rejection

---

src/core/QueryManager.ts
test/ObservableQuery.ts

Fix: ObservableQuery reducers should be called with latest variables/data

---

AUTHORS
CHANGELOG.md
src/ApolloClient.ts

Fix crash if resetStore() or getInitialState() called prior to query/mutation

---

ROADMAP.md

I accidentally ticked the wrong box in https://github.com/apollographql/apollo-client/pull/1306. This fixes that 😊

Fix incorrect roadmap check mark

---

README.md

TODO:
@helfer, and here it is!

Add Blaze integration to ReadMe

---

CHANGELOG.md
src/core/ObservableQuery.ts
test/ObservableQuery.ts

This PR fixes the bug in https://github.com/apollographql/react-apollo/issues/483

Set pollInterval to undefined when calling stopPolling

---

CHANGELOG.md
src/core/QueryManager.ts

this is bug fix for #1336 
TODO:

Add null check for lastResult in queryListenerForObserver

---

src/transport/afterware.ts
src/transport/batchedNetworkInterface.ts
src/transport/middleware.ts
src/transport/networkInterface.ts
test/batchedNetworkInterface.ts

afterware + batchNetworkInterface

---

src/core/QueryManager.ts

Addresses https://github.com/apollographql/apollo-client/issues/1335

Better error stack reporting

---

CHANGELOG.md
package.json

1.0.0 rc.1

---

CHANGELOG.md
package.json
src/core/QueryManager.ts
src/index.ts
test/client.ts
test/mutationResults.ts

1.0.0 rc.2

---

package.json

Closes #1417
https://greenkeeper.io/
TODO:

fix(package): update graphql-anywhere to version 3.0.1

---

src/core/QueryManager.ts

Makes issues like https://github.com/apollographql/apollo-client/issues/1406 less likely.

Don’t allow pollInterval on query

---

src/ApolloClient.ts

So we have a place to link to when people ask questions like that in https://github.com/apollographql/apollo-client/issues/1364

add docs for resetStore

---

src/ApolloClient.ts
src/store.ts

This patch fix issue #1312
TODO:

Specify type of ApolloClient.reducer

---

CHANGELOG.md
package.json

1.0.0 rc.3

---

CHANGELOG.md
package.json

1.0.0 rc.4

---

CHANGELOG.md
package.json

1.0.0 rc.5

---

CHANGELOG.md
package.json

Thanks to everyone who contributed! :tada:

1.0.0 rc.6

---

test/client.ts

This is a failing test to demonstrate issue #1363.
TODO:

failing test: interface query w/ conditional fragments

---

CHANGELOG.md
package.json
src/ApolloClient.ts

New fragment matching and a few other improvements

1.0.0-rc.7

---

CHANGELOG.md
package.json
src/core/QueryManager.ts
src/index.ts
src/transport/Deduplicator.ts
src/transport/networkInterface.ts
test/client.ts
test/getFromAST.ts
test/mocks/mockNetworkInterface.ts
test/networkInterface.ts
test/proxy.ts
test/queryTransform.ts
typings.d.ts

Bumping to the newest premajor of `graphql-tag`. If the integration tests pass here, I will bump `graphql-tag` to 2.0 and update this PR accordingly.
TODO:

Bumping to `graphql-tag`@2.0

---

AUTHORS
CHANGELOG.md
src/transport/batchedNetworkInterface.ts
src/transport/batching.ts
test/batching.ts

More efficient QueryBatcher

---

CHANGELOG.md
package.json
scripts/deploy.sh

Some fixes + dependency updates.

1.0.0 rc.8

---

CHANGELOG.md
package.json
src/ApolloClient.ts
src/data/proxy.ts
src/store.ts
test/ApolloClient.ts
test/proxy.ts

Respect addTypename in imperative store reads/writes

---

src/ApolloClient.ts
src/core/QueryManager.ts
src/data/proxy.ts
src/data/resultReducers.ts
src/data/store.ts

Fixes [#1526](https://github.com/apollographql/apollo-client/issues/1526)
TODO:

Added missing fragmentMatcher to diffQueryAgainstStore options

---

CHANGELOG.md
src/core/QueryManager.ts
test/mutationResults.ts

Fix missing addTypename in result reducers

---

src/core/QueryManager.ts

Correct form is `fetchPolicy`
TODO:

Rename mistakingly called `cachePolicy` in comment

---

src/queries/queryTransform.ts

Now using `String.lastIndexOf(needle, 0) === 0`

Replace usage of String.startsWith

---

CHANGELOG.md

CHANGELOG: remove pre-1.0 text

---

AUTHORS
src/index.ts

As part of fixing https://github.com/apollographql/react-apollo/issues/423, `SubscriptionNetworkInterface` needs to be exported from Apollo Client.
TODO:

Export SubscriptionNetworkInterface

---

.github/ISSUE_TEMPLATE.md

@helfer @stubailo I created a webpackbin for apollo 💯 
This should make it even easier for people to create reproductions (it includes apollo-client, react-apollo, and a server built using graphql-tools!)
https://www.webpackbin.com/bins/-KjAoAmOoExoJhPIpPu1
I've also submitted it to be a boilerplate https://github.com/cerebral/webpackbin/issues/21

Added webpackbin to issue template

---

.travis.yml

@helfer now that 1.1.2 is out we can point to the master branch of RA

use master of react apollo for testing

---

CHANGELOG.md
src/data/fragmentMatcher.ts
src/data/proxy.ts
src/data/replaceQueryResults.ts
src/data/resultReducers.ts
src/data/store.ts
src/data/writeToStore.ts
src/util/warnOnce.ts
test/ApolloClient.ts
test/client.ts
test/mutationResults.ts
test/networkInterface.ts
test/proxy.ts
test/roundtrip.ts
test/subscribeToMore.ts
test/util/wrap.ts
test/warnOnce.ts
test/writeToStore.ts

Fixes #1611
Check to make sure shape of response matches query when writing to store.
still to complete:
TODO:

Strict writes

---

.travis.yml
src/core/ObservableQuery.ts

Fixes #1092
No extra test for this because afaict we never had an issue with it. Just doing it out of caution.

Ensure options.variables is set in setVariables

---

.travis.yml

@jbaxleyiii here's the PR to merge once we update the snapshot for RA! 🙂

Re-enable react-apollo tests

---

test/writeToStore.ts

This simplifies the `writeResultToStore` tests.

Simplify the writeResultToStore tests

---

AUTHORS
CHANGELOG.md
src/ApolloClient.ts

As discussed in [#1657 (comment)](https://github.com/apollographql/apollo-client/issues/1657#issuecomment-299536799)
TODO:

Expose dataIdFromObject in addition to dataId

---

CHANGELOG.md
src/core/QueryManager.ts

I was not able to make a failing test in Apollo Client, but this fixes the reproduction in react-apollo/#170, so I think it's worth releasing.
TODO:

Attempt at fixing 170 race condition

---

src/queries/getFromAST.ts

space before semicolon removed

---

CHANGELOG.md
index.js.flow
src/actions.ts
src/data/mutationResults.ts
src/queries/getFromAST.ts
src/transport/networkInterface.ts
test/getFromAST.ts

Operation name

---

src/data/proxy.ts
test/proxy.ts

**NOTE**:
This opens a can of worms on whether other parameters should be checked for existence with appropriate error messages.
TODO:

Issue 1771

---

src/data/writeToStore.ts
test/writeToStore.ts

add query information to error message

---

package.json

Pin @types/node to 7.0.29

---

src/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts

Change return type of mutate and fetchQuery

---

rollup.config.js
scripts/deploy.sh
src/ApolloClient.ts

Added node -e script to deploy.sh to fix version detection using umd build.
TODO:

Fix version detection

---

CHANGELOG.md
src/transport/batchedNetworkInterface.ts
test/batchedNetworkInterface.ts

Give batchInterval a default value (10 ms)

---

package.json

chore: pin @types/lodash to 4.14.65

---

package-lock.json
package.json
test/batchedNetworkInterface.ts
test/optimistic.ts

This fixes the failing builds on Travis due to new lint errors with the latest TSLint.
TODO:

Upgrade Chai and fix TSLint 5.5.0 failures

---

src/core/QueryManager.ts
test/client.ts

Fix apollographql/react-apollo#771

Check if mutation option exists

---

src/ApolloClient.ts
test/client.ts

Remove string from ```reduxRootSelector``` in ApolloClient constructor is it was misleading

---

CHANGELOG.md
package.json

prerelease version bump

---

package.json

fix(package): update apollo-link to version 0.2.0

---

package.json

Move @types/isomorphic-fetch to devDependencies

---

package.json
packages/apollo-client/package.json
packages/apollo-link-core/package.json
packages/graphql-anywhere/package.json
packages/zen-observable-ts/package.json

This expands our bundle size testing to include required dependencies now moved into this library 👍

added filesize checks for required deps

---

CHANGELOG.md
package.json

*1.9.0* 🎉 thank you everyone who contributed to this release!

version bump for release

---

packages/apollo-cache-core/src/cache.ts
packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/cache-inmemory/inMemoryCache.ts
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/types.ts
packages/apollo-client/src/scheduler/scheduler.ts

Adjust invalidation callbacks to include the latest data

---

.all-contributorsrc
package.json

Setup all-contributors-cli

---

CHANGELOG.md
src/index.js.flow

- `[Object]` means array of length 1 with Object. Instead we want `Array<Object>`
- ___* were typos. The correct values from code is __*
---
Follow up of https://github.com/apollographql/react-apollo/pull/952 :)

Fixed flow annotations

---

packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/cache-inmemory/inMemoryCache.ts
packages/apollo-client/src/core/ObservableQuery.ts
packages/apollo-client/src/core/QueryManager.ts

More cleanup of cache implementation and QueryManager usage

---

.travis.yml
package.json
packages/apollo-cache-core/package.json
packages/apollo-client/package.json
packages/apollo-client/src/core/QueryManager.ts
packages/graphql-anywhere/package.json

@shadaj @stubailo this fixed the bug with setOptions and all other tests still passed. Not sure what the goal of this was aside from optimization?
@meteor-bot this is a trivial PR (no changelog needed)

remove optimizations to get setOptions working

---

CHANGELOG.md
package.json
src/core/ObservableQuery.ts
src/queries/store.ts
test/client.ts
test/deduplicator.ts
test/mocks/mockFetch.ts
test/readFromStore.ts
test/scheduler.ts
test/tests.ts

1.9.2 and prettier updates

---

.github/stale.yml

Fix typo for stale bot

---

.travis.yml
Upgrade.md

A trivial change to speed up tests ⏩ and some updates to the upgrade guide

tweak upgrade guide and speed up CI

---

packages/apollo-cache-inmemory/src/inMemoryCache.ts

This is a fairly trivial fix, I think.

Transform ducument before writing to store.

---

packages/apollo-client/src/core/__tests__/ObservableQuery.ts

Tests needn't (and shouldn't) be gendered

---

packages/apollo-cache-inmemory/package.json
packages/apollo-cache/package.json
packages/apollo-client-preset/package.json
packages/apollo-client/package.json
packages/apollo-client/src/__tests__/mutationResults.ts
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/__tests__/QueryManager/links.ts
packages/apollo-utilities/package.json
packages/graphql-anywhere/package.json

Update to the newest beta of links

Link updates

---

package.json
packages/apollo-client/CHANGELOG.md
packages/apollo-client/package.json
packages/apollo-client/src/__mocks__/mockWatchQuery.ts
packages/apollo-client/src/__tests__/client.ts
packages/apollo-client/src/core/ObservableQuery.ts
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/__tests__/ObservableQuery.ts
packages/apollo-client/src/core/__tests__/QueryManager/index.ts
packages/apollo-client/src/index.ts

This fixes a few bugs found during the `react-apollo` upgrade specifically around how often the observer refires and how errors are cached. Good news is it should make the 2.0 even faster!
🎉

Observable rerender

---

AUTHORS
CHANGELOG.md
src/transport/networkInterface.ts
test/networkInterface.ts

Attempt at resolving https://github.com/apollographql/apollo-client/issues/2238

Fix response not being included with errors that have response body

---

packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/index.ts

Expose ApolloCurrentResult

---

packages/apollo-cache-inmemory/README.md

Cache docs are here! IDK if we want to link to these on the website, but I feel like it might save us a little bit of time if we can 😀

docs(cache): added readme for apollo-cache-inmemory

---

packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/__tests__/graphqlSubscriptions.ts
packages/apollo-client/src/__tests__/mutationResults.ts
packages/apollo-client/src/__tests__/optimistic.ts
packages/apollo-client/src/core/ObservableQuery.ts
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/__tests__/ObservableQuery.ts

Added initial test for #2333 based on issue info

added test for 2333

---

packages/apollo-cache/src/cache.ts
packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/__tests__/ObservableQuery.ts

Transform for link

---

packages/apollo-cache-inmemory/src/readFromStore.ts

Fix for https://github.com/apollographql/apollo-client/issues/2350

Prefer every instead of reduce

---

packages/apollo-cache-inmemory/CHANGELOG.md
packages/apollo-cache-inmemory/src/__tests__/cache.ts
packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts
packages/apollo-cache-inmemory/src/inMemoryCache.ts
packages/apollo-cache-inmemory/src/readFromStore.ts

Also, ran prettier on everything
Fixes #2221

Make sure not to broadcast during a transaction

---

packages/apollo-cache-inmemory/package.json
packages/apollo-cache/package.json
packages/apollo-client-preset/package.json
packages/apollo-client/CHANGELOG.md
packages/apollo-client/package.json
packages/apollo-client/src/ApolloClient.ts
packages/apollo-client/src/core/ObservableQuery.ts
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/__tests__/QueryManager/index.ts
packages/apollo-utilities/package.json
packages/graphql-anywhere/package.json

@jay1337 @seeden this *should* fix the mutations / queries bug in react-apollo (the `rc7`).
Could you try it out for me? (its released)

Fix mutations

---

packages/apollo-client-preset/README.md

docs(apollo-client-preset): Add simple example

---

.gitignore
docs/_config.yml
docs/package.json
docs/source/reference/index.md

This turns back on typedoc (it will need some more work, but its a decent start!)
cc @peggyrayzis if we work on this, we can use it to generate API docs in all our repos

added rough API docs with typedoc

---

docs/source/2.0-migration.md

docs(migration): cleaned up copy, changed 2.0 example

---

packages/apollo-client/CHANGELOG.md
packages/apollo-client/scripts/deploy.sh
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/__tests__/QueryManager/links.ts

Fix a minor bug, prep for 2.0 launch

Final countdown

---

Upgrade.md

Correct typo

---

.travis.yml
README.md
package.json
packages/apollo-cache-inmemory/package.json
packages/apollo-cache/package.json
packages/apollo-client-preset/package.json
packages/apollo-client/CHANGELOG.md
packages/apollo-client/package.json
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-utilities/package.json
packages/graphql-anywhere/package.json

The official 2.0 is ready for updating now and checkout the brand new docs [here](https://www.apollographql.com/docs/react/) and let us know what you think!

Apollo Client 2.0

---

docs/source/basics/network-layer.md

Fixed broken syntax (missing parentheses)

---

docs/source/2.0-migration.md

What it says on the tin. I ran into this weird a weird error message about store.

docs: react-apollo ApolloProvider no longer does redux Provider

---

.travis.yml
packages/apollo-client/package.json
packages/apollo-utilities/CHANGELOG.md
packages/apollo-utilities/src/__tests__/transform.ts
packages/apollo-utilities/src/transform.ts

These changes will make creating custom directive links easier to implement 👍

Directive improvements

---

docs/source/2.0-migration.md

Changed they to the as I believe was originally intended.

Updated "they" to "the" in the docs

---

packages/apollo-cache-inmemory/src/writeToStore.ts

Fixed issue 2414: /n should be \n

---

docs/source/basics/caching.md

Fix typo in docs

---

docs/_config.yml
docs/source/basics/caching.md
docs/source/recipes/fragment-matching.md

docs(fragment-matcher): add fragment matcher docs

---

docs/source/basics/network-layer.md

Fix extra )

---

docs/source/recipes/fragment-matching.md

docs(fragment-matching): fixed code block formatting

---

docs/source/features/fragments.md

Fix broken link to webpack loader fragments

---

README.md
packages/apollo-client/AUTHORS

Fix README.md for 2.0

---

docs/source/recipes/authentication.md

I'm guessing this change is necessary?  I don't see anything about gql under graphql-tools nor anything mentioned about "tools" in this doc.

Update gql to import from graphql-tag

---

docs/source/features/optimistic-ui.md

Update gql to be from graphql-tag

---

packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/core/ObservableQuery.ts
packages/apollo-client/src/core/__tests__/ObservableQuery.ts

Fix for https://github.com/apollographql/react-apollo/issues/1320

fix(apollo-client): fix errors missing on currentResult

---

packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/core/QueryManager.ts
packages/apollo-client/src/core/__tests__/QueryManager/links.ts
packages/apollo-client/src/core/watchQueryOptions.ts

Pass context to link chain when doing a mutation

---

docs/source/basics/setup.md

Typo in npm command

---

docs/source/2.0-migration.md

docs#2483 remove a line

---

docs/source/2.0-migration.md

…headers
Because with apollo link getting headers in the response is quite different from the previous version.

Add afterware example about authenticating via headers

---

docs/source/basics/queries.md

fix broken link

---

docs/source/basics/caching.md

docs(caching): Fix typo in cacheResolvers

---

packages/apollo-client/CHANGELOG.md
packages/apollo-client/src/scheduler/__tests__/scheduler.ts
packages/apollo-client/src/scheduler/scheduler.ts

Fix startPolling/setOptions when adjusting pollInterval

---

docs/source/basics/setup.md

[Docs] Fix basics/setup.md fragments section link

---

docs/source/features/caching.md

This content does not appear to exist anywhere that I (nor Google) can find. :-(

Remove link to how it works

---

docs/source/basics/queries.md

Fix link to pagination recipe

---

packages/apollo-client/src/core/watchQueryOptions.ts

Just a small doc fix for a typo.

docs: s/Wether/Whether

---

docs/source/basics/setup.md

Fix two links in basics/setup

---

docs/source/index.md

Update index.md you query -> your query

---

docs/source/basics/setup.md

[docs] fixed few broken links

---

docs/source/basics/caching.md

I managed to delete source repo for #2595
Let's continue here and delete old PR

[docs] update normalization section

---

docs/source/basics/network-layer.md

WebSocket's -> WebSockets

---

packages/apollo-cache-inmemory/package.json
packages/apollo-cache/package.json
packages/apollo-client/package.json
packages/apollo-utilities/package.json
packages/graphql-anywhere/package.json

Fix jsnext:main path

---

docs/source/recipes/server-side-rendering.md

This change is related to [apollographql/apollo-link#284](https://github.com/apollographql/apollo-link/pull/284). Basically it suggests using SchemaLink (A new link for binding to a local schema) instead of essentially reimplementing it for SSR.

[Docs] Update local queries SSR to suggest SchemaLink

---

docs/source/features/cache-updates.md
docs/source/recipes/query-splitting.md

Closes #2676

---

docs/_config.yml
docs/package.json
docs/source/recipes/recompose.md

Shocki tv patch 2

---

docs/source/basics/caching.md

Hold off on merging until we publish `apollo-cache-persist`.

Added recipe for cache persistence

---

packages/apollo-cache-inmemory/src/types.ts

I think this is unnecessary :P

Don't import types from themselves

---

packages/apollo-client/src/core/watchQueryOptions.ts

fix typo avaiable => available

---

packages/apollo-client-preset/README.md

current instructions lack 2 deps. as per this issue https://github.com/apollographql/apollo-client/issues/2786

add missing dependencies to apollo client preset

---

docs/source/recipes/authentication.md

This is just a minor change. Probably no need to explain it.

[Docs] Cleanup React code

---

docs/source/basics/caching.md

See also https://github.com/reactjs/redux/blob/ed2b9e2df001d27fdef69739e0410eb9d1fb836f/docs/recipes/ServerRendering.md#inject-initial-component-html-and-state

caching.md: JSON escaping for embed security

---

docs/source/features/error-handling.md

The name of prop appears to be incorrect here.

errors -> error

---

docs/source/recipes/webpack.md

Add section for create-react-app to webpack.md

---

docs/source/recipes/recompose.md

Fix typos in recompose.md

---

docs/source/features/subscriptions.md

Error: attach query result to component props

---

docs/source/basics/network-layer.md

Fixed typo

---

docs/source/features/cache-updates.md

This was pointing to another section of the page, looks like the section link wasn't followed correctly by the redirect.

Update `update` non working link

---

packages/apollo-cache-inmemory/CHANGELOG.md
packages/apollo-cache-inmemory/src/types.ts
packages/apollo-client/AUTHORS

Fixes https://github.com/apollographql/apollo-client/issues/2959

Fix IntrospectionResultData type definition

---

packages/apollo-client/AUTHORS
packages/apollo-utilities/CHANGELOG.md
packages/apollo-utilities/src/__tests__/transform.ts
packages/apollo-utilities/src/transform.ts

Fixes https://github.com/apollographql/apollo-client/issues/2884
This utility is need for this PR in apollo-link-state https://github.com/apollographql/apollo-link-state/pull/193

Get directives from document

---

packages/apollo-boost/package.json
packages/apollo-cache-inmemory/package.json
packages/apollo-cache/package.json
packages/apollo-client/package.json
packages/apollo-utilities/package.json
packages/graphql-anywhere/package.json

- apollo-boost@0.1.0
- apollo-cache-inmemory@1.1.8
- apollo-cache@1.1.3
- apollo-client@2.2.4
- apollo-utilities@1.0.7
- graphql-anywhere@4.1.4

chore: Publish

---

docs/source/why-apollo.md

Why Apollo doc fixes

---

packages/apollo-boost/README.md

Need to pass the correct 'GET_MOVIES' to the Query component and not 'query'.

Fix ReadMe for apollo-boost

---

docs/source/features/static-typing.md

fix spelling of implemented

---

packages/apollo-client/src/core/watchQueryOptions.ts

Fix a typo

---

docs/source/recipes/pagination.md

Removed blank line of code and fixed use of fetchMoreResult, matching current GitHunt
https://github.com/apollographql/GitHunt-React/blob/c0b18795a18b3da42dc90cf7c63b29b14965206d/ui/Feed.js#L227-L231

Update pagination.md updateQuery

---

docs/source/recipes/authentication.md

Fix wording

---

.github/ISSUE_TEMPLATE.md

Update to use new issue labeling; use consistent terminology.

Update feature request instructions

---

docs/source/features/cache-updates.md

Syntax error in example for cache-updates

---

packages/apollo-boost/README.md

Small change to the readme under apollo-boost.

Readme update: ApolloApp example returns wrapped App component

---

packages/apollo-cache/CHANGELOG.md
packages/apollo-cache/package.json
packages/apollo-cache/src/__tests__/cache.ts
packages/apollo-cache/src/cache.ts

First time contributor here!
I've added some tests to one of the more sparse files while familiarizing myself with the codebase.

Expand apollo-cache code coverage

---

CHANGELOG.md
src/core/QueryManager.ts
test/client.ts

Fixes #2272 on v1 branch
EDIT: I'm fairly sure I've based this on the correct branch, but please let me me know if I've done a silly.

Prevent unhandled rejections with cache-and-network

---

docs/source/features/developer-tooling.md

[docs] Fix typo in developer-tooling.md

---

docs/source/essentials/get-started.md

Well I'm reading the docs tonight so PRs incoming 🚀

Fix Grammar 📝

---

docs/source/features/performance.md

docs: typo: onSeries -> oneSeries

---

docs/package.json
renovate.json

Remove renovate config from nested package.json

---

packages/apollo-cache-inmemory/README.md

[Docs] Add link to fragment matcher recipe

---

docs/source/essentials/queries.md

correct networkStatus reference link

---

docs/source/recipes/static-typing.md

Remove extraneous > from static typing example

---

docs/source/advanced/caching.md

Clarifying language

---

docs/source/essentials/mutations.md

Make language precise

---

docs/source/recipes/static-typing.md
packages/apollo-client/AUTHORS

Fix docs typo

---

docs/source/recipes/static-typing.md

Small typos. I signed the Meteor CLA already.

Typos in static-typing.md

---

docs/source/why-apollo.md

Typo in why-apollo.md

---

docs/source/why-apollo.md

Added reference to render prop API

---

docs/source/advanced/boost-migration.md

Observable import for boost-migration

Observable import for boost-migration.md #3359

---

docs/source/essentials/mutations.md

Resolves apollographql/react-apollo#1973

docs(Mutation): removes client from docs

---

renovate.json

Just adding myself to `renovate` assignees/reviewers.

Add hwillson to renovate assignees/reviewers

---

docs/source/recipes/babel.md

The Babel plugin name has changed for `babel-plugin-graphql-ast`: https://github.com/detrohutt/babel-plugin-import-graphql/tree/v2.4.4

Update to docs page: Compiling queries with Babel 

---

docs/_config.yml

Set up redirects for simple example recipe

---

docs/source/recipes/static-typing.md

Remove duplicate word "full" from documentation

---

docs/source/recipes/static-typing.md

The initial comment was a bit misleading.
Fixes #3461.

Clarfiy `graphql` input props typing code comment

---

README.md

Fixes https://github.com/apollographql/apollo-client/issues/3330.

Fix Vanilla JS link in README

---

docs/source/features/server-side-rendering.md

to reflect https://reactjs.org/docs/hello-world.html

Docs: change div id to root

---

docs/source/advanced/caching.md

Fix grammar for `cacheRedirects`

update caching.md documentation

---

docs/_config.yml
docs/source/features/defer-support.md

Docs: Add Experimental Defer Support

---

docs/source/essentials/mutations.md

Re-fix https://github.com/apollographql/apollo-client/pull/3808.

Fix broken mutations section next steps links

---

package-lock.json

Package adjustments based on npm audit results.

NPM audit adjustments

---

docs/source/advanced/subscriptions.md
docs/source/api/react-apollo.md

Reference: https://github.com/apollographql/react-apollo/pull/2298

Add `<Subscription />` `fetchPolicy` to the docs

---

packages/apollo-client/src/ApolloClient.ts

Just fixing some typos I found while reading through source. Look forward to contributing more to Apollo!

Fix some minor typos in ApolloClient file

---

docs/source/api/react-apollo.md

docs: fix typo

---

CHANGELOG.md
docs/source/advanced/fragments.md

As titled. I found it really confusing using fragments for the first time, especially around trying to figure out what the part after the on clause was reserved for. Hopefully this PR makes it more helpful! :)

Add Clarification on How to Use Fragments 

---

docs/source/advanced/fragments.md

fixes a silly typo (missing end quote) in fragments.md

---

CHANGELOG.md
docs/source/advanced/caching.md

docs: Remove redundant sentence

---

packages/apollo-client/src/ApolloClient.ts
packages/apollo-client/src/__tests__/__snapshots__/ApolloClient.ts.snap

This should keep folks from continuing to encounter issue #3639.

Fix error message about ApolloClient({ link, cache }) options.

---

docs/source/advanced/caching.md

Fixed small spelling mistake from "specfic" to "specific"

---

docs/package-lock.json
docs/package.json

This branch updates the docs theme to add a expand/collapse all button

Upgrade docs theme to 0.2.45

---

docs/package-lock.json
docs/package.json

This branch upgrades the docs theme for a better developer experience

Upgrade theme to 0.2.46

---

docs/package-lock.json
docs/package.json

This branch upgrades the docs link for better "Edit on GitHub" link URLs

Upgrade docs theme to 0.2.49

---

docs/source/react-apollo-migration.md

capitalized R for React before the word tree

typo in react-apollo-migration.md

---

docs/gatsby-config.js
docs/package-lock.json
docs/package.json
netlify.toml

This branch upgrades the docs theme to get better handling of versions, and fixing deploy preview links.

Upgrade docs theme to 0.3

---

docs/source/api/react-apollo.md

Minor changes to remove the needless `if else if`.

Cleaned up the code a bit

---

packages/apollo-client/src/core/__tests__/QueryManager/index.ts

It looks like the other 92 tests in this file are being unintentionally skipped!

Run all QueryManager tests

---

packages/apollo-cache-inmemory/src/__tests__/cache.ts
packages/apollo-cache-inmemory/src/__tests__/diffAgainstStore.ts
packages/apollo-cache-inmemory/src/__tests__/fragmentMatcher.ts
packages/apollo-cache-inmemory/src/__tests__/readFromStore.ts
packages/apollo-cache-inmemory/src/__tests__/roundtrip.ts
packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts
packages/apollo-cache-inmemory/tsconfig.json

Partial progress towards #4850

Enable typecheck cache apollo-cache-inmemory tests

---

docs/source/essentials/local-state.md

It appears that this bit had out-of-date information. This update makes it match the current code example.

remove old documentation

---

docs/source/essentials/local-state.md

remove ungrammatical comma

---

packages/apollo-boost/.npmignore

fix(apollo-boost): don't publish __tests__ or jest config

---

docs/package-lock.json
docs/package.json
docs/source/api/react-components.mdx
docs/source/essentials/get-started.mdx
docs/source/essentials/local-state.mdx
docs/source/features/error-handling.mdx
docs/source/features/server-side-rendering.mdx

This branch reverts 9df4d07a059313d3a0aca0c9a6ce02b509a023ce and upgrades the docs theme to bring in a fix from https://github.com/gatsbyjs/gatsby/pull/16344

Use markdown headings

---

CHANGELOG.md
docs/source/essentials/mutations.mdx

Fixes https://github.com/apollographql/react-apollo/issues/3321.

Fix useMutation typo

---

.github/CODEOWNERS

Add StephenBarlow as codeowner for docs/

---

docs/gatsby-config.js
docs/source/api/apollo-client.mdx

Clean up ApolloClient class reference

---

docs/source/essentials/queries.mdx

General editorial pass for clarity and simplicity (on one of our highest-traffic articles)

Content edit to Queries article

---

docs/source/features/developer-tooling.md

Updates the service's name and standardizes the language we use to describe it

Engine to Graph Manager

---

docs/gatsby-config.js
docs/package-lock.json
docs/package.json

This branch is trying out a new top-navigation strategy

WIP: Docset switcher

---

src/react/data/OperationData.ts
src/react/data/QueryData.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useSubscription.ts
src/react/testing/mocks/mockLink.ts

Bringing over relevant changes from the React Apollo 3.1.2 release:
- https://github.com/apollographql/react-apollo/pull/3515
- https://github.com/apollographql/react-apollo/pull/3539
- https://github.com/apollographql/react-apollo/pull/3514

React updates

---

src/cache/inmemory/writeToStore.ts

These changes fix two subtle problems (specifically on the `release-3.0` branch, not `master`):
1. Calling `Object.assign` in the fragment case was not recursively merging fields that happened to collide with existing fields.
2. Blindly setting `newFields[storeFieldName] = this.processFieldValue(...)` also ran the risk of overwriting existing fields without merging, even though `processFieldValue` does recursively process any nested selection sets.
Instead, we can reuse the powerful `DeepMerger` utility, which preserves the identities of unchanged input objects, and creates at most one copy of each input object that needs to be updated, so that the input objects remain untouched by the merge.
As an additional improvement, we can reuse the same `DeepMerger` object(s) throughout a single …

Properly merge StoreObjects in StoreWriter#processSelectionSet.

---

docs/source/networking/advanced-http-networking.md

@hwillson  It's a PR on a PR! :D

Advanced HTTP copyedit

---

src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/utils/useBaseQuery.ts

To line up with https://github.com/apollographql/react-apollo/commit/0901f4ac2b1800dab423b63bd9e041c863a2425f.

Revert recent useQuery onCompleted changes

---

docs/package-lock.json
docs/package.json

chore(deps): update dependency gatsby-theme-apollo-docs to v2.3.13

---

docs/package-lock.json
docs/package.json

chore(deps): update dependency gatsby-theme-apollo-docs to v2.3.14

---

docs/gatsby-config.js

This branch adds the version 3 beta docs to the version dropdown in the sidebar

Add 3.0 beta to the docs version dropdown

---

docs/source/development-testing/static-typing.md

Fix closing html tag

---

docs/gatsby-config.js
docs/package-lock.json
docs/package.json

Specify separate local/default versions

---

src/__tests__/ApolloClient.ts
src/__tests__/optimistic.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/__tests__/diffAgainstStore.ts
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/entityStore.ts
src/core/__tests__/QueryManager/links.ts
src/core/index.ts

Should fix #5793, which was due to a bug I introduced in #5772.

Guard against missing this.data[dataId] object in EntityStore#get.

---

docs/source/caching/cache-interaction.md

add updated cache.evict args to docs

---

CHANGELOG.md

Changelog adjustments to clearly identify breaking changes. I've reviewed the full AC 3.0 commit history to make sure we aren't missing anything (🤞I caught them all).

Changelog adjustments

---

docs/gatsby-config.js
docs/source/migrating/apollo-client-3-migration.md

Apollo Client 3.0 migration guide

---

docs/source/data/local-state.mdx
docs/source/data/mutations.mdx
docs/source/data/queries.mdx
docs/source/data/subscriptions.mdx

The `subscribeToMore` section still needs a pass, but thought I'd open a PR for what we've got

Edit to Client subscription docs

---

src/link/http/__tests__/HttpLink.ts

Found debugger while reading code.

Remove `debugger` in tests

---

docs/shared/query-result.mdx

Update docs to fix broken link

---

docs/source/data/queries.mdx

Fix source url for network status

---

src/cache/inmemory/writeToStore.ts

As it turns out, `processSelectionSet` can do everything that `writeSelectionSetToStore` was previously doing! Since they're both `private` methods, we might as well unify them into a single method (still called `processSelectionSet`, the more generic of the two names).

Collapse writeSelectionSetToStore into processSelectionSet.

---

src/react/hooks/__tests__/useQuery.test.tsx

This PR adds test cases for bug #6106, I was trying to solve the bug myself but thanks @benjamn for the quick fix. Would you mind if we add my test cases in?

Add test for bug #6106

---

src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts

Avoid clobbering existing keyFields with undefined value.

---

docs/source/migrating/apollo-client-3-migration.md

DX decided to clean up all unnamed operations during our docs jam today! 🚀

Fix unnamed operation in migration article

---

docs/source/api/link/apollo-link-rest.md
docs/source/api/react/hoc.mdx
docs/source/api/react/hooks.mdx
docs/source/caching/cache-configuration.md
docs/source/caching/cache-interaction.md
docs/source/data/local-state.mdx
docs/source/data/queries.mdx
docs/source/data/subscriptions.mdx
docs/source/get-started.mdx
docs/source/why-apollo.mdx

- Cleaned up a bunch of the operations to be specific about the type! 
- Edited operation examples so that they have names on 'em!

[Docs] Added changes to be specific about GraphQL Operations.

---

docs/source/development-testing/developer-tooling.md

Follow up from https://github.com/apollographql/apollo-client-devtools/issues/73#issuecomment-630999845 , to support @jcreighton.

Adding Firefox addon link

---

docs/source/development-testing/testing.mdx

Typo in second paragraph, changed "functoinality" to "functionality".

Fixed typo in testing.mdx

---

CHANGELOG.md
package-lock.json
package.json

Update graphql dependency to 15.0.0

---

docs/source/data/mutations.mdx

The mutation needs to return the id for the cache to be updated

changed the query for mutation update

---

docs/source/development-testing/developer-tooling.md

Update the `developer-tooling` readme for the Graph Manager to Studio product rename

---

src/react/hooks/utils/useBaseQuery.ts

Fix comment in useBaseQuery

---

docs/source/migrating/apollo-client-3-migration.md

using @latest will install last stable version, Need to use @beta to install last beta version (v4)

fix instructions to install v4 of react-hoc and react-components

---

docs/source/performance/server-side-rendering.mdx

renderToStaticMarkup is in ReactDOMServer, not ReactDOM

---

docs/source/local-state/local-resolvers.mdx
docs/source/local-state/local-state-management.mdx
docs/source/local-state/querying-and-updating.mdx

Starting small, much more to come this week!

Edits to Local State overview article

---

src/core/index.ts

Simplified imports/exports

---

docs/source/index.mdx

doc:typo: fix typo

---

docs/source/caching/cache-configuration.md

Fix example variable

---

docs/source/migrating/apollo-client-3-migration.md

Adding youtube AC3 migration video

---

src/utilities/testing/index.ts

fix(testing): export MockedProviderProps from '@apollo/client/testing'

---

docs/source/api/core/ApolloClient.mdx

Make note about watchQuery refer to useQuery hook instead of Query component

---

docs/source/data/subscriptions.mdx

Adds a missing parentheses to code block at Authenticate over WebSocket (optional)

docs: Add missing closing brace to WebSocketLink example

---

package.json

I believe this was just a mistake: https://github.com/apollographql/apollo-client/pull/6856#discussion_r483103579

fix: move `terser` from deps to dev deps

---

docs/source/local-state/reactive-variables.mdx

Added an extra explanation of what happens when updating a reactive variable.  Specifically, adding the interaction with the useReactiveVar custom hook.

Update explanation of reactive variables to include interaction with useReactiveVar

---

src/utilities/policies/__tests__/relayStylePagination.test.ts
src/utilities/policies/pagination.ts

Should help with issues like #7367, though I shared some caveats in https://github.com/apollographql/apollo-client/issues/7367#issuecomment-732378757.

Make relayStylePagination preserve extra incoming.pageInfo properties.

---

docs/package-lock.json
docs/package.json
docs/source/migrating/apollo-client-3-migration.mdx

This PR changes a plain youtube `iframe` embed to use the `VideoFrame` component, which maintains an aspect ratio and auto-resizes to fit the size of its parent container.

Upgrade docs theme and use VideoFrame for youtube embed

---

docs/source/performance/server-side-rendering.mdx

Fix typo in SSR docs

---

docs/source/data/queries.mdx

removed unused `useState`

---

docs/source/caching/cache-interaction.md

Missing cache id line?

---

docs/shared/query-result.mdx

Easy navigation and easy reading for others

Fix broken url in docs

---

CHANGELOG.md
examples/bundling/no-tree-shaking/rollup-ac2/package-lock.json
examples/bundling/no-tree-shaking/rollup-ac2/package.json
examples/bundling/tree-shaking/rollup-ac2/package-lock.json
examples/bundling/tree-shaking/rollup-ac2/package.json
package-lock.json
package.json

Update graphql-tag to v2.12.0

---

docs/source/api/link/apollo-link-ws.md

Workin' through Link docs one link at a time

WebSocketLink edits

---

packages/apollo-cache-inmemory/src/fragmentMatcher.ts

Fix #5477 
Change with the new link.

Fix broken link in error message about fragments

---

ROADMAP.md

February 2021 roadmap update

---

package-lock.json
package.json

Should fix the `ts-invariant` part of issue #7734, thanks to https://github.com/apollographql/invariant-packages/pull/81.

Update ts-invariant to version 0.6.1.

---

docs/source/index.mdx

Add Svelte

---

docs/source/integrations/integrations.md

Fix typo for angular integration's website link

---

docs/source/index.mdx

Add Meteor URL

---

docs/source/performance/optimistic-ui.mdx

This article's been getting a fair amount of feedback lately so figured I'd take a pass at it

Edits to Optimistic UI article

---

docs/source/api/react/ssr.md

This looks out of date? Updating for the new style imports.
(Similar to https://www.apollographql.com/docs/react/api/react/testing/)
Thanks!

[docs] Update ssr.md for @apollo/client 3.x style imports

---

docs/source/caching/cache-interaction.md

Update docs for to add `id` to `cache.modify` add item example

---

docs/source/development-testing/static-typing.md

Fixing typo on static typing docs

---

.github/ISSUE_TEMPLATE/question-discussion.md
COLLABORATORS.md
CONTRIBUTING.md
README.md
docs/source/api/link/apollo-link-rest.md
docs/source/why-apollo.mdx

Reason: https://community.apollographql.com/t/coming-from-spectrum-welcome/44

Replace Spectrum references with community.apollographql.com

---

docs/source/networking/advanced-http-networking.md

The missing bracket prevents the code from being interpreted.

Added a missing bracket

---

src/core/QueryInfo.ts
src/core/QueryManager.ts
src/react/hooks/__tests__/useMutation.test.tsx

Fixes for refetchQueries #8274, as well as fixes for using document nodes in refetchQueries/include arrays.

RefetchQueries fixes

---

docs/shared/query-result.mdx

Clarify `fetchPolicy` behavior of refetched queries

---

CHANGELOG.md
src/react/data/QueryData.ts

Rebase of https://github.com/apollographql/apollo-client/pull/7980

Optional chaining on usequery

---

docs/source/data/queries.mdx
docs/source/index.mdx

Describe nextFetchPolicy in queries.mdx

---

docs/source/local-state/managing-state-with-field-policies.mdx
docs/source/local-state/reactive-variables.mdx

Minor edits to local state docs

---

docs/source/api/react/hooks.mdx

Fix typo in useLazyQuery API - Function Signature

---

docs/source/api/link/apollo-link-error.md

Fix broken links for error types

Fix broken links

---

docs/shared/mutation-options.mdx
docs/source/api/cache/InMemoryCache.mdx

To resolve remaining omission noted in #7723

Add missing documentation for `fetchPolicy` option of `useMutation`

---

docs/source/performance/optimistic-ui.mdx

Docs examples location has moved

---

docs/source/caching/advanced-topics.mdx

docs: added missing colon in Caching Redirects

---

config/resolveModuleIds.ts

Use path.sep instead of hardcoded "/" to make it work cross platform.

Fix path separator bug in resolveModuleIds.ts

---

src/__tests__/local-state/export.ts
src/cache/core/cache.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/readFromStore.ts
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/watchQueryOptions.ts
src/react/hooks/__tests__/useQuery.test.tsx
src/react/parser/index.ts
src/utilities/graphql/__tests__/getFromAST.ts
src/utilities/testing/mocking/mockFetch.ts

fix general typos and componentDidUpdate in subscription-hoc

---

docs/source/development-testing/static-typing.md

Fixing docs typo

---

docs/source/caching/cache-field-behavior.md
docs/source/caching/overview.mdx
docs/source/development-testing/testing.mdx
docs/source/pagination/overview.mdx

docs: Replace instances of 'data graph' with 'graph'

---

docs/source/api/cache/InMemoryCache.mdx
docs/source/caching/cache-interaction.md

Closes https://github.com/apollographql/apollo-client/issues/8698

document updateQuery/updateFragment

---

docs/package-lock.json
docs/package.json

Getting inconsistent build successes across docsets, trying to line everything up at least until we change our strategy and only have the actual docs "engine" in a single repo

Get AC docs in line with other docset settings

---

ROADMAP.md

Small ROADMAP adjustments

---

docs/source/pagination/core-api.mdx

Fix typo "orignal" to "original"

---

docs/source/performance/optimistic-ui.mdx

Update Optimistic UI Document with inclusive language

---

src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/useLazyQuery.ts

Fix lazy query rejections

---

docs/source/development-testing/client-schema-mocking.mdx

`marak/faker-js` no longer leads anywhere, its new home is https://github.com/faker-js/faker

Update reference to faker-js as new repository

---

docs/source/api/link/apollo-link-subscriptions.md
docs/source/api/link/apollo-link-ws.md
docs/source/api/link/introduction.mdx
docs/source/data/subscriptions.mdx

Edits to new graphqlws subscription docs

---

docs/source/api/link/apollo-link-batch-http.mdx

Update Apollo PersistedQueries in the Apollo BatchHTTP Link

---

ROADMAP.md

Just correcting the wrong link in ROADMAP.md

Correct the wrong link in ROADMAP.md

---

docs/source/data/subscriptions.mdx

Docs: fix typo in subscriptions.mdx

---

docs/source/performance/babel.md

Add link to ts-transform-graphql-tag in the performance docs

---

docs/source/caching/advanced-topics.mdx

Add missing closing parenthesis on code snippet

docs: fix code snippet

---

docs/source/data/file-uploads.md

This PR addresses the changes submitted in #5481 and updates the content from the original submission.

adds documentation on file uploads

---

docs/source/api/link/apollo-link-rest.md

The tests were failing on #9600 so I opted to create  a new PR with the suggested change as it's a good improvement.

fixes pr 9600

---

README.md

Adds myself to the readme. 
This PR exists mostly as a dry-run for branching / opening a pull request / etc.

Add a new maintainer (Yours Truly) to README

---

docs/source/get-started.mdx

The Apollo Client [Getting started](https://www.apollographql.com/docs/react/get-started) article currently relies on a Codesandbox instance that queries the Coinbase API. We decided that it'd be better to better to update this article to use an API that Apollo manages and updates (I ended up going with the [FlyBy API ](https://odyssey-flyby.netlify.app/) from [Voyage I](https://www.apollographql.com/tutorials/voyage-part1/intro-to-federation)).

Update the getting started guide to use the FlyBy API

---

docs/source/api/react/hooks.mdx

Just some small touchups to the PR I saw come through a couple days ago

Minor edits to new useReactiveVar reference

---

docs/source/local-state/local-resolvers.mdx

Updates the warning message pointing to a new issue.

updates local resolver warning

---

CHANGELOG.md

Adds the changes from #10134 to CHANGELOG.md

Add changes from #10134 to CHANGELOG.md

---

ROADMAP.md

oct 2022 roadmap update

---

docs/source/api/link/apollo-link-rest.md
src/link/persisted-queries/index.ts

Small updates for AS4

---

src/core/ApolloClient.ts

Add connect to dev tools check

---

README.md
ROADMAP.md

- updates roadmap for nov 2022
- removes the word apollo from readme maintainer section

updates roadmap nov 2022

---

docs/source/get-started.mdx

docs: displays the error correctly

---

CHANGELOG.md
src/__tests__/__snapshots__/graphqlSubscriptions.ts.snap
src/errors/index.ts
src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap

Add name property to ApolloError

---

CHANGELOG.md

Update CHANGELOG with changes from #10235

---

CHANGELOG.md
docs/source/api/link/apollo-link-batch-http.mdx
docs/source/api/link/apollo-link-http.md
docs/source/networking/advanced-http-networking.md

Adds a changelog entry and documentation for the new `preserveHeaderCase` option from https://github.com/apollographql/apollo-client/pull/9891
- ~~[ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)~~
- ~~[ ] Make sure all of the significant new logic is covered by tests~~

Changelog and docs for preserveHeaderCase

---

.github/PULL_REQUEST_TEMPLATE.md

Adds an item to the pull request template checklist for a changeset if applicable.

chore: update PR template with link to CONTRIBUTING.md

---

docs/source/performance/server-side-rendering.mdx

Fixes the last comment in #6996

docs: Remove errant JSON.parse statement

---

.github/workflows/lock.yml

The change in https://github.com/apollographql/apollo-client/pull/10536 didn't help things. Let's log the output and process only issues to narrow down the cause.

chore: log output and only process issues in lock workflow

---

.github/workflows/snapshot-release.yml

chore: specify owner and head repo in snapshot release action

---

docs/source/get-started.mdx

Update FlyBy API link

---

.changeset/dry-crabs-thank.md

Add missing changeset for #10601

Add a changeset for #10601

---

docs/source/caching/advanced-topics.mdx

docs: Update advanced-topics.mdx to use AsyncStorage from the community package

---

docs/source/development-testing/static-typing.md

fix typo - static-typing.md

---

docs/source/development-testing/testing.mdx

Insert a missing preposition in the documentation for testing react components.

Insert a missing preposition

---

.circleci/config.yml
.size-limit.cjs

This one is for any Tweaks we might want to do to size-limits :)

size-limit tweaks

---

docs/shared/DisplayClientError.js
docs/source/errors.mdx

I _think_ I've gotten a handle on this page and how it'll work, but please scrutinize these edits to make sure I haven't misrepresented anything!

Content edit for AC error page

---

ROADMAP.md

[Rendered](https://github.com/apollographql/apollo-client/blob/update-roadmap/ROADMAP.md)

Add 3.9 to roadmap

---

docs/source/data/queries.mdx

The document mentioned a TypeScript file while it's just a JavaScript file. This PR should fix just that to avoid confusion to developers :)

Update queries.mdx documentation 📃

---

.changeset/pre.json
.circleci/config.yml
package-lock.json
package.json

Updates `package.json` to latest version on `main` and changes the `tag` in `pre.json` to `rc`.

Prepare for `rc` release

---

renovate.json

Let's give this a try? :)
https://docs.renovatebot.com/key-concepts/dashboard/

enable renovate dependencyDashboard

---

docs/source/api/react/ssr.md
docs/source/performance/server-side-rendering.mdx

Update to latest reactjs.org urls in SSR docs

---

.prettierignore
docs/source/config.json
docs/source/development-testing/reducing-bundle-size.mdx

document `globalThis.__DEV__`

---

src/react/hooks/__tests__/useBackgroundQuery.test.tsx

Went to remove these exports but I see you already did @jerelmiller :) Just updated the tests to align with our docs examples.

Refactor tests to remove RefetchFunction/FetchMoreFunction type helpers

---

docs/source/caching/cache-configuration.mdx

fix space issues

---

docs/source/data/fragments.md

Docs: Fix usequery path in Fragments page

---

docs/source/networking/authentication.mdx

Remove unused import in vue example

fix docs: Remove unused split import

---

docs/shared/mutation-result.mdx

add `onQueryUpdated` to `useMutation` execution option docs

---

renovate.json

To unblock the [all devdependencies (major) PR](https://github.com/apollographql/apollo-client/pull/11148), ignore `glob` for now.

Update renovate.json to ignore glob

---

docs/source/integrations/integrations.md

Lit is the current library name and lit.dev the current website.

Replace lit-element with Lit in integrations.md

---

src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/testing/internal/profile/Render.tsx
src/testing/internal/profile/profile.tsx

@jerelmiller can you take a look?

Profiler test render tracking

---

package-lock.json
package.json
src/react/hoc/__tests__/mutations/lifecycle.test.tsx
src/react/hoc/__tests__/queries/observableQuery.test.tsx
src/react/hoc/__tests__/shared-operations.test.tsx

#11148 was bumping a few things that are failing, so I'm doing it manually here now (and fixing the new lint errors)

update some devDependencies

---

integration-tests/browser-esm/html/jspm-prepared.html
integration-tests/browser-esm/html/unpkg-unmangled.html
package-lock.json
package.json
src/cache/inmemory/reactiveVars.ts

This unblocks https://github.com/apollographql/apollo-client/pull/11350 so we can release 3.8.8.

Upgrade optimism version to latest

---

.api-reports/api-report-cache.md
.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/tough-timers-begin.md
docs/shared/useBackgroundQuery-options.mdx
docs/shared/useFragment-options.mdx
docs/shared/useSuspenseQuery-options.mdx
docs/source/api/cache/InMemoryCache.mdx
docs/source/api/react/hooks.mdx
docs/source/caching/garbage-collection.mdx
src/cache/core/types/Cache.ts
src/cache/core/types/DataProxy.ts
src/cache/inmemory/types.ts
src/core/watchQueryOptions.ts
src/react/types/types.ts

deprecate `canonizeResults`

---

docs/source/data/subscriptions.mdx

A follow-on from https://github.com/apollographql/apollo-client/pull/11301.

chore: add docs for relay and urql network adapters

---

docs/source/caching/cache-configuration.mdx

Fix double semicolons in code example

fix: Remove duplicate double semicolon in docs

---

.github/CODEOWNERS

chore: add client-typescript team to CODEOWNERS

---

docs/shared/ApiDoc/EnumDetails.js
docs/shared/ApiDoc/Function.js
docs/shared/ApiDoc/ParameterTable.js
docs/shared/ApiDoc/PropertySignatureTable.js
docs/shared/ApiDoc/getInterfaceReference.js
docs/shared/ApiDoc/index.js
netlify.toml

This reverts commit f688036b0c48f84a60100b6ff3574a3940baf953.
Need to see if the docs build correctly with this now.

Revert "Revert "Replace Generics in PropertySignatureTable""

---

CHANGELOG.md

The example code in the changelog was not in the right place.

move `createQueryPreloader` example

---

docs/source/caching/advanced-topics.mdx

Update outdate link in advanced-topics.mdx

---

docs/source/integrations/integrations.md

Update Vue.js plugin link to new GitHub repository

---

.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_internal.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.size-limits.json
docs/shared/ApiDoc/PropertySignatureTable.js
docs/source/api/react/components.mdx
docs/source/caching/memory-management.mdx
docs/source/data/mutations.mdx
docs/source/data/queries.mdx
docs/source/data/subscriptions.mdx
src/core/ApolloClient.ts
src/react/hooks/useFragment.ts
src/react/internal/cache/QueryReference.ts
src/react/query-preloader/createQueryPreloader.ts
src/react/types/types.documentation.ts

Closes  https://github.com/apollographql/apollo-client/issues/11687.

fix: options links and remove @ link syntax

---

.github/workflows/change-prerelease-tag.yml
.github/workflows/exit-prerelease.yml
.github/workflows/prerelease.yml

chore: remove unneeded repositories and owner config

---

.github/workflows/change-prerelease-tag.yml
.github/workflows/prerelease.yml

chore: update prerelease.yml

---

package-lock.json
package.json

Splits out update from https://github.com/apollographql/apollo-client/pull/11767

Upgrade react testing library to next major

---

.changeset/clean-icons-sparkle.md
.size-limits.json
src/react/hooks/useMutation.ts

Fixes concerns that were brought up in ##11852

`useMutation`: use `useIsomorphicLayoutEffect` instead of `useLayoutEffect`

---

.github/workflows/prerelease.yml

Reverts apollographql/apollo-client#11941
Round 3 😂

Revert "Add back "fix: skip PR creation if no prerelease changesets exist"""

---

docs/source/api/link/persisted-queries.mdx
docs/source/data/defer.mdx

Updates uses of "Apollo Router" to "GraphOS Router" or "Apollo Router Core" where necessary

Update router terminology

---

README.md

Updates "Who is Apollo" text and links.

Update "Who is Apollo"

---

README.md

Adding a short announcement one-liner to bring visibility to GraphQL Summit

Update README.md with summit callout

---

.changeset/wet-shirts-juggle.md
.size-limits.json
src/react/hooks/useSubscription.ts

Fix missing `getServerSnapshot` function for useSubscription

---

renovate.json

This is a mix of renovate options, I hope one of them does the trick.

renovate: don't request reviewers

---

docs/source/data/suspense.mdx

- fix positions of destructured parameters for useLoadableQuery hook

docs: Update suspense.mdx

---

docs/source/data/refetching.mdx

Fix wrong typographical error in the documentation from `ingore` to `ignore`

[docs] small typographical error in refetching.mdx

---

src/utilities/caching/sizes.ts

Addresses discrepency reported in https://github.com/apollographql/apollo-client/issues/12011.

Update default value referenced in comments for cache sizes

---

src/__tests__/ApolloClient.ts

While working on data masking, I wanted to validate that `watchFragment` could handle nested fragments and fragments registered with the fragment registry. Thankfully this already works, but I did not see any existing tests that checked these assumptions, so this PR adds 2 tests to ensure we don't break this use case with data masking.

Add some tests for `watchFragment` for nested fragments and the fragment registry

---

.changeset/fuzzy-shrimps-call.md
.size-limits.json
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts

Fixes #12048 - thank you for the report @maciesielka

useFragment: keep current result on a memoized mutable object

---

docs/source/pagination/core-api.mdx

Closes https://github.com/apollographql/apollo-client/issues/12079

Make it clearer that fetchMore variables merge is a shallow merge in docs

---

package-lock.json
package.json
patches/eslint-plugin-testing-library+6.3.0.patch
src/react/components/__tests__/client/Query.test.tsx
src/react/components/__tests__/client/Subscription.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
src/testing/experimental/__tests__/createTestSchema.test.tsx
src/testing/internal/index.ts
src/testing/internal/renderHelpers.tsx
src/testing/matchers/index.d.ts

@testing-library/react-render-stream api bikeshedding

---

src/masking/types.ts

Fixes the failing API report check on the 3.12 branch

Fix failing api report check

---

.changeset/kind-toys-tie.md

Add missing changeset from #12121

Add changeset for #12121

---

.changeset/cold-apes-bow.md
CHANGELOG.md

Republish 3.12.0-rc.0 since it accidentally published as 3.11.11-rc.0 🤦‍♂️

Fix 3.12 rc changelog

---

src/react/types/types.documentation.ts

clarification for mutationHookOptions.ignoreResults in the docs

---

src/core/__tests__/masking.test.ts

I accidentally merged a few tests that had incorrect assertions in #12141 so this fixes them for accuracy.

Fix incorrect assertions on several tests

---

src/core/masking.ts

One more pass at some refactoring in an attempt to reduce some bundle size.

Refactor masking algorithm to reduce bundle size

---

.size-limits.json
src/core/masking.ts

Some last final byteshaving for masking

data masking byte shaving

---

.changeset/light-carpets-double.md
.circleci/config.yml
package-lock.json
package.json

Updates our dev dependency and allowed peer dependency range for React 19.

Bump React deps to v19 stable release

---

.changeset/clever-zebras-mate.md
.circleci/config.yml
package-lock.json
package.json

Closes #12185
Drops support for React 16.

Drop support for React 16

---

docs/source/development-testing/schema-driven-testing.mdx
docs/source/development-testing/testing.mdx
src/react/hooks/__tests__/useQuery.test.tsx

Fix size of CodeSandbox buttons ([1](https://www.apollographql.com/docs/deploy-preview/5a45ee6884bd86d00296769a/react/development-testing/testing#sandbox-example), [2](https://www.apollographql.com/docs/deploy-preview/5a45ee6884bd86d00296769a/react/development-testing/schema-driven-testing#sandbox-example))

docs: set Codesandbox button width

---

docs/source/data/queries.mdx

Some parts of the fetch policy information don't have space.

docs: add missing spaces in fetchPolicy table

---

docs/source/api/link/apollo-link-subscriptions.md

Fixes link on subscriptions page as reported by docs feedback

docs: fix link

---

src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx

These two are quite flaky so I hope this helps a bit.

de-flake tests

---

scripts/memory/package-lock.json
scripts/memory/package.json
scripts/memory/tests.cts
scripts/memory/tsconfig.json

another small tooling-related one

remove dependency on `mocha` from memory tests

---

.changeset/grumpy-dogs-add.md
.size-limits.json
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/react/internal/cache/QueryReference.ts

turn queryRef symbols into `Symbol.for` calls

---

.api-reports/api-report-react.api.md
.size-limits.json
eslint-local-rules/import-from-export.ts
eslint-local-rules/index.mjs
eslint.config.mjs
src/cache/index.ts
src/core/index.ts
src/index.ts
src/link/batch-http/index.ts
src/link/batch/index.ts
src/link/core/index.ts
src/link/retry/index.ts
src/react/index.react-server.ts
src/react/index.ts
src/testing/core/index.ts
src/testing/index.ts
src/testing/internal/index.ts
src/utilities/index.ts
src/utilities/internal/index.production.ts
src/utilities/invariant/index.development.ts

replace wildcard re-exports with individual exports

---

src/__tests__/client.ts
src/__tests__/graphqlSubscriptions.ts
src/__tests__/mutationResults.ts
src/core/__tests__/ApolloClient/general.test.ts

Reducing some more noise in core tests by fixing some warnings emitted to the console.

Silence more core tests warnings

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-testing_experimental.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/chilled-hornets-watch.md
.changeset/strange-wolves-fold.md
.changeset/weak-radios-trade.md
.size-limits.json
src/core/ObservableQuery.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/types.ts

Changes in tests right now show up where this still needs to be adjusted/fixed.

refactor some code in `QueryInfo`

---

.api-reports/api-report-core.api.md
src/core/index.ts

I just noticed this while reviewing #12562, so I thought we can get this fixed real quick.

fix up some type exports in `/core`

---

src/__tests__/refetchQueries.ts

rewrite `refetchQueries` with deterministic order of `onQueryUpdated` calls

---

docs/source/local-state/local-resolvers.mdx

See https://github.com/apollographql/apollo-client/issues/10060#issuecomment-2859223414 for motivation

Remove local resolvers deprecation message

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-errors.api.md
.api-reports/api-report-link.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-testing_internal.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report-utilities_internal.api.md
.api-reports/api-report.api.md
config/build.ts
config/deprecateInternals.ts
config/helpers.ts
config/inlineInheritDoc.ts
package.json

New build step: @deprecated tag for @internal apis

---

.github/workflows/prerelease.yml

See https://github.com/apollographql/apollo-client/actions/runs/15311280548

Fix failing version command

---

.circleci/config.yml

This is temporary until we get to #12688

temporarily disable the Next.js integration test

---

.api-reports/api-report-link_http.api.md
.api-reports/api-report.api.md
.changeset/old-avocados-cover.md
.changeset/tame-rice-explain.md
.size-limits.json
src/link/http/BaseHttpLink.ts
src/link/http/HttpLink.ts
src/link/http/__tests__/HttpLink.ts
src/link/http/selectHttpOptionsAndBody.ts

Add `accept` option to `HttpOptions`

---

.api-reports/api-report-link_context.api.md
.api-reports/api-report-link_error.api.md
.api-reports/api-report-link_http.api.md
.api-reports/api-report-link_persisted-queries.api.md
.api-reports/api-report-link_remove-typename.api.md
.api-reports/api-report.api.md
.changeset/weak-owls-buy.md
src/__tests__/__snapshots__/exports.ts.snap
src/link/context/__tests__/index.ts
src/link/context/index.ts
src/link/error/index.ts
src/link/http/HttpLink.ts
src/link/persisted-queries/__tests__/persisted-queries.test.ts
src/link/persisted-queries/index.ts
src/link/remove-typename/index.ts
src/link/remove-typename/removeTypenameFromVariables.ts

This PR is best viewed without whitespace

migrate links to classes

---

.changeset/silent-lobsters-try.md

This was missed yesterday but we should also make the new codegen package rc.

Release codegen as rc

---

.api-reports/api-report-react.api.md
.changeset/mighty-jobs-drum.md
.size-limits.json
scripts/codemods/ac3-to-ac4/src/imports.ts
src/__tests__/__snapshots__/exports.ts.snap
src/react/index.ts

Don't export `gql` from `/react` entrypoint

---

config/apiExtractor.ts

preserve original docblocks in `client.api.json`

---

.api-reports/api-report-errors.api.md
.api-reports/api-report.api.md
.size-limits.json
config/build.ts
config/inlineInheritDoc.ts
src/errors/CombinedGraphQLErrors.ts

allow variables in `inheritDocs`

---

.github/workflows/prerelease.yml

This should fix the error in https://github.com/apollographql/apollo-client/actions/runs/16756024344

Fix prerelease workflow

---

.changeset/great-seas-buy.md
.size-limits.json
config/processInvariants.ts

`invariant.error` should be called in prod

---

.github/workflows/prerelease.yml

Fixes https://github.com/apollographql/apollo-client/actions/runs/16793132874/job/47558558616

Try fixing release again

---

.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report.api.md
.changeset/weak-goats-melt.md
.size-limits.json
src/core/index.ts
src/masking/index.ts
src/masking/types.ts

Followup from https://github.com/apollographql/apollo-client/pull/12837#discussion_r2266187448

Remove the `DataMasking` interface

---

.changeset/flat-suns-watch.md
.size-limits.json

Adds the missing changeset for #12838 so that we can release the new entrypoint. I will update to the corrected commit hash and PR number in the changelog before rc.12 is released.

Adds changeset for #12838

---

.api-reports/api-report-v4-migration.api.md
.changeset/sour-wasps-bathe.md
scripts/codemods/ac3-to-ac4/README.md
scripts/codemods/ac3-to-ac4/src/__tests__/apolloClientInitialization.test.ts
scripts/codemods/ac3-to-ac4/src/apolloClientInitialization.ts
scripts/codemods/ac3-to-ac4/src/removals.ts
scripts/codemods/ac3-to-ac4/src/renames.ts
src/v4-migration.ts

last-minute codemod tweaks and corrections

---

packages/ai/src/mocking/GrowingSchema.ts
packages/ai/src/mocking/__tests__/GrowingSchema.test.ts

This is a bit of a different approach - I'll comment inline.

GrowingSchema: split schema growing and response validation

---

docs/source/integrations/integrations.mdx

Package hasn't been updated since 7 years + only seems to support `"apollo-client": "^1.0.1"`. Probably not worth recommending that…

Remove polymer-apollo

---

.github/workflows/release.yml
.size-limits.json

Publish works fine but there was an error trying to parse the published packages. This attempts to fix

Update release script (again)

---

.github/workflows/release.yml

Actually fix publish slack message

---

.size-limits.json
docs/source/data/file-uploads.mdx

https://github.com/jaydenseric/apollo-upload-client/issues/359 added support for Apollo Client v4 in v19.0.0. This change includes the new import location for 4.0

Update file uploads page
