apollographql/apollo-client

design.md
I think we should agree on a set of principles that define why this library exists. They will help frame future decisions about the design, and make it clear how it is different from other GraphQL client libraries.
=> Draft: Design principles

appveyor.yml, package.json
This PR brings support for using the free tier of [Appveyor](http://www.appveyor.com/) to test this project on windows alongside the linux test travis is running. An apollosstack account will need to be setup on appveyor, then this project selected to build it. We can also add an Appveyor badge if wanted once that is configured.
Example build: https://ci.appveyor.com/project/NewSpring/apollo-client/build/1.0.5
=> Add windows testing via Appveyor

src/diffAgainstStore.ts, test/readFromStore.ts, test/writeToStore.ts
The response from the GraphQL fragment:
```
fragment FragmentName on Item {
stringField,
numberField,
nestedObj {
stringField,
numberField
}
}
```
Can contain a null field instead of any field or a nested object:
```js
const result = {
id: 'abcd',
stringField: 'This is a string!',
numberField: 5,
nullField: null,
nestedObj: null,
};
```
This PR handles that correctly, whereas before it would have errored when reading from the store.
=> Add tests and handling for null response fields

src/QueryManager.ts, src/debug.ts, src/diffAgainstStore.ts, src/networkInterface.ts, src/parser.ts, src/queryPrinting.ts, src/readFromStore.ts, src/store.ts, src/storeUtils.ts, src/writeToStore.ts, test/QueryManager.ts, test/diffAgainstStore.ts, test/networkInterface.ts, test/queryPrinting.ts, test/readFromStore.ts, test/roundtrip.ts, test/writeToStore.ts, tsconfig.json
We now define a list of entry files we want to include in the build instead of using a `exclude` list of directories.
=> Remove reference paths

.vscode/launch.json, src/QueryManager.ts, src/parser.ts, src/store.ts, test/QueryManager.ts
Addresses #29 
Currently doesn't support variables, we need to add support for those in queries _and_ mutations.
=> Super basic mutation support

src/QueryManager.ts, src/diffAgainstStore.ts, src/readFromStore.ts, src/store.ts, src/storeUtils.ts, src/writeToStore.ts, test/QueryManager.ts, test/readFromStore.ts, test/roundtrip.ts, test/writeToStore.ts
Definitely requires a fair amount of changes!
Basically, everywhere we kept track of queries, fragments, or selection sets before, we need to pass along variables now.
Fixes #31
=> Variable support

src/QueryManager.ts, src/networkInterface.ts, test/QueryManager.ts, test/networkInterface.ts
This fixes #33 
A GraphQL server can respond back to a query with both data and errors. The network interface does not currently handle that.
```
interface GraphQLResult {
data?: Object;
errors?: Array<GraphQLError>;
}
````
@stubailo how do you want me to handle this? If the result has data I can pass it back as a `<GraphQLResult>` and the query manager can split the data up?
=> Pass errors to handler function in network interface

.travis.yml, package.json, src/QueryManager.ts, src/diffAgainstStore.ts, src/index.ts, src/queryPrinting.ts, src/storeUtils.ts, src/writeToStore.ts, test/QueryManager.ts, test/diffAgainstStore.ts, test/queryPrinting.ts, typings.json
Working on implementing #42, looking for feedback on the design there! Not ready for feedback on the implementation though.
=> Enable query diffing

src/writeToStore.ts, test/readFromStore.ts, test/writeToStore.ts
Since lists from GraphQL should be of the same type, this basically just places the array in the store as is if the first non-null item in the array is a scalar.
Does this make sense, or do we want to try to denormalize it? That looks like it will be a little messier, as the GraphQL parser doesn't treat arrays of scalars that way.
=> Arrays of Scalar Values

.travis.yml, appveyor.yml
This PR updates Travis and Appveyor to always run on the latest versions of both LTS and stable. Since Travis uses `nvm` (also see https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against), we can just use `4` to load the latest LTS version (which will be the 4.x series until the next LTS is released) and `5` to run the latest stable version (which is currently 5.x). See also https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png. I believe Appveyor follows the same semantics (https://www.appveyor.com/docs/lang/nodejs-iojs#selecting-node-js-or-io-js-version).
=> Run Travis / Appveyor on latest Node LTS / stable

src/QueryManager.ts, src/index.ts, src/store.ts, test/QueryManager.ts, test/client.ts, test/store.ts, test/tests.ts
This brings all of the apollo data in redux under one key. It defaults to `apollo`, but gives the option to supply your own key (with or without an existing store). It also adds some tests and warnings for using an existing store.
With regards to using an existing store, here were my thoughts. We may be on the same page here, but just wanted to get it written down :smile_cat: 
It doesn't seem like best practice, or like redux really wants you to, dynamically add reducers to an existing store unless using the `replaceReducer` function. Using `replaceReducer` requires you to have all of the other reducers in the store handy, then doing a `combineReducers`, and passing that to `existingStore.replaceReducers(newlyCombinedReducers)`.
It feels dirty to have people passing all their reducers to …
=> Refactor apollo data in to top level key

src/data/extensions.ts, src/data/store.ts, src/data/writeToStore.ts, src/index.ts, src/store.ts, test/QueryManager.ts, test/diffAgainstStore.ts, test/store.ts, test/writeToStore.ts
Fixes #93 - "don't treat ID as special unless told to do so"
Still needs new tests for querying for data with `id`, but without the extension.
Also, changes internal APIs for `createApolloStore` and `apolloReducer` - no external API changes though.
=> Get rid of hardcoded 'id'

package.json, src/QueryManager.ts, src/data/diffAgainstStore.ts, src/queryPrinting.ts, test/QueryManager.ts, test/diffAgainstStore.ts, test/queryPrinting.ts
Fixes #109 and #85 
✅  Still need to write a test for variable definition and query name preservation in QueryManager.
Also, we can do query diffing in a smarter way, going to file an issue about that soon.
=> [WIP] Turn off forceFetch by default, preserve query name and variables

src/QueryManager.ts, src/actions.ts, src/index.ts, src/queries/store.ts, test/QueryManager.ts, test/client.ts
Extracted from @martijnwalraven's PR #97 
Fixes #78
=> Implement basic network error handling

package.json, src/data/extensions.ts, src/index.ts
A few minor bugs I ran across when building apollo-react.
- Change binding methods of client (`this` was undefined on the client methods)
- Fix oddity in typescript definitions
I also exported a couple of the readFromStore utils to setup a manual cache read for now until a sync way to get existing data is in place
=> Minor bug fixes and exporting of readFromStore utils for manual cache reads

src/QueryManager.ts, src/data/store.ts, src/queries/store.ts, test/QueryManager.ts
We can do this better in the future by actually canceling the request itself fwiw
=> Fix potential error on returning result after unsubscribed

src/QueryManager.ts, test/QueryManager.ts
`refetch(variables: any)` is now possible on a query handle.
Fixes #131
=> allow passing variables into a query refetch

src/index.ts, src/store.ts, test/client.ts, test/store.ts
Initial discussion here: https://github.com/apollostack/react-apollo/issues/22
When performing server side rendering, the apollo-client populates the store with all of the data the app requested. In order to save subsequent requests on the client side, the PR exposes a way to rehyrdate the internal redux store with the data from the server.
The added api to the client makes it easy to integrate into any SSR methods / stack.
```js
const client = new ApolloClient({
initialState,
});
```
```js
// on server during render
// after application has gotten all of the data it needs
const initialState = client.store.getState()
// inject into template
<script>window.__APOLLO_STORE__ = initialState</script>
// on client
const client = new ApolloClient({
initialState: __APOLLO_STORE__,
});
```
=> allow for rehydrating the store

Gruntfile.js, package.json, src/networkInterface.ts, src/util/Observable.ts, test/client.ts, test/mocks/mockNetworkInterface.ts, test/networkInterface.ts
We weren't linting any subdirs of `src` before. Fixed resulting lint errors.
Fixes #137
=> Fix linting to actually run on all files using Grunt

.travis.yml
Deploys will now be run by Travis based on specified git tags. When creating a new tag, travis will be notified and try to deploy that commit to npm.
=> setup library for auto-deploys

.gitignore, .travis.yml, package.json, scripts/deploy.sh
@stubailo @helfer @martijnwalraven 
This PR brings in the ability to locally run `npm run deploy` and ship a new build
=> Deploy script

CHANGELOG.md, src/data/resultUtils.ts, src/data/store.ts, src/queries/store.ts, test/QueryManager.ts
=> Fix #156 by accepting non-spec-compliant empty error array

package.json, src/util/Observable.ts, test/QueryManager.ts
=> Add basic interoperability with other Observable implementations

CHANGELOG.md, src/queries/getFromAST.ts
=> Add docs URL to error message

CHANGELOG.md, src/gql.ts, test/gql.ts, test/tests.ts
=> Memoize gql parse results

CHANGELOG.md, src/QueryManager.ts, test/QueryManager.ts
=> Log unhandled network errors

CHANGELOG.md
I didn't realize that NPM actually treats minor version bumps as breaking changes in the `0.x.y` series of versions, so users still get warned about breaking changes even when Apollo Client is not 1.0. This means we should only bump to the 1.0 version once it's important to have a stable API and we consider breaking changes a lot more carefully than we do now.
=> Update 1.0 goal in changelog

CHANGELOG.md, src/QueryManager.ts, src/data/diffAgainstStore.ts, src/index.ts, test/QueryManager.ts, test/client.ts
The goal is to allow people to pass their own ID getter functions to pick the key that is used for an object when it is put into the store. This addresses #204, but also makes #180 much easier.
TODO:
Testing strategy:
=> [WIP] Pluggable normalization

CHANGELOG.md, src/QueryManager.ts, src/actions.ts
Prefix Action Types with `APOLLO_`
[#210](https://github.com/apollostack/apollo-client/issues/210)
TODO:
=> rename action types

CHANGELOG.md, src/QueryManager.ts, test/QueryManager.ts
This is for a change to the QueryManager on refetch to return a Promise instead of void. By returning a promise you eliminate the need to wrap any requests for updating data. So instead of:
```js
refreshFeed = (resolve, reject) => {
this.props.data.refetch();
resolve();
}
<ReactPullToRefresh
onRefresh={ this.refreshFeed }>
</ReactPullToRefresh>
```
You can call `refetch` directly from the Compontent: 
```js
<ReactPullToRefresh
onRefresh={ this.props.data.refetch }
</ReactPullToRefresh>
```
TODO:
=> Refetch promise

ambient.d.ts, package.json, src/QueryManager.ts, src/queries/queryTransform.ts, test/queryTransform.ts, test/tests.ts, typings.json, typings/browser/ambient/apollo-client/index.d.ts, typings/main/ambient/apollo-client/index.d.ts
Added the __typename addition logic with unit tests. Haven't integrated with QueryManager yet - will do that as the next step. #27 
TODO:
=> Implement method to add __typename field to queries

CHANGELOG.md, src/QueryManager.ts
Fix for #231.
* Add check for `listener` in QueryManager's `broadcastQueries()`
It is possible the deletion of a query listener in `stopQuery()`
and the `forOwn` iteration of query listeners in `broadcastQueries()` to
overlap, causing a race condition. This explicitly checks that
the listener exists before attempting to invoke it.
=> Resolve stopQuery/broadcastQueries race condition

CHANGELOG.md, package.json, src/QueryManager.ts, src/index.ts, src/queries/queryTransform.ts, test/QueryManager.ts, test/client.ts, test/queryTransform.ts
Added a way to plug a query transform function into the QueryManager constructor so that fields other than just `__typename` can be added to the query AST.
#230 
TODO:
=> Pluggable query transforms

CHANGELOG.md, package.json, src/QueryManager.ts, test/client.ts, test/queryTransform.ts
Fixed the bug where queries weren't getting updated on when forceFetch was set to true.
TODO:
=> [0.3.12] Fixed so that queries can be transformed on forceFetch=true

CHANGELOG.md, src/QueryManager.ts, src/actions.ts, src/data/store.ts, src/mutations/store.ts, test/client.ts
Implements named fragments within mutations.
Solves #273.
TODO:
=> Named fragments within mutations

src/QueryManager.ts, test/QueryManager.ts
Test regarding issue #239. Hope this is okay.
=> Add test for QueryManager continuing to poll after refetch (see issue #239)

src/data/storeUtils.ts, test/QueryManager.ts, test/client.ts, test/writeToStore.ts, typings/browser/globals/graphql/index.d.ts, typings/main/globals/graphql/index.d.ts
This is a work in progress to add support for object parameters in mutations and thus support reindex.io default mutation format.
I did succeed in making all tests pass BUT the fix is obviously wrong so I reach out here to get feedback on which other part of the project should be breaking so I can add some tests there and create a proper fix.
I also reused a duplicated test.
=> [WIP] Allow objects parameters in mutations

CHANGELOG.md, src/QueryManager.ts, src/networkInterface.ts, src/queries/getFromAST.ts, test/client.ts, test/getFromAST.ts
Sending the operation name of the query down the server (probably helpful for logging, etc.).
TODO:
=> Send operation name to the server

src/batching/queryMerging.ts, test/queryMerging.ts
A small fix for an issue that came up when testing query merging with GitHunt. Basically, consider a a query with two top level fields:
```
query {
fortuneCookie
__typename
}
```
Then, suppose this query is composed with other queries. It used to be that only the last field would get written to the decomposed data - this PR fixes that. No update to CHANGELOG because this is not a user-facing change (yet) since batching has not been exposed (yet).
TODO:
=> Query merging fix

CHANGELOG.md, src/batching/queryMerging.ts, test/queryMerging.ts
This PR fixes the issue #296 and incorporates the test provided in #297.
It seems that if `gql` is passed exactly the same query document twice, it will return a reference to the same object. This can be problematic when we want to merge the two queries. This PR changes how the requests array is cloned so that this isn't an issue.
TODO:
=> Fix query merging with the same query with diff. variable values

CHANGELOG.md, package.json
=> Bump version and add to changelog

CHANGELOG.md, src/index.ts
TODO:
It'd be nice to import `writeQueryToStore` and `writeFragmentToStore` directly.
=> Export writeQueryToStore and writeFragmentToStore.

CHANGELOG.md, src/data/readFromStore.ts, test/readFromStore.ts
TODO:
Adds optional `returnPartialData` argument to `readQueryFromStore` and `readFragmentFromStore`.
While implementing updates from a CouchDB `_changes` feed, I found that I sometimes had information from the feed that wasn't yet in the store. While I could use `readSelectionSetFromStore` and pass `returnPartialData: true`, it seems that having the option to `returnPartialData` from both `readQueryFromStore` and `readFragmentFromStore` would be useful.
=> Add optional returnPartialData argument.

CHANGELOG.md, src/queries/queryTransform.ts, test/queryTransform.ts
=> Don't add duplicate field names

CHANGELOG.md, src/index.ts, test/client.ts
Exposed a `printAST` method that can be used to turn query ASTs into query strings.
TODO:
=> Expose printAST

CHANGELOG.md, src/QueryManager.ts, src/index.ts, src/queries/getFromAST.ts, src/scheduler.ts, test/QueryManager.ts, test/client.ts, test/getFromAST.ts
Adding a way to reference fragments from different components of your application and compose queries using those fragments. See #338 
TODO:
=> Fragment referencing/Query composition support

CHANGELOG.md, ambient.d.ts, package.json, src/QueryManager.ts, src/index.ts, src/networkInterface.ts, src/queryPrinting.ts, test/client.ts, test/getFromAST.ts, test/mocks/mockNetworkInterface.ts, test/networkInterface.ts, test/queryMerging.ts, test/queryTransform.ts, test/scopeQuery.ts, typings/browser/globals/apollo-client/index.d.ts, typings/browser/globals/apollo-client/typings.json, typings/browser/globals/graphql/index.d.ts, typings/browser/modules/lodash/index.d.ts, typings/main/globals/apollo-client/index.d.ts, typings/main/globals/apollo-client/typings.json, typings/main/globals/graphql/index.d.ts, typings/main/modules/lodash/index.d.ts
Success:
```
➜  apollo-client git:(no-graphql-dep) tree node_modules | grep graphql
├── graphql-tag
```
Should resolve #261 and #163
This is to work around https://github.com/graphql/graphql-js/issues/414
Thanks for @abhiaiyer91's work on bundling in the dependency into `graphql-tag`.
TODO:
=> Remove graphql dependency entirely

CHANGELOG.md, src/data/diffAgainstStore.ts, test/diffAgainstStore.ts
I'm still experimenting with this in my app, so I'm not sure this is at all the correct approach to fix #359. Any thoughts/pointers/direction?
TODO:
=> WIP: Return undefined for fields not in store. (fixes #359)

CHANGELOG.md, src/index.ts
=> export addQueryMerging

CHANGELOG.md, src/networkInterface.ts, test/networkInterface.ts
=> Made sure single queries are not merged together

CHANGELOG.md, src/queries/directives.ts, test/directives.ts
=> Don't throw on unknown directives

CHANGELOG.md, src/QueryManager.ts, src/scheduler.ts, src/util/Observable.ts, test/QueryManager.ts, test/getFromAST.ts
=> Move methods to observable (Issue #194)

CHANGELOG.md, src/QueryManager.ts, src/errors.ts, src/index.ts, src/scheduler.ts, test/QueryManager.ts, test/client.ts, test/errors.ts, test/tests.ts
Unifying the error handling so that both GraphQL errors and network errors will be presented in the form of rejected promises or errors on observers. This makes it easier to deal with both types of errors and not have to always introduce two different types of error handling code.
TODO:
=> [Breaking change] Unify error handling

.travis.yml
TODO:
I've never seen something pass in 4 and 6 but fail in 5, and nobody should be using 5 anyway since it's not LTS or the latest stable.
=> Remove node 5 from tests to speed things up

.vscode/launch.json, CHANGELOG.md, ambient.d.ts, package.json, src/QueryManager.ts, src/actions.ts, src/data/mutationResults.ts, src/index.ts, src/mutations/store.ts, src/optimistic-data/store.ts, src/store.ts, test/QueryManager.ts, test/client.ts, test/optimistic.ts, test/store.ts, test/tests.ts, typings/browser/globals/apollo-client/index.d.ts, typings/main/globals/apollo-client/index.d.ts
=> [WIP] Optimistic UI

CHANGELOG.md, src/data/mutationResults.ts, test/mutationResults.ts
What's the preferred kind of test case for this, where a map function unintentionally returned `undefined`? I added one, but it seems…strange.
TODO:
=> WIP: Fix map function returning undefined.

CHANGELOG.md, src/data/diffAgainstStore.ts
Trying to improve an error message by using `JSON.stringify` so `storeObj` doesn't show up as `[Object object]` in the console all the time. I suppose it is possible that `storeObj` would be so big that we wouldn't want to do that…but I've not run in to that personally.
I'm not sure if adding the bit about `returnPartialData` is really the best advice, though it is certainly one common solution I've ended up using. Thoughts?
TODO:
=> Improve error message.

CHANGELOG.md, src/QueryManager.ts, src/index.ts
Adds an option that lets the application developer specify the width of the batcher's polling interval. Fixes #394 
TODO:
=> Add batcherPollInterval as an option to ApolloClient

CHANGELOG.md, src/QueryManager.ts, src/data/readFromStore.ts, test/QueryManager.ts
This PR makes it so that observables are only fired when the data received changes. This means that observers will only be fired if there's an updated result in the store. We do a deep diff before doing this. Solves #400. 
I ran a comparison using the Chrome CPU profiler with and without this particular changeset on the Galaxy UI. 
Before: 
After: 
There is a single large element on this page that isn't changing in this particular query. As you can see clearly in the "before", this element is rendered for no reason and this rendering is eliminated in the "after". Secondly, there is also consistently reduced time to render the list of items that _are_ changing since some of them don't actually change (~80ms to ~40ms). This isn't a particularly complex page so the performance improvements …
=> Don't fire any query observables if the query result didn't change

CHANGELOG.md, src/QueryManager.ts, src/actions.ts, src/data/mutationResults.ts, src/data/writeToStore.ts, src/index.ts, test/mutationResults.ts, test/optimistic.ts, test/writeToStore.ts
=> Mutation reducers

CHANGELOG.md, src/QueryManager.ts, src/index.ts, src/queries/getFromAST.ts, src/queries/queryTransform.ts, test/getFromAST.ts, test/queryTransform.ts
=> Refactored query transformer (Issue #373)

package.json, src/data/store.ts
The soon-to-be-released v2.0 of TypeScript will bring a lot of new cool features. Cherry-picking the releases notes, I believe the apollo-client will especially benefit from the discriminated union types (https://github.com/Microsoft/TypeScript/pull/9163), the smarter flow analysis, and the explicit `null` and `undefined` checks.
This PR updates the Typescript compiler to use the v2.0-[beta](https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/). There is one logic error detected by the new flow analysis:
```
106             result: action.result,
~~~~~~
src/data/store.ts(106,28): error TS2339: Property 'result' does not exist on type 'QueryResultAction | QueryErrorAction | QueryInitAction | QueryResultClientAction | QueryStopActio...'.
```
I haven’t …
=> Update Typescript to 2.0

test/client.ts
Added a (passing) test that checks whether or not the list of fragment definitions is flattened by `createFragment`. Motivated by #421 
TODO:
=> Fragment flattening

src/index.ts
There is no `/src` after publishing ApolloClient to the npm so TypeScript is very angry.
Closes #429
=> Fix paths of ObservableQuery and WatchQueryOptions in index.ts

test/QueryManager.ts
Added a test for the error that is supposed to be thrown when we try to `noFetch` a polling query.
TODO:
=> Added a test for `noFetch` error

CHANGELOG.md, src/queries/getFromAST.ts, test/client.ts
This fixes an issue that arises when you perform the same query multiple times, and that query has fragments.
Because `addFragmentsToDocument` _appends_ fragments to `queryDoc.definitions`, each time the query is performed, the query document gains a new copy of each fragment.  This is particularly egregious, since `graphql-tag` maintains an identity map for queries.
For example, the following currently results in a server error (duplicate fragment authorDetails) on the second query:
```js
const fragments = createFragment(gql`
fragment authorDetails on Author {
author {
firstName
lastName
}
}`);
const query = gql`{ author { ...authorDetails } }`;
client.query({query, fragments}); // Success
client.query({query, fragments}); // BOOM: Duplicate fragment authorDetails
```
=> Bugfix: Don't mutate fragments that are attached to query documents

CHANGELOG.md, package.json, src/ObservableQuery.ts, src/QueryManager.ts, src/actions.ts, src/data/diffAgainstStore.ts, src/data/mutationResults.ts, src/data/replaceQueryResults.ts, src/data/store.ts, src/index.ts, src/watchQueryOptions.ts, test/fetchMore.ts, test/mocks/mockNetworkInterface.ts, test/tests.ts
TODO:
Design:
- `fetchMore` method on an observable query
- allows to fetch the same query, or a new query with any amended variables, fragments, etc
- the results of the `fetchMore` query always are fetched from the server
- the reducer function passed into `fetchMore` is responsible for merging the new result into the existing query results
=> Initial implementation of `fetchMore`

CHANGELOG.md, src/QueryManager.ts, src/index.ts, test/QueryManager.ts, test/client.ts, test/scheduler.ts
Added loading state tracking as per #464, #466 and #342.
TODO:
=> Added loading state tracking

CHANGELOG.md, src/ObservableQuery.ts, src/QueryManager.ts, src/index.ts, test/QueryManager.ts
Added an `invalidateQueries` option to `client.mutate` as per #448. 
TODO:
Rebased on top of Slava's PR #472.
=> Refetch queries

CHANGELOG.md, src/ObservableQuery.ts, test/fetchMore.ts
TODO:
------
This is kinda a bug that wasn't caught by the original test suite for `fetchMore`. I will add another test for this.
=> Extend original variables in refetch and fetchMore

CHANGELOG.md, src/ObservableQuery.ts, src/QueryManager.ts, src/util/errorHandling.ts, test/mutationResults.ts
=> Do not swallow errors from user-submitted functions

src/QueryManager.ts
=> Refactoring fetchQueryOverInterface within QueryManager

CHANGELOG.md, src/ObservableQuery.ts, test/fetchMore.ts
=> `updateQuery` on ObservedQuery

CHANGELOG.md, src/QueryManager.ts, src/data/diffAgainstStore.ts, test/QueryManager.ts
TODO:
After diffing queries, removing parts that could be queried from the store,
some variables in the query can become unused, causing errors pointing
out unused variables.
This patch, walks the query and fragments asts and filters out the variables
no longer used.
=> Remove unused variables from queries

CHANGELOG.md, src/batching/queryMerging.ts, test/queryMerging.ts
From @amandajliu's work w/ GitHunt, we discovered that there were some issues with the way query merging handled arrays and null values in the response. This PR fixes those issues.
TODO:
=> Fixed bugs with query merging

CHANGELOG.md, src/scheduler.ts, test/scheduler.ts
Reopened https://github.com/apollostack/apollo-client/pull/555 to add changelog and merge.
TODO:
=> Fix scheduling when the poll interval is the same, thanks @pfulop

CHANGELOG.md, src/data/diffAgainstStore.ts, test/QueryManager.ts
=> Collect used variables in directives

src/index.ts
instead of arrow functions on top of properties.
Without that it really hurts to do something like `super.watchQuery` :crying_cat_face: 
---
=> Refactor ApolloClient to use direct methods

package.json, src/index.ts, test/client.ts
This simply exposes a `resetStore` method on the client and passes the call along to the `QueryManager`.
I added a test to confirm the `QueryManager` method gets called, but wasn't sure it was necessary to re-test the store actually being reset, since that's tested in `QueryManager`. But I'm happy to add it if we do need it.
Fixes #567
=> Client Reset Store Method

src/AUTHORS, src/QueryManager.ts
👋 Was walking through the code base and noticed the `networkInterface` arg passed to `fetchQueryOverInterface` was in fact never used in that fn.
It seems like the only place where it ends up being used is in the `QueryBatcher`, which already has a reference to the `networkInterface`.
All tests and linters still pass so I assume it was indeed not needed.
TODO:
=> Remove unused networkInterface argument in fetchQuery

CHANGELOG.md, src/store.ts
=> If there are no optimistic updates to apply, return immediately.

CHANGELOG.md, src/batching/queryMerging.ts, test/queryMerging.ts
Fixes #551. Would be great if @jmiazga could confirm whether this PR works.
Tested and works correctly on GitHunt.
TODO:
=> Fixed the error passing situation with query merging

CHANGELOG.md, src/batching/queryMerging.ts, test/queryMerging.ts
=> Explore directives for variable usages in query merging

CHANGELOG.md, src/batchedNetworkInterface.ts, src/networkInterface.ts, test/batchedNetworkInterface.ts, test/client.ts, test/mocks/mockFetch.ts, test/tests.ts
Adds transport-level query batching support to Apollo Client (see #505).
TODO:
=> Transport-level query batching

CHANGELOG.md, src/data/diffAgainstStore.ts, test/diffAgainstStore.ts
https://github.com/apollostack/apollo-client/pull/580
TODO:
=> Improve partial data to work with fragments

CHANGELOG.md, src/networkInterface.ts
=> Overridable options in network layer for middleware

src/queries/getFromAST.ts, test/getFromAST.ts
Throws an error if type definitions detected in queries other than "OperationDefinition" and "FragmentDefinition".
TODO:
=> Fix issue #636

package.json, test/client.ts, test/mutationResults.ts, tsconfig.json, typings.d.ts
=> Back to use noImplicitAny

package.json, src/data/diffAgainstStore.ts, test/readFromStore.ts
=> Remove deepAssign, use lodash.merge to fix null fragment bug

src/QueryManager.ts, test/QueryManager.ts
Because `QueryManager` uses a map of `queryResults: queryId => result`, and `queryListenerForObserver` checks diffs against query results, `next()` callbacks don't trigger for the second subscriber.
This is a particular problem as `observer.result()` internally uses a subscriber, so it's not even that unusual a use-case.
=> Failing test for subscribing twice.

CHANGELOG.md, src/QueryManager.ts, test/QueryManager.ts
Fix for bug identified in #690 and #594 (in the latter, some further API possibilities are discussed, but this addresses only the narrower case of #690).
=> allow unknown query in refetchQueries, warn but continue

CHANGELOG.md, src/QueryManager.ts, src/queries/store.ts, test/client.ts, test/mutationResults.ts
=> Fix #647 - Read store in returnPartialData mode if the previous queries failed or were cancelled

src/ObservableQuery.ts, src/QueryManager.ts, test/ObservableQuery.ts
<strike>This PR is rebased from https://github.com/apollostack/apollo-client/pull/635.</strike>
<strike>It also should not be merged until we've confirmed with RA.</strike>
=> Add observable query current result

test/QueryManager.ts, test/util/observableToPromise.ts
@helfer I was thinking about how it's awkward to pass `done` around and how mocha is much more suited to dealing with promises, and I figured out a way to turn something that fires multiple times (like an observable) into a promise that resolves or rejects.
What do you think? Does it make it hard to understand what the tests are doing?
These two sample tests are pretty much unmodified by the change (in terms of what they do).
=> First implementation of observable to promise

CHANGELOG.md, package.json, src/core/QueryManager.ts, src/data/debug.ts, src/data/diffAgainstStore.ts, src/data/readFromStore.ts, src/data/storeUtils.ts, src/index.ts, test/diffAgainstStore.ts, test/readFromStore.ts, test/roundtrip.ts
Part of https://github.com/apollostack/apollo-client/issues/728
First step towards https://github.com/apollostack/apollo-client/issues/617
TODO:
-----
Still to do:
=> Refactor query reading to use graphql-anywhere

package.json, src/data/debug.ts, src/data/mutationResults.ts, src/data/writeToStore.ts, typings.d.ts
Removed `lodash.isarray` from codebase to stop npm warning on install. Switched with `Array.isArray`
TODO:
=> Removes lodash.isarray dependency in favor of Array.isArray

CHANGELOG.md, src/core/ObservableQuery.ts, test/QueryManager.ts
I noticed recently when using refetch that requests kept being made when other changes caused a component to rerender. This was traced back to the refetch method incorrectly changing the options on the query to set forceFetch to be true versus having it only apply to the manual refetch call.
TODO:
=> refetch should only modify variables on original query

AUTHORS, CHANGELOG.md, package.json
=> Fixed #713 with OptionalDependencies approach

CHANGELOG.md, src/ApolloClient.ts, src/actions.ts, src/core/QueryManager.ts, src/core/watchQueryOptions.ts, src/data/mutationResults.ts, src/data/resultReducers.ts, src/data/store.ts, src/optimistic-data/store.ts, src/store.ts, test/mutationResults.ts, test/optimistic.ts
TODO:
Things to note:
1. The reducer will run on every result, including the result of its own query.
2. The reducer (right now) does not run on subscription results (pending subscription API change), and it does not run on query results that didn't hit the server (i.e. QUERY_RESULT_CLIENT). It also doesn't run when errors are returned. We may need to update this in the future.
3. Reducers run serially. A reducer gets the store with modifications from previous reducers already applied.
4. Reducers run after writing the result to store, and after result behaviors.
This feature could use a few more tests to make sure the interactions with other features (eg. optimistic updates) is solid.
=> WIP: Result reducers

CHANGELOG.md, package.json, src/data/readFromStore.ts, src/data/writeToStore.ts, test/client.ts, test/diffAgainstStore.ts, test/mutationResults.ts, test/readFromStore.ts, test/roundtrip.ts, test/tests.ts, test/util/wrap.ts
=> Rewrite fragment evaluation to do less guessing

CHANGELOG.md, src/actions.ts, src/core/QueryManager.ts, src/data/store.ts, test/graphqlSubscriptions.ts
=> Make GraphQL subscriptions fire a redux action

CHANGELOG.md, src/ApolloClient.ts, src/core/QueryManager.ts, src/index.ts, src/queries/queryTransform.ts, src/transport/networkInterface.ts, test/QueryManager.ts, test/client.ts, test/fetchMore.ts, test/graphqlSubscriptions.ts, test/mocks/mockQueryManager.ts, test/mutationResults.ts, test/optimistic.ts, test/queryTransform.ts, test/scheduler.ts, test/tests.ts
=> Implement addTypename option and remove queryTransformer

CHANGELOG.md, src/core/QueryManager.ts, src/data/readFromStore.ts, src/data/writeToStore.ts, test/QueryManager.ts, test/client.ts, test/networkInterface.ts, test/tests.ts
=> WIP: Fix reject on refetch

CHANGELOG.md, src/core/ObservableQuery.ts, test/ObservableQuery.ts
Fix issue as discussed @helfer. Has been released in 0.4.22
=> Return errors from `currentResult`.

CHANGELOG.md, src/queries/store.ts, src/store.ts, test/client.ts, test/store.ts
Partially solves https://github.com/apollostack/apollo-client/issues/732
TODO:
=> Fix rehydration

src/data/resultReducers.ts, test/mutationResults.ts
Fixes an issue with result reducers running before a query finished loading and adds a test for it.
TODO:
=> fix result reducer bug with partialData

package.json, test/QueryManager.ts, test/tests.ts, tsconfig.json, typings.d.ts
This is primarily to make it work w/ typedoc.
=> Make typings work w/o using `compilerOptions.lib`.

package.json
I don't think it's needed in `dependencies`.
Also, it makes a problem because `es6-promise` is defined twice, in `dependencies` and `devDependencies` with different version requirements.
=> Remove unnecessary es6-promise

AUTHORS, CHANGELOG.md, src/transport/networkInterface.ts, test/networkInterface.ts
=> Enable chaining for middlewares and afterwares in the network interface - Issue 564

CHANGELOG.md, src/ApolloClient.ts, src/core/watchQueryOptions.ts, src/index.ts
Would help a lot with things like this
https://github.com/apollostack/angular2-apollo/issues/141#issuecomment-257858263
=> Create and expose MutationOptions ;)

CHANGELOG.md, src/index.ts
@helfer This way you could switch `DeprecatedSubscriptionOptions` with some new interface that is not deprecated and it won't break `angular2-apollo`
=> Expose SubscriptionOptions

CHANGELOG.md, src/ApolloClient.ts
This will help with this problem: http://stackoverflow.com/questions/36677733/why-jsx-props-should-not-use-arrow-functions
TODO:
=> bind resetStore to this

src/core/QueryManager.ts
as explained here #870, the options.reducer function of graphql does currently not automatically include the `__typename`.
=> watchQuery should respect addTypename

src/data/mutationResults.ts, src/data/readFromStore.ts, src/data/writeToStore.ts, test/client.ts, test/mutationResults.ts, test/optimistic.ts, test/readFromStore.ts, test/writeToStore.ts
I was hacking around with some ideas for inspecting the store, and ran into a problem - ID references are not always stored the same way.
When it's an object field, the reference looks like:
```js
fieldKey: {
type: 'id',
id: 'asdf',
generated: false,
}
```
When it's an array field, it's not wrapped at all:
```js
fieldKey: [
'asdf',
'qwer',
]
```
This is problematic if one wants to write a tool that can follow query trees through the store. Looks like when we initially refactored to escape these IDs in the store, we didn't go all the way and totally forgot about arrays.
This PR fixes it to look like:
```js
fieldKey: [
{ type: 'id', id: 'asdf', generated: false },
{ type: 'id', id: 'qwer', generated: false },
}
```
Note: This involved updating some of the old mutation behavior code. We …
=> Make storing IDs in arrays consistent with the rest of the store

src/core/QueryManager.ts
When `observer.next` is called in `queryListenerForObserver` based on the results of a given query and *itself* throws an error, the error handling logic surrounding it automatically casts that error into an `ApolloError`, even though it didn't originate within `apollo-client`. 
This is a big problem in `react-apollo` (see [this issue](https://github.com/apollostack/react-apollo/issues/326)). `observer.next` calls the method that forces a rerender, and when child components throw an error they bubble up and wind up being handled by the `catch` statement in `queryListenerForObserver`, which turns it into an `ApolloError`, effectively swallowing the error.
This PR rearranges the error handling logic in order to effectively capture errors that occur *within* `apollo-client` (such as …
=> Fix error handling for observer.next

AUTHORS, package.json, src/queries/getFromAST.ts, test/getFromAST.ts, typings.d.ts
See this [issue](https://github.com/apollostack/react-apollo/issues/325) on `react-apollo` to see what lead to this coming to this particular repo, and #897 for information on the bug / temporary workarounds.
Attaching multiple references to the same fragment results in the creation of an invalid document - we want to make sure we’re only attaching _distinct_ fragments to the document.
Attaching multiple references to the same fragment like:
```js
const someFragment = createFragment(gql`
fragment SomeFragment on SomeEdge {
someField
}
`);
const someOtherFragment = createFragment(gql`
fragment SomeOtherFragment on SomeEdge {
...SomeFragment
}
`, [someFragment, someFragment]);
```
results in a query document that looks like
```graphql
query {
fragment SomeOtherFragment on SomeEdge { …
```
=> Only attach distinct fragments to document

CHANGELOG.md, src/ApolloClient.ts, src/core/QueryManager.ts, src/data/readFromStore.ts, src/data/resultReducers.ts, src/data/storeUtils.ts, src/index.ts, src/store.ts, test/QueryManager.ts, test/customResolvers.ts, test/readFromStore.ts, test/tests.ts
These are the cherry-picked commits from #809 to implement only cache redirects (and not yet fully support client-side computed fields).
TODO:
=> Cache redirects

AUTHORS, CHANGELOG.md, src/core/QueryManager.ts
TODO:
Fixes https://github.com/apollostack/apollo-client/issues/891
The error wasn't caught anywhere. Should anything be done with the error? For subscriptions it is handled via the store I believe.
=> Catch `fetchQuery` errors in `startQuery`.

CHANGELOG.md, src/core/QueryManager.ts, src/store.ts, test/QueryManager.ts, test/client.ts, test/store.ts
TODO:
We prevent throwing inside the reducer by wrapping it in a try/catch block. The error will still be reported to the user.
=> Safe Apollo Reducers that can't crash the store

CHANGELOG.md, src/core/QueryManager.ts, test/client.ts
=> Catch errors in observer.next and error.next

CHANGELOG.md, src/ApolloClient.ts, src/fragments.ts, test/client.ts, test/tests.ts
=> deprecate fragments everywhere

appveyor.yml
disables node_modules caching since the npm client can't update dependencies properly
=> remove appveyor cache

CHANGELOG.md, package.json, src/ApolloClient.ts, src/core/QueryManager.ts, src/store.ts
This PR changes any places that uses `Object.assign` with lodash's assign function. This is so the library is usable on IE without having to use polyfills. Other places in the code were using lodash/assign aside from these two spots.
=> Use lodash/assign instead of Object.assign

AUTHORS, CHANGELOG.md, src/actions.ts, src/core/QueryManager.ts, src/core/watchQueryOptions.ts, src/queries/store.ts, test/QueryManager.ts, test/client.ts, test/store.ts
Libraries such as react-apollo can pass metadata with their queries,
which can be read by tools such as the Apollo Chrome DevTools.
=> Add "metadata" argument to watchQuery

CHANGELOG.md, package.json, src/ApolloClient.ts
=> Check explicitly for production instead of development for dev tools (v0.5.20)

CHANGELOG.md, package.json, scripts/deploy.sh, src/ApolloClient.ts, src/version.ts
=> Add version to client instance

AUTHORS, CHANGELOG.md, analyze/src/index.js, analyze/webpack.config.js, package.json
Added a new analyze script to the package.json that makes it possible to inspect what modules make it into the published package and how efficiently it bundles in a webpack v2 project.
The script runs a compilation and builds the analyze test project (that only imports this library) with webpack and the webpack-bundle-analyzer plugin in production mode. Once complete the plugin opens  your browser to an interactive analysis at http://localhost:8888.
See [discussion](https://github.com/apollostack/apollo-client/issues/684#issuecomment-266983921).
=> Added an analyze script

CHANGELOG.md, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/queries/store.ts, test/QueryManager.ts, test/client.ts, test/mutationResults.ts, test/optimistic.ts, test/store.ts
Fixes #902 #903 (?) #993 #1026 
This was a pretty hairy affair, but I think I've managed to untangle things enough so that stopped queries are now actually removed from the store and no longer tracked. That means that their reducers and updateQuery functions no longer run.
I don't think #903 is really fixed by this, but the discussion there is so long that I think it's better if we start a new issue about running reducers for other variables than the current query variables (cc @richburdon @yurigenin)
TODO:
=> Fix reducers

AUTHORS, package.json, src/transport/batchedNetworkInterface.ts, src/transport/networkInterface.ts, test/batchedNetworkInterface.ts, test/mocks/mockFetch.ts
Reverts apollostack/apollo-client#1018
Turns out isomorphic-fetch doesn't work in react native.
=> Revert "Ensure transporters are using isomorphic-fetch instead of browser only whatwg-fetch"

src/core/ObservableQuery.ts, src/core/QueryManager.ts, test/ObservableQuery.ts
Hi,
QueryObservable setOptions method does not handle switching from noFetch=true to noFetch=false.
This PR solves this.
If you agree, I can add test (eventually please give me some indication if it is not straightforward).
=> setOptions now handle going from noFetch=true to noFetch=false

src/data/mutationResults.ts, src/data/resultReducers.ts
References issue #939.
This allows the reducer to use variables passed to the query in order to determine whether the data is relevant to that query or not.
=> Pass query variables to reducer function

src/index.ts
Enables writing:
```js
<RefreshControl
refreshing={this.props.data.networkStatus === NetworkStatus.refetch}
onRefresh={this.handleRefetch}
/>
```
instead of current:
```js
<RefreshControl
refreshing={this.props.data.networkStatus === 4}
onRefresh={this.handleRefetch}
/>
```
TODO:
=> Expose NetworkStatus enum in the public API

CHANGELOG.md, src/core/QueryManager.ts, test/client.ts
=> Set variables to an empty object if undefined

test/client.ts
Closes https://github.com/apollostack/apollo-client/issues/807
It seems like the issue itself was fixed, but perhaps a test had not yet been added?
=> Add Test: network interface rejection

CHANGELOG.md, package.json, src/transport/batchedNetworkInterface.ts, src/transport/networkInterface.ts, test/batchedNetworkInterface.ts, test/mocks/mockFetch.ts, test/networkInterface.ts
After much discussion we decided to add whatwg-fetch back in, at least until version 1.0.
No longer including a fetch polyfill will break Apollo Client for users on older browsers or Safari, and developers might not find out about it in their tests, so it seems prudent to keep it until we can find out a way to make it very clear that a fetch polyfill should be installed alongside Apollo Client.
=> Add whatwg-fetch back in

AUTHORS, CHANGELOG.md, src/ApolloClient.ts
fixes #800
Enabling strictNullChecks in apollo-client itself caused a lot of errors so while it may be best solution over time, this is a quicker one that fixes the current errors.
=> fix: Typescript error with strictNullChecks

CHANGELOG.md, src/core/QueryManager.ts, src/data/storeUtils.ts, test/mutationResults.ts, test/writeToStore.ts
Fixes https://github.com/apollostack/apollo-client/issues/852 and https://github.com/apollostack/apollo-client/issues/1094 but only for mutations (its the Apollo reducer errors that get swallowed, not user reducer errors. Although user code may be called from the Apollo reducer).
This invalidates a previously expected behavior so I had to delete an old test. However the old behavior was a rejection of functionality allowed by the spec (or more accurately by GraphQL server implementations). By removing the test and changing the functionality we are not introducing a breaking change.
In https://github.com/apollostack/apollo-client/issues/852 @stubailo also mentioned updating [`graphql-anywhere`](https://github.com/apollostack/graphql-anywhere/blob/5335986c60786d62734f701385648a7da59ecff1/src …
=> Support optional arguments in mutations

src/core/ObservableQuery.ts, test/ObservableQuery.ts
WIP - failing test for https://github.com/apollostack/apollo-client/issues/1077
TODO:
=> Do not fire a query when changing options if unsubscribed

.travis.yml
I get a lot of email notifications from Travis that are just noise. This disables email notifications. If you like getting emails we can enable them selectively: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
Talked to @helfer who is for this change.
=> Disable email notifications

CHANGELOG.md, src/core/QueryManager.ts, src/scheduler/scheduler.ts, src/transport/batching.ts
Removed explicit typing for NodeJS.Timer so as to not impose node typings on projects that depend on apollo-client
PR per Issue: https://github.com/apollographql/apollo-client/issues/1247
All tests passing, lint passing, compiles without error.
=> Removed explicit typing for NodeJS.Timer

CHANGELOG.md, src/core/ObservableQuery.ts
Closes https://github.com/apollographql/apollo-client/issues/1255
=> Remove orphan promise

src/transport/networkInterface.ts
Touched on in #439.
This is an attempt at implementing a request retry when a request returns with a `401`.
Changes in this PR plus the below afterware seem to work for our purposes.
```
{
applyAfterware(res, next) {
if (res.response.status === 401) {
return res.response.json().then((json) => {
if (json.errorCode === 'TOKEN_NEEDS_REFRESH') {
console.log(`Error: ${json.errorCode}`)
// Get the new oauth2 token.
return fetch(`${ckHttpClient.API_URL}/oauth2/token`, {
method: 'POST',
headers: getHeaders(),
body: JSON.stringify({
'refreshToken' : window._REFRESH_TOKEN
})
}).then((res) => {
return res.json()
}).then((data) => {
// Put the token on the window object.
if (data.accessToken && data.refreshToken) {
window._ACCESS_TOKEN = data.accessToken
window._REFRESH_TOKEN = data.refreshToken …
```
=> mutations for afterware to support retrying requests

src/core/QueryManager.ts
=> Don't compare against cache if forceFetch is true

src/transport/batching.ts
I am currently trying to get batching working with persisted queries (https://github.com/apollographql/persistgraphql). Very recently, a PR has been merged which makes this much easier. However, the batching network interface from apollo-client currently swallows every request values except for "query", "operationName", and "variables".
The change in this PR simply pipes through any properties from the request objects in the batch.
=> Do not swallow request attributes when using query batching.

CHANGELOG.md, ROADMAP.md, src/core/QueryManager.ts, src/core/types.ts, test/ObservableQuery.ts, test/QueryManager.ts, test/customResolvers.ts, test/subscribeToMore.ts, test/util/subscribeAndCount.ts
This adds an initial naïve implementation that prefers stale data over partial data. When we are about to update our observers and we see that we can only get partial data from the store, instead of throwing an error (which was the old behavior) we instead return the data from the last result and set a `stale` flag to true.
Theoretically, a more detailed algorithm would only return stale data for individual objects instead of the entire result, but this should be more than enough to provide a better user experience than an error.
This is another item on our 1.0 roadmap.
=> Return stale data over error

CHANGELOG.md, ROADMAP.md, src/actions.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/queries/networkStatus.ts, src/queries/store.ts, test/fetchMore.ts
Closes https://github.com/apollographql/apollo-client/issues/851
This PR makes sure that the `fetchMore` network status is set appropriately in Redux when `fetchMore` is called from `ObservableQuery`. Because `fetchMore` spawns a new query with a different id the implementation of this network status is a little tricky. It feels like the best way to do it is adding the query id we may be fetching more for to our Redux actions which will change the network status on the correct query. Unfortunately, there is no easy, clean, way to do that.
This PR also cleans up error handling for `fetchMore` so if an error is thrown in a query spawned by `fetchMore` that error will be correctly propagated back to the parent query.
I contemplated keeping the information required to compute a `fetchMore` …
=> Use `fetchMore` network status

CHANGELOG.md, src/core/watchQueryOptions.ts
The typescript def for refetchQueries only accepts strings. Adding the option for a the object syntax as well.
=> Adding updated typescript defs for refetchQueries.

CHANGELOG.md, src/index.ts
@helfer @stubailo I ran into an issue with testing where I needed the ability to addTypename.
Since adding typename to the document is the default in apollo client, applications typically have them added to their query before flight. When we want to mock the query using the mockNetworkinterface (https://github.com/apollographql/apollo-test-utils/blob/master/src/mocks/mockNetworkInterface.ts#L200 or https://github.com/apollographql/react-apollo/blob/master/src/test-utils.tsx#L227), we need to add the typename to the query from the test. This can be done on the test level, or possibly in the react-apollo or test-utils mockNetworkInterface.
Either way, we will need the exported addTypename.
TODO:
=> export addTypenameToDocument to root export

src/errors/ApolloError.ts
Removes manual stack trace setting. This is the cause of our error stack traces only showing `Error:` and not displaying a message.
=> Remove manual stack trace setting

CHANGELOG.md, package.json, src/core/QueryManager.ts, src/index.ts, src/transport/Deduplicator.ts, src/transport/networkInterface.ts, test/client.ts, test/getFromAST.ts, test/mocks/mockNetworkInterface.ts, test/networkInterface.ts, test/proxy.ts, test/queryTransform.ts, typings.d.ts
`graphql-tag` has deprecated the export of the `printer` export (which we use for various AST-related tasks here in `apollo-client`). when `graphql-tag@v2` comes out, we can switch to using the printer / parser from the `graphql` package, but for now we know about the deprecation warning and can safely ignore it.
addresses [graphql-tag#54](https://github.com/apollographql/graphql-tag/issues/54)
TODO:
=> Bumping `graphql-tag`, ignoring deprecation warnings

src/core/QueryManager.ts, test/client.ts
This is an alternate approach to #1348 for fixing #1141. This approach is a bit more of a head-scratcher when you run into the code, but it doesn't break as many tests.
=> Rethrow caught errors in setTimeout

CHANGELOG.md
then rc-2 has been introduced in  https://github.com/apollographql/apollo-client/commit/f8e48d937a33ca0271a55dda9a7a8b6d1d0cd0eb, the wrong version string has slipped into the changelog. 
Fixing that...
=> Fix a typo in the version number

package.json
This PR adds a package.json script that runs `node --inspect` (see [here](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.e7rtzv53j))  on the benchmarks so that we can easily look at traces. 
TODO:
=> Added benchmark:inspect to package.json

CHANGELOG.md, src/core/ObservableQuery.ts, test/fetchMore.ts
This patch fix issue #1384
TODO:
=> Remove data property from fetchMore result

src/ApolloClient.ts
Kept the type as `string | ApolloStateSelector` so that the tests can allow for backcompat / an upgrade path
TODO:
=> Fix documentation for reduxRootSelector, reduxRootSelector must be a function

src/ApolloClient.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/types.ts, test/graphqlSubscriptions.ts
This patch removes duplicate SubscriptionOptions interface definition from types and changes it from document to query.
TODO:
=> Remove duplicate SubscriptionOptions interface

CHANGELOG.md, src/core/QueryManager.ts, test/client.ts
=> Fix mutation error action before reject ApolloError

package.json
After cloning the project and running `npm install`, `npm run dev` would fail unless you happened to have nodemon installed globally. It is best practice to define dependencies per-project.
=> Added missing nodemon devDependency.

src/core/QueryManager.ts
Fixes #1449.
Obvious in retrospect. Note to self for next time: when in doubt, don't merge.
Reverts apollographql/apollo-client#1133
=> Revert "Do not swallow execute errors"

CHANGELOG.md, src/index.ts
Added `HTTPBatchedNetworkInterface` as an index export to make it easier
to subclass externally, consistent with `HTTPFetchNetworkInterface`.
Also tidied some of the whitespace and comments nearby.
=> Export HTTPBatchedNetworkInterface from the package index.

CHANGELOG.md, src/core/ObservableQuery.ts, src/core/watchQueryOptions.ts, test/subscribeToMore.ts
This patch fix #871 using the recommendations of #879
TODO:
=> Make updateQuery option of subscribeToMore optional

src/ApolloClient.ts
Gotta catch em all!
(this prints a suggestion to install the devtools to the console of Chrome users during development)
=> add devtools suggestion to Apollo Client

CHANGELOG.md, src/transport/Deduplicator.ts, test/deduplicator.ts, test/fetchMore.ts
=> Fix deduplicator

CHANGELOG.md, src/core/QueryManager.ts
This sets `notifyOnNetworkStatusChange` back to `false` by default. It was an issue because many folks were surprised that their components were re-rendering more often.
We decided that it was better to revert this change now even though it's breaking, because we assume that very few people have made the switch yet and come to rely on this feature.
=> Revert notify

src/transport/networkInterface.ts, test/client.ts
=> Throw a network error only if there's not GraphQL errors

CHANGELOG.md, src/ApolloClient.ts, src/core/QueryManager.ts, src/data/fragmentMatcher.ts, src/data/fragmentMatcherIntrospectionQuery.ts, src/data/proxy.ts, src/data/readFromStore.ts, src/index.ts, src/queries/queryTransform.ts, src/store.ts, test/client.ts, test/diffAgainstStore.ts, test/fragmentMatcher.ts, test/proxy.ts, test/readFromStore.ts, test/roundtrip.ts, test/tests.ts
Fixes #1337 #1363 #1379 #1113 #857 #771 #1297 #1273 #961 #933
Not 100% sure all of these issues will be fixed, but it should fix a good number of them.
TODO:
=> WIP: Fragment matcher

src/core/ObservableQuery.ts
Fixes #1032
I'm not sure if the error message is too verbose.
=> Make fetchMore throw an error if the updateQuery option is missing

package.json, typings.d.ts
thanks to apollographql/graphql-tag#63 `graphql-tag@^1.3.2` contains declaration of `print` function.
=> Remove the declaration of graphql-tag/bundledPrinter

src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/data/fragmentMatcher.ts, test/ObservableQuery.ts, test/client.ts, test/fragmentMatcher.ts
This PR removes the auto-init functionality from the new fragment matcher (to make it synchronous) and fixes a small bug that caused currentResult to return empty data in some circumstances.
=> Fix currentResult / fragment matcher

CHANGELOG.md
Correct form is `fetchPolicy`
TODO:
=> Rename mistakingly called `cachePolicy` in changelog

CHANGELOG.md, package.json, src/ApolloClient.ts, test/client.ts
Reverts apollographql/apollo-client#1597
This PR broke some expectations around what fetch policies are allowed in combination with pollInterval.
=> Revert "Added default query options"

CHANGELOG.md, src/data/fragmentMatcher.ts, src/data/writeToStore.ts, src/util/warnOnce.ts, test/ApolloClient.ts, test/diffAgainstStore.ts, test/proxy.ts, test/readFromStore.ts, test/roundtrip.ts, test/tests.ts, test/util/wrap.ts, test/warnOnce.ts
Print a warning when the heuristic fragment matcher is used on an interface or union fragment condition.
TODO:
=> FragmentMatcher warning

CHANGELOG.md, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/watchQueryOptions.ts, test/ObservableQuery.ts, test/QueryManager.ts, test/client.ts
This PR introduces a new fetch policy, which can be used by react-apollo and other integrations to keep a query in Apollo's store, but mark it as "standby". Standby queries will not watch the store, will not be refetched on store reset, but can be used in `updateQueries` and `refetchQueries` calls. This is mainly a response to issues like https://github.com/apollographql/react-apollo/issues/622 and https://github.com/apollographql/react-apollo/issues/531.
=> Recycler standby

.travis.yml, src/index.ts
This PR will run tests for react-apollo on every CI build of apollo-client. The goal here being that we want to ensure we don't break other libs when updating / changing AC. 
If this works, I'd love to add in apollo-angular (and any other popular libs needed).
This will make testing feedback take longer so we don't want to add *everything*
This points to https://github.com/apollographql/react-apollo/pull/679 but when that and #1644 are merged, we can point to master.
> This also removes node 4 from the testing matrix. Node 4 ships with npm 2 which doesn't like the mixed peer deps with react-apollo. Instead of updating npm, since node 4 is in no longer active (https://github.com/nodejs/LTS) lets just use node 6
@helfer those PR's don't need to be released necessarily, just merged to master
=> [WIP] Linked test ci

src/index.ts
@helfer there were a few types that react-apollo was importing from sub directories in AC. This made local linked dev + CI linking a pain / impossible.
TODO:
=> exported react-apollo types for easier local dev

CHANGELOG.md, src/data/readFromStore.ts, src/data/writeToStore.ts
TODO:
unfortunately my editor settings are such that it hides directories called data, previous pr [#1643] was not complete
=> fix more object assign

CHANGELOG.md, src/data/readFromStore.ts, test/QueryManager.ts, test/roundtrip.ts
Fixes #1551
This bug was due to an error introduced in the PR that tried to ensure referential equality between subsequent results.
TODO:
=> Fix null array bug

src/ApolloClient.ts, src/core/QueryManager.ts, src/scheduler/scheduler.ts, test/QueryManager.ts
Fixes #1334 (polling during SSR should be disabled)
=> Disable polling during SSR

src/index.ts
Exposing getMutationDefinition on the client so mutations can be tracked via apollo-client-devtools.
- Discussion can be found here https://github.com/apollographql/apollo-client-devtools/issues/35
- PR for apollo-client-devtools can be found here https://github.com/apollographql/apollo-client-devtools/pull/36
I am not that familiar with this typescript, so not 100% if there is anything else I need to do. If there is please let me know and I will sort it out. I don't think any tests are required, but if you feel otherwise let me know. I haven't updated any docs as functions like getQueryDefinition is not documented.
=> Exposed getMutationDefinition for devtools enhancement

test/diffAgainstStore.ts, test/roundtrip.ts
These tests now fail because they are not throwing the `console.error`
=> Tests that use withError were silently failing

CHANGELOG.md, src/data/writeToStore.ts
When an error occurs in `writeToStore`, the error message is enhanced with the body of the location source. The source doesn't always exist, however, so we should check before trying to access its body. Here is an example of this happening:
TODO:
=> Check if location source exists when rethrowing in `writeToStore`

AUTHORS, CHANGELOG.md, src/actions.ts, src/core/QueryManager.ts, src/core/watchQueryOptions.ts, src/optimistic-data/store.ts, test/optimistic.ts
Allow the developer to pass a function instead of an object to `optimisticResponse`:
```js
const optimisticResponse = ({ text }) => ({
__typename: 'Mutation',
createTodo: {
__typename: 'Todo',
id: '99',
text,
completed: true,
},
});
```
This will allow more flexibility in where/how the `optimisticResponse` is defined - it will no longer have to be colocated with the call to `mutate()` in order to get the data context for the response, allowing code reuse and more choices for ui framework integration.
I'm new to typescript, so let me know if I need to do something different with the type changes.
TODO:
discussed with @helfer prior to submission, and it's small - but it's been a while since we discussed it, and it affects the external API, so happy to discuss.
If this looks good, I'll do …
=> Optimistic response function

AUTHORS, CHANGELOG.md, src/ApolloClient.ts, src/core/QueryManager.ts, test/QueryManager.ts
=> Reset store returns a promise

.travis.yml
This method turned out to be more of a pain then a help. Working on a different way now but in the meantime, I'm going to pin the AC version on react-apollo so greenkeeper will work for us
=> remove inital version of dep linking

AUTHORS, CHANGELOG.md, src/data/fragmentMatcher.ts
The types:
`Original` : what is currently on `master`
`Fixed`: proposal in this PR
----
`data` represents a schema that will break due to invalid typing of `possibleTypes`.
`data2` will generate an error.
----
TL;DR;, I am trying to consume a GraphQL endpoint that is returning `[]` in `possibleTypes`, which `apollo-client` is refusing to accept.
```ts
type Fixed = {
__schema: {
types: [{
kind: string,
name: string,
possibleTypes: {
name: string,
}[],
}],
},
};
type Original = {
__schema: {
types: [{
kind: string,
name: string,
possibleTypes: [{
name: string,
}],
}],
},
};
const data: Fixed = {
__schema: {
types: [
{
kind: 'someKind',
name: 'someName',
possibleTypes: []
}
]
}
};
const data2: Original = data; 
```
=> IntrospectionResultData: fix broken typing

AUTHORS, CHANGELOG.md, src/ApolloClient.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/data/readFromStore.ts, src/data/store.ts, src/data/storeUtils.ts, src/queries/queryTransform.ts, src/transport/networkInterface.ts, test/client.ts, test/networkInterface.ts, test/readFromStore.ts, test/util/wrap.ts, test/writeToStore.ts
This gives the client specific knowledge of the `@connection` directive so that the store key can be properly derived from the directive. This also updates the query transformer to remove the directive before sending requests to the server. This fixes #1779 
TODO:
=> Specifically handle the connection directive when selecting store keys, fix #1779

package.json
Started causing problems with types of `process.env` at 8.0.4.
=> Pin @types/node again

AUTHORS, CHANGELOG.md, src/ApolloClient.ts, src/transport/networkInterface.ts, test/client.ts, test/mocks/mockNetworkInterface.ts
Adds adapter that converts an ObservableNetworkInterface, which returns an Observable, to a normal NetworkInterface. This provides the entry point for the new network layer, which returns Observables.
TODO:
=> Add Observable support in the Network Interface

package-lock.json
Just runned `npm install` and it changed the lock file. Sounds like this change was forgotten.
=> Updated package-lock.json to 1.7.0.

CHANGELOG.md, src/actions.ts, src/core/QueryManager.ts, src/data/store.ts, src/optimistic-data/store.ts, src/queries/store.ts, src/store.ts, test/client.ts, test/store.ts
Depends on https://github.com/apollographql/apollo-client/pull/1857
TODO:
=> Remove the dependencies on queries and mutations in the store from the data resolver

rollup.config.js
Since there's the `window.Redux` [available](https://github.com/reactjs/redux#installation) we can take advantage of it.
`const globals = {}` - is a space to put packages that's objects are available in global scope.
`exports: 'named'` - just to stay close to what rollup's [documentation says](https://rollupjs.org/#big-list-of-options)
=> Instrument rollup to use window.Redux

CHANGELOG.md, package.json, src/ApolloClient.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/mutations/store.ts, src/queries/store.ts, src/scheduler/scheduler.ts, src/store.ts, test/QueryManager.ts, test/client.ts, test/store.ts, test/tests.ts
Depends on https://github.com/apollographql/apollo-client/pull/1846
This moves out the query store out from Redux into a separate class. Many now unused Redux actions are still dispatched for compatibility with applications that depend on those actions.
TODO:
=> Remove the query store from Redux

CHANGELOG.md, package.json, src/ApolloClient.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/mutations/store.ts, src/queries/store.ts, src/scheduler/scheduler.ts, src/store.ts, test/QueryManager.ts, test/client.ts, test/optimistic.ts, test/store.ts, test/tests.ts
=> Remove mutation tracking from the store

CHANGELOG.md, src/data/store.ts, test/fetchMore.ts
Per request #1873, related to #1906 
Can confirm issue described in #1906 by altering the assertion from
```javascript
for (let i = 1; i <= 20; i++) {
assert.equal(comments[i - 1].text, `comment ${i}`);
}
```
to
```javascript
for (let i = 1; i <= 10; i++) {
assert.equal(comments[i - 1].text, `comment ${i + 10}`);
}
for (let i = 11; i <= 20; i++) {
assert.equal(comments[i - 1].text, `comment ${i}`);
}
```
=> Adds failing test for fetchMore utilizing a connection

CHANGELOG.md, src/data/mutationResults.ts
Address #1818 
Using the `Object` type can be pretty restrictive, as you can't access properties on it. Using `Record` will let TS users access arbitrary properties on the objects.
[TS example showing usage of `Record` vs `Object`](https://www.typescriptlang.org/play/index.html#src=let%20x%3A%20Record%3Cstring%2C%20any%3E%0D%0A%0D%0Ax%20%3D%20%7B%20a%3A%201%20%7D%0D%0Ax.b%20%3D%204%0D%0A%0D%0Alet%20y%3A%20Object%0D%0Ay%20%3D%20%7B%20a%3A%201%20%7D%0D%0Ay.b%20%3D%204)
=> Replace usage of `Object` with `Record`

src/index.js.flow, test/flow.js
I don't believe "this" as an argument is a convention in flow, also flow seemed to be struggling with the union of interface[] types so I consolidated them into an array of the union of the interfaces. 
Added test cases modified from the copy/paste examples of middleware use from the docs.
=> Fix flow signature for middleware

CHANGELOG.md, package.json, src/ApolloClient.ts, test/client.ts
With the additional functionality, Apollo Client is able to use an `apollo-link` directly as the network interface. The `ObservableNetworkInterface` is no longer needed.
=> Added apollo-link support for the network interface and deprecated ObservableNetworkInterface

AUTHORS, CHANGELOG.md, src/index.js.flow, test/flow.js
When adding middleware and afterware to the network interface, it should only accept either `applyMiddleware` or `applyBatchMiddleware`, but not both. The way to types were defined, it would accept both types of middleware. This is the error that the test case I added would give:
```
test/flow.js:33
33: const middleware: MiddlewareInterface[] = [{
^^^^^^^^^^^^^^^^^^^ property `applyMiddleware` of MiddlewareInterface. Property not found in
97: export type NetworkMiddleware = Array<MiddlewareInterface | BatchMiddlewareInterface>;
^^^^^^^^^^^^^^^^^^^^^^^^ BatchMiddlewareInterface. See: src/index.js.flow:97
test/flow.js:48
48: const afterware: AfterwareInterface[] = [{
^^^^^^^^^^^^^^^^^^ property `applyAfterware` of AfterwareInterface. Property not found in
98: export type NetworkAfterware = …
```
=> Fix NetworkMiddleware flow type

CHANGELOG.md, src/ApolloClient.ts, src/core/watchQueryOptions.ts
This adds basic documentation on roughly the same level as query and mutate.
I want to add the subscribe method to the web docs and figured this as a pre-req
=> Add documentation for ApolloClient.subscribe

CHANGELOG.md, package.json, src/ApolloClient.ts, test/client.ts
Replacing `apollo-link` with `apollo-link-core` to reduce bundle size
=> Move to apollo-link-core

renovate.json
Renovate is currently configured to use the schedule "after 10pm and before 5am on every weekday" however without a configured "timezone" then these times will default to UTC. This PR adds the America/Los_Angeles IANA time zone to the `renovate.json` configuration file, assuming that's the preferred timezone for this schedule.
=> chore: Configure timezone for Renovate

AUTHORS, CHANGELOG.md, src/transport/batchedNetworkInterface.ts, test/batchedNetworkInterface.ts
I discovered a problem when writing a prototype. If you write a query like this (reproducible [here](https://github.com/ben/react-apollo-error-template)):
```graphql
query abc {
allTrainers @connection(key: "abc") { name }
}
```
…it works perfectly when using the standard `networkInterface`, since that one [strips out the `@connection` bits before transmitting the query](https://github.com/apollographql/apollo-client/blob/ae390a30cb330073645e886f9c1f20d2a509994e/src/transport/networkInterface.ts#L207-L215). However, when using `createBatchingNetworkInterface`, the `@connection` directive is not stripped, and is included with the request payload, which rightly confuses the server.
This adds a bit of code to bring the batch interface to parity with the standard one, at least for this …
=> Trim @connection directives when using batch network interface

AUTHORS, CHANGELOG.md, src/core/ObservableQuery.ts, src/core/QueryManager.ts, test/ObservableQuery.ts
A pseudo-race condition exists for observable queries that return a result from `currentResult()` before `setUpQuery()` is invoked. The condition causes a referential equality checks to fail for results obtained before and after `setUpQuery()`, despite the results being truly equal.
This is problematic for `react-apollo` apps, since it can cause an unnecessary second render during initial component mounting, which is a perf-sensitive time for most apps (especially those built in React Native).
Here's the problem, in step-by-step detail:
1. A `graphql` query HOC from `react-apollo` begins mounting.
1. In `componentWillMount()`, it creates an `ObservableQuery` (but it doesn't subscribe).
1. In its initial `render()`, it calls `currentResult()` on the `ObservableQuery` instance, and reads a …
=> Update lastResult with computed value of currentResult()

src/index.js.flow, test/flow.js
Since the type NetworkInterface was defined as a class, ApolloClient didn't allow for custom network interfaces to be passed. 
After a quick look in the codebase I discovered that NetworkInterface is also defined as an interface in Typescript.
=> Fix flow type issue with custom network interfaces

src/index.js.flow, test/flow.js
We're experiencing issues with mounting the apolloClient middleware in our own redux state tree. 
This is caused because the type signature of the middleware method is conflicting with the redux's own flow type definition. I figured it'd be better to reuse redux's Middleware type since apolloClient.middleware() seems to be designed specifically to plug the apolloClient into your own redux store.
=> Align middleware flow types with redux middleware types.

CHANGELOG.md, src/scheduler/scheduler.ts, test/scheduler.ts
Hi,
I had the case where I had some network errors while my query was set with polling options and until it was manually restarted, it didn't try to do anything.
This change allows to poll even if there is a network error.
=> Allow data fetch after a NetworkError when polling

CHANGELOG.md, src/ApolloClient.ts, test/client.ts
Apollo Client would warn if two queries were in flight at the same time, since `resolved` was not properly scoped.
=> fixed two queries in flight bug for Apollo Link

CHANGELOG.md, src/ApolloClient.ts
This is a hotfix for issue #2013 
The networkInterface config will be assigned with query config itself, without copying the config properties to a new object.
=> Fixed the networkInterface config applying

.vscode/launch.json, CHANGELOG.md, package.json, src/ApolloClient.ts, test/graphqlSubscriptions.ts, tsconfig.json
=> Fixed single response and added subscriptions to links

src/index.js.flow, test/flow.js
Trying to do so:
```js
createNetworkInterface( {
uri: '/api/v1/graphql',
opts: {
// Additional fetch options like `credentials` or `headers`
credentials: 'same-origin',
}
} )
```
will lead to flow error:
```sh
node_modules/apollo-client/apollo.umd.js.flow:124
124:   opts?: ?RequestOptions,
^^^^^^^^^^^^^^^ null. This type is incompatible with the expected param type of
v
38:         opts: {
39:             // Additional fetch options like `credentials` or `headers`
40:             credentials: 'same-origin',
41:         }
^ object literal. See: config/project/index.js:38
```
because `NetworkInterfaceOptions` and `BatchingNetworkInterfaceOptions` were defined as interfaces not types.
=> fix: flow: prevent RequestOptions null error

package.json, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/__mocks__/mockLinks.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/__tests__/mutationResults.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager.ts, packages/apollo-client/src/scheduler/__tests__/scheduler.ts, packages/apollo-client/src/scheduler/scheduler.ts
This PR allows AC to accept multiple results from a network request (i.e. using Apollo link). It supports it in both mutations and queries, though currently there is not a top level API for `watchMutation`. 
@DxCx this is the work that was needed to support defer / live. The link for defer / live support will need to handle merging the updated results with what was in the store though. In another PR I'm going to add the store to the operation context so it can be used within links
=> Multiple results

CHANGELOG.md, src/data/readFromStore.ts, test/diffAgainstStore.ts
Hey look, another referential equality bug :trollface: 
These are really painful on React Native, where every unnecessary rerender is results in traffic over the bridge and thus a moment of unresponsive UI. It's clear that an effort to maintain referential equality was grafted onto the original code; I'm hoping it's more cohesively incorporated into the architecture of v2.
**Problem and fix description from the commit message:**
A logic error was causing the `readStoreResolver` from applying a `previousResult` to a top-level ID obtained via a custom resolver.
Effectively, this bug was causing the result of any query routed through a custom resolver to fail reference equality checks, even if the result is served completely from the cache and is completely unchanged.
This commit adds a …
=> Use previous results for fields from custom resolvers

package.json, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/__mocks__/mockLinks.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/__tests__/mutationResults.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts, packages/apollo-client/src/core/__tests__/QueryManager.ts, packages/apollo-client/src/scheduler/__tests__/scheduler.ts, packages/apollo-client/src/scheduler/scheduler.ts, packages/apollo-client/src/util/Observable.ts
This PR has a skipped test that I'm trying to debug around how unsubscribe works if data hasn't fired. I can't tell if it is my implementation of ZenObservable or a bug in that library. 
I'm going to work on that + a couple other observable PR's and merge them into this once to hopefully fix the test.
=> remove internal observable imlementation

package.json, packages/apollo-cache-core/src/cache.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__mocks__/mockQueryManager.ts, packages/apollo-client/src/__tests__/ApolloClient.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/__tests__/fetchMore.ts, packages/apollo-client/src/__tests__/graphqlSubscriptions.ts, packages/apollo-client/src/__tests__/mutationResults.ts, packages/apollo-client/src/__tests__/subscribeToMore.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts, packages/apollo-client/src/core/__tests__/QueryManager.ts, packages/apollo-client/src/scheduler/__tests__/scheduler.ts
This removes internal usage of `addTypename` within apollo-client in favor of the document being transformed by the cache.
cc @nevir
=> remove internal use of typename

packages/apollo-client/src/data/store.ts
If someone throws during an `update`, `this.cache` never gets set back to the original guy - leaving the store forever stuck in a transaction
---
Probably could use some extra logging/tests too - but not sure what exact form that should take
=> Gracefully handle errors during optimistic transactions

package.json, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/__mocks__/mockLinks.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/live.ts, packages/apollo-utilities/CHANGELOG.md, packages/apollo-utilities/src/__tests__/directives.ts, packages/apollo-utilities/src/directives.ts
When using watchQuery with a `@live` directive somewhere in the selection set, we need to bypass the cache for making requests because it sets up a network subscription (and should even if the data is in the cache). So if there is a `@live` directive, we should always make the request.
The new utility could be helpful for things like cache specific directives (i.e. `@cache(ttl: 1000)`)
=> Live support

AUTHORS, CHANGELOG.md, src/util/isEqual.ts, test/isEqual.ts
Fixes https://github.com/apollographql/apollo-client/issues/2132
=> isEqual should not fail if objects don't have proto

CHANGELOG.md, src/util/isEqual.ts
Hey there.
I've stumbled upon a bug where my query wasn't updated and refetched when I was changing the variables object (calculated from props) that contained dates. I've tracked it down to the `isEqual` util function, which treated different dates as equal.
Should I add some tests to cover this case?
=> Treat dates properly in `isEqual`

README.md
Note that this adds a link to https://www.npmjs.com/package/apollo-client-preset
but that package has no README. I dropped the missing link on HttpLink (no pun
intended) because I'm not sure what URL its docs will eventually be at.
=> README.md: some grammar, spelling, and clarity suggestions

AUTHORS, CHANGELOG.md, src/transport/networkInterface.ts, test/networkInterface.ts
Hey Apollo team! Thanks for making apollo-client, it's awesome 🙂 
My team is working on integrating apollo-client into our codebase and have several middleware functions that need to be on each request. We also have a need to have middleware failures terminate the request chain so that downstream subscribers can catch the error and act appropriately.
This follows the express API, where you can pass data to the `next` function to have it terminate the request chain and proceed to the error handler. In this case, rejecting the promise allows a downstream subscriber to use `catch` to handle the error.
The biggest risk here is that some people don't sanitize the input into `next`. If they have it as a handler that passes data back, it would assume it's an error when it may not be. For …
=> Allow middleware to terminate the request chain early

src/index.js.flow, test/flow.js
Fixes a flow issue with refetchQueries by converting MutationOptions from an interface to an object type.
We saw some issues with flow being unable to resolve the type of the refetchQueries property in a MutationOptions object.
In general flow seems to have some problems with Union types consisting out of Array types. E.g.: https://flow.org/try/#0FAYw9gdgzgLgBDAprAXHAggJ0wQwJ4A8smAlhAOYB8cAPhtvgRAK4C2ARoptQLxwDaARgC6AbiA
Most of the times these issues can be solved by providing additional type hints. However, it seems that because MutationOptions is defined as an interface, flow is unable to resolve the type, even when hints are provided. 
After a quick check I noticed that this is can be solved by converting MutationOptions to an object type. 
flow still isn't able to resolve the type of …
=> Flow type fix: Convert MutationOptions to an object type.

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts
This PR fixes the default `errorPolicy` in `mutate`, that was set to `'ignore'` but should be `'none'` for backwards compatibility with 1.0. This was briefly discussed with @jbaxleyiii on Slack
=> Set default errorPolicy to 'none' in QueryManager#mutate

packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/__tests__/fetchMore.ts, packages/apollo-client/src/__tests__/mutationResults.ts, packages/apollo-client/src/__tests__/optimistic.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts, packages/apollo-client/src/scheduler/__tests__/scheduler.ts, packages/apollo-client/src/util/subscribeAndCount.ts, packages/apollo-client/src/util/wrap.ts
Commits from https://github.com/apollographql/apollo-client/pull/2199 plus a couple of fixes. Thanks @jamesreggio!
=> Jest fixes

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts, packages/apollo-cache-inmemory/src/writeToStore.ts
This PR fixes a small bug that happens when you attempt to write a result to the store without a `__typename`, when the query has been transformed with the `addTypenameToDocument` function that adds the `__typename` field.
This should warn saying that the `__typename` field is missing, but it was failing early in the process since it was attempting to access the `directives` property in the field, which doesn't exist in the `__typename` field added by the transform. And actually, the directives property is optional according to the spec so we should check for its existence.
The fix is just adding a check for that.
=> Avoid undefined error when missing typename while writing a result to store

Upgrade.md, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-client-preset/package.json, packages/apollo-client-preset/src/__tests__/smoke.ts, packages/apollo-client-preset/src/index.ts, packages/apollo-client/CHANGELOG.md, packages/apollo-client/package.json
This PR updates the underlying link in the `apollo-client-preset` and the `apollo-link` to the new version for the base client.
If you previously used either `apollo-fetch` or `apollo-client`, you will need to change the way `use` and `useAfter` are implemented in your app. They can both be implemented in a link like so:
*Before*
```js
// before
import ApolloClient, { createNetworkInterface } from 'apollo-client';
const networkInterface = createNetworkInterface({ uri: '/graphql' });
networkInterface.use([{
applyMiddleware(req, next) {
if (!req.options.headers) {
req.options.headers = {};  // Create the header object if needed.
}
req.options.headers['authorization'] = localStorage.getItem('token') ? localStorage.getItem('token') : null;
next();
}
}]);
```
*After*
```js
import { ApolloLink …
```
=> New http link

CHANGELOG.md, src/core/QueryManager.ts
Implements: https://github.com/apollographql/react-apollo/issues/1168
Allows a user to refetchQueries conditionally by inspecting the result. i.e.:
```
mutate({
variables: {id:2},
refetchQueries: ({data:deleteResponse}) => deleteResponse.result.ok? [fetchUsers]:[]
})
```
=> Added conditional refetchQueries

CHANGELOG.md, src/core/types.ts
The issue came about when trying to specify IDs in Apollo configuration to tell queries about updates when new information becomes available for an Angular project, as per http://dev.apollodata.com/angular2/cache-updates.html
The original solution was proposed by @Nyaruiru:
https://github.com/apollographql/apollo-client/issues/2201#issuecomment-334992653
and was updated to pass tests.
=> Adds interface to allow for specification of IDs on Apollo Client

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/index.ts
It'd be helpful for UI integration libraries such as new angular-apollo, which will be released soon!
=> Expose ApolloClientOptions - Type of ApolloClient's constructor options

package.json, packages/apollo-client/CHANGELOG.md, packages/apollo-client/package.json, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/ApolloClient.ts
- throw an error if client is not initialized w/ link or cache
- added `graphql` as a dev dependency to `apollo-client`
- added postinstall script for lerna bootstrap
Closes #2319
=> fix(client): throw error if constructor not initialized properly

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-cache/src/cache.ts, packages/apollo-cache/src/types/DataProxy.ts, packages/apollo-client/src/ApolloClient.ts
instead of `Cache.DiffResult`.
Fixes #2308
=> cache: `readQuery` returns now the query result

docs/source/index.md
Small fix for misspelled word in doc site's side-nav
=> Docs navtive -> native

docs/source/basics/setup.md
In practice, installation of `graphql` is required as it is listed as a `peerDependency` of `apollo-client`. If you don't install this, you will get an error stating that the module `graphql/language/printer` is not found.
=> Add graphql as a required dependency to install

packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/__snapshots__/ApolloClient.ts.snap
Whenever ApolloClient is supplied without the `cache` or `link` properties the console outputs a link to the React setup docs which isn't available. 
To clarify: this URL is dead https://www.apollographql.com/docs/react/setup
whether this isn't: https://www.apollographql.com/docs/react/basics/setup.html
=> Use correct URL to React setup docs

docs/source/basics/network-layer.md
Old code didn't have enough closing parens, and also declared a function with parameters that weren't actually used.
=> docs: fix syntax error

docs/source/basics/network-layer.md
The [multiple-middleware example](https://www.apollographql.com/docs/react/basics/network-layer.html#linkMiddleware) has an error in the code as `from()` only takes an array of links.
=> fix(docs): `from` takes an array of links.

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/data/store.ts
Could not figure out why my UI was not being updated after a successful update. Empty errors array sent by server was the cause, this fully fixed it for me.
=> Fixed mutation result error checking for empty array

packages/apollo-client/AUTHORS, packages/apollo-client/package.json
- Moved @types/zen-observable dependency to optionalDependencies in apollo-client
- Added zen-observable as a dependency in apollo-client
=> Fix for missing zen-observable dependencies

docs/source/features/subscriptions.md
Rename `wsClient` to `wsLink` for consistency
=> Rename `wsClient` to `wsLink` for consistency

docs/source/basics/mutations.md
gql should always import from 'graphql-tag'.  See https://github.com/apollographql/apollo-client/issues/2432
=> Correct gql imports (from graphql-tag)

docs/source/recipes/babel.md
On following the installation instructions on this page of the wiki: https://www.apollographql.com/docs/react/recipes/babel.html
The yarn installation instructions fail with the following error:
```
yarn add --save-dev babel-plugin-graphql-tag
yarn add v1.0.2
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
The solution is to use the `--dev` flag instead of `--save-dev`:
```
yarn add --dev babel-plugin-graphql-tag
```
=> Fixed incorrect yarn installation instructions on 'Precompilation with babel' docs

docs/source/recipes/authentication.md
Opened [this issue (#2443)](https://github.com/apollographql/apollo-client/issues/2443) a couple days ago, decided to look through the code today to see if I could fix it, turned out to be a simple docs error:
`credentials` should not be nested inside `opts`, this does not work. It needs to be on the top level of the object.
=> [Documentation change] Passing credentials in opts:{} is incorrect

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts
Hi,
When forcing the option `connectToDevTools` to true, apollo tries to attach `__APOLLO_CLIENT__` on window. Even if window is undefined ( Which will fail )
=> prevent from accessing window if not defined

docs/source/recipes/authentication.md
The underlying fetch library (https://github.com/github/fetch) simply accepts a `credentials` key on the config object for cookie control.
=> Remove unnecessary "opts" key in client config docs

package.json, packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/package.json, packages/apollo-cache-inmemory/src/__tests__/__snapshots__/mapCache.ts.snap, packages/apollo-cache-inmemory/src/__tests__/__snapshots__/roundtrip.ts.snap, packages/apollo-cache-inmemory/src/__tests__/__snapshots__/writeToStore.ts.snap, packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts, packages/apollo-cache-inmemory/src/mapCache.ts, packages/apollo-cache-inmemory/src/writeToStore.ts, packages/apollo-client/package.json
A few things happening in this PR:
- fix bundlesize after hidden breaking change caused all builds to be green (need to follow up and reduce size of some packages again)
- adjust new Map Cache impl to force string coercion for ids
- add in printer for easier debugging of store problems.
**Note / call for ideas**
I don't like including the printer, however it is already in included in part of the required packages (apollo-link) so it won't actually increase overall bundle size of end applications. I really would like to do what the React team does and start to ship a dev and a production bundle. Anyone want to start in that direction?
=> add printer for better store warnings

docs/source/recipes/pagination.md
I have two suggestions here:
1. Preserve __typename.
2. Only update the result set if there are new edges returned.
I'm not sure how significant the first issue is, but it throws a console warning.  The second is a significant issue.  Consider the scenario where loadMoreEntries is called and the server returns an empty dataset:
```
{
comments: {
edges: [],
pageInfo: {
endCursor: null,
hasNextPage:false,
}
}
}
```
This stores endCursor as null on the client, and any subsequent calls to loadMoreEntries will end up returning additional results from the beginning of the dataset.
=> Fix Relay pagination example

docs/source/basics/mutations.md
Summary
----------
There are several broken links in the mutations page (https://www.apollographql.com/docs/react/basics/mutations.html) that point to old urls from before 2.0. 
Changes Proposed
-------------------
The DataProxy links are left alone for now, since those parts of the API reference seem to no longer exist? Maybe those links can just point to their respective sections in https://www.apollographql.com/docs/react/features/caching.html
----
Addresses broken links referred to in #2522
=> Fix broken links in /docs/react/basics/mutations to other pages

codecov.yml
There are quite a few comments posted on new PRs right now, and the code coverage information is already available via the GitHub PR status. I think it's mostly just noise.
=> Don't post comments from Codecov

packages/apollo-cache-inmemory/src/writeToStore.ts, packages/apollo-client/CHANGELOG.md, packages/apollo-client/benchmark/index.ts, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/ApolloClient.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts, packages/apollo-client/src/core/__tests__/QueryManager/multiple-results.ts, packages/apollo-client/src/scheduler/__tests__/scheduler.ts, packages/apollo-client/src/scheduler/scheduler.ts, packages/apollo-utilities/src/directives.ts, packages/apollo-utilities/src/fragments.ts, packages/apollo-utilities/src/getFromAST.ts, packages/apollo-utilities/src/index.js.flow, packages/apollo-utilities/src/storeUtils.ts
This PR does a few things:
- run newest version of prettier on code base (still need to fix dev tooling to do this for us)
- fix a bug with writeFragment / writeQuery
- remove the lastVariables code
I'm going to run this build against react-apollo locally prior to merging (done, calling this a green build!)
Fixes https://github.com/apollographql/apollo-client/issues/2570, https://github.com/apollographql/apollo-client/issues/2360, and https://github.com/apollographql/apollo-client/issues/2415
=> fix writeFragment and readFragment issue

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts
This PR fixes the bug introduced with the 2.0 version where `currentResult()` calls wouldn't return referentially equal results even if it could.
Fixes https://github.com/apollographql/apollo-client/issues/2453, and https://github.com/apollographql/apollo-client/issues/2489
=> ensure ref equality when calling currentResult if possible

packages/apollo-cache/src/cache.ts, packages/apollo-cache/src/types/DataProxy.ts, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts
=> [WIP] Instruct TS that reading from cache could sometime give null

docs/source/recipes/server-side-rendering.md
This adds cache: InMemoryCache() to the SSR example. Without this, the server crashes on start:
```
Error:
In order to initialize Apollo Client, you must specify link & cache properties on the config object.
This is part of the required upgrade when migrating from Apollo Client 1.0 to Apollo Client 2.0.
For more information, please visit:
https://www.apollographql.com/docs/react/basics/setup.html
to help you get started.
```
I'm not sure if this is the correct cache to use on the server (I've used Apollo for less than a day) so please correct me if I should be using something different here.
=> Add Apollo cache to client on server-side example.

packages/apollo-cache-inmemory/src/writeToStore.ts, packages/apollo-client/AUTHORS, packages/apollo-client/CHANGELOG.md
This PR ensures that heuristics warnings (`'WARNING: heuristic fragment matching going on!'`) don't get fired in production.
=> Ensure that heuristics warnings are not logged in production

docs/source/basics/setup.md
Similar to https://github.com/apollographql/react-apollo/pull/1364.
2.0. ApolloProvider is not based on `react-redux`s Provider anymore, so one cannot pass Redux store as `store` prop.
=> docs(setup): Remove mention about passing Redux store to ApolloProvider

docs/source/recipes/server-side-rendering.md
When reading through the "Server Side Rendering" docs of Apollo, I've noticed that the "Local Query" section doesn't actually provide an example on how to set up an Apollo Link that doesn't start additional network requests, so I've added a couple of lines of code there as an example.
=> Add example to server-side-rendering's local query section

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts
In a scenario where one updates state via a third party real time provider, one can run into situations where the real time provider is unable to do so. For instance with network outages. To be able to refetch all observed queries will make sure the state is in the correct state. Reset store cannot be used for this scenario, because it rejects any query that is mid-flight.
=> feat: expose a method to refetch all observed queries

dangerfile.ts, packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/objectCache.ts
We had big performance issues with Apollo lately. 
It seems that the bottleneck always was the cache. While debugging, we recognized the massive cost of the `toObject()`  method in `ObjectCache.ts`. 
In the current version this method clones the whole cache every time a new GraphQL query is received. 
As we didn't find any use for a unique instance, this pull request removes the overhead. 
Following some performance examples:
**Current Version:**
**Without Cloning:**
=> fix(ObjectCache): removes not used cloning

packages/apollo-client/benchmark/github-reporter.ts, packages/apollo-client/benchmark/thresholds.ts
This fixes the issue with benchmark results not being reported when processing pull requests from forks, which do not have the `TRAVIS_COMMIT` environment variable in the Travis build but instead have `TRAVIS_PULL_REQUEST_SHA`.
=> Use TRAVIS_PULL_REQUEST_SHA when publishing benchmark results

docs/source/basics/setup.md
Also search this page https://www.apollographql.com/docs/react/basics/setup.html#graphql for the string "][]" without quotes. No idea how to fix that one.
=> Fixing links to "the the most important thing exported by react-apollo"

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/inMemoryCache.ts
This allows subclasses of `InMemoryCache` (for example https://github.com/rportugal/apollo-cache-redux/blob/master/src/reduxCache.ts) to directly access the data managed by the `InMemoryCache`.
The use case I'm trying to implement is a Null Cache, in which the data is always cleared up after a `read()` operation.
=> Change data to protected

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts
This passes optimistic responses through to links so that they can perform work based on it (for example: to retry mutations w/ optimistic responses)
Also, refactored `QueryManager`'s approach to building operation objects to pass to link to ensure that it's consistent (it's not completely consistent today - see the TODOs - but moves in that direction).
=> Include optimistcResponse in the link context for mutations

packages/apollo-client/benchmark/github-reporter.ts
Travis appears to have a lot of performance variation across builds, so this increases the tolerance when checking if the results are within the thresholds.
=> Increase benchmark tolerance to better handle Travis performance variation

packages/apollo-cache-inmemory/src/fragmentMatcher.ts
Fixes a broken link in the heuristic fragment matcher warning.
=> Fix link to IntrospectionFragmentMatcher docs

packages/apollo-client/src/index.ts
This PR is related to [resolving react-apollo's issue](https://github.com/apollographql/react-apollo/issues/1486).
This issue can be easily resolved with few lines of code though, there is a glitch.
As you can see in [this import statement](https://github.com/apollographql/react-apollo/blob/177ccad8f3166c54b9df3eea17930ffdae302e46/src/types.ts#L1-L11), `apollo-client` exports every needed types for their dependencies. But `ErrorPolicy` type is missing.
I could import `ErrorPolicy` type using this statement.
```js
import { ErrorPolicy } from 'apollo-client/core/watchQueryOptions';
```
Since this syntax conflicts the styles of the import statement which already written, It will be better if `ErrorPolicy` type is exported in `index.ts`.
=> Export ErrorPolicy type from ApolloClient

docs/source/recipes/query-splitting.md
import { InMemoryCache } from 'apollo-cache-imemory';
->
import { InMemoryCache } from 'apollo-cache-inmemory';
=>  The spelling is wrong

docs/source/basics/caching.md, docs/source/basics/mutations.md, packages/apollo-client/AUTHORS
Resolves #2760 
- fixes broken links from mutate's `options.update` to readQuery/etc
- fixes a formatting mistake in the readQuery docs
=> readQuery docs improvements

package.json, packages/apollo-cache/src/__tests__/__snapshots__/utils.ts.snap, packages/apollo-cache/src/__tests__/utils.ts, packages/apollo-cache/src/cache.ts, packages/apollo-cache/src/types/Cache.ts, packages/apollo-cache/src/types/DataProxy.ts, packages/apollo-cache/src/utils.ts, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/ApolloClient.ts
- Added writeData to base cache & DataProxy
- Created `utils` file with helper methods for `writeData`
Once this is merged, I can cut a release, update Apollo Client, and move over the tests for `writeData` from state link. It looks like all the tests for the DataProxy methods live there instead of in `apollo-cache`.
=> Add cache.writeData to base cache type & DataProxy

docs/source/features/cache-updates.md
I've attempted to clarify why connection directives are needed but It could probably do with use case examples too.
=> @connection directive clarification

packages/apollo-utilities/CHANGELOG.md, packages/apollo-utilities/src/directives.ts
Fixes a minor typo in an error message when an invalid parameter is used for the `@skip` or `@include` directives: "bool ean" -> "boolean"
=> Fix typo in error message

docs/source/basics/setup.md
Small documentation change, regarding a typo used twice: "infomation", instead of "information".
=> Typo "infomation"

docs/source/recipes/authentication.md
In the authentication recipe, when a token does not exist, `authorization: null` is added to the request headers .  This assumes that the server will interpret "null" as unauthenticated and not throw an error.  The safer approach would be to include the Authorization header only when the token exists.
=> Safer approach to adding Authentication header

docs/source/basics/caching.md, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/fetchPolicies.ts, packages/apollo-client/src/core/watchQueryOptions.ts
This PR seeks to support a new `FetchPolicy` called `no-cache`. Unlike `network-only` (which has a somewhat confusing name I admit), this policy bypasses reads **AND** writes when interacting with the client. So it can be used to "turn off caching" when needed. This applies to mutations as well which now support using `FetchPolicy` but only for this use case (will throw otherwise)
=> support no-cache requests

packages/apollo-client/src/core/__tests__/fetchPolicies.ts
Based on the description in the [docs](https://www.apollographql.com/docs/react/basics/caching.html#ignore), and the code in the tests, I think the description is incorrect. So I fixed it!
=> Fix test description

README.md
Simple update to README so there's only two dashes in "--save" for installation instructions
=> Remove extra dash in npm install --save statement (Docs only!)

packages/apollo-client/src/data/mutations.ts
`ApolloClient.resetStore()` will eventually invoke `MutationStore.reset()`.
If `ApolloClient.resetStore()` is invoked while a mutation is in flight (i.e., blocked on networking), when the mutation is complete, `markMutationError` or `markMutationComplete` will fail to find the mutation by its ID and will cause a null-pointer error.
This PR guards around the scenario. Simply returning in the event that the mutation ID lookup yields no results (as this PR does) should be safe because we've signaled no further interest in the result of the mutation at the time that we invoked `resetStore()`.
=> Check for null mutation before making bookkeeping updates

packages/apollo-utilities/CHANGELOG.md, packages/apollo-utilities/src/storeUtils.ts
This PR fixes an issue with `apollo-link-state` where adding the `@client` directive to the object key in #2710 broke `cache.writeData`:
https://github.com/apollographql/apollo-link-state/issues/187
This fix is temporary until we can think of a more robust solution for directional directives like `@client` and `@rest`. With directional directives, the cache doesn't care about the directive since it only impacts the execution, not the results. This is in contrast to translational directives like `@uppercase`, where the result is altered.
=> Add client, rest, and export to known directives in apollo-utilities

packages/apollo-client/AUTHORS, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts
This PR will add results.data to the query result if the errorPolicy is set to "all" as the documentation presumed.
Fixes issue #2703
=> BUGFIX: Add data to query result if errorPolicy is set to all

docs/source/basics/caching.md
When I tried to do this without `__typename`, I got a console warning when writing and an error when subsequently reading.
=> Use __typename when adding objects via writeQuery

package.json, packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-cache-inmemory/src/types.ts, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/links.ts
A `getCacheKey` function on the context would be super useful, not only for state-link when writing a fragment to the cache but also for cache resolvers.
Instead of:
```js
import { toIdValue } from 'apollo-utilities';
import { InMemoryCache } from 'apollo-cache-inmemory';
const cache = new InMemoryCache({
cacheResolvers: {
Query: {
book: (_, args) => toIdValue(cache.config.dataIdFromObject({ __typename: 'Book', id: args.id })),
},
},
});
```
Now, you can do this:
```js
import { InMemoryCache } from 'apollo-cache-inmemory';
const cache = new InMemoryCache({
cacheResolvers: {
Query: {
book: (_, args, { getCacheKey ) => getCacheKey({ __typename: 'Book', id: args.id }),
},
},
});
```
=> Add getCacheKey to context for cache resolver

docs/source/recipes/meteor.md
starting apollo engine with `engine.start()`
and using the right variable name for using the middleware
=> Fix the code in docs for apollo engine with meteor

packages/apollo-client/benchmark/github-reporter.ts
This reduces the error message length, which was causing failed updates to the GitHub status.
=> Fix errors when reporting failed benchmarks to GitHub

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/__tests__/diffAgainstStore.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-cache-inmemory/src/types.ts, packages/apollo-cache-inmemory/src/writeToStore.ts, packages/apollo-client/src/core/__tests__/QueryManager/multiple-results.ts
We need a way to differentiate `cacheResolvers`, which run before link execution and are synchronous, from `clientState.resolvers` in `apollo-client-preset`, which are async and run inside a link. Renaming `cacheResolvers` to `cacheRedirects` helps distinguish between the two.
Don't merge this right away, I want to get everyone's feedback first! One downside is that we already changed the name with the 2.0 release 🤔
=> InMemoryCache: Change cacheResolvers to cacheRedirects

packages/apollo-boost/CHANGELOG.md, packages/apollo-boost/package.json, packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/package.json, packages/apollo-cache/CHANGELOG.md, packages/apollo-cache/package.json, packages/apollo-client/AUTHORS, packages/apollo-client/CHANGELOG.md, packages/apollo-client/package.json, packages/apollo-utilities/CHANGELOG.md, packages/apollo-utilities/package.json, packages/graphql-anywhere/CHANGELOG.md, packages/graphql-anywhere/package.json
I noticed that the coverage files generated from jest are not mapped correctly. There is an undocumented configuration option in jest, `mapCoverage`, that fixes TypeScript coverage maps. I've added it to each package's jest config.
=> Map coverage to original source

docs/source/2.0-migration.md
This tiny PR simply adds a new line between the HTML markup and markdown markup to fix the broken link in the `update` section.
Before:
After:
=> Fix 2.0-migration.md formatting

docs/source/2.0-migration.md
In the documentation `onError` callback passes an object of `{networkError, graphQLErrors}` to the callback. The `networkError` parameter is  `undefined` if no network error happens, as seen in the code:
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-error/src/index.ts#L31
Which matches how the library is used in its [own documentation](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-error).
This PR changes the param to have a default value of `{}`, alternative approach would be checking for `if (networkError && networkError.statusCode === 401)`, both are fine with me :)
=> Update 2.0-migration.md onError documentation

docs/source/quick-start.md
Hi, I was reading the [quick-start](https://www.apollographql.com/docs/react/quick-start.html) today and I noticed the example appears to use the wrong variable name for the query property.
=> Use the correct variable name for the query prop

packages/apollo-boost/CHANGELOG.md, packages/apollo-boost/src/index.ts
As mentioned in #3044 setting up apollo-boost with a request parameter did not pass proper operation propery to the registered function. Therefore you cannot set authorization headers as described in the quick start.
This PR passes the proper operation to the registered callbacks and fixes #3044
No further changes were made.
=> [apollo-boost] pass operation prop to config.request

packages/apollo-client/AUTHORS, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts
When a query was stopped, it was removed from the Map but it was
then invalidated, creating a new unusable item that takes memory.
This commit just invalidate the query before removing it in order to
delete it for ever.
I have no idea if changing the order of these functions will have an impact for production usage, but it seems fixing the memory leak.
I created a small gist to play with Apollo Client: https://gist.github.com/Kmaschta/9d4e6c5a68c9978177d42a068dfed2f6
To run it, just copy the files, install the dependencies and run it with node:
```bash
yarn install
node --inspect index.js
curl http://localhost:3000/test
```
I used [siege](https://www.joedog.org/siege-home/) to simulate a high number of requests.
```bash
timeout 10s siege http://localhost:3000/test
timeout 10s siege …
```
=> Fix Memory Leak in Query Manager

packages/apollo-client/src/ApolloClient.ts
The generic type on subscribe is missing. Its easy enough to just default it to any and pass it to `Observable<T>`. No loss in current behavior, but typing on the response.
=> Add type generic to subscribe

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/__tests__/subscribeToMore.ts, packages/apollo-client/src/core/QueryManager.ts
Subscriptions will make optimistic queries in the cache become non-optimistic with `subscribeToMore`. See #3062  for unwanted effects
This PR addresses this issue
=> Pass non-optimistic query to subscribeToMore  #3062

package.json, packages/apollo-cache/rollup.config.js, rollup.config.js
The ts-jest package requires the `coverageMap` option to be enabled to get accurate coverage mapping back to the typescript files.
The rollup bundles' sourcemaps were pointing to the compiled javascript files, now they point a the ts files.
=> Sourcemaps for rollup bundles

docs/_config.yml, docs/public/_redirects
Note: This PR targets #3097.  It will merge into that PR.
---
These redirects maintain the URLs in existence before the React Apollo 2.1 docs overhaul.
This includes both Netlify redirects for redirects that should be handled by the server (specifically, those that don't include anchor tags on the "from" side) and also a JavaScript-powered `redirects` directive in the `_config.yml` which utilizes a mechanism in the theme.
=> Add redirects for existing React Apollo 2.0 docs URLs.

docs/source/essentials/get-started.md, docs/source/react-apollo-migration.md
If `data` is destructured it returns only `rates` array which is contrary to what is said in the description 😉 
Also there is a typo on `New in React Apollo 2.1` page at the bottom `ApolloConsumer`
`there is a new version of context that makes is easier` should be `there is a new version of context that makes it easier`
=> Code not matching description & small typo

docs/source/react-apollo-migration.md
Both `withOne` and `withTwo` queries were returning `one` prop.
=> Fix small copy-paste error in HOC example

renovate.json
Essentially, the scope and default settings for Renovate's `pinVersions` has changed in v12, which explains the incorrect version pinning suggestion for `peerDependencies` witnessed in https://github.com/apollographql/apollo-client/pull/3298.
For the full back-story, see the conversation in the following links.
Ref: https://github.com/renovateapp/renovate/releases/tag/12.0.0
Ref: https://github.com/apollographql/apollo-server/pull/954
Ref: https://github.com/apollographql/apollo-server/pull/955
=> Accommodate breaking changes in Renovate v12.

docs/source/essentials/get-started.md
Update code and language in the **Create a client** section (Get started) page.
Currently, the example and language is slightly in accurate.
The `data` argument passing to the resolve handler is actually the query result object with `{ data, loading, networkStatus, ... }`.
Proposed an update with the minor change in the language to avoid confusion.
=> [docs] Update code and language in Get started: Create a client

docs/source/essentials/local-state.md
"in our *client* application" --> the server DB is the actual single source of truth.
=> Clarify "single source of truth"

docs/source/recipes/static-typing.md
Just a double `>` symbol when declaring types for `withCharacter`
=> Fix typo line 217 of static-typing recipes

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/writeToStore.ts, packages/apollo-client/AUTHORS
Typo fix in writeToStore documentation.
=> Fix typo in documentation

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/objectCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-client/AUTHORS, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/data/queries.ts, packages/graphql-anywhere/CHANGELOG.md, packages/graphql-anywhere/src/graphql.ts
Taken together, these small optimizations to frequently executed functions cut the time taken to read one large query from 4.5ms to 2.25ms. The specific benchmark is in a [private repository](https://github.com/apollographql/benchmarks), though perhaps we could make it public?
I have a lot more ideas about how to cache (and invalidate) partial query responses, which should improve repeated read performance significantly, but the changes in this PR will still be worthwhile for the first (cold cache) read.
=> Improve read performance for complicated queries by up to 50%

docs/source/advanced/caching.md
Really minor change, just adding back an import line that exists in:
- https://github.com/apollographql/react-docs/blob/master/source/cache-updates.md#update
- and also in the angular docs of the site: https://www.apollographql.com/docs/angular/features/cache-updates.html#directAccess
=> Fix: add missing import in caching update docs

docs/source/advanced/subscriptions.md
Coming from https://github.com/apollographql/subscriptions-transport-ws/issues/111
Or maybe `query` prop should actually be `subscription` and the actual API should be changed.
=> fix Subscription component prop name

packages/graphql-anywhere/CHANGELOG.md, packages/graphql-anywhere/src/graphql.ts
Thanks to @HoangPaul for reporting this problem in #3393.
=> Fix #3393 by making merge function more defensive.

README.md
The link to the watchQuery API docs is currently broken. Submitted a PR for this fix in `vue-apollo` earlier too: [PR](https://github.com/Akryum/vue-apollo/pull/269).
Also, replaced the squared brackets around the ‘apollo-client API reference’ text with parenthesis for better readability (IMHO).
=> Fix watchQuery link to docs and ‘enhance’ link

ISSUE_TRIAGE.md
We're going to drop the `blocking` label, so this removes the `blocking` reference from the `ISSUE_TRIAGE.md` doc.
=> Remove `blocking` label

dangerfile.ts
We're currently reminding contributors to add their name to the `AUTHORS` file on every PR, whether they've added their name already or not. This creates a fair bit of PR noise. After some internal discussion, we've decided that maintaining the `AUTHORS` file isn't really needed anymore. Contributor details are already tracked using GitHub's contributors functionality, and the original intent of the `AUTHORS` file (to support people from companies that only allow contributions if their
name can be included in a specific contribution file) is no longer a priority. This commit removes the `AUTHORS` danger check. We'll keep the `AUTHORS` file in place for now. Thanks!
=> Remove danger AUTHOR request

docs/source/features/error-handling.md
=> fix: add a </pre> to error-handling.md

docs/source/api/react-apollo.md
Fixed some anchor conflicts and a broken anchor in the docs.
=> Documentation anchor fixes

docs/source/essentials/local-state.md
Small code sample change to clarify that the Apollo client instance is being used, instead of interacting with the cache directly. 
Fixes #3349.
=> Changed `cache` to `client` to clarify code sample

docs/source/advanced/caching.md
The `cacheResolvers` and `customResolvers` options where changed to `cachRedirects`.
Fixes #3365.
=> Change `cacheResolvers` to `cacheRedirects` in `InMemoryCache` docs

dangerfile.ts
From my commit message on 5d3889cf:
---
As demonstrated in the Danger test[0] on apollographql/apollo-client#3444, the `author` property is not always set.  While it could make sense to individually look at each individual commit's "login", Git commits are not always tied to GitHub users so it seems more relevant to look at the GitHub login of the user (or bot!) opening the PR, when making decisions about whether to apply bot-only policies.
[0]: https://circleci.com/gh/apollographql/apollo-client/8427
=> Correct Dangerfile to account for commits which aren't tied to a GitHub user.

docs/source/recipes/babel.md, docs/source/recipes/webpack.md
Hi, I'm going to be doing an official release of my package soon and I hated the name so I changed it lol. I've updated all of the occurrences in the docs to the new name and fixed the links.
Note I'm leaving the original repo intact. So the links won't be broken without this PR, but I've deprecated the package on NPM. Users installing the old package will get a warning asking them to switch to `babel-plugin-import-graphql`.
=> Change name of deprecated package babel-plugin-inline-import-graphql-ast

packages/apollo-client/package.json, packages/apollo-client/src/core/__tests__/QueryManager/index.ts
While merging in https://github.com/apollographql/apollo-client/pull/3500 we encountered `rxjs` `from` issues in some of the tests. I added `rxjs-compat` to work around these issues, but this shouldn't be needed. This commit aims to revert the `rxjs-compat` changes, to see if the CI gods will now be appeased.
=> Remove `rxjs-compat` use

packages/apollo-boost/CHANGELOG.md, packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache/CHANGELOG.md, packages/apollo-client/CHANGELOG.md, packages/apollo-utilities/CHANGELOG.md, packages/graphql-anywhere/CHANGELOG.md
`CHANGELOG` updates for each package (prepping for release). This also includes some random cleanup, to get the `CHANGELOG`'s into a more uniform format. This cleanup will be taken further in the future.
=> CHANGELOG updates for all packages

docs/package.json
Manually, without Renovate because we're outside normal Renovate hours for this repository.
=> chore(deps): update dependency `meteor-theme-hexo` to v1.0.13.

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache/CHANGELOG.md, packages/apollo-cache/src/cache.ts, packages/apollo-cache/src/types/Cache.ts, packages/apollo-cache/src/types/DataProxy.ts, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts
This sort of falls outside of all of the checklist items above, so I checked them.
Currently, when using the read/write methods on the cache, it is very easy to make mistakes, by simply misspelling a variable for example.
This PR adds optional generic arguments to methods used to manipulate the cache.
I've made sure to add a default for all of the new generic arguments, so it should not break anything.
=> Add optional generics to cache manipulation methods

packages/apollo-boost/README.md
This keeps these docs consistent with the [docs website](https://www.apollographql.com/docs/react/essentials/get-started.html#installation), which might help with people reading on npmjs.
=> Remove @beta tag from apollo-boost install instruction

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/readFromStore.ts
The change to create a simple property rather than using `Object.defineProperty` was originally made in the interest of performance, but it seems to be causing problems for some users: https://github.com/apollographql/apollo-client/pull/3300#issuecomment-393252909
=> Restore non-enumerability of resultFields[ID_KEY].

packages/apollo-utilities/CHANGELOG.md, packages/apollo-utilities/src/util/maybeDeepFreeze.ts
The "own" in `getOwnPropertyNames` ensures that all the names would pass the `hasOwnProperty` test.
Regarding [this comment](https://github.com/apollographql/apollo-client/pull/3300#issuecomment-390529032) by @jamesreggio, I would much rather patch `apollo-utilities` than revert the use of `Object.create(null)`, since empty prototype-free objects never accidentally appear to have properties inherited from `Object.prototype` (a correctness concern), and lookups of missing properties are faster since there's no prototype chain. Far from being deficient, `Object.create(null)` objects are what empty objects should always have been in JavaScript.
=> Avoid needless hasOwnProperty check in deepFreeze.

docs/source/recipes/authentication.md
Users who have followed the getting started guide are likely still using Apollo Boost which doesn't support adding custom links. Switching to the proper ApolloClient is necessary to get the header authorization working (and cookie auth only works because the Apollo Boost defaults include `credentials: 'same-origin'` already.
=> Highlight the switch to apollo-client

packages/apollo-cache-inmemory/CHANGELOG.md, packages/apollo-cache-inmemory/src/inMemoryCache.ts
After #3444 removed `Map`-based caching for `addTypenameToDocument` (in order to fix memory leaks), the `InMemoryCache#transformDocument` method now creates a completely new `DocumentNode` every time it's called (assuming `this.addTypename` is true, which it is by default).
This commit uses a `WeakMap` to cache calls to `addTypenameToDocument` in `InMemoryCache#transformDocument`, so that repeated cache reads will no longer create an unbounded number of new `DocumentNode` objects. The benefit of the `WeakMap` is that it does not prevent its keys (the original `DocumentNode` objects) from being garbage collected, which is another way of preventing memory leaks.  Note that `WeakMap` may have to be polyfilled in older browsers, but there are many options for that.
This optimization will be …
=> Cache query documents transformed by InMemoryCache.

docs/source/api/apollo-client.md
Adding the following types:
- `ApolloQueryResult`
- `ApolloCurrentResult`
Fixes https://github.com/apollographql/apollo-client/issues/3412.
=> Add missing `Apollo*Result` types to the API docs

packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/watchQueryOptions.ts
`ApolloClient.query` is currently configured to accept `WatchQueryOptions`, which means the docs show people that passing things like `pollingInterval` into `ApolloClient.query` is supported (when in reality it's only supported when using `ApolloClient.watchQuery`). These changes add a new `QueryOptions` interface, and pull some of the common options out into a parent `QueryBaseOptions` interface. `ApolloClient.query` has been updated to use the `QueryOptions` interface, which should help clear up a bit of confusion.
Fixes https://github.com/apollographql/apollo-client/issues/3395.
=> Add `QueryOptions` and `QueryBaseOptions` interfaces

packages/apollo-boost/CHANGELOG.md, packages/apollo-boost/package.json, packages/apollo-boost/src/__tests__/config.ts, packages/apollo-boost/src/index.ts
This is related to https://github.com/apollographql/apollo-client/issues/3220
New tests have been added
---
I've read through some discussions on this and I see that there are different opinions on the appropriateness of this kind of change and how it relates to your idea of the opinionated nature of ApolloBoost. Obviously, feel free to close the PR and disregard.
The challenge I'm running into, and which motivated this pull request, is that I have one small configuration change I need to make to the internal InMemoryCache configuration. That one small change is forcing me to drop ApolloBoost and instead configure everything manually.
It would be more user-friendly to be able to use ApolloBoost as is, but pass in specific dependency's when required while still retaining the rest of the …
=> Allow pre-configured cache to be given as config option to Apollo Boost Client

CHANGELOG.md, packages/apollo-client/CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/index.ts
When the new `QueryBaseOptions` and `QueryOptions` interfaces were created in
https://github.com/apollographql/apollo-client/commit/eb89b23f667f0854443950ce9301945d8596d7a6, `ModifiableWatchQueryOptions` was replaced by `QueryOptions` when checking the `query` `defaultOptions` used in the Apollo Client constructor. Unfortunately, this introduced a small type check bug since the `query` property in `QueryOptions` is a mandatory property, whereas `ModifiableWatchQueryOptions` did not include this property. This commit replaces the use of `QueryOptions` with `QueryBaseOptions` when type checking `query` in `defaultOptions`, since `QueryBaseOptions` doesn't have a `query` property.
Fixes https://github.com/apollographql/apollo-client/issues/3583.
=> Fix typescript issue with `defaultOptions` in constructor

docs/source/essentials/mutations.md
Re-applies the effect of https://github.com/apollographql/apollo-client/pull/3370 now that the [original PR](https://github.com/apollographql/react-apollo/pull/1945) is merged.
=> Update MutationResult API docs to include `client`

packages/apollo-utilities/CHANGELOG.md, packages/apollo-utilities/src/storeUtils.ts
Fix for #3398 
Switched from string template to normal string concatenation in order to avoid white spaces in the console output after reformating with prettier.
=> Remove whitespaces from error msg.

docs/source/essentials/local-state.md
=> Correct section id for "Next steps" in local-state.md

docs/source/api/react-apollo.md
Associated with https://github.com/apollographql/react-apollo/pull/1922.
=> Add `onCompleted` and `onError` props to `Query` API docs

docs/_config.yml
I added a section on the sidebar with links to related guides.
I chose `State Management`, `Testing React Components`, and ` Schema Design` as I thought those were the most relevant guides to client developers.
=> [docs] added related guides

docs/source/api/apollo-client.md
Continuation of https://github.com/apollographql/core-docs/pull/310.
=> Add missing `subscribe` entry to the Apollo Client API docs

.github/ISSUE_REPLY_TEMPLATE.md, docs/source/essentials/local-state.md, docs/source/features/developer-tooling.md, docs/source/recipes/meteor.md, docs/source/recipes/recompose.md, docs/source/recipes/simple-example.md, docs/source/why-apollo.md
This updates all blog URLs in the documentation to use blog.apollographql.com
as the domain, rather than dev-blog.apollodata.com.
=> docs: Update blog URLs to reference blog.apollographql.com.

docs/source/essentials/get-started.md
The existing page for _Add React to a New App_ (previously; now broken: https://reactjs.org/docs/add-react-to-a-new-app.html) has been moved to https://reactjs.org/docs/create-a-new-react-app.html.
This updates the documentation to accommodate that change!
=> docs: Update link to `create-react-app` instructions.

docs/source/features/pagination.md
=> Pagination: fix typo

CHANGELOG.md, packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts, packages/apollo-cache-inmemory/src/writeToStore.ts
If a custom `dataIdFromObject` function returns a numeric ID with the value 0, it's seen as being a falsy value. This then prevents the query result associated with the ID from being written to the store. These changes adjust the falsy check to accommodate 0 based custom ID's.
Fixes #2164.
=> Adjust `dataIdFromObject` logic to handle ID's with a value of 0

CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts
Release 2.3.6 broke Typescript compilation. `QueryManager`'s `getQueryWithPreviousResult` method included an invalid `variables` return type in the auto-generated `core/QueryManager.d.ts` declaration file. The type definition had a locally referenced path, that appears to have been caused by the typescript compiler getting confused at compile/publish time. `getQueryWithPreviousResult` return types are now excplicity identified, which helps Typescript avoid the local type reference. For more details, see https://github.com/apollographql/apollo-client/issues/3729.
Fixes #3729.
=> Fix broken `getQueryWithPreviousResult` return type declaration

CHANGELOG.md, packages/apollo-client/package.json
Since the ^ operator only covers any minor version if the major version is not 0 (since a major version of 0 is  technically considered development by semver 2), the current ^0.11.0 || ^14.0.0 graphql range doesn't cover 0.12.* or 0.13.*.
Fixes #3737.
=> Adjust `graphql` peer dep to cover explicit minor ranges

docs/source/api/react-apollo.md, docs/source/essentials/mutations.md
Doc updates to explain the `react-apollo` `awaitRefetchQueries` option added in https://github.com/apollographql/react-apollo/pull/2214.
=> Add `react-apollo` `awaitRefetchQueries` docs

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, ISSUE_TRIAGE.md
Starting very shortly, all Apollo Client feature requests and discussions will be managed under the new https://github.com/apollographql/apollo-feature-requests repo. This PR kick starts the necessary documentation and issue template changes needed to point people in the right direction.
=> Update docs and issue template with FR repo details

package.json, packages/apollo-boost/package.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache/package.json, packages/apollo-client/package.json, packages/apollo-utilities/package.json, packages/graphql-anywhere/package.json
A recent Renovate merged Jest update caused all tests to start to fail, due to JSDom security errors. This config adjustment was recommended in the Jest repo to address this issue.
Relates to:
https://github.com/facebook/jest/issues/6766#issuecomment-408344243
=> Jest config adjustment to address recent JSDom issue

renovate.json
`tooling` is too generic as a label, and could be used for any kind of tooling. It doesn't add much when triaging issues, so let's get rid of it.
=> Remove `tooling` label used by renovate

docs/source/api/react-apollo.md, docs/source/basics/queries.md
The `fetchMore` docs were using an outdated parameter name of `queryVariables`. This updates the docs to use the proper `variables` param name.
Fixes #3694.
=> Update `fetchMore` docs to use proper `variables` parameter

CHANGELOG.md, docs/source/advanced/caching.md
Mention that when `refetchQueries` is called with an array of strings, Apollo Client tries to find previously run queries with those names, and run them again (with the same variables).
Fixes #3617.
=> Add note about calling `refetchQueries` with an array of strings

CHANGELOG.md, packages/apollo-boost/README.md
The Apollo Boost README config options section, and provided config example, are outdated and have caused some confustion for people. Since we already have everything up to date in the official docs, this commit removes the duplicated (and invalid) section from the README, replacing it with a link to the docs.
Fixes #3210.
=> Remove outdated README section

CHANGELOG.md, packages/apollo-cache-inmemory/src/mapCache.ts, packages/apollo-cache-inmemory/src/recordingCache.ts, packages/apollo-client/src/__tests__/graphqlSubscriptions.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/watchQueryOptions.ts, packages/apollo-client/src/util/subscribeAndCount.ts, packages/apollo-client/src/util/wrap.ts, packages/apollo-client/tsconfig.json, packages/apollo-utilities/src/getFromAST.ts, packages/graphql-anywhere/src/graphql-async.ts, packages/graphql-anywhere/src/graphql.ts
Currently `client.subscribe` calls are ignoring `no-cache` fetch policy settings. These changes make sure `no-cache` avoids writing subscription results to the cache.
Fixes #3709.
Fixes #3532.
=> Adjust `subscribe` to recognize the `no-cache` fetch policy

docs/source/api/apollo-client.md
Make sure that the docs clearly specify that when setting Apollo Client `defaultOptions` to be used with React Apollo `<Query />` components, `defaultOptions.watchQuery` should be used.
Reference: https://github.com/apollographql/apollo-client/issues/3452#issuecomment-410322219
=> Doc change for `defaultOptions.watchQuery` when using React Apollo

packages/apollo-client/benchmark/github-reporter.ts, packages/apollo-client/package.json
=> Replace deprecated `github` package with `@octokit/rest`

CHANGELOG.md, docs/source/advanced/subscriptions.md
subscriptions-transport-ws is a peer dependency
=> subscriptions-transport-ws is a peer dependency

CHANGELOG.md, docs/source/essentials/mutations.md
=> broken next steps links

CHANGELOG.md, docs/source/essentials/queries.md
As mentioned in this issue, https://github.com/apollographql/react-apollo/issues/1875, these props seem to not exist or at least are non-functional. This PR is to reduce confusion when using the `Query` component.
=> Remove any reference to delay and load props

docs/source/essentials/queries.md
They are listed in the API section (https://www.apollographql.com/docs/react/api/react-apollo.html#query-props), so let's add them elsewhere.
=> Add missing `onComplete` and `onError` props to "Queries" docs

CHANGELOG.md, docs/source/advanced/subscriptions.md, docs/source/api/react-apollo.md
Doc updates for the new `<Subscription/>` `onSubscriptionData` callback option.
Reference: https://github.com/apollographql/react-apollo/pull/1966
=> Docs updates for https://github.com/apollographql/react-apollo/pull/1966

CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts, packages/apollo-client/src/core/types.ts
These changes adjust `mutate`'s `refetchQueries` option to allow queries to include a custom `context` option. This `context` will then be used when refetching the query, overriding any `context` that was previsouly set with the query, when it first ran.
These changes are a continuation of #3580. They do not include automatically setting the `context` of
refetched queries to say the `context` used for the parent mutation. A `context` has to be specified
with each refetched query, if needed. This was done to maintain backwards compatibilty (e.g. preventing issues that might arise by all of a sudden running refetched queries with a mutation `context`, that wasn't explicitly requested).
=> Allow `context` option in `refetchQueries`

CHANGELOG.md, docs/source/advanced/caching.md, docs/source/api/apollo-client.md, docs/source/recipes/authentication.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/ApolloClient.ts
A new `clearStore` method has been added, that will remove all data from the store. Unlike `resetStore`, it will not refetch active queries after removing store data.
Fixes #2411.
Fixes #2774.
Fixes #3539.
Fixes #3813.
=> Add `clearStore` method

docs/source/api/react-apollo.md
- Resolve logic issue ( `component.saySomething()` should be `component.getWrappedInstance().saySomething()` )
- Introduce `wrappedInstance` constant for clarity
=> Correct WrappedInstance example in React Apollo docs

packages/graphql-anywhere/src/utilities.ts
A common part of many GraphQL/TypeScript setups is automatically generating TypeScript typings for any queries/mutations/fragments in the source code. For example, at [Trialspark](https://www.trialspark.com/), we're using [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator).
It would be great to more easily leverage the interfaces that tool is generating for our GraphQL fragments when using the `filter()` function from graphql-anywhere.
This PR makes `filter()` generic on two, **optional** type arguments. The first represents the filtered data that is returned; the second represents the larger superset of data that is passed. This way, we can pass the autogenerated typings for our fragments to the `filter()`s that use those fragments:
```typescript
import { …
```
=> Make graphql-anywhere filter function generic

docs/source/api/react-apollo.md, docs/source/essentials/queries.md
To line up with the React Apollo `partialRefetch` changes in https://github.com/apollographql/react-apollo/pull/2003.
=> Query `partialRefetch` API doc changes

CHANGELOG.md, packages/apollo-cache-inmemory/package-lock.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache-inmemory/src/fixPolyfills.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/queryKeyMaker.ts, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-cache-inmemory/src/writeToStore.ts
Since publishing `apollo-cache-inmemory@1.3.0` officially, several bugs have been reported, so we have removed the `latest` tag from 1.3.0 and restored the old 1.2.10 version as `latest`. The most recent 1.3.x release is now tagged as `next`, so you can install it by running
```bash
npm install apollo-cache-inmemory@next
```
The more information we include in the cache keys used by the `InMemoryCache`, the more different cached results can be distinguished from one another. It's a bug if a change in some input value can change the result without also producing a different cache key. The typical solution is to include the relevant input data in the cache key returned by `makeCacheKey`. Note that not all input data needs to be included explicitly in the cache key, since some inputs are …
=> [WIP] Fix various apollo-cache-inmemory 1.3.x bugs.

packages/apollo-client/src/ApolloClient.ts
There is currently a bug involving `window.navigator` when running apollo-client with React Native (see issue here: https://github.com/apollographql/apollo-client/issues/3137).
This PR simply adds one more additional check before accessing `indexOf`.
=> Make window.navigator.userAgent check more defensive for React Native.

packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts
I discovered this issue when using `react-router-dom` `<Redirect />`s in my app. My situation was, I had a parent component—let's call it `<PersonPage />`:
```jsx
<PersonPage>
{/* ... */}
</PersonPage>
```
And in that person page, I'm querying for a person:
```jsx
const personPageQuery = gql`
query personForPersonPage {
person(id: "abc") {
id
firstName
lastName
}
}
`;
<PersonPage>
<Query query={personPageQuery}>
{() => (
/* ... */
)}
</Query>
</PersonPage>
```
And inside the person page, I have a child page, `<PersonDetailsPage />`. And **`<PersonPage />` redirects to it on page load**:
```jsx
const personPageQuery = gql`
query personForPersonPage {
person(id: "abc") {
id
firstName
lastName
}
}
`;
<PersonPage>
<Query query={personPageQuery}>
{() => (
<Switch>
<Redirect from="/" …
```
=> Fix incomplete data being passed as query result

packages/apollo-client/package.json, packages/apollo-client/src/__mocks__/mockLinks.ts, packages/apollo-client/src/__tests__/subscribeToMore.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/watchQueryOptions.ts, packages/apollo-client/tsconfig.test.json
Currently, `subscribeToMore` can have only one type.
But Query and Subscription might be a different type.
Actually, our test already has such a case:
https://github.com/apollographql/apollo-client/blob/fd7622126dd314b7efb4e74a2944c986a3102378/packages/apollo-client/src/__tests__/subscribeToMore.ts#L306
I've noticed current our tests and mocks are broken in point of typing because ts-jest doesn't check type and tsc doesn't compile them.
https://github.com/apollographql/apollo-client/blob/fd7622126dd314b7efb4e74a2944c986a3102378/packages/apollo-client/tsconfig.json#L14-L15
I fixed `__tests__/subscribeToMore.ts` to pass compiling to test my change.
If you maintainers think it should be done by another PR, please feel free to ask me.
@joe-re Thank you for your help to fix this problem 🙏
=> Fix type for subscribeToMore

packages/apollo-cache-inmemory/package.json
This PR adds a `sideEffects` entry for a (seemingly new) file, `fixPolyfills`. This file does indeed have side effects. In the setup at Shopify, we have a part of the build that fails when files were unexpectedly tree shaken, and this file is currently tripping that check.
=> Add sideEffect entry for fixPolyfills in inmemory-cache

packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts, packages/apollo-utilities/package-lock.json, packages/apollo-utilities/package.json, packages/apollo-utilities/src/util/cloneDeep.ts
Fixes #3992, along with a few other miscellaneous improvements.
As #3992 (and specifically the [reproduction](https://codesandbox.io/s/q7rkm6y1ow) that @OurMajesty provided) demonstrates, now that the `InMemoryCache` may return the same object for multiple reads (when the data have not changed), the `previousResult` is often exactly (`===`) the same object as `newData.result`, which was causing the code removed by [this commit](https://github.com/apollographql/apollo-client/commit/d6a673fbc1444e115e90cc9e4c7fa3fc67bb7e56) to return early instead of broadcasting the watch.
This early return was unsafe, because the contents of the object may have changed since they were previously broadcast, so we actually do need to report those modifications, even though the object reference is the same. …
=> Various improvements around previousResult/newData change detection.

package.json, packages/apollo-cache-inmemory/src/fixPolyfills.ts, packages/apollo-cache-inmemory/src/optimism.ts
In IE11, `Map.prototype.set` is not spec-compliant and returns `undefined`. This commit removes the chained calls on `Map` to avoid the `TypeError`.
=> Fix apollo-cache-inmemory in IE11

packages/apollo-utilities/src/util/__tests__/isEqual.ts, packages/apollo-utilities/src/util/isEqual.ts
Unfortunately some of our legacy pages still have libraries that modify prototypes of built-in objects. This was causing our cache (https://github.com/convoyinc/apollo-cache-hermes) to behave very strangely. After some debugging, I found that `isEqual` was broken due to a missing `hasOwnProperty` check, and thus always evaluated to false!
=> Fix apollo-utilities isEqual bug due to missing hasOwnProperty check.

packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts
This commit is a more conservative version of https://github.com/apollographql/apollo-client/pull/4032/commits/e66027c5341dc7aaf71ee7ffcba1305b9a553525.
We still need to make a deep clone of `observableQuery.lastResult` in order to determine if future results are different (see #3992), but we should be able to restrict the use of that snapshot to a single method, rather than replacing `observableQuery.lastResult` with the snapshot.
Should help with #4054 (cc @jsslai).
=> Implement ObservableQuery#isDifferentFromLastResult.

packages/apollo-cache-inmemory/package-lock.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache-inmemory/src/__tests__/diffAgainstStore.ts, packages/apollo-cache-inmemory/src/readFromStore.ts
As #4081 demonstrates, if there are key collisions during result merging, it's possible for source objects that were previously merged by reference into the `target` object (`finalResult.result`) to be modified destructively by later merges, which in some cases can lead to cycles in the results returned by the cache.
This version of the `merge` function uses a copy-on-first-write strategy to ensure we never modify `target` objects that might once have been `source` objects. The code could have been considerably simpler if I didn't try to track `pastCopies`, but performance and memory usage are very important for this code, which is why I went to the trouble of limiting the number of shallow copies made during a single `merge`.
=> Avoid modifying source objects when merging cache results.

CHANGELOG.md, docs/source/essentials/local-state.md
[`apollo
client:codegen`](https://github.com/apollographql/apollo-tooling#apollo-clientcodegen-output) only looks inside `gql` tags. We need to use `gql` for the client-side schema so that the codegen validator will recognize the schema at all.
This will update the apollo-client docs so that they'll be compatible with codegen.
=> 📝 update local state docs to work with apollo-cli codegen

CHANGELOG.md, package.json, packages/apollo-cache-inmemory/package-lock.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache-inmemory/src/__tests__/__snapshots__/cache.ts.snap, packages/apollo-cache-inmemory/src/__tests__/__snapshots__/mapCache.ts.snap, packages/apollo-cache-inmemory/src/__tests__/cache.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/index.ts
This tweak should help with #4210, since temporary optimistic `ObjectCache` objects will no longer be `instanceof DepTrackingCache`, so the result caching system will be disabled for those reads, and thus the temporary cache objects will not be retained in any cache keys.
Using a cache type other than `DepTrackingCache` disables result caching by making the all-important `makeCacheKey` functions return falsy (undefined) values [here](https://github.com/apollographql/apollo-client/blob/7d0ed16a97e57cb3789f352fd4f359eaaa2eec0b/packages/apollo-cache-inmemory/src/readFromStore.ts#L123) and [here](https://github.com/apollographql/apollo-client/blob/7d0ed16a97e57cb3789f352fd4f359eaaa2eec0b/packages/apollo-cache-inmemory/src/readFromStore.ts#L144). Disabling result caching for these reads makes …
=> Avoid using DepTrackingCache for optimistic reads.

packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/core/QueryManager.ts
Fix for `client.watchQuery<TData, TVariables>` that creates `ObservableQuery<TData, OperationVariables>`.
=> fix(ApolloClient): Pass TVariables to ObservableQuery in watchQuery

CHANGELOG.md, package-lock.json, package.json, packages/apollo-cache/src/utils.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/types.ts, packages/apollo-client/src/data/queries.ts, packages/apollo-client/src/errors/ApolloError.ts, packages/apollo-utilities/src/__tests__/transform.ts, packages/apollo-utilities/src/getFromAST.ts, packages/apollo-utilities/src/transform.ts, packages/apollo-utilities/src/util/filterInPlace.ts, packages/apollo-utilities/tsconfig.json
The graphql AST transformation capabilities provided by `apollo-utilities` are no longer in synch with `graphql` 14.x, as they rely on being able to directly modify a graphql based AST. `graphql` 14.x has made the internal document structure read only, so we'll need to update `apollo-utilities` to use a different approach (likely using [`graphql`'s visitor](https://graphql.org/graphql-js/language/#visitor) functionality). We've know about this for a while (Renovate keeps reminding us - e.g. https://github.com/apollographql/apollo-client/pull/3875), but we should definitely address this sooner than later.
As a start, this PR updates the `@types/graphql` and `graphql` dev deps to the latest 14.x based versions, which will break CI. This PR will serve as a placeholder until this is …
=> Modernize `apollo-utilities` graphql transformation functionality

docs/source/features/pagination.md
I spent two hours trying to get the cursor based pagination to work and the only thing I was missing was the __typename, however, it wasn't in the example and struggled to find the answer elsewhere. Can you please add it to the example as it will likely help others.
=> Example docs does not show the __typename is required

docs/source/essentials/get-started.md
Someone reported on Twitter that the getting started example server was still pulling from Launchpad, so I switched it to CodeSandbox 🤦‍♀️
=> Update example server to CodeSandbox

package.json
`graphql-anywhere` is no longer used by Apollo Client, and `apollo-boost` is going to be deprecated soon. This commit removes them from the `bundlesize` check, to get the total bundle size amount down to something that better reflects reality.
=> Remove `graphql-anywhere` and `apollo-boost` from bundlesize

CHANGELOG.md, packages/apollo-cache-inmemory/package-lock.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache-inmemory/src/cacheKeys.ts, packages/apollo-cache-inmemory/src/declarations.d.ts, packages/apollo-cache-inmemory/src/depTrackingCache.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts
Since we've been struggling to declare correct types for the `optimism` npm package (for example: #4158, #4327), I finally decided to move the declarations into the `optimism` package itself: https://github.com/benjamn/optimism/commit/03b3f88424f718073513a22d2a3ab5dc13e15b90
Pretty easy! I wish I'd done this sooner.
Should fix #4327.
=> Update optimism to use its new TypeScript declarations.

packages/apollo-utilities/src/__tests__/transform.ts, packages/apollo-utilities/src/transform.ts
After upgrade to `apollo-utilities@1.1.0` queries with `@client` directive start throwing errors because of injected `__typename` field.
=> fix(removeDirectivesFromDocument): Assert field directives type.

package.json, packages/apollo-boost/package-lock.json, packages/apollo-boost/package.json, packages/apollo-cache-inmemory/package-lock.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache/package-lock.json, packages/apollo-cache/package.json, packages/apollo-client/package-lock.json, packages/apollo-client/package.json, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__mocks__/mockLinks.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/scheduler/__tests__/scheduler.ts, packages/apollo-client/src/scheduler/scheduler.ts, packages/apollo-client/tsconfig.test.json, packages/apollo-utilities/package-lock.json, packages/apollo-utilities/package.json, packages/graphql-anywhere/package-lock.json, packages/graphql-anywhere/package.json
In my rush to release https://github.com/apollographql/apollo-client/pull/4234, I removed some previously public members from the `QueryManager` and forgot to include an explicit dependency on the `tslib` package. This PR reverts the `QueryManager` changes for now, at least until https://github.com/apollographql/react-apollo/issues/2738 can be addressed, and fixes https://github.com/apollographql/apollo-client/issues/4332 by adding `tslib` to the dependencies of all client packages.
To prevent further breakage due to automatic patch updates, we will release new patch versions of the relevant packages after this PR is merged.
Once the underlying issues are fixed, we will un-revert the `QueryManager` changes and revisit how the package versions should be bumped.
=> Revert breaking changes mistakenly released in patch update

docs/source/api/apollo-client.md, package.json, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/ApolloClient.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/scheduler/__tests__/scheduler.ts, packages/apollo-client/src/scheduler/scheduler.ts
Inspired by https://github.com/apollographql/react-apollo/issues/2738, it should be possible to shut down an `ApolloClient` instance without making assumptions about its implementation details.
This `client.stop()` method should also be useful for server-side rendering, where you're supposed to create (and throw away) a new `ApolloClient` instance for each request.
I'm not entirely sure this implementation cleans up everything that might need to be cleaned up, but I am sure it's better than nothing.
=> Support ApolloClient#stop for safe client disposal.

packages/apollo-client/src/core/QueryManager.ts
This commit was extracted from https://github.com/apollographql/apollo-client/pull/4337, since the problem it solves seems unrelated to that PR.
The `QueryManager#stop` method cancels all pending fetches by running `this.fetchQueryRejectFns`. However, this leads to some unhandled promise rejections during tests, which might go unnoticed because they don't cause the test suite to fail.
This commit makes the `QueryManager#stop` method a bit more aggressive about stopping active queries and unsubscribing from observables, which prevents the unhandled rejections.
=> Prevent unhandled rejections by stopping QueryManager more thoroughly.

docs/source/essentials/local-state.md
Hi! :wave: 
This PR just fixes some links to section headers in the `Local state management` part of the docs.
Cheers.
=> docs(local-state): Fix links to section headers

CHANGELOG.md, docs/source/recipes/react-native.md
Apollo dev tools were just merged into master of react native debugger.
https://github.com/jhen0409/react-native-debugger/pull/298
@peggyrayzis suggested to add a section about it in Apollo documentation.
The updated React Native Debugger is not released for download, but it will be done soon.
=> Adding a section about react native debugger support for apollo dev tools

CHANGELOG.md, docs/source/api/apollo-client.md
I wondered why the ApolloClient.reFetchObservableQueries is not part of the documentation because its public api. Would love to see this merged.
=> add reFetchObservableQueries to ApolloClient docs

packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts
`removeQuery` was previously only calling `unsubscribe` on an operation's subscription, which doesn't trigger the `error` or `complete` handlers, thus the promise's `reject` function is not cleaned up (removed from `fetchQueryRejectFns`)
This PR changes `fetchQueryRejectFns` into a `Map`, and modifies `removeQuery` to delete an operation's associated reject fns from that map
Confirmed to have fixed the repo in https://github.com/apollographql/apollo-client/issues/3555 (cloned it and linked a local apollo-client to the project)
Should also fix https://github.com/apollographql/apollo-client/issues/3766 (although don't have a repro that exactly matches the submitted bug flow), possibly https://github.com/apollographql/apollo-client/issues/2919
Might not fix …
=> Fix: removeQuery not removing a fetch's reject fn, mistakenly triggering "store reset when query in flight" error when store resets

.github/ISSUE_TEMPLATE/question-discussion.md, COLLABORATORS.md, CONTRIBUTING.md, README.md, docs/source/why-apollo.md, packages/apollo-client/ROADMAP.md
Replace all mentions of the Apollo community Slack group with Apollo Spectrum.
=> Goodbye Slack, hello Spectrum

package-lock.json, package.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache/package.json, packages/apollo-client/package.json, packages/apollo-utilities/package.json, packages/graphql-anywhere/package.json
Changes to make sure calling `npm run watch` in any of this repo's child packages ensures the final bundles are built after compilation has completed. For the full details on why this is needed, see: https://github.com/apollographql/react-apollo/pull/2765
=> Make sure `npm run watch` builds ESM/UMD bundles

packages/apollo-client/src/__tests__/local-state/export.ts, packages/apollo-client/src/__tests__/local-state/resolvers.ts, packages/apollo-client/src/core/LocalState.ts
In an effort to simulate `defaults` behaviour from `apollo-link-state`, we're leveraging cache results when running local resolvers. The idea being that if a local resolver isn't defined for a `@client` field, the local resolver handling code can then fallback on using any matching cache results, to resolve the field. While this works in theory, it has introduced a few problems, like the one reported in #4474.
Since local resolvers adhere to Apollo Client's query fetch policy, by default the cache is consulted first, when trying to resolve a `@client` field. This means we shouldn't need to attempt to resolve from the cache again, when processing local resolvers, in most cases. There are a few situations where we
might want to do this, but the requirements are theoretical at this point, …
=> Stop using cache results in local resolver root values

packages/apollo-client/src/__tests__/local-state/export.ts, packages/apollo-client/src/__tests__/local-state/general.ts, packages/apollo-client/src/core/LocalState.ts
If an application was previously using `apollo-link-state`, updating to `apollo-client@2.5.0` could cause problems because `@client` fields are now stripped by the integrated `LocalState` API, and thus will not be passed into the link chain.
This commit should ease the transition by enabling the `LocalState` functionality only if client `resolvers` were passed to the `ApolloClient` constructor, or the `LocalState#setResolvers` method has been called.
If no client resolvers have been specified, `@client` fields will remain in the query passed to the link chain, so `apollo-link-state` can still process them, though a warning will be logged in development.
If you want to use `@client` directives to read from or write to the cache without running resolver functions, you can pass an empty …
=> Enable local state only when client resolvers provided.

packages/apollo-client/src/__mocks__/mockQueryManager.ts, packages/apollo-client/src/__mocks__/mockWatchQuery.ts, packages/apollo-client/src/util/observableToPromise.ts, packages/apollo-client/src/util/subscribeAndCount.ts
Since the published code resides in `apollo-client/lib`, relative module identifiers should not assume the existence of the `apollo-client/src` directory.
In all likelihood, these `../../src` identifiers snuck in because of VS Code's auto-import functionality. In addition to auditing automatic imports more carefully in code reviews, perhaps we should add some sort of test that forbids `../../src` identifiers in generated code?
Then again, these particular imports are only importing types, so they do not correspond to any generated import code in `apollo-client/lib`, which is perhaps why they have gone unnoticed until now.
=> Avoid ../../src in relative module identifiers.

docs/source/essentials/get-started.md
"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."
https://stackoverflow.com/a/19578808/142358
=> Remove --save option as it isn't required anymore

CHANGELOG.md, package.json, packages/apollo-cache-inmemory/src/__tests__/__snapshots__/cache.ts.snap, packages/apollo-cache-inmemory/src/__tests__/__snapshots__/mapCache.ts.snap, packages/apollo-cache-inmemory/src/__tests__/cache.ts, packages/apollo-cache-inmemory/src/__tests__/roundtrip.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts
Part of the plan I outlined in this comment: https://github.com/apollographql/apollo-client/issues/4464#issuecomment-467548798
If we could trust application code not to modify cache results, we wouldn't have to save deep snapshots of past results in order to implement `isDifferentFromLastResult` correctly (see #4069).
> Aside: why doesn't the cache just return defensive copies of all results? https://github.com/apollographql/apollo-client/issues/4031#issuecomment-435103281
While you might agree that immutability is a worthwhile aspiration, it can be hard to maintain that discipline across your entire application over time, especially in a team of multiple developers.
This commit implements a new `freezeResults` option for the `InMemoryCache` constructor, which (when true) causes all cache …
=> Support InMemoryCache({ freezeResults: true }) to help enforce immutability.

docs/_config.yml, docs/package-lock.json, docs/package.json
Enabling `hexo-versioned-netlify-redirects` to finish wiring up older [2.4 docs](https://version-2-4--apollo-client-docs.netlify.com/docs/react/).
=> Enable `hexo-versioned-netlify-redirects` for docs versionning

CHANGELOG.md, docs/source/recipes/react-native.md
We no longer want to maintain a list of external React Native example apps, so this PR removes the request from the docs. Maintaining a list of external links requires review/vet/approve/etc overhead, and is not something we can devote time to right now unfortunately.
Closes https://github.com/apollographql/apollo-client/pull/4428.
=> Remove request for React Native example apps

CHANGELOG.md, config/rollup.config.js, package-lock.json, package.json, packages/apollo-boost/package-lock.json, packages/apollo-boost/package.json, packages/apollo-cache-inmemory/package-lock.json, packages/apollo-cache-inmemory/package.json, packages/apollo-cache/package-lock.json, packages/apollo-client/package-lock.json, packages/apollo-client/package.json, packages/apollo-utilities/package-lock.json, packages/apollo-utilities/package.json, packages/graphql-anywhere/package-lock.json
Should help address https://github.com/apollographql/apollo-client/issues/4519.
Implemented and explained by https://github.com/apollographql/invariant-packages/pull/1.
=> Assign unique error codes to production invariant errors.

package-lock.json, package.json
Explanation: https://github.com/siddharthkp/bundlesize/pull/260#issuecomment-462760969
Also using `@condenast/bundlesize` for the `apollo-link` packages: https://github.com/apollographql/apollo-link/pull/965
=> Use @condenast/bundlesize to avoid compiling iltorb.

packages/apollo-boost/src/__tests__/config.ts, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts
The `cloneDeep` helper from `apollo-utilities` has begun showing up prominently in some performance profiles (#4464), because we were forced to start taking snapshots of previous results to guard against destructive modifications (#4069).
While we cannot mandate immutable data handling for all application code that interacts with Apollo Client, we can give developers the tools to eliminate the runtime cost of using `cloneDeep`, which is incurred to defend against destructive modifications of cache results. If we don't have to worry about destructive updates, we can skip calling `cloneDeep`. Some cooperation from the application developer is required to achieve this goal, and that's what this PR enables.
This new (highly recommended) strategy has two parts:
```ts
const client = new …
```
=> Avoid costly cloneDeep snapshots when cache results are known to be immutable.

packages/apollo-client/src/__tests__/local-state/general.ts, packages/apollo-client/src/core/LocalState.ts
The local resolvers are disabled warning message has been confusing people who want local resolvers disabled (so they want `@client` directives passed through the link chain), but aren't using `apollo-link-state` (they're using other custom links that leverage `@client`). This PR adjusts the warning message to remove the mention of `apollo-link-state`, and be explicit about `@client` directives being passed into the link chain.
=> Adjust wording of disabled local resolvers warning message

package.json, packages/apollo-cache-inmemory/package-lock.json, packages/apollo-cache-inmemory/package.json, packages/apollo-client/package-lock.json, packages/apollo-client/package.json, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__mocks__/mockLinks.ts, packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/__tests__/graphqlSubscriptions.ts, packages/apollo-client/src/__tests__/local-state/__snapshots__/general.ts.snap, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/data/store.ts, packages/apollo-client/src/util/observables.ts, packages/apollo-utilities/src/transform.ts
As part of our ongoing effort to reduce bundle sizes (#4324), this PR makes a number of key improvements:
* Uses `invariant.{warn,error}` and `InvariantError` more consistently, to enable stripping long error strings in production via https://github.com/apollographql/invariant-packages.
* Eliminates the external dependency on https://www.npmjs.com/package/apollo-link-dedup in favor of a shorter internal implementation in the `getObservableFromLink` method.
* Uses the `getObservableFromLink` method to unify a substantial portion of query, mutation, and subscription logic.
* Introduces several reusable operators for working with `Observables`: `afterAllUnsubscribed`, `multiplex`, and `asyncMap`.
* Trims a large quantity of low-hanging bytes from `ObservableQuery.ts`.
The individual commits …
=> Further reduce bundle size by improving QueryManager and ObservableQuery.

packages/apollo-cache-inmemory/src/fixPolyfills.ts
This is fix for issue https://github.com/apollographql/apollo-client/issues/4417
This solution is inspired from this thread https://stackoverflow.com/a/41975448/6836965
=> Fix for 4417 apollo-cache-inmemory's fixPolyfills declares block-scoped variables that can cause duplicate types

CHANGELOG.md, package.json, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/local-state/resolvers.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-utilities/src/index.ts, packages/apollo-utilities/src/util/canUse.ts
Much of this work was previously duplicated for every request, which was not only wasteful for obvious reasons, but also limited the benefits of caching based on `DocumentNode` references, since repeatedly transforming the same document changes its referential identity, making it hard to tell whether a given document has been encountered before.
=> Perform all DocumentNode transforms once, and cache the results.

packages/apollo-client/src/core/QueryManager.ts
Normally local state resolvers run [in `getObservableFromLink`](https://github.com/apollographql/apollo-client/blob/68169f31a4d4d41af9a90ae1fed4414255e829a3/packages/apollo-client/src/core/QueryManager.ts#L1190-L1195), which is called from `fetchRequest`, which is called from `fetchQuery`.
When `fetchQuery` does not call `fetchRequest`, it's still important to run [forced](https://www.apollographql.com/docs/react/essentials/local-state.html#forcing-resolvers) resolvers, but it makes more sense to do that immediately after the `fetchRequest` logic, rather than waiting until query listeners are invoked as a result of calling `broadcastQueries`.
Another nice upshot of this reorganization is that the `QueryListener` function no longer needs to contain any `await` expressions.
=> Move resolver forcing logic from QueryListener to fetchQuery.

package.json, packages/apollo-client/src/__tests__/fetchMore.ts, packages/apollo-client/src/__tests__/local-state/export.ts, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/QueryManager.ts
When using `client.watchQuery` to setup an `Observable` against a query that's using `@client @export` directives, cache changes could happen that lead to the value of the `@client @export` variable changing. When this happens, if the watched query is using a mixture of local and remote data, the watched query itself might become invalid, since the `@client @export` variable used to fetch the original data has now changed. 
To address this, this PR updates the `ObservableQuery` observers such that they first check to see if `@client @export` directives are being used, and update any associated variables. `ObservableQuery` will then perform a `refetch` using the new variables if needed, otherwise it will let the observers continue with their normal behaviour. 
It's important to note that …
=> Accommodate `@client @export` variable changes in `ObservableQuery`

packages/apollo-boost/src/index.ts
This fixes the apollo-boost `PresetConfig` type definition to accept `UriFunction` for the uri.
Here's the definition in apollo-http-link-common:
https://github.com/apollographql/apollo-link/blob/06701f3b6ea6bb4abbc1520821ccd585cbff07a1/packages/apollo-link-http-common/src/index.ts#L62
=> Fix apollo-boost uri type

docs/source/advanced/boost-migration.md
Migration from `apollo-boost` is missing `graphql-tag` as a dependency which should be installed that provides the same default as Apollo Boost.
=> Add missing `graphql-tag` dependency

packages/apollo-client/src/__tests__/subscribeToMore.ts, packages/apollo-client/src/core/watchQueryOptions.ts
Addresses #4246.
I was having some issues installing all needed dependencies, but this is just a type change and TSC doesn't show any errors for me.
=> feat(apollo-client): Adds type vars to subscribeToMore for variables

CHANGELOG.md, packages/apollo-client/src/core/QueryManager.ts
This PR fixes a bug with `fetchPolicy="no-cache"`, where data initially _appears_, and then subsequently _disappears_ (e.g. https://github.com/apollographql/apollo-client/issues/3452#issuecomment-438209541). I was able to reproduce the issue:
1. Use `InMemoryCache`.
2. Make a query with `fetchPolicy="no-cache"`. It will resolve correctly and the data will be available.
3. While that query is still being observed (via `ObservableQuery`), make a separate query using `cache-and-network` (I don't think the `fetchPolicy` is actually significant here).
4. When the new query updates the cache:
1. `QueryManager#broadcastQueries()` is called.
1. A cache watch's `callback` (which was incorrectly setup when the `no-cache` query was created) is executed and calls `this.setQuery(queryId, () => ({ …
=> Fix `QueryManager` for queries with `fetchPolicy="no-cache"`

CHANGELOG.md, packages/apollo-cache-inmemory/src/fragmentMatcher.ts, packages/apollo-client/src/__tests__/client.ts
I came across a bug where IntrospectionFragmentMatcher will break when using a fragment on the root query ([example here](https://codesandbox.io/s/jz8jwjk933)).  #3402 suggested applying #3484's fix for the heuristic matcher to the fragment matcher.  It seems to have worked.
=> Fix IntrospectionFragmentMatcher handling of fragment on root query

CHANGELOG.md, packages/apollo-client/src/__tests__/fetchMore.ts, packages/apollo-client/src/core/ObservableQuery.ts
This PR addresses issue #2286 (and #3901)
Every call of `fetchMore` on `ObservableQuery` causes another query to be created my queryManager. After this query gets executed, its result is merged into parent query's result. But child query is not disposed, it just sticks around in `queryManager.queries`/ `queryManager.queryStore` and does nothing. As far as I understand, this is a leak, and this query should be disposed. 
Please correct me if this is desired behavior, or if this change can produced any unexpected side-effects.
=> Remove unused queryId after fetchMore

docs/package.json
This branch removes the `--prefix-paths` option from `gatsby develop` called by our NPM start script in the docs.
=> Remove --prefix-paths from development

packages/apollo-client/src/__tests__/ApolloClient.ts, packages/apollo-client/src/__tests__/mutationResults.ts
The impetus for expanding the test suite is #2415 (comment)
By expanding this test suite, it proves without a doubt that mutate with standard payloads as well as writeQuery trigger observable updates. apollo-client is working as expected and this just rules out standard usage as a bug that some are seeing in #2415.
Closes #2415 
Supersedes #4264
=> Expand observables testing

docs/source/essentials/get-started.md
On 'Get Started' page, I think we should `import { gql } from 'apollo-boost'` instead of `import gql from 'graphql-tag'` since at the beginning of this page we tell a reader to `npm install apollo-boost react-apollo graphql --save` (we don't install `graphql-tag`).
=> Docs: import gql from apollo-boost instead of graphql-tag

CHANGELOG.md, packages/apollo-client/src/ApolloClient.ts, packages/apollo-client/src/__tests__/client.ts
This makes `clearStore` work similarly to how `resetStore` works, which is to say the cache is first cleared and then callbacks are run. This resolves issue #4694
=> Call clearStore callbacks after clearing store

docs/source/recipes/static-typing.md
Using a Query component directly makes the code cleaner and removes a extra
build artifact when the extending class does not add any methods.
We also add in the query for the component to make the shape of the `Data` interface more clear.
Related to  https://github.com/apollographql/react-apollo/pull/2721
=> Docs: Use Query and typescript generics over class

CHANGELOG.md, packages/apollo-client/src/core/LocalState.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts, packages/apollo-client/src/core/watchQueryOptions.ts, packages/apollo-client/src/data/mutations.ts, packages/apollo-client/src/data/queries.ts, packages/apollo-client/src/data/store.ts
PR #1370 inexplicably removed support for a useful feature: the ability to opt into receiving partial results from the cache for queries that are not fully satisfied by the cache, by passing the `returnPartialData: true` option to `client.watchQuery`.
This feature is especially important in conjunction with React (or any other view framework Apollo integrations that use `client.watchQuery`), since it can prevent rerendering `undefined` data just before fetching a larger query over the network.
A lot has changed since PR #1370 was merged in March 2017. The author and reviewer of that PR no longer work for Apollo, and I would like to believe that our current development culture would prevent us from ripping out such a useful feature without providing a meaningful replacement.
=> Support returnPartialData for watched queries again.

CHANGELOG.md, packages/apollo-client/src/core/__tests__/fetchPolicies.ts, packages/apollo-client/src/data/queries.ts
Blindly setting `networkStatus` to `NetworkStatus.loading` after the client part of a `cache-and-network` query was destroying useful information about the status of the request. Instead, we should set `networkStatus` to `NetworkStatus.ready` only when the request is complete, and leave `networkStatus` untouched otherwise.
Should fix #3660, #4693, and https://github.com/apollographql/react-apollo/issues/1217.
=> Preserve networkStatus for incomplete cache-and-network queries.

packages/apollo-boost/src/index.ts
The `request` property for the `PresetConfig` interface can be of type `(operation: Operation) => void`, so I've updated the type to the following:
```
(operation: Operation) => Promise<void> | void;
```
I found this out because I was initializing a new `ApolloClient` as follows:
```ts
new ApolloClient<CacheType>({
uri: ...,
request: operation => {
operation.setContext(...);
},
resolvers: ...,
cache: ...,
})
```
Which works, but the typing complains about the `request` property not being of the type `(operation: Operation) => Promise<void>`, so I had to instead return a Promise that immediately resolves as follows:
```ts
new ApolloClient<CacheType>({
uri: ...,
request: operation => {
operation.setContext(...);
return Promise.resolve();
},
resolvers: ...,
cache: ...,
})
```
=> Update PresetConfig types in Apollo-Boost

packages/apollo-client/src/__tests__/local-state/export.ts, packages/apollo-utilities/src/transform.ts
=> Do not add __typename to @client selection sets @export-ed as input variables.

packages/apollo-client/src/index.ts
React Apollo (and potentially other projects) will want access to `WatchQueryFetchPolicy`.
=> Export WatchQueryFetchPolicy

packages/apollo-client/src/core/QueryManager.ts
The last time I touched this code in #4243, I thought it was worthwhile to preserve the behavior of sometimes batching polling query fetches in the same tick of the event loop.
However, as @voxtex points out in #4786, almost any batching strategy will lead to unpredictable fetch timing, skipped fetches, poor accounting for fetch duration (which could exceed the polling interval), and so on. On top of that, even the premise that "batching is good" comes into question if it doesn't happen consistently.
An implementation which uses independent timers seems much simpler and more predictable.
=> Stop batching polling query fetches.

docs/source/advanced/caching.md
The `readQuery` call may return an object that is shared with the current contents of cache, which can cause some weird behavior if you mutate the `readQuery` result.
=> Clarify that the result of `readQuery` should not be modified

docs/source/features/optimistic-ui.md
It's not generally safe to mutate the result of `readQuery` directly as in some circumstances the object you are mutating is shared with an object in the cache, so you can get some weird bugs from doing this.
=> Fix unsafe `update` example

CHANGELOG.md, packages/apollo-client/src/core/ObservableQuery.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts
Should help with the problem reported by @supercranky in [this comment](https://github.com/apollographql/apollo-client/issues/4636#issuecomment-483218323).
The apparent reasoning for preserving the `no-cache` and `network-only` fetch policies is that refetching requires a "network" fetch policy, but I believe `cache-and-network` should also count as a "network" fetch policy, since it always attempts to fetch from the network in addition to fetching from the cache. Even if that network request fails, it may be useful (e.g. for offline usage) to return partial data from the cache, which is currently not possible when refetching, given the `refetch` method's behavior of overriding non-network/cache-friendly `fetchPolicy`s.
=> Preserve cache-and-network fetchPolicy when refetching.

CHANGELOG.md, packages/apollo-cache-inmemory/src/__tests__/fragmentMatcher.ts, packages/apollo-cache-inmemory/src/fragmentMatcher.ts, packages/apollo-cache-inmemory/src/writeToStore.ts
Should fix #4848 by allowing fragments to match against the root `Query` selection set.
Note that this implementation does not inject `__typename` into the query document using `addTypenameToDocument`, since that would needlessly increase the size of every query/response, and we can always infer the `__typename` of the `Query`.
=> Pretend that __typename exists on the root Query.

docs/source/recipes/testing.md
Newer versions of Apollo Client require the use of a `GraphQLError` object, when mocking a real GraphQL error.
Relates to: https://github.com/apollographql/react-apollo/issues/2737
=> Fix invalid `GraphQLError` mocking example

CHANGELOG.md, config/rollup.config.js, package-lock.json, package.json
Background: https://github.com/apollographql/apollo-client/issues/4843#issuecomment-495717720
Closes my previous PR #4864, which attempted a similar ESM-to-CJS transformation using TypeScript instead of Babel.
I was tempted to use [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/en/next/babel-plugin-transform-runtime.html) here, but that would have required adding a runtime dependency on `@babel/runtime` to all Apollo Client packages. Also, since we're only running the modules transform, the set of runtime helpers is effectively limited to `interopRequireDefault` and `interopRequireWildcard`, whose implementations can be inlined safely without increasing bundle sizes very much.
Fixes #4843.
=> Compile ESM bundle to CJS using Babel instead of Rollup.

CHANGELOG.md, packages/apollo-utilities/package-lock.json, packages/apollo-utilities/package.json, packages/apollo-utilities/src/util/__tests__/isEqual.ts, packages/apollo-utilities/src/util/isEqual.ts
as requested here: https://github.com/apollographql/apollo-client/pull/4903#pullrequestreview-245170706
I don't care which one of the PRs get's merged, as long as the bug is fixed
=> refactor custom isEqual to utilise lodash.isequal

CHANGELOG.md, package-lock.json, packages/apollo-utilities/package-lock.json, packages/apollo-utilities/package.json, packages/apollo-utilities/rollup.config.js, packages/apollo-utilities/src/util/isEqual.ts
Follow-up to #4915. I have kept the tests from that PR, just not the `lodash`-based implementation of `isEqual`.
The `lodash.isequal` package has a ton of extra features we don't need, and [weighs in](https://bundlephobia.com/result?p=lodash.isequal) at a whopping 10KB minified (3.8KB after gzip). Very little of that machinery is really necessary to fix #4824.
I extracted this functionality into a separate npm package called [`@wry/equality`](https://www.npmjs.com/package/@wry/equality), so we have the flexibility to depend on the same logic in other packages without importing `apollo-utilities`.
[Here](https://github.com/benjamn/wryware/blob/master/packages/equality/src/equality.ts)'s the new implementation.
=> Reimplement isEqual without pulling in massive lodash.isequal.

docs/source/essentials/local-state.md
There's an indent spacing issues in the docs where there are extra indentations on the `visibilityFilter`, `networkStatus` properties of the `data` object.
=> docs: fix indent spacing issues in cache sample

docs/source/api/react-apollo.md, docs/source/essentials/get-started.md, docs/source/essentials/local-state.md, docs/source/essentials/mutations.md, docs/source/essentials/queries.md
This branch changes `<` and `>` signs into `&lt;` and `&gt;`in the v2.4 docs. This is so that our markdown parser doesn't get type definitions confused with html tags, e.g. `<string>` or `<ApolloQueryResult>`
=> Escape lt/gt signs in v2.4 docs

docs/source/advanced/subscriptions.md, docs/source/api/react-apollo.md
This branch turns `<` and `>` characters in our docs to `&gt;` and `&lt;`, respectively. This allows our markdown parser to tell the difference between html tags and content.
=> Escape gt/lt tags in type definitions

CHANGELOG.md, docs/source/api/react-apollo.md, docs/source/essentials/queries.md
This PR adds a quick mention of the missing `returnPartialData` feature we re-enabled in Apollo Client 2.6.
=> Add `returnPartialData` to the API docs

.vscode/settings.json, packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts, packages/apollo-cache-inmemory/src/depTrackingCache.ts, packages/apollo-cache-inmemory/src/fragmentMatcher.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/mapCache.ts, packages/apollo-cache-inmemory/src/objectCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-cache-inmemory/src/types.ts, packages/apollo-cache-inmemory/src/writeToStore.ts
Because of this incorrect path, VSCode was not picking up the correct `tsc` version and thus ignoring `tsconfig.json` in some of our packages, namely `apollo-cache-inmemory`.
=> Fix VSCode settings.json typescript.tsdk option.

docs/source/api/react-hooks.mdx
=> useQuery --> useLazyQuery

packages/apollo-boost/src/index.ts
I think the more proper way would be using `forEach` here, as `map` is needlessly returning an array of undefined elements.
=> Use `forEach` instead of `map` for error logging

packages/apollo-client/src/__tests__/client.ts
Spotted an `it.only` in the client tests which is causing some tests not to run and reducing coverage.
=> Remove .only in client tests

docs/gatsby-config.js, docs/package-lock.json, docs/package.json
This branch supplies the old `checkLinksExceptions` in the new way:
```js
checkLinksOptions: {
exceptions: [...]
}
```
=> Upgrade the docs theme and supply check-links options properly

docs/gatsby-config.js
In preparation for Apollo Client 3 documentation work, this PR sets the default document selector version to 3, and wires the `version-2.6` branch in as the 2.6 option.
=> Set the default doc selector to version 3

packages/apollo-cache-inmemory/src/__tests__/__snapshots__/cache.ts.snap, packages/apollo-cache-inmemory/src/__tests__/cache.ts, packages/apollo-cache-inmemory/src/__tests__/roundtrip.ts, packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts, packages/apollo-cache-inmemory/src/inMemoryCache.ts, packages/apollo-cache-inmemory/src/readFromStore.ts, packages/apollo-cache-inmemory/src/writeToStore.ts, packages/apollo-client/src/__tests__/ApolloClient.ts, packages/apollo-client/src/__tests__/optimistic.ts, packages/apollo-client/src/core/__tests__/ObservableQuery.ts
This option was first added in Apollo Client 2.6, as a way to help enforce immutability of cache results: https://github.com/apollographql/apollo-client/pull/4514
As promised in [the Apollo Client 2.6 blog post](https://blog.apollographql.com/whats-new-in-apollo-client-2-6-b3acf28ecad1), all cache results will be frozen/immutable in the next major version (3.0):
> In Apollo Client 3.0, we intend to make both `freezeResults` and `assumeImmutableResults` `true` by default, in addition to using the TypeScript `Readonly<T>` type to discourage destructive modifications. In other words, if you embrace immutability now, you won’t have to do anything when it becomes mandatory.
I have not yet removed the `assumeImmutableResults` option from the `ApolloClient` constructor, since cache …
=> Remove freezeResults option, assuming always true.

CHANGELOG.md, package-lock.json, package.json, packages/apollo-client/package.json
Changes were made a while back to stop `prettier` changes from being applied automatically at commit time. This commit goes further and fully removes `prettier`. The Apollo Client team has decided to no longer use `prettier` to enforce code formatting across the codebase. In most cases existing code styles should be followed as much as possible, but this is not a hard and fast rule.
=> Fully remove prettier

docs/source/essentials/local-state.mdx
`cache-first` is the default fetchPolicy, according to https://www.apollographql.com/docs/react/api/react-apollo/#optionsfetchpolicy, but for some reason this page indicates that `cache-and-network` is default. 🙅‍♂
=> Update docs with default fetchPolicy

docs/source/api/react-hoc.mdx
In the HOC API reference, we were using some invalid markdown for some of the links. This branch fixes those links!
=> Fix links on the hoc page

docs/source/essentials/local-state.mdx
Serves to replace #5261, because a pipe inside a code element apparently can't be escaped cleanly 😢The simplest fix seems to be just not rendering a couple of method names in monospace.
=> Fix table in docs broken by unescaped pipes

packages/apollo-client/src/core/watchQueryOptions.ts
Without this typescript complains that `fetchMore` doesn't accept a `context` property, but it actually does.
=> fix: fetchMore should accept `context`

CHANGELOG.md, package.json, src/cache/core/cache.ts, src/cache/core/types/Cache.ts, src/cache/inmemory/__tests__/entityCache.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityCache.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts
This PR adds a handful of powerful new methods to the official `InMemoryCache` class:
* The `cache.gc()` method removes any _unreachable_ objects from the normalized cache, using a [tracing garbage collection](https://en.wikipedia.org/wiki/Tracing_garbage_collection) strategy (as opposed to reference counting). Reachability is determined starting from a set of root entity IDs, which includes any IDs that have been directly written to or read from the cache—including the synthetic `ROOT_QUERY` ID, which is the default ID used when no specific ID is provided. From this root set of reachable IDs, garbage collection traces all child references (computed lazily and cached aggressively) until the entire reachable reference graph has been visited. Any remaining unvisited IDs are then removed …
=> Implement InMemoryCache garbage collection and eviction.

src/__tests__/__snapshots__/ApolloClient.ts.snap, src/cache/inmemory/__tests__/__snapshots__/cache.ts.snap, src/cache/inmemory/__tests__/diffAgainstStore.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts, src/utilities/storeUtils.ts
Adding `__typename` fields to the query by calling `addTypenameToDocument` used to be necessary for writing results to the cache, but now (thanks to this PR) `__typename` fields in result objects are automatically written to the cache, so no transformation is necessary.
ApolloClient still calls `cache.transformDocument` to get a query with `__typename` fields to send to the server, and the cache still relies on results from the server coming back with `__typename` fields, but the cache no longer needs the query to be transformed to include `__typename`.
Compared to PR #5311, this commit should not be a breaking change. PR #5311 ultimately failed because hiding `__typename` fields threatened to disrupt `readFragment` => transform => `writeFragment` workflows, because `writeFragment` needs …
=> Stop calling addTypenameToDocument before InMemoryCache reads/writes.

package-lock.json, package.json, src/cache/inmemory/entityCache.ts
Ever since #3394, we have used the http://npmjs.org/package/optimism to speed up repeated cache reads, by recording dependencies on specific cache IDs while computing functions like [`StoreReader#executeSelectionSet`](https://github.com/apollographql/apollo-client/blob/2de5d3b180536ea477d539d1886798405b889dcb/src/cache/inmemory/readFromStore.ts#L140-L142), and later invalidating those cached results if/when the underlying data changed in the cache.
While this system has proven to be logically correct and net-beneficial for many use cases, it wasn't as fast as it could be, because we handled the underlying ID-specific dependencies as if they were cached functions that could be recomputed, and paid the price of allowing them to have child dependencies of their own, even though they never …
=> Update optimism to use lighter-weight dependency API in EntityCache.

src/__mocks__/mockLinks.ts, src/__mocks__/mockQueryManager.ts, src/__mocks__/mockWatchQuery.ts, src/__tests__/__snapshots__/client.ts.snap, src/__tests__/client.ts, src/__tests__/fetchMore.ts, src/__tests__/local-state/general.ts, src/__tests__/local-state/resolvers.ts, src/__tests__/mutationResults.ts, src/__tests__/optimistic.ts, src/__tests__/subscribeToMore.ts, src/__tests__/utils/itAsync.ts, src/__tests__/utils/subscribeAndCount.ts, src/__tests__/utils/wrap.ts, src/core/__tests__/ObservableQuery.ts, src/core/__tests__/QueryManager/index.ts, src/core/__tests__/fetchPolicies.ts, src/core/__tests__/scheduler.ts, src/react/hooks/__tests__/useMutation.test.tsx, src/react/hooks/__tests__/useQuery.test.tsx, src/react/testing/mocks/MockedProvider.tsx, src/react/testing/mocks/mockLink.ts, src/react/testing/utils/createClient.ts
Because Jest has no ability to trace uncaught exceptions back to the test responsible for throwing them, the Apollo Client test suite has been plagued for a long time by "No more mocked responses for the query" errors, often causing unrelated tests to fail.
I have finally tracked the source of these errors down to the implementation of `MockLink`, which was using `throw` to raise exceptions, potentially outside the bounds of the test for which the `MockLink` was originally created.
This gigantic commit does two things:
* Make all `done`/`done.fail`-style tests use `Promise` `resolve` and `reject` functions instead (the bulk of the changes). This is important because we don't want stray `done.fail` calls causing tests that have already passed to fail, and `resolve`/`reject` are …
=> Promise-ify all tests, and pass a Promise reject function to mocking utilities.

src/__tests__/optimistic.ts, src/cache/inmemory/__tests__/optimistic.ts, src/cache/inmemory/inMemoryCache.ts, src/core/QueryManager.ts
This is potentially an observable breaking change for code that accesses the real (as opposed to optimistic) cache during optimistic updates, rather than using the provided `proxy` object.
Previously, the real `InMemoryCache` would also have its `cache.data` and `cache.optimisticData` properties temporarily updated to point to the new optimistic layer, so it would behave like the `proxy` cache for the duration of the transaction. Now, only the `proxy` object is updated, and the real cache is left untouched.
If this change causes any problems, the most likely solution is to make sure optimistic update functions only access the provided `proxy` object, if they are expecting to read or write optimistic data. See the tests that were updated in this commit for examples of this correction. …
=> Avoid modifying actual cache while recording optimistic transactions.

package-lock.json, package.json
https://github.com/apollographql/apollo-client/pull/5451#discussion_r335302740
This ensures it'll work without errors for Expo. Current RN (0.61) is on React 16.9.
Btw, why is it in `optionalDependencies` and not `peerDependencies `? You might get 2 copies of react then, which causes super weird errors
=> chore: set react version to the one in RN 0.59

src/cache/inmemory/__tests__/diffAgainstStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/policies.ts, src/core/__tests__/QueryManager/links.ts
It was already possible to pass an object with `__typename` and any key fields (like `id`) to the `this.identify` method in field `read` and `merge` functions, but `this.identify` only returns a string ID, whereas it's often more useful to wrap that ID with in a `{ __ref: <id> }` object.
Hence `toReference`. I considered the name `lookup` as well, but I decided it wasn't completely obvious what `lookup` would do, based on the name.
Also, `this.identify` might be inaccessible if the `read` or `merge` function is implemented using an arrow function rather than a shorthand method or normal function expression, whereas the `toReference` function is always bound to the `Policies` object.
=> Provide toReference helper function in FieldFunctionOptions.

config/rollup.config.js, package-lock.json, package.json, src/index.ts, src/react/context/ApolloConsumer.tsx, src/react/context/ApolloContext.ts, src/react/context/ApolloProvider.tsx, src/react/context/__tests__/ApolloConsumer.test.tsx, src/react/context/__tests__/ApolloProvider.test.tsx, src/react/data/MutationData.ts, src/react/data/OperationData.ts, src/react/data/QueryData.ts, src/react/data/SubscriptionData.ts, src/react/hooks/__tests__/useApolloClient.test.tsx, src/react/hooks/useApolloClient.ts, src/react/hooks/useMutation.ts, src/react/hooks/useSubscription.ts, src/react/hooks/utils/useBaseQuery.ts
I was hopeful the changes made in https://github.com/apollographql/apollo-client/commit/e53d1e3f37924432261aa0954fdf39170b0e29e4 would have fixed the issues we were seeing with multiple React contexts being created (usually one for testing utilities like `MockedProvider`, another for the application under test). While those changes do work in most cases, the approach of always pulling the `ApolloProvider` from the `apollo-client.cjs.js` bundle confuses some tools/webpack configs, like Storybook.
This PR replaces the previous approach by ensuring the `ApolloContext` code is only ever referenced using CommonJS. By using CJS to refer to this file across the entire codebase, we ensure that we're only ever pointing to one copy of the source. We're not pointing to a copy that has been converted …
=> Use CommonJS to deduplicate React context copies

src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/__tests__/ObservableQuery.ts, src/react/data/QueryData.ts, src/react/hooks/__tests__/useQuery.test.tsx, src/react/hooks/utils/useBaseQuery.ts
As an exploration of potential improvements after Apollo Client 3.0, I recently attempted to make `InMemoryCache` reads asynchronous, so that custom field `read` functions could return a promise, or perhaps an async iterator, which would ultimately allow us to remove our current local state implementation, which would be a significant bundle size savings.
The bad news: I had to update a lot of tests (no surprise there) in ways that felt too drastic for the Apollo Client 3.x release line, so I think we should postpone the idea of async cache reads until at least Apollo Client 4.0. Oh well!
The silver lining: I made a series of changes to prepare for async cache reads that make lots of sense right now. Hence, the contents of this PR.
The most important change is `Stop reading from cache in …
=> Avoid reading from cache in ObservableQuery#getCurrentResult.

CHANGELOG.md, package-lock.json, packages/apollo-client/src/core/LocalState.ts, packages/apollo-client/src/core/__tests__/LocalState.ts
Implements proposal from https://github.com/apollographql/apollo-feature-requests/issues/110 (cc @hwillson)
This allows local resolvers to understand what fields are selected via named fragments. Previously it wasn't possible for local resolvers to know what fields were selected by named fragments.
Includes test (and verified fails prior to this change)
=> Provide fragmentMap to local resolvers via info parameter

CHANGELOG.md, config/prepareDist.js, config/rollup.config.js, src/cache/index.ts, src/core/index.ts, src/react/context/ApolloConsumer.tsx, src/react/context/ApolloContext.ts, src/react/context/ApolloProvider.tsx, src/react/context/__tests__/ApolloConsumer.test.tsx, src/react/context/__tests__/ApolloProvider.test.tsx, src/react/hooks/__tests__/useApolloClient.test.tsx, src/react/hooks/__tests__/useLazyQuery.test.tsx, src/react/hooks/__tests__/useMutation.test.tsx, src/react/hooks/__tests__/useQuery.test.tsx, src/react/hooks/__tests__/useSubscription.test.tsx, src/react/hooks/useApolloClient.ts, src/react/hooks/useMutation.ts, src/react/hooks/useSubscription.ts, src/react/hooks/utils/useBaseQuery.ts, src/react/hooks/utils/useDeepMemo.ts, src/react/react.ts
Similar to the changes made in #5541, this commit adds a direct entry point for the Apollo Client cache code. Importing from `@apollo/client/cache` gives access to the cache code directly, without pulling in other parts of the Apollo Client codebase.
=> Wire up the `@apollo/client/cache` entry point

CHANGELOG.md, src/__tests__/__snapshots__/ApolloClient.ts.snap, src/__tests__/local-state/export.ts, src/__tests__/local-state/general.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/writeToStore.ts, src/core/__tests__/QueryManager/index.ts
These changes realize the consequences of the following extremely important principles:
1. In order to accumulate GraphQL data over time, the `InMemoryCache` must be able to merge the fields of different response objects together, as those objects are written to the cache.
2. However, **merging the fields of two objects is allowable only when those objects are known to have the same identity.**
If we cannot determine the identities of both objects (using `__typename` and `id`, or `keyFields`), or their identities are different, we should never merge their fields together, because doing so risks combining unrelated fields into the same logical entity object, resulting in an object that could never have been returned by the GraphQL server.
3. Even if two objects have the same identity, …
=> Never merge fields in cache unless objects have same identity.

src/cache/inmemory/__tests__/diffAgainstStore.ts, src/cache/inmemory/__tests__/optimistic.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/__tests__/recordingCache.ts, src/cache/inmemory/entityCache.ts, src/cache/inmemory/helpers.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts, src/core/__tests__/QueryManager/links.ts
I encourage reading all the commit messages included here, but the final commit is the capstone:
Until now, the `InMemoryCache` result caching system (introduced by #3394) registered dependencies on specific entity objects by ID, which meant changes to any of the fields of an entity in the cache would invalidate every query result that previously involved that entity, even if not all of those queries actually used any of the fields that changed.
While this system was logically correct, it resulted in unnecessary recomputation of cached query results. Perhaps most dramatically, any changes to the fields of the `ROOT_QUERY` object would necessitate the recomputation of every query that involved any root query fields, because those queries depended on the `ROOT_QUERY` ID rather than the …
=> Finer-grained InMemoryCache result caching.

src/cache/inmemory/__tests__/diffAgainstStore.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/__tests__/recordingCache.ts, src/cache/inmemory/__tests__/roundtrip.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts
_This PR builds on #5617, but you do not need to review those changes first._
I believe the job of a GraphQL cache is not simply to remember the results of past GraphQL queries, but to ingest those queries into a **client-side data graph** that faithfully replicates a subset of the complete data graph described by your schema.
To that end, the name `EntityCache` feels slightly inaccurate, because this data structure is the source of truth for your client-side data graph, which consists of entity objects, their fields, and their references to each other, to name just a few concepts that transcend the particulars of caching GraphQL results.
Instead, I think `EntityStore` more accurately reflects the first-class status of the client-side data graph, with the `InMemoryCache` as a wrapper of …
=> Rename EntityCache to EntityStore.

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts
_This PR builds on #5617, so you might want to review that one first._
On the writing side, this change prevents `merge` functions from destructively modifying the existing data, which is a very real temptation given the history of mutability in Apollo Client.
On the reading side, the risk is less worrisome, but it still makes sense to freeze any existing data exposed to untrusted code. The recently introduced `getFieldValue` helper function provides a convenient bottleneck for calling `maybeDeepFreeze`.
Because of the `process.env.NODE_ENV` guards (and runtime checks within `maybeDeepFreeze`), this freezing happens only in development, so it has no cost in production.
The `InMemoryCache` implementation (`EntityStore`, `StoreReader`, `StoreWriter`, etc.) will never destructively modify …
=> Deep-freeze existing values passed to read and merge functions.

docs/source/get-started.mdx
Without a cache specified in the client config, the client will error. Basically, this part of the docs doesn't work.
Tested with 3.0.0-beta4.
=> Add InMemoryCache import to introductory example code

src/react/data/QueryData.ts
The changes made in #5565 mean that `QueryData#fetchData` should no longer directly rely on `ObservableQuery#getCurrentResult` or `ObservableQuery#result`. This PR adjusts `fetchData` such that it returns a new Promise that resolves when the `ObservableQuery` subscription receives new data, re-using the same `startQuerySubscription` business rules that non-SSR renders adhere to. This ensures that the `queryPromises` (in `react/ssr/RenderPromises`) stored for SSR resolve properly after new data is received.
=> Adjust `fetchData` to accommodate #5565

src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/inMemoryCache.ts
After you've specified accurate [`keyFields` policies](https://github.com/apollographql/apollo-client/blob/release-3.0/docs/source/caching/cache-configuration.md#customizing-identifier-generation-by-type) for your types, the last thing you want is for application code to reimplement that logic just to compute IDs to use with methods like `InMemoryCache#evict`.
This commit introduces a method called `InMemoryCache#identify`, which takes a result object and computes its ID based on its `__typename` and primary key fields, so that you can do `cache.evict(cache.identify(entity))` to evict an object from the cache, without any manual string manipulation.
=> Support cache.identify(entity) for computing entity ID strings.

package.json, src/__tests__/__snapshots__/client.ts.snap, src/cache/core/cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/helpers.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/types.ts
This PR adds an additional (optional) parameter to the `cache.evict` method, to delete a specific field from a normalized entity by calling `cache.evict(id, fieldName)`. The shorter `cache.evict(id)` version works as before.
Please read the commit messages to understand what was tricky/subtle about implementing this interface. In particular, `fieldName` is the actual name of the field, as defined in your schema, and thus it may refer to multiple field values (if the field takes arguments), all of which should be invalidated when the field is deleted.
=> Support eviction of specific entity fields.

src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/readFromStore.ts
The `previousResult` option was originally a way to ensure referential identity of structurally equivalent cache results, before the result caching system was introduced in #3394. It worked by returning `previousResult` whenever it was deeply equal to the new result.
The result caching system works a bit differently, and in particular never needs to do a deep comparison of results. However, there were still a few (test) cases where `previousResult` seemed to have a positive effect, and removing it seemed like a breaking change, so we kept it around.
In the meantime, the equality check has continued to waste CPU cycles, and the behavior of `previousResult` has undermined other improvements, such as freezing cache results (#4514). Even worse, `previousResult` effectively disabled an …
=> Stop paying attention to previousResult in InMemoryCache.

src/cache/inmemory/__tests__/optimistic.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/readFromStore.ts
This PR restores the full benefits of result caching (#3394) when optimistic updates are pending, which should significantly improve the performance of optimistic updates. Apollo Client 2.x did not attempt to apply result caching to optimistic data, and the `EntityStore` (fka `EntityCache`; see #5618) introduced by Apollo Client 3.0 has been getting the cache key logic slightly wrong since it was first implemented, so the problem addressed by this PR falls somewhere between a bug and an optimization opportunity.
Details can be found in the commit messages, reproduced here:
The result caching system introduced by #3394 gained the ability to cache optimistic results (rather than just non-optimistic results) in #5197, but since then has suffered from unnecessary cache key diversity during …
=> Improve optimistic result caching by limiting cache key diversity.

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts
The `getFieldValue(fieldName)` helper function was introduced in #5617 for reading fields from the current `StoreObject` during `read` functions.
This commit adds a second parameter to `getFieldValue`, `foreignRef`, which is an optional `Reference`. When `foreignRef` is provided, `getFieldValue` will read the specified field from the `StoreObject` identified by the `foreignRef`, instead of reading from the current `StoreObject`.
In either case, `getFieldValue` reads an existing value from the cache, without invoking any `read` functions, so you cannot use `getFieldValue` to set up expensive (and potentially cyclic) chains of `read` functions.
With this new ability to read fields from arbitrary `Reference` objects, `read` functions can explore the entire reachable cache without having to …
=> Allow getFieldValue to read from foreign Reference objects.

package.json, src/core/QueryManager.ts, src/core/watchQueryOptions.ts, src/react/data/QueryData.ts, src/react/hooks/__tests__/useQuery.test.tsx
When `partialRefetch` is enabled the `useQuery` hook will automatically perform a query refetch, if it doesn't get a complete cache hit for the query. These changes ensure that `useQuery` re-renders with the data that's cached after the query has been refetched.
=> Ensure query listeners use new cache data with partialRefetch

package.json, src/cache/inmemory/__tests__/diffAgainstStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/core/__tests__/QueryManager/links.ts
Custom field `read` functions might need to perform expensive computations, so caching the results of `read` functions is encouraged. Unfortunately, there is no good way for the `InMemoryCache` to provide that caching automatically, since `read` function results could depend on any/all/some/none of the arguments passed to the field, and only the application developer knows which arguments are important.
At this point you might be thinking, "Doesn't the developer already have an opportunity to tell the cache which arguments are important by configuring `keyArgs: [...]` in the field policy?" While that statement is true, it's only the beginning of the story. When you specify `keyArgs`, you're telling the cache how to distinguish multiple values for a given field, but the `read` and `merge` …
=> Storage and invalidation for custom field read functions.

package.json, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/writeToStore.ts
As I've been working with the new `typePolicies` configuration API, I've become increasingly convinced that the presence of a `read` or `merge` function in a `FieldPolicy` should imply `keyArgs: false` by default, because those functions will almost always want full control over the interpretation of arguments, and it's annoying to have to pass `keyArgs: false` every time (with an obligatory comment explaining what it does), just to get that desired behavior.
If the developer has defined a `read` or `merge` function but still wants the cache to differentiate field values according to certain arguments, that's easy: just add an explicit `keyArgs: [...]` property to the `FieldPolicy`, to override the inferred `keyArgs: false`.
=> Assume keyArgs:false when read or merge functions are defined.

package.json, src/cache/inmemory/__tests__/diffAgainstStore.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/roundtrip.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts, src/utilities/graphql/storeUtils.ts
Although we removed the `FragmentMatcher` abstraction in PR #5073, and the `HeuristicFragmentMatcher` no longer exists, we kept trying to match fragments whenever all their fields matched, even if the fragment type condition was not satisfied by the `__typename` of the object in question.
I recently came to appreciate just how harmful this best-effort matching can be, when I realized that it means we call `executeSelectionSet` (on the reading side) and `processSelectionSet` (on the writing side) for *every* unmatched fragment, and then just throw away the result if any fields are missing, but not before recording those fields as missing in a weaker way than usual, using the `ExecResultMissingField.tolerable` boolean.
Not only is this strategy potentially costly for queries with lots of …
=> Fully eliminate the concept of heuristic fragment matching.

docs/source/data/local-state.mdx
This is just a small thing I noticed while reading the docs about getting the id from an object. I was a bit confused, because I tried searching the docs for dataObjectFromId, and of course didn't find anything else. ;)
=> Correct docs typo use `dataIdFromObject` not `dataObjectFromId`

src/cache/inmemory/helpers.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/writeToStore.ts
Ever since implementing support for custom `merge` functions, I have been unsatisfied with the `MergeOverrides` concept, especially because a mistake in the processing of overrides recently resulted in a fairly significant bug, fixed by commit 8c58be5671cd587ce82b26d937f22a882c333014.
Instead of tracking `MergeOverrides` separately from the fields processed by `processSelectionSet` and `processFieldValue` (which is not only error-prone but also complicates the return values of those methods), we can embed the necessary `FieldNode` and `__typename` information within the field data returned by `processSelectionSet`, using recognizable `FieldValueToBeMerged` objects, which are safely removed by `Policies#applyMerges` before the fully processed fields are written into the `EntityStore` …
=> Refactor custom field merge function processing.

package.json, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
Although the needs of `read` functions are not exactly the same as those of `merge` functions, I have recently come to realize that the extra properties of `ReadFunctionOptions` as compared with the shared `FieldFunctionOptions` (`readField`, `storage`, and `invalidate`) actually do make sense for `merge` functions in some relatively obscure but nevertheless legitimate scenarios, and the prospect of using the same interface for both sets of options (that is, just `FieldFunctionOptions`) is appealing for all sorts of reasons: symmetry, simplicity, explainability, and even code sharing.
Specifically, `readField` is useful for `merge` functions that maintain a paginated *set* of child objects (as opposed to a simple list), and need to read fields from those objects (which might be …
=> Unify FieldFunctionOptions between read and merge functions.

src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/inMemoryCache.ts
Fixes #5733, which was caused by multiple watches having the same cache key, so none except the first were ever re-broadcast, since the first broadcast had the side effect of marking the later watches as clean, before `this.watches.forEach` had a chance to visit them.
Background: PR #5644 reenabled an important optimization for the `InMemoryCache#broadcastWatches` method, allowing it to skip watches whose results have not changed. Unfortunately, while this optimization correctly determined whether the result had changed, it did not account for the possibility of multiple distinct consumers of the same result, which can happen (for example) when multiple components use the same query and variables via different `useQuery` calls.
Fortunately, the fix is straightforward (if not exactly …
=> Include watch.callback in maybeBroadcastWatch cache keys.

src/__tests__/local-state/general.ts
The next major version of `graphql-js` deprecates the `introspectionQuery` constant (thanks to https://github.com/graphql/graphql-js/pull/2124) that was previously leveraged in Apollo Client tests for obtaining the introspection query (to be clear, this is the query used to introspect a server, not the result of the introspection itself) in one particular test.
This deprecation isn't entirely surprising since the `getIntrospectionQuery` utility method has existed since `graphql@0.12` and is the recommended way to obtain this query in more recent versions of `graphql`, so this changes that test to use that new method.
I discovered this while investigating our compatibility with the most recently published `graphql@15.0.0-alpha.2` on `apollo-server`, `apollo-tooling` and `apollo-client`. …
=> Use `getIntrospectionQuery` rather than `introspectionQuery` constant.

config/rollup.config.js
This project no longer produces a UMD rollup bundle so the existing `globals` configuration is obsolete and can be confusing. In this case we can replace the `external` function with an array of module names. Thanks!
=> simplify rollup external configuration

CHANGELOG.md, src/react/data/MutationData.ts
apollographql/react-apollo#3417 adjusted `useMutation` to make sure the current `ApolloClient` instance is available in the result returned when `useMutation` is first called. Unfortunately, the changes in that PR are unintentionally modifying the `useState` based `result` object directly, instead of using `setResult`. This is ultimately leading to inconsistencies around the `client` instance sometimes being included in the result and stored as the `previousResult`, and other times not being included. This can then lead to infinite loop / too many render problems caused by the `!equal(this.previousResult, result)` check in `updateResult` always passing, and the state continuously being updated by repeated calls to `setResult`.
This commit adjusts the returned `useMutation` result to be a …
=> Avoid un-necessary `useMutation` re-renders

src/cache/inmemory/entityStore.ts, src/cache/inmemory/helpers.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/types.ts
When I originally wrote this code, I was motivated to keep the `get` and `getFieldValue` methods separate because they had different return types. [Method signature overloading](https://medium.com/@kevinkreuzer/typescript-method-overloading-c256dd63245a) solves that problem using just the type system, so we can have one method implementation rather than two.
At the same time, I was able to eliminate unnecessary inheritance and method overriding in the `Layer` subclass by using an `instanceof` check in `EntityStore#get`.
=> Unify EntityStore#{get,getFieldValue} methods.

src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/types.ts
Folks testing AC3 (👋 @ahrnee) have already reported some confusion about evicted data seeming to reappear in the context of optimistic mutation updates: https://github.com/apollographql/apollo-client/issues/5746#issuecomment-570693257
To prevent this confusion, I think we need to honor the force implied by the word `evict` and remove all traces of the given `dataId`/`fieldName` from all layers the cache, rather than only evicting from the top layer of the cache (namely, `this.optimisticData`).
=> Make InMemoryCache#evict remove data from all EntityStore layers.

package.json, src/cache/inmemory/entityStore.ts
Explicit `instanceof` checks are so much more readable and less surprising than multiple method implementations spread across different classes. This implementation also avoids creating multiple `Set` objects when there are any active optimistic `Layer`s.
=> Avoid inheritance/overriding in EntityStore#getRootIdSet.

CHANGELOG.md, src/__tests__/local-state/resolvers.ts, src/cache/inmemory/readFromStore.ts, src/utilities/graphql/transform.ts
Solves #5781 by keeping data written by `cache.writeData` from appearing incomplete just because it does not have `__typename` fields that were not explicitly present in the original query.
Since `InMemoryCache#transformDocument` is responsible for adding these `__typename` fields automatically, it makes sense for the `StoreReader` belonging to the `InMemoryCache` to detect and ignore those fields later, rather than handling this somewhere else, such as the `QueryManager#transform` method, where `transformDocument` is called.
@hwillson Another way of looking at this issue is that this bit of code in the `queryListenerForObserver` callback is mishandling "incomplete" data, as we've observed before:
```ts
const resultFromStore: ApolloQueryResult<T> = {
data: stale ? lastResult && …
```
=> Allow missing __typename if field added by addTypenameToDocument.

CHANGELOG.md, package.json, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/__tests__/ObservableQuery.ts, src/react/data/QueryData.ts
This partially reverts two commits from PR #5565, preserving related improvements that have happened in the meantime:
* Revert "Remove partial field from `ApolloCurrentQueryResult` type."
This reverts commit ca2cef659210dc77b21f251d97d69eefcc8f18e0.
* Revert "Stop reading from cache in `ObservableQuery#getCurrentResult`."
This reverts commit 01376a3ad09e1a806d7517cad44502b4355456af.
One of the motivations behind the original changes was to lay the foundations for eventually supporting asynchronous (specifically, `Promise`-based) cache reads, but that form of asynchrony is no longer a goal of Apollo Client 3.0 or any planned future version (there will be other ways to deliver results asynchronously, without requiring every cache read to return a `Promise`), so there's not as much benefit …
=> Read from cache again in ObservableQuery#getCurrentResult.

CHANGELOG.md, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/inMemoryCache.ts
Reactive local variables are functions that allow you to store local state in a well-known, private location, outside of the cache, consume that state while reading queries from the cache, and update the state whenever you like.
Basic usage:
```ts
const lv = cache.makeLocalVar(123)
console.log(lv()) // 123
console.log(lv(lv() + 1)) // 124
console.log(lv()) // 124
lv("asdf") // TS type error
```
TypeScript infers the value type of the variable based on the initial value, which is why switching from a number to a string is a type error here.
Any parts of any queries that relied upon the value of the variable will be invalidated when/if the variable's value is updated:
```ts
const cache: InMemoryCache = new InMemoryCache({
Person: {
fields: {
name() {
return nameVar();
},
}, …
```
=> Implement reactive variables for tracking local state.

src/cache/index.ts, src/cache/inmemory/types.ts, src/core/index.ts
This is a follow-up to commit 451a22f89e694c4c6bb059a716fd76b10daa9bb1, which exported these items from `@apollo/client`, but not from `@apollo/client/cache`, which can be used in isolation from `@apollo/client`. Now, the same exports are exported both ways.
This should help with using the `Reference` type for parameters of `read` and `merge` functions, since the type can be more easily imported now:
```ts
// Either of these import styles works:
import { Reference, isReference, makeReference } from "@apollo/client"
import { Reference, isReference, makeReference } from "@apollo/client/cache"
```
=> Export Reference type and related utilities from @apollo/client/cache.

CHANGELOG.md, package.json, src/cache/core/cache.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/diffAgainstStore.ts, src/cache/inmemory/__tests__/optimistic.ts, src/cache/inmemory/__tests__/recordingCache.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/types.ts
One of the most important internal changes in Apollo Client 3.0 is that the result caching system (introduced in #3394) now tracks its dependencies at the field level, rather than at the level of whole entity objects, thanks to #5617.
As proof that this transformation is complete, we can finally remove the ability to read entire entity objects from the `EntityStore` by ID, so that the only way to read from the store is by providing both an ID and the name of a field. The logic I improved in #5772 is now even simpler, without needing multiple overloaded `EntityStore#get` signatures.
In the process, I noticed that the `EntityStore#has(ID)` method was accidentally depending on any changes to the contents of the identified entity, even though `store.has` only "cares" about the existence of …
=> Disallow reading entire StoreObject from EntityStore by ID.

src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/inMemoryCache.ts
I would ideally like to push this check down into `readQueryFromStore`, but for now it seems worthwhile to fix this bug in the simplest way possible.
This seems like it could help with #4402, though the original reporter found another way to work around that problem.
=> Check correct store in InMemoryCache#read.

docs/gatsby-config.js
This branch removes the now-unused `filepathPrefix` option from the docs`TypescriptApiBox` component config.
=> Remove unused docs config option

config/rollup.config.js
I don't know who needs to hear this, but apparently `options.mangle.toplevel` only mangles (shortens the names of) top-level variable and function declarations. To fully prune the unused declarations from your bundle, you need `options.compress.toplevel` as well!
=> Add toplevel:true to terser options.compress as well as .mangle.

src/__tests__/client.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/readFromStore.ts
Previously, when a `Reference` object was encountered in the cache but the entity it referred to had been removed from the cache, we would muddle along and likely end up reporting missing fields within the object, without explicitly reporting that the object itself was missing.
With these changes, such errors will be thrown by `diffQueryAgainstStore`, unless `returnPartialData: true` is specified, just like missing field errors.
Should help with #5797, though a reproduction would be helpful.
=> Detect dangling references in executeSelectionSet.

docs/source/data/subscriptions.mdx, src/core/index.ts
A few small changes to enforce that graphql utilities should be imported from `@apollo/client/utilities` (instead of being available through the main `@apollo/client` bundle).
=> Small utilities export changes

CHANGELOG.md, config/rollup.config.js, package-lock.json, package.json, src/config/jest/setup.ts, src/core/index.ts, src/types/graphql-tag.d.ts, tsconfig.json
Make sure we're re-exporting all public `graphql-tag` exports, while ensuring that valid types exist.
=> Re-export all public `graphql-tag` exports

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
Follow-up to #5680.
Assuming `keyArgs:false` just because a `merge` function (or a `read` function) was defined means that the following pattern can actually change cache behavior in surprising ways:
```ts
const cache = new InMemoryCache({
Person: {
fields: {
friends: {
// This is supposed to be identical to what the cache does by
// default, except without warnings about data loss, but it
// subtly alters the default argument-based field identity
// behavior when arguments are provided to the friends field.
merge(_, incoming) {
return incoming;
},
},
},
},
},
});
```
Although this `merge` function mirrors how the cache behaves without a `merge` function, it has the benefit of making that behavior explicit, thereby silencing the warnings introduced by #5833. In order to …
=> Assume keyArgs:false only if *both* read and merge provided.

src/react/hooks/__tests__/useQuery.test.tsx
This is as it says on the box.
Essentially, SSR rehydration won't work if `useQuery` doesn't return `data` upon the first invocation when it's available. This was a problem in `3.0.0-beta.22` and seems to have been fixed now, but I wanted to ensure there was a regression test in place to avoid future issue.
=> Add test validating `useQuery` returns a result upon first call, when available

src/cache/inmemory/policies.ts
Previously, I thought it was important to process any child object fields with custom `merge` functions before processing their parents, which required a post-order traversal of the result tree (in other words,
calling `policies.applyMerges` recursively on `incoming.__value` *before* invoking the custom `merge` function). I have come to realize this was a mistake, for a few different and somewhat subtle reasons.
First, a `merge` function should be able to return merged data in any format (specified by the `TExisting` type), but it should also be able to assume the incoming data has not been modified by `merge` functions. Reasoning about data types is much simpler if the `incoming` data is always just the type of data returned by the GraphQL server/schema (`StoreValue`, most generically), …
=> Rework traversal strategy in Policies#applyMerges.

src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/index.ts, src/types/graphql-tag.d.ts, src/utilities/observables/Observable.ts, src/utilities/observables/observables.ts, src/utilities/testing/observableToPromise.ts, src/utilities/testing/subscribeAndCount.ts
A few minor export changes:
- Re-export `ZenObservable.Observer` and `ZenObservable.Subscription` as `Observer` and `ObservableSubscription` (see https://github.com/apollographql/apollo-client/commit/739f0fa6c529d962d9c40032f7caa812f49651d5 for an explanation of the naming)
- Simplify/cleanup the `graphql-tag` re-exports
=> Minor export changes

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts
Every use case for `options.invalidate` (introduced in #5667) can be handled more precisely using
local variables (introduced in #5799).
There's no reason to invalidate every query that consumed the field when you can invalidate just the queries that depended on specific local variables. In the case where a field's `read` function only consumes a single local variable, the effect of updating that variable is the same as calling `options.invalidate`.
Storing local variables in the `options.storage` object is still often a good idea, because that way they're scoped to the field, rather than being shared global variables. You can see an example of that in the tests that I updated in this PR.
This change should also make it easier to explain field invalidation in our documentation, because we …
=> Eliminate options.invalidate function in favor of local variables.

docs/source/caching/cache-field-behavior.md, src/cache/inmemory/policies.ts
Thanks to @tafelito for actually trying out the code examples in the new cache policies documentation (see #5881)! I have simplified the suggested edits to the examples, but (I hope) preserved their intent.
As for the TypeScript changes, we were previously defaulting `TExisting` to `StoreValue`, and `TIncoming` to `TExisting`, but that was never really helpful (and sometimes just frustrating), because the definition of the [`StoreValue`](https://github.com/apollographql/apollo-client/blob/2c5374b78ef7be17cc84b145fcdddd9c4618ee5e/src/utilities/graphql/storeUtils.ts#L36-L45) type reads like an incomplete list of some of the types you might find inside the cache:
```ts
export type StoreValue =
| number
| string
| string[]
| Reference
| Reference[]
| null
| undefined
| void
| Object;
```
When …
=> Address feedback on pagination examples raised in #5881.

docs/source/caching/cache-field-behavior.md, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
One of the benefits of #5880 is that any custom `merge` function gets to see its `incoming` data before any nested `merge` functions have been run, so `merge` functions have full control over how the contents of their input arguments get combined, in principle.
In practice, it's actually pretty tricky to implement a correct custom `merge` function that might encounter any non-normalized data, because even non-normalized objects can have custom `merge` functions for their fields, which must be called.
We've been (briefly) recommending that people ignore this edge case and simply return `{ ...existing, ...incoming }` when combining non-normalized objects, so that no fields are lost. However, this style ignores the possibility that the `existing` and `incoming` objects might have totally …
=> Provide options.mergeObjects for easy and correct recursive merging.

src/core/index.ts
Fixes #5889 
We're already exporting `toPromise` and it's likely that there are many custom links out there that rely on `fromPromise` so this makes sense.
=> export fromPromise

src/cache/inmemory/__tests__/__snapshots__/roundtrip.ts.snap, src/cache/inmemory/__tests__/__snapshots__/writeToStore.ts.snap, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityStore.ts, src/core/__tests__/QueryManager/index.ts
More meaningful warnings are coming (#5833) when merging non-normalized data in the cache, and we can save some code by not worrying about edge cases that don't matter.
=> Simplify EntityStore#merge.

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
Sometimes the key arguments for a field need to be determined dynamically, but that shouldn't mean the `keyArgs` function has to perform its own stable serialization. Allowing `keyArgs` functions to return a `KeySpecifier` array makes it easy to report which fields matter, and in what order they should be serialized.
Small breaking change: `keyArgs` functions now receive the arguments object as their first parameter, rather than the `FieldNode`. Other details (including the `field`) may be found in the `context` parameter.
=> Allow keyArgs functions to return KeySpecifier arrays.

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
Analogous to #5913, but for `keyFields` instead of `keyArgs`.
=> Allow keyFields functions to return KeySpecifier arrays.

src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts
This is truly an implementation detail / refactoring, with no observable behavioral changes, but I didn't want to sneak it into an unrelated PR, where it would clutter the changes.
The commit messages should explain everything, for anyone who is curious.
Thanks to better minification, this PR saves 14 bytes (minified + gzip), a very small but nice bonus.
=> Simplify makeFieldValueGetter.

docs/source/api/link/apollo-link-rest.md, docs/source/data/local-state.mdx, docs/source/migrating/apollo-client-3-migration.md
This PR addresses the suggestions made in https://github.com/apollographql/apollo-link-rest/issues/237#issuecomment-580301418:
- Change all erroneous `@apollo/link-rest` name references back to `apollo-link-rest` (since the `@apollo` namespace is reserved for Apollo (the company) maintained projects)
- Add a small mention of `apollo-link-rest` in the Migration Guide, explaining how to use the AC3 ready version
Note that the AC3 ready version of `apollo-link-rest` hasn’t been published yet, but is ready in https://github.com/apollographql/apollo-link-rest/pull/241.
=> AC3 apollo-link-rest doc updates

CHANGELOG.md, src/cache/core/types/Cache.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts
The `cache.writeQuery` and `cache.writeFragment` methods do a great job of adding data to the cache, but their behavior can be frustrating when you're trying to _remove_ specific data from a field. The typical cycle of reading data, modifying it, and writing it back into the cache does not always simply replace the old data, because it may trigger custom `merge` functions which attempt to combine `incoming` data with `existing` data, leading to confusion.
For cases when you want to apply a specific transformation to an existing field value in the cache, we are introducing a new API, `cache.modify(id, modifiers)`, which takes an entity ID and an object mapping field names to modifier functions. Each modifier function will be called with the current value of the field, and should return a …
=> Implement InMemoryCache#modify for surgically transforming fields.

CHANGELOG.md, src/__tests__/client.ts, src/cache/core/cache.ts, src/cache/core/types/DataProxy.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/readFromStore.ts
Writing data to a specific entity object in the cache should not require the additional boilerplate of creating a named fragment with a type condition.
All the cache really cares about is the top-level selection set of the query or fragment used to read or write data, and from that perspective queries are an almost perfect substitute for fragments, in almost all cases.
In other words, this code
```ts
cache.writeFragment({
id,
fragment: gql`
fragment UnnecessaryFragmentName on UnnecessaryType {
firstName
lastName
}
`,
data: {
__typename: "UnnecessaryType",
firstName,
lastName,
},
});
```
can now be written as just
```ts
cache.writeQuery({
id,
query: gql`{ firstName lastName }`,
data: { firstName, lastName },
});
```
Once you get used to using queries instead of fragments, you may begin to …
=> Allow cache.{read,write}Query to take options.id.

CHANGELOG.md, package.json, src/__tests__/local-state/export.ts, src/core/ObservableQuery.ts
PR https://github.com/apollographql/apollo-client/pull/4604 fixed an issue where changes made to `@client @export` based variables didn't always result in re-running the query that was using the variable. Unfortunately, these changes are a bit too aggressive. They're triggering a `refetch` when an `@client @export` based variable changes (and a few additional conditions are met), and while using the `ObservableQuery.refetch()` method does fix the original issue, it leads to a situation where the query being re-run is always fired over the network, even if the updated query could have been resolved from the cache. `ObservableQuery.refetch()` forces queries to use a network based fetch policy, which means if the query was originally fired with a `cache-first` policy (for example), and has …
=> Prevent @client @export from firing unnecessary network requests

src/react/data/QueryData.ts, src/react/types/types.ts
fixes #5933
`npm t` and `npm run build` both came back clean for me.
=> tighten QueryTuple to indicate observable fields may be absent

CHANGELOG.md, src/cache/inmemory/entityStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts, src/utilities/common/mergeDeep.ts, src/utilities/graphql/directives.ts
Although we've been building Apollo Client 3.0 with performance in mind, making sure (for example) that you only pay for the features you use, we haven't focused on optimizing raw performance per se, until now.
Using an especially large query and response object provided by a customer/contributor, I was able to reduce initial (cold) execution times for the following write/read round-trip from ~150ms (measured using the latest published beta, `@apollo/client@3.0.0-beta.34`) to to ~95ms, a 37% improvement, and average (warm) execution times from ~105ms to ~25ms, a 76% improvement:
```ts
const start = Date.now();
cache.writeQuery({
query,
data: result.data,
variables,
});
cache.watch({
query,
variables,
optimistic: true,
immediate: true,
callback(data) {
console.log(Date.now() - start, …
```
=> Various cache read and write performance optimizations.

package.json, src/cache/inmemory/fixPolyfills.native.ts, src/cache/inmemory/fixPolyfills.ts
React Native used to have `Map` and `Set` polyfills that relied on tagging objects with a special `__MAP_POLYFILL_INTERNAL_HASH__` property, which breaks down when the object to be tagged happens to be frozen.
In 833072ee11a3c06f7d83964faae02e157f272dfb (#3964) I introduced a workaround to make sure objects got tagged before becoming non-extensible, which robustly solved the problem for any `Map` and `Set` polyfills that rely on an object tagging strategy (not just the React Native ones).
> Note that Apollo Client freezes objects only in development (using `maybeDeepFreeze`), so the problem `fixPolyfills.ts` was intended to solve was only ever a problem in development.
A while back, I submitted [this PR](https://github.com/facebook/react-native/pull/21492) to React Native that make their …
=> Remove fixPolyfills.ts, except when bundling for React Native.

docs/source/caching/cache-field-behavior.md, src/cache/core/types/common.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts, src/core/LocalState.ts
The `options.toReference` helper function is provided to custom `read` and `merge` functions via their `options` parameter, as well as to `cache.modify` modifier functions, via their `details` parameter (#5909). See the tests included in this commit for examples of all three usages.
The original purpose of `toReference` was to return a `Reference` object, `{ __ref: <entity ID> }`, given an object with a `__typename` and the necessary key fields for that type. If these expectations are not met, `toReference(obj)` can return `null`, to indicate that the object could not be identified.
Another `toReference` failure mode (besides returning `null`) is returning a `Reference` object that doesn't actually refer to anything stored in the cache. While this case is handled gracefully during cache …
=> Support toReference(obj, true) to persist obj into cache.

CHANGELOG.md, src/cache/core/cache.ts
Hello there,
Just a quick PR based on the discussion over at #5966 
Please try not to be too impressed by my 4 lines of code.
=> Add default implementation of ApolloCache#gc

CHANGELOG.md, src/cache/index.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/inMemoryCache.ts
This PR makes two user-visible changes:
* The `cache.makeLocalVar` API introduced in #5799 has been renamed to `cache.makeVar`, for brevity and to avoid direct association with Apollo Client 2.x local state. Reactive variables should replace most use cases for local state, but they have many other potential uses. The type of the returned variable is now `ReactiveVar<T>` instead of `LocalVar<T>`.
* Updating a reactive variable with a new value will now trigger a call to `cache.broadcastWatches()`. Because the `ApolloCache` API is mostly synchronous, this broadcast is also synchronous, but it's possible to batch multiple variable updates together by performing them within a `cache.performTransaction` block.
These changes are vital for making reactive variables truly reactive, but we still …
=> Make updating cache.makeVar variables broadcast watches.

CHANGELOG.md, src/__tests__/local-state/export.ts, src/core/ObservableQuery.ts
The changes made in #5946 helped address an issue where queries with `@client @export` variables were making unnecessary network requests. While those changes work, they're currently preventing watched queries using `@client @export` from updating the `@export`ed variable, as new data is received. This commit fixes that issue.
=> Ensure @client @export variables in watched queries are updated

CHANGELOG.md, docs/source/migrating/apollo-client-3-migration.md, src/ApolloClient.ts, src/__tests__/ApolloClient.ts, src/__tests__/__snapshots__/ApolloClient.ts.snap, src/__tests__/local-state/general.ts, src/core/LocalState.ts
Apollo Client 2.x allowed `@client` fields to be passed into the `link` chain if `resolvers` were not set in the constructor. This allowed `@client` fields to be passed into Links like `apollo-link-state`. Apollo Client 3 enforces that `@client` fields are local only, meaning they are no longer passed into the `link` chain, under any circumstances. We're making this change as we're slowly starting to deprecate the Local State API (and local resolvers) in favor of the new Type Policies API. Since we want people to be able to use the Type Policies API (and `@client`) without local resolvers, we don't want to force them to always define `resolvers: {}` in their `ApolloClient` constructor, to prevent `@client` fields from being passed into the `link` chain.
If anyone wants to preserve this …
=> Prevent `@client` fields from being passed into the Link chain

src/__tests__/client.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/core/QueryInfo.ts, src/core/QueryManager.ts
As the discussion in https://github.com/apollographql/apollo-client/pull/5909#issuecomment-598752881 makes clear, there are still some gaps preventing some cache modifications from being successfully broadcast by the `QueryManager`. This PR adds additional (failing) tests for other important methods that modify the cache, as well as additional commits that attempt to fix those problems.
=> More tests of automatic broadcast for cache.{writeQuery,modify,evict}.

CHANGELOG.md, src/__tests__/ApolloClient.ts, src/__tests__/client.ts, src/__tests__/mutationResults.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/__tests__/roundtrip.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts, src/core/QueryManager.ts, src/utilities/graphql/directives.ts, src/utilities/testing/wrap.ts
The changes in `src/cache/inmemory/writeToStore.ts` make it an error rather than just a warning to write a result into the `InMemoryCache` with missing data fields, addressing an old `// XXX` comment that was grandfathered into the `StoreWriter` class.
This will be a **breaking change** for any code that was previously ignoring the warning, which means this change is appropriate for Apollo Client 3.0, but likely will not require any migration steps for most applications.
While updating the relevant tests, I realized that the `withWarning` pattern could (and should) be eliminated.
=> Throw when writing inconsistent query/data to InMemoryCache.

src/core/ObservableQuery.ts, src/core/__tests__/ObservableQuery.ts, src/core/__tests__/QueryManager/recycler.ts, src/core/watchQueryOptions.ts
The `ObservableQuery` class currently has two different ways of referring to the same variables, and goes to considerable trouble to keep `this.variables` and `this.options.variables` in sync.
We can eliminate this confusion by making `this.variables` a getter for `this.options.variables`, so only `this.options.variables` ever needs to be updated.
Getter functions have been supported [since ECMAScript 5, including Internet Explorer 9](https://caniuse.com/#feat=mdn-javascript_builtins_object_defineproperty), thanks to the `Object.defineProperty` API, which is how TypeScript compiles the code:
```js
Object.defineProperty(ObservableQuery.prototype, "variables", {
get: function () {
return this.options.variables;
},
enumerable: true,
configurable: true
});
```
Normally I would prefer to …
=> Make ObservableQuery.variables a getter for this.options.variables.

CHANGELOG.md, src/__tests__/client.ts, src/__tests__/local-state/general.ts, src/__tests__/subscribeToMore.ts, src/cache/core/types/DataProxy.ts, src/cache/core/types/common.ts, src/cache/index.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/readFromStore.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/__tests__/ObservableQuery.ts, src/core/__tests__/QueryManager/index.ts, src/core/__tests__/QueryManager/recycler.ts, src/core/__tests__/fetchPolicies.ts, src/core/types.ts, src/errors/ApolloError.ts, src/react/data/QueryData.ts, src/react/hooks/__tests__/useQuery.test.tsx, src/react/types/types.ts, src/utilities/testing/observableToPromise.ts
One of the most counterintuitive and confusing behaviors of Apollo Client is to silently re-deliver previous results whenever an incomplete result is read from the cache [here](https://github.com/apollographql/apollo-client/blob/9df809bd36c892653871a30df4d559222ee16458/src/core/QueryManager.ts#L556-L578):
```ts
// If there is some data missing and the user has told us that they
// do not tolerate partial data then we want to return the previous
// result and mark it as stale.
const stale = !diff.complete && !(
returnPartialData ||
partialRefetch ||
fetchPolicy === 'cache-only'
);
const lastResult = observableQuery.getLastResult();
const resultFromStore: ApolloQueryResult<T> = {
data: stale ? lastResult && lastResult.data : diff.result,
loading: isNetworkRequestInFlight(networkStatus), …
```
=> Stop delivering "stale" results to ObservableQuery.

src/core/ObservableQuery.ts
Fixes #6106, as confirmed using @huchenme's excellent [reproduction](https://codesandbox.io/s/client-3-hook-0r52i), because we are no longer skipping the comparison of properties like `this.lastResultSnapshot.loading` and `newResult.loading`.
=> Compare entire result objects in isDifferentFromLastResult.

CONTRIBUTING.md
Quick instructions to help new Apollo Client developers get up to speed. These instructions cover:
- How to build Apollo Client (once and in watch mode)
- How to test Apollo Client (once, in watch mode, and for specific files)
- How to wire a dev checkout of Apollo Client into an application, to test/verify core changes in a real app
=> Add development steps to the contributing guide

CHANGELOG.md, src/__tests__/client.ts, src/__tests__/local-state/resolvers.ts, src/cache/core/cache.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/inMemoryCache.ts
Most importantly, this change allows callers of `cache.modify` (#5909) to avoid passing `"ROOT_QUERY"` as the ID for modifications of root Query data.
Making the `dataId` parameter optional and moving it after the `modifiers` parameter felt much more idiomatic and understandable than than trying to support two conflicting type signatures for the `modify` method, even though that extra effort could have avoided the breaking change.
Please remember that the `cache.modify` API was added relatively recently in `@apollo/client@3.0.0-beta.34` by PR #5909, so it has never been out of beta testing, so breaking changes like this are still fair game.
=> Make dataId parameter of cache.modify optional.

CHANGELOG.md, src/__tests__/__snapshots__/graphqlSubscriptions.ts.snap, src/__tests__/client.ts, src/__tests__/local-state/__snapshots__/general.ts.snap, src/__tests__/optimistic.ts, src/core/__tests__/QueryManager/index.ts, src/errors/ApolloError.ts, src/errors/__tests__/ApolloError.ts, src/react/hooks/__tests__/useQuery.test.tsx
Implements FR: https://github.com/apollographql/apollo-feature-requests/issues/46
For consistency, strips the prefix from both GraphQL and Network errors. See "Stripping prefix" in https://github.com/apollographql/apollo-client/issues/1812#issuecomment-416011965
=> Remove "[GraphQL|Network] error" from error messages

src/cache/inmemory/policies.ts
This appears to occur when the field is not in the cache based on experiments.
=> Mark that FieldFunctionOptions.readField can return undefined

src/core/LocalState.ts, src/core/QueryManager.ts, src/core/watchQueryOptions.ts, src/link/core/types.ts
Sets typings for `data` to pre graphql@15 state and consistent with https://github.com/graphql/graphql-js/blob/master/src/execution/execute.d.ts#L48
Related to #6111
=> Supply TData generic removed in GraphQL v15

CHANGELOG.md, package.json, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/utilities/graphql/storeUtils.ts
Implementation of eviction by arguments API discussed here: https://github.com/apollographql/apollo-client/issues/6098.
Evicts entities in the cache with exact matches of field names and arguments.
=> [3.0] Eviction of fields by specific arguments

src/ApolloClient.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/__tests__/QueryManager/index.ts
Once upon a time, reusing the `watchQuery` code path for both `QueryManager#query` and `QueryManager#watchQuery` seemed to make things simpler, even though it involved unnecessary work for the `query` case. In reality, it made things more complicated, because we needed to distinguish `ObservableQuery`s we were actually observing (and might refetch) from those that we created for a single query and then threw away. If we call `fetchQuery` instead of `watchQuery` in the `query` method, we don't end up with any special non-observing/refetching `ObservableQuery` objects. Bonus: -104 bytes minified+gzip bundle size!
=> Avoid creating throwaway ObservableQuery for single queries.

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/helpers.ts, src/cache/inmemory/policies.ts
Almost certainly fixes #6245, though I couldn't find a way to reproduce the original problem using `...existing` syntax as @3nvi suggested.
=> Avoid mutating incoming data in Policies#applyMerges.

package-lock.json, package.json, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts
If we're about to write a result object into the store, but we happen to know that the exact same (`===`) result object would be returned if we were to reread the result with the same inputs right now, then we can skip the rest of the `processSelectionSet` work for this object, and immediately return a `Reference` to it.
Note that this trick only works because result objects are immutable (frozen in development), which allows us to assume the structure of a `===` result object has not changed since it was originally returned.
The `executeSelectionSet.peek` method is also vital here, since we need a way to check the latest cached result without recomputing the result if it's missing or dirty. This PR depends on these two recent `optimism` PRs: https://github.com/benjamn/optimism/pull/65, …
=> Optimization: skip writing still-fresh result objects back into the EntityStore.

CHANGELOG.md, src/core/QueryInfo.ts, src/core/__tests__/QueryManager/index.ts
- Update failing tests
- Closes #6277
=> Replace ExecutionResult with FetchResult

src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
First introduced by PR #6078, the `context.keyObject` property allows `KeyFieldsFunction` functions to report the primary keys that they used to compute the ID, which allows the `StoreWriter` to make sure those fields are always written into the cache, even if they were not mentioned in the query used for writing.
Reporting of `context.keyObject` happens automatically when you specify `keyFields` in a type policy, but `defaultDataIdFromObject` (which is called when there is no `keyFields` configured for a given `__typename`) was missing this functionality, prior to this commit.
While I was working with this code, I noticed that `defaultDataIdFromObject` was probably not doing the right thing for `id` or `_id` fields that are objects rather than strings or numbers (such as the MongoDB …
=> Adjust defaultDataIdFromObject to set context.keyObject.

docs/source/caching/cache-field-behavior.md, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
When I was first writing this code, I imagined the `Policies` object might be useful in advanced cases. Since then, I have not found any practical uses for `options.policies` that can't be satisfied by narrower APIs, and `Policies` API has changed quite a bit.
To preserve our freedom to change the internal `Policies` API without breaking anyone's code, and to simplify the context object types of `read`, `merge`, `keyFields`, and `keyArgs` functions, I think we should stop passing `options.policies` to the various cache policy functions.
For anyone who really needs access to the `Policies` object, it can still be obtained via `cache.policies`.
=> Stop exposing Policies to read/merge/key{Fields,Args} functions.

src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts, src/utilities/graphql/storeUtils.ts
I decided to split these changes out from PR #6288 after all, per my
comment https://github.com/apollographql/apollo-client/pull/6288#issuecomment-629556637.
=> Allow calling readField with ReadFieldOptions.

CHANGELOG.md, src/cache/core/__tests__/cache.ts, src/cache/core/cache.ts, src/cache/core/types/Cache.ts, src/cache/core/types/DataProxy.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts
As discussed in https://github.com/apollographql/apollo-client/issues/6262#issuecomment-626864804, it would be convenient to be able to silence the broadcast of cache updates for methods like `cache.writeQuery`, `cache.writeFragment`, and `cache.evict`.
While this was an easy change for `writeQuery` and `writeFragment`, which already accept various named options (see [`Cache.Write{Query,Fragment}Options`](https://github.com/apollographql/apollo-client/blob/9c69f97c11f0ea74df472edffcfa27d80807d80c/src/cache/core/types/DataProxy.ts#L56-L78)), it was a bit trickier in the case of `cache.evict`, which instead has positional parameters: `id: string`, `fieldName?: string`, and `args?: Record<string, any>` (see #6141 if `args` is new to you).
Compared to named options, the ergonomics of …
=> Allow silencing broadcast for cache update methods.

CHANGELOG.md, src/__tests__/client.ts, src/__tests__/local-state/resolvers.ts, src/cache/core/cache.ts, src/cache/core/types/common.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/helpers.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/types.ts
The `cache.modify` API was first introduced in #5909 as a quick way to transform the values of specific existing fields in the cache. At the time, `cache.modify` seemed promising as an alternative to the `readQuery`-transform-`writeQuery` pattern, but feedback has been mixed, most importantly from our developer experience team, who have helped me understand why `cache.modify` would be difficult to learn and to teach.
While my refactoring in #6221 addressed concerns about broadcasting `cache.modify` updates automatically, the bigger problem with `cache.modify` is simply that it requires knowledge of the internal workings of the cache, making it nearly impossible to explain to developers who are not already Apollo Client 3 experts. As much as I wanted `cache.modify` to be a selling point …
=> Remove experimental cache.modify method.

docs/source/data/queries.mdx
This updates the docs talking about `networkStatus` to import and use the `NetworkStatus` enum rather than the number `4` for readability.
=> docs: use NetworkStatus enum rather than numbers

src/react/context/ApolloContext.ts
In some cases, Symbol may be shimmed but not Symbol.for. In those cases,
the existing code would throw on platforms with no native Symbol (IE11).
This change ensures `Symbol.for` exists before using it, preventing the
issue.
We encountered this issue because of a deferred script partially shimming Symbol. After trying to load Apollo code asynchronously, IE11 would occasionally throw.
=> Check Symbol.for exists in addition to Symbol before using it.

CHANGELOG.md, src/errors/ApolloError.ts
Expands typing of `ApolloError` to include `ServerError` and `ServerParseError`. Fixes #6309
=> Expand error types to match actual error data

src/core/QueryManager.ts, src/core/__tests__/ObservableQuery.ts
When someone chooses `cache-and-network` or `network-only` as their initial `FetchPolicy`, they almost certainly do not want future cache updates to trigger unconditional network requests, which is what repeatedly applying the `cache-and-network` or `network-only` policies would seem to require.
Instead, when the cache reports an update after the initial network request, subsequent network requests should be triggered only if the cache result is incomplete.
This behavior corresponds exactly to switching to a `FetchPolicy` of `cache-first`, which we can achieve by modifying `options.fetchPolicy` in `QueryManager#fetchQueryObservable` for the _next_ `fetchQueryObservable` call, using the same options object that the `Reobserver` always passes to `fetchQueryObservable`.
Note: if these …
=> Fall back to cache-first after cache-and-network or network-only.

docs/source/data/local-state.mdx
Follow up to: https://github.com/apollographql/apollo-client/pull/6350/commits/806b077a65179b8d06b70295ba50bd4cf69a562e
It looks like we forgot to document renaming of `modifiers` to `fields` in `local-state` docs. 
This small PR fixes the issue.
Thanks a lot for reinstating `cache.modify` @benjamn
=> Document .modifiers renaming for local-state

config/rollup.config.js, examples/bundling/no-tree-shaking/rollup-ac3-no-react/package-lock.json, examples/bundling/no-tree-shaking/rollup-ac3/package-lock.json, examples/bundling/tree-shaking/rollup-ac3-no-react/package-lock.json, examples/bundling/tree-shaking/rollup-ac3/package-lock.json, examples/bundling/tree-shaking/rollup-ac3/package.json, src/react/context/ApolloConsumer.tsx, src/react/context/ApolloContext.ts, src/react/context/ApolloProvider.tsx, src/react/context/__tests__/ApolloConsumer.test.tsx, src/react/context/__tests__/ApolloProvider.test.tsx, src/react/hooks/__tests__/useApolloClient.test.tsx, src/react/hooks/__tests__/useLazyQuery.test.tsx, src/react/hooks/__tests__/useMutation.test.tsx, src/react/hooks/__tests__/useQuery.test.tsx, src/react/hooks/__tests__/useSubscription.test.tsx, src/react/hooks/useApolloClient.ts, src/react/hooks/useMutation.ts, src/react/hooks/useSubscription.ts, src/react/hooks/utils/useBaseQuery.ts, src/react/hooks/utils/useDeepMemo.ts, src/react/react.ts
PR #5577 introduced a new way of lazily loading React to help prevent modern bundlers from requiring React when used with `@apollo/client/core` (in other words, without any of Apollo Client's React components). While this approach works well for applications that aren't using React, it introduces problems for bundlers and applications that are using React (as outlined in #6035 and #6352). There are several different ways we can address this, and we might do something more substantial in the future, but for now this commit manipulates Apollo Client's core CJS bundle at build time, to make the React require optional.
Fixes #6035.
Fixes #6352.
=> Replace requireReactLazily with CJS bundle manipulation

src/cache/core/cache.ts, src/cache/core/types/Cache.ts, src/cache/core/types/common.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/types.ts
Background: https://github.com/apollographql/apollo-client/pull/6350#issuecomment-635666826
The `cache.modify` method and its related types are fairly `InMemoryCache`-specific, which is why it felt safest to confine `cache.modify` to `InMemoryCache` when I brought it back in #6350. In practice, however, that confinement just makes `cache.modify` harder to use (annoyingly, not helpfully) in cases where an `ApolloCache` is all that's available.
You could also argue that `cache.modify` has roughly the same standing (in terms of `InMemoryCache`-specificity) as `cache.identify` or `cache.gc`, which are also part of the "Optional API" of the `ApolloCache` base class. In that sense, `cache.modify` is simply joining those other AC3 APIs as part of `ApolloCache` (and thus also `InMemoryCache`).
=> Hoist cache.modify method declaration to ApolloCache.

CHANGELOG.md, src/__tests__/client.ts, src/cache/core/cache.ts, src/cache/core/types/Cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts
We've been finding lately that named options APIs are much easier to work with (and later to extend), because you can think about the different options independently, and future additions of new named options tend to be much less disruptive for existing code.
Since we're approaching a major new version of Apollo Client (3.0), and the `cache.evict` method did nothing in AC2 anyway, there's no sense preserving the alternate API with positional arguments, now that we support `Cache.EvictOptions`.
In other words, this is definitely a breaking change, but only for those who have been using using the `@apollo/client` betas. Thank you for your patience and understanding; we know changes like this can be annoying if you were using `cache.evict` heavily, but we think the uniformity of always …
=> Require Cache.EvictOptions when calling cache.evict.

src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/readFromStore.ts
Question: When `cache.read{Query,Fragment}` encounters a dangling reference (one that does not currently refer to any normalized entity object in the cache), should the cache behave as if the (nonexistent) target of the reference was an empty object, and report any requested fields as missing, or should the cache generate some other kind of error that reflects the the absence of the whole object?
I think we could answer this question either way, but I'm leaning towards the first option.
Note: it's normal for the cache to end up with dangling references when whole entity objects are evicted, or when a reference is created (e.g. by `toReference` in a `read` function) without writing any data into the cache. Cleaning up dangling references is a tricky problem, requiring application-level …
=> Stop treating dangling references differently from empty objects.

src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/readFromStore.ts
This reverts commit c81071374225a2f94e86a6f0693fe99f17b1724f, introduced recently in PR #6365. My optimism that #6365 was an improvement seems to have been misplaced, since it caused the regression reported in #6368. We're too close to the AC3 RC/release to be floating risky changes like these without clear and compelling justifications.
=> Revert PR #6365

CHANGELOG.md, src/__tests__/ApolloClient.ts, src/__tests__/optimistic.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/writeToStore.ts, src/core/__tests__/QueryManager/index.ts, src/utilities/graphql/storeUtils.ts
> This is a revival of PR #5833, which has accumulated too many merge conflicts over the last few months to be worth rebasing.
One consequence of #5603 is that replacing non-normalized data in the cache can result in loss of useful data, which is preferable to mistakenly  merging unrelated objects, but not ideal.
In almost every case, the right solution is to make sure the data can be normalized, or (if that isn't possible) to define a custom `merge` function for the field in question, within the parent type policy.
It turns out we can give a very detailed warning about such situations in development, and that's what this commit does. For example:
```
Cache data may be lost when replacing the d field of a Query object.
To address this problem (which is not a bug in Apollo Client), either …
```
=> Warn when clobbering non-normalized data in the cache.

docs/source/integrations/react-native.md
Related to [6321](https://github.com/apollographql/apollo-client/issues/6321)
I tried to dig if there are any official examples, but with no success so I believe the most proper thing to do is to remove the non-existent ones.
=> Removed broken/nonexistent example URLs from React Native docs.

.vscode/launch.json
I've found F5 doesn't start test correctly.
It seems this setting is outdated.
I've just copied from the official recipe and changed jest config path to ./config/jest.config.js.
https://github.com/microsoft/vscode-recipes/tree/485d405916e82919d845d2fd038b77f32d5191e8/debugging-jest-tests#configure-launchjson-file-for-your-test-framework
=> Update .vscode/launch.json to match official recipe.

CHANGELOG.md, src/ApolloClient.ts, src/__tests__/ApolloClient.ts
Provides support for setting a new `ApolloLink` (or link chain) after `new ApolloClient()` has been called, using a public `ApolloClient.setLink()` method.
This is a follow up of https://github.com/apollographql/apollo-client/pull/3877, and a continuation of https://github.com/apollographql/apollo-client/pull/4297.
=> Allow setting new ApolloLink after ApolloClient instantiation

docs/source/caching/cache-configuration.md
The docs indicate you can set `keyFields: false`, but the description of that field doesn't tell you what setting `false` actually does. I'm making the assumption here that this change correctly describes what `false` does.
Can a maintainer confirm this is accurate before merging? I didn't actually confirm my change is accurate, but it's what I assume happens based on the context.
=> Describe what `false` does for keyFields

src/cache/inmemory/inMemoryCache.ts, src/react/hooks/__tests__/useQuery.test.tsx
This is a failing test for issue #5790 that demonstrates an optimistic rollback issue when an error is received.
=> Let maybeBroadcastWatch broadcast older results, even if unchanged.

src/cache/inmemory/policies.ts
Minor tweaks to `defaultDataIdFromObject`'s type:
- there's a conditional for the presence of `context` in the function body, so it can be made optional
- the function always returns `string | undefined`, so the return type should reflect that
=> Fix defaultDataIdFromObject type declaration

src/react/data/QueryData.ts
PR #6216 introduced these `isMounted` guards, and was merged just before the `v3.0.0-rc.0` release. It appears (see #6386) that requiring the component to be mounted is too restrictive, specifically when doing server-side rendering, since the concept of mounting doesn't make sense without a DOM.
=> Allow onNewData to be called when unmounted, during SSR.

src/react/data/QueryData.ts, src/react/hooks/__tests__/useQuery.test.tsx
This reverts commits b6da9c89a9e6f75dc6799e7bf2668bbbcbab7e9d (#6388) and c76804eea2afcd3df4e01d5a8db3ae2c4c553aee (#6216).
Preventing StrictMode warnings in React is not worth introducing bugs that break applications. We will need to reconsider how best to prevent warnings for unmounted components.
=> Revert #6388 and #6216, fixing #6386 and #6385.

src/cache/inmemory/__tests__/readFromStore.ts
When an object is evicted from the cache, common intuition says that any dangling references to that object should be proactively removed from elsewhere in the cache. Thankfully, this intuition is misguided, because a much simpler and more efficient approach to handling dangling references is already possible, without requiring any new cache features.
As the tests added in this commit demonstrate, the cleanup of dangling references can be _postponed_ until the next time the affected fields are _read_ from the cache, simply by defining a custom `read` function that performs any necessary cleanup, in whatever way makes sense for the logic of the particular field. This lazy approach is vastly more efficient than scanning the entire cache for dangling references would be, because it kicks in …
=> Test that cache evictions propagate to parent queries.

src/cache/core/types/common.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts
The story we're telling in #6412 about using custom `read` functions to filter out dangling references works best if there's an easy way to check whether a `Reference` points to existing data in the cache. Although we could have introduced a new `options.isValidReference` helper function, I think it makes sense to let the existing `options.isReference` function handle this use case as well.
=> Support options.isReference(ref, true) to check Reference validity.

package.json, src/core/ObservableQuery.ts, src/react/hooks/__tests__/useQuery.test.tsx
Issue #6334 exposed a problem where the `lastResult` mechanism we use to prevent duplicate subscription notifications (when data hasn't changed) can unintentionally block certain results from propagating through Apollo Client. This leads to issues like loading states not being updated properly, due to new partial results looking similar to last results.
This commit ensures that last results are properly cleared out when new partial results come in.
Fixes #6334
=> Ensure last results are reset when working with partial data

src/cache/core/types/DataProxy.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/readFromStore.ts, src/core/QueryManager.ts, src/core/__tests__/fetchPolicies.ts
This fixes an issue found by @darkbasic while working with optimistic updates: https://github.com/apollographql/apollo-client/issues/6183#issuecomment-630108767
The `cache-first` `FetchPolicy` is important not just because it's the default policy, but also because both `cache-and-network` and `network-only` turn into `cache-first` after the first network request (#6353).
Once the `cache-first` policy is in effect for a query, any changes to the cache that cause the query to begin reading incomplete data will generally trigger a network request, thanks to (#6221).
However, if the source of the changes is an optimistic update for a mutation, it seems reasonable to avoid the network request during the mutation, since there's a good chance the incompleteness of the optimistic data is only …
=> Avoid network after incomplete optimistic cache results.

src/core/ObservableQuery.ts, src/core/__tests__/ObservableQuery.ts
In my codebase, we keep references to ObservableQuery objects and occasionally use them multiple times via `.result()` (to get a promise).
We noticed that when `errorPolicy` is `none`, the second call to `.result()` does _not_ yield a rejected promise but a resolved one, as if `errorPolicy` were `all`.
Added failing tests in the first commit (see CI result) and what I hope will fix the issue in the second commit. Feels like inverting the order of the calls may have unintended consequences but locally tests seem to pass.
=> Add tests for errorPolicy:none and fix ObservableQuery bug with unpersisted error

src/cache/inmemory/entityStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts
Similar to `ReadMergeContext` before it, the `ReadMergeModifyContext` type contains field declarations needed by `read`, `merge`, and `modify` functions, most importantly the `NormalizedCache` object, `context.store`, which provides one-stop access to important methods like `context.store.{getFieldValue,toReference,canRead}`.
`ReadMergeModifyContext` also serves as a supertype for the `ReadContext` and `WriteContext` types used during reading and writing of queries and fragments, allowing existing `ReadContext` and `WriteContext` objects to be passed without modification as `ReadMergeModifyContext` objects to `policies.readField` and `policies.applyMerges`.
=> Refactor ReadMergeContext to ReadMergeModifyContext.

src/cache/core/cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/inMemoryCache.ts
There are a number of scenarios where an object found in the cache will have the union type `StoreObject | Reference`. Rather than forcing application code to check `isReference` and access the `reference.__ref` property manually, we can simply make `cache.identify` work for both `StoreObject` and `Reference` objects.
=> Allow cache.identify to take Reference objects.

src/core/QueryInfo.ts, src/core/__tests__/QueryManager/index.ts
Ever since the big refactoring in #6221 made the client more aggressive about triggering network requests in response to incomplete cache data (when using a `FetchPolicy` of `cache-first`), folks testing the betas/RCs have reported that feuding queries can end up triggering an endless loop of unhelpful network requests.
This change does not solve the more general problem of queries competing with each other to update the same data in incompatible ways (see #6372 for other mitigation strategies), but I believe this commit will effectively put a stop to most cases of endless network requests.
See my lengthy implementation comment for more details, since this is a non-obvious solution to a very tricky problem.
Should fix #6307, #6370, #6434, and #6444.
=> Stop feuds by skipping cache writes for unchanged network results.

CHANGELOG.md, package.json, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/readFromStore.ts
This commit implements the proposal for automatic filtering of dangling references that I described in https://github.com/apollographql/apollo-client/pull/6425#issuecomment-642200353.
The filtering functionality demonstrated by #6412 (and updated by #6425) seems useful enough that we might as well make it the default behavior for any array-valued field consumed by a selection set. Note: the presence of `field.selectionSet` implies the author of the query expects the elements to be objects (or references) rather than scalar values. A list of scalar values should not be filtered, since it cannot contain dangling references.
By making `.filter(canRead)` automatic, we free developers from having to worry about manually removing references from lists after evicting entities from the cache. …
=> Automatically filter out dangling references from arrays.

CHANGELOG.md, src/__tests__/fetchMore.ts, src/cache/inmemory/policies.ts, src/core/ObservableQuery.ts, src/react/hooks/__tests__/useQuery.test.tsx, src/utilities/index.ts, src/utilities/policies/pagination.ts
What began as an attempt to fix #5951 ultimately turned into the realization that the `updateQuery` function used by `fetchMore` is worse in almost every way than an equivalent field policy `merge` function.
Not only do you have to pass `updateQuery` every time you call `fetchMore`, but that repetition encourages a dangerously simplistic strategy of just concatenating the arrays together.
By contrast, a field policy needs to be defined only once, operates at the field level rather than the query level, and has a chance to examine field arguments to guide the merging process. Also, the `keyFields: false` default configuration allows the field policy to avoid the awful `fetchMore` hack of cramming additional results into the original array (keyed by the original arguments, which `fetchMore` …
=> Deprecate fetchMore updateQuery function, and provide basic field policy helper functions

CHANGELOG.md, src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/policies.ts, src/utilities/index.ts, src/utilities/policies/pagination.ts
This helper function makes it very easy to consume paginated lists from Relay-friendly GraphQL servers, such as the [Artsy search API](https://metaphysics-production.artsy.net):
```ts
import { InMemoryCache } from "@apollo/client"
import { relayStylePagination } from "@apollo/client/utilities"
const cache = new InMemoryCache({
Query: {
fields: {
// The ["query"] argument keeps searches separated by args.query (but not
// by any other arguments, since the field policy will handle them).
search: relayStylePagination(["query"]),
},
},
},
});
```
With this field policy in place, you never need to provide an `updateQuery` function when calling `fetchMore` for the `Query.search` field, since the `merge` function handles that logic far more reliably than any `updateQuery` …
=> Implement a relayStylePagination field policy helper function.

docs/source/api/link/apollo-link-rest.md
Going through the Apollo Link Rest docs, I've found that swapi.co has migrated to swapi.dev.
The new URI is https://swapi.dev/api/
This PR updates the URL in the tutorial to match the new URL.
=> Fix Rest Link URL

docs/shared/query-result.mdx, src/core/ObservableQuery.ts, src/react/data/QueryData.ts
`refetch()` can be called with a subset of the variables so it seems appropriate to use a `Partial<>` here to prevent TypeScript errors. Please let me know if I'm mistaken or if there is a better practice here. Thanks!
=> Change refetch() arg to use Partial<TVariables>

docs/source/caching/cache-field-behavior.md, src/cache/core/types/common.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/entityStore.ts
Previous to this PR, `toReference` accepted objects with a `__typename` and primary key fields. Creating references for a StoreObject _without_ a `__typename` meant importing `makeReference`. In lieu of that, we decided to modify `toReference` to accept an id (in which case, it calls `makeReference` and returns the result) or a Reference object (in which case, it returns that object as-is).
=> Allow toReference to accept an id or Reference

src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/policies.ts, src/utilities/policies/pagination.ts
Should fix #6477.
Fields like `connection.totalCount` are not part of the official Relay connection [specification](https://relay.dev/graphql/connections.htm), but it seems most servers support `totalCount`, judging by this official documentation: https://graphql.org/learn/pagination/#end-of-list-counts-and-connections
Note that our `relayStylePagination` helper function does not need to know about `totalCount` specifically, but merely saves any extra connection fields in the `merge` function and later returns them from the `read` function.
=> Let relayStylePagination read function return extra connection fields.

packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts
This PR fixes #4948 and #5444, when `startPolling()` is called immediately after `stopPolling()`, it tricks `maybeFetch()` into believing the scheduled task is still valid (as it takes pollingInfo's existence before go ahead to call `fetchQuery()`).
This leads to extra query be fetched.
=> Clear setTimeout handle in stopPollingQuery()

docs/source/migrating/boost-migration.md
Looks like the Apollo Boost migration guide wasn't updated along when `apollo-link-state` was deprecated. I just did the migration myself and noticed this warning `Found @client directives in a query but no ApolloClient resolvers were specified. This means ApolloClient local resolver handling has been disabled, and @client directives will be passed through to your link chain.` so after digging in a bit I found the relevant [docs page](https://www.apollographql.com/docs/react/data/local-state/#migrating-from-apollo-link-state) that mentioned that it's now deprecated and how to migrate from it.
Hopefully this will save other people time 😃
=> Removed deprecated withClientState from boost migration

docs/gatsby-config.js, docs/package-lock.json, docs/package.json
This branch upgrades the docs Gatsby theme to take advantage of a restructuring to the `TypescriptApiBox` component that should avoid timing out builds on Netlify.
=> Upgrade gatsby theme to use new tsapibox

src/cache/core/types/DataProxy.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/entityStore.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/__tests__/readFromStore.ts, src/cache/inmemory/readFromStore.ts, src/core/QueryManager.ts, src/core/__tests__/fetchPolicies.ts
This reverts commit 94509386e984e093bd67f2ca995fcd4d89574b95 (#6419).
The logic of `diff.optimistic` needs rethinking. Any query could read from the cache at a time when optimistic updates are in progress, and that possibility should not affect the network behavior of the query.
I had hoped that the dependency tracking system would serve to protect queries whose field dependencies were unrelated to the optimistic updates, but I have now observed at least one case where this hope was badly mistaken, while debugging an endless loading spinner issue with the latest versions of `@apollo/client` (`rc.3`-`rc.8`) in the studio.apollographql.com application.
As I [mentioned](https://github.com/apollographql/apollo-client/pull/6419#discussion_r437709911) in #6419, I was not able to reproduce the …
=> Revert "Avoid network after incomplete optimistic cache results. (#6419)"

CHANGELOG.md, config/rollup.config.js, package.json, src/__tests__/client.ts, src/cache/index.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/inMemoryCache.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/reactiveVars.ts
The `makeVar` method was originally attached to `InMemoryCache` so that we could call `cache.broadcastWatches()` whenever the variable was updated. See #5799 and #5976 for background.
However, as a number of developers have reported, requiring access to an `InMemoryCache` to create a `ReactiveVar` can be awkward, since the code that calls `makeVar` may not be colocated with the code that creates the cache, and it is often desirable to create and initialize reactive variables before the cache has even been created.
As this commit shows, the `ReactiveVar` function can infer the current `InMemoryCache` from a contextual `Slot<InMemoryCache>`, when called without arguments (that is, when reading the variable). When the variable is updated (by passing a new value to the `ReactiveVar` …
=> Make makeVar a global function instead of a method of InMemoryCache.

CHANGELOG.md, config/prepareDist.js, config/rollup.config.js, docs/source/migrating/apollo-client-3-migration.md, src/react/ssr/__tests__/useLazyQuery.test.tsx, src/react/ssr/__tests__/useQuery.test.tsx, src/react/ssr/getDataFromTree.ts, src/react/ssr/index.ts, src/react/ssr/renderToStringWithData.ts
This PR migrates all `@apollo/react-ssr` functionality out of the https://github.com/apollographql/react-apollo repo, into this project. SSR features are kept out of the main `@apollo/client` bundle, and are instead reachable through the `@apollo/client/react/ssr` entry point.
=> Migrate all React Apollo SSR features into Apollo Client

docs/source/api/link/introduction.md
An `Observable` is the thing `forward()` returns, and `Observable#subscribe()` is passed the `Observer`.
=> Fixed typo in link docs

docs/package-lock.json, docs/package.json, renovate.json
This branch pins `typedoc` to version 15 to avoid build errors
=> Use typedoc 15

CHANGELOG.md, src/__tests__/mutationResults.ts, src/__tests__/optimistic.ts, src/cache/core/cache.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/inMemoryCache.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/utilities/common/errorHandling.ts
Providing an `optimisticResponse` when performing a mutation is never mandatory, since optimistic updates are an optimization for perceived performance. By corollary, if you switch back and forth between providing an `optimisticResponse` and simply waiting for the mutation to finish, that choice should have no lasting impact on the final state of the cache. After the mutation finishes, you should not be able to tell that there was ever an `optimisticResponse`.
`InMemoryCache` maintains a system of layered `EntityStore` objects to represent optimistic updates, so it can easily throw individual layers away when a mutation finishes, ultimately leaving only the "realistic" data behind. However, in cases where two or more optimistic mutations are running at the same time, directly competing to …
=> Run final mutation update against non-optimistic data.

src/__tests__/local-state/general.ts, src/core/ObservableQuery.ts, src/react/hooks/__tests__/useQuery.test.tsx
useQuery fails to get updated values for forced client-side resolvers
watchQuery performs as expected
=> Fix @client(always: true) bug with useQuery, and add regression test.

CHANGELOG.md, src/react/components/__tests__/client/Query.test.tsx, src/react/data/QueryData.ts, src/react/hoc/__tests__/queries/lifecycle.test.tsx, src/react/hoc/__tests__/queries/loading.test.tsx
Ever since https://github.com/apollographql/react-apollo/pull/1639, Apollo's React functionality has preserved a strange and nonsensical policy of falling back to the _previous_ data for `loading: true` results, even though the previous data may have nothing to do with the current request, as #6039 demonstrates. Results with `loading: true` may provide `data` from the cache (if any), but they should never simply reuse data from a previous result, which may have been derived using different variables. Instead, `result.data` should be undefined for loading states that do not have any partial cache data to provide.
This is potentially a breaking change for code that blindly relied on `result.data` being defined whenever `result.loading` is `true`, but I believe the bugs this change will fix …
=> Stop delivering previous data in unrelated loading results.

CHANGELOG.md, src/__tests__/graphqlSubscriptions.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/watchQueryOptions.ts, src/utilities/testing/mocking/mockSubscriptionLink.ts
Resolves apollographql/apollo-feature-requests#93
Allow a context to be supplied when creating subscriptions, and pass that context through to the links.
There are a bunch of other changes in here that I'm pretty sure was made by the linter or prettier or whatever you've got going. Some pre-commit hook that automatically ran. I'll mark those changes and I can get rid of them if you want.
=> Pass context from subscriptions through to links

src/__tests__/fetchMore.ts, src/core/ObservableQuery.ts, src/react/hooks/__tests__/useQuery.test.tsx
Should fix #6354, #6542, #6534, and #6459.
Reliable delivery of loading results is one of the core benefits that Apollo Client strives to provide, especially since handling loading states tends to be such an annoying, error-prone task in hand-written state management code, and Apollo Client is all about keeping hand-written state management code to a minimum.
Ever since I refactored the `FetchPolicy` system in #6221, the `fetchMore` method of `ObservableQuery` has not been delivering a loading state before sending its request. Instead, the observed query was updated only once, after the completion of the `fetchMore` network request. I've been aware of this problem for a while now, but I procrastinated solving it because I knew it would be, well, annoying. With the final release of AC3 …
=> Simulate loading result for original query before fetchMore.

CHANGELOG.md, src/react/data/QueryData.ts, src/react/hooks/__tests__/useQuery.test.tsx
Recent Apollo Client core refactoring has made it unnecessary to attempt to block duplicate `useQuery` renders when `skip` is `true`.
Fixes #5877
=> Stop blocking duplicate renders based on skip settings

config/prepareDist.js, config/rollup.config.js, src/link/http/index.ts
Since the HTTP link is required by Apollo Client, its contents are already requireable when using CJS with the `@apollo/client` CJS bundle. There might be cases where people want to import HTTP link functionality directly however, so we'll also create a HTTP link CJS bundle. While we're in here, let's also expose `rewriteURIForGET` (since this was exposed in `apollo-link-http`).
Fixes #6109
=> Create a `@apollo/client/link/http` CJS bundle

package.json
https://twitter.com/SemanticRelease/status/1249795728253353986
=> Update peerDependencies in package.json

src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/policies.ts, src/utilities/policies/pagination.ts
If the `relayStylePagination` `merge` function receives neither `args.after` nor `args.before`, the incoming edges cannot be spliced into the existing edges by cursor, so they must replace the existing edges.
Should fix #6592.
=> Replace existing edges when args.{after,before} not provided.

docs/shared/subscription-options.mdx
The `skip` options was added to `useSubscription` towards the end of last year. This just updates the docs for that change.
=> Docs: Add skip to subscription options

package.json
This reverts commit 831b7abce7a3dea09398dd8c2fc53638a1b3f3f9.
We rushed this in just before the AC3 launch without fully thinking through the consequences. From https://github.com/apollographql/apollo-client/pull/6594#issuecomment-658797100:
> I think you ought to reconsider this change. See [this explanation](https://github.com/jaydenseric/apollo-upload-client/pull/201#issuecomment-657916102). It's also been rejected in other prominent repos like [React](https://github.com/facebook/react/pull/19356).
> 
> tl;dr: it's likely that at some point in the future, a new major version of at least one of these peer dependencies will be released that isn't compatible with Apollo Client's use of it. This will cause Apollo Client to break without warning if the consumer upgrades this dependency. …
=> Revert "Update package.json peerDependencies (#6594)"

docs/source/performance/server-side-rendering.mdx
The Apollo Client SSR functionality is migrated into `@apollo/client` - @hwillson in [#6499](https://github.com/apollographql/apollo-client/issues/6499). This PR updates the documentation page for the Server Side Rendering guides.
=> Update import entry point for Apollo SSR in documentation

docs/source/migrating/hooks-migration.md
The Apollo Client SSR functionality is migrated into `@apollo/client` - @hwillson in [#6499](https://github.com/apollographql/apollo-client/issues/6499). This PR updates the migration guide page in the v3 documentation.
=> Update migrating guide for SSR

config/rollup.config.js, docs/source/api/link/apollo-link-schema.md
This prevents the `@apollo/client/link/schema` CommonJS bundle (which is used by Node.js) from accidentally pulling in the entire dependency tree of `graphql/execution/execute`.
This duplication not only increased the `@apollo/client/link/schema` CJS bundle size from 1.31kB to a whopping 22.6kB, but also caused `instanceof` to stop working reliably for types like `GraphQLSchema`, because there might be more than one definition of that constructor in play, and `instanceof` is sensitive to the exact constructor function you pass as the right-hand argument.
Should fix #6621, allowing us to revert #6622. Thanks to @stolinski for surfacing this issue.
=> Add graphql/execution/execute to external list in rollup.config.js.

src/react/types/types.ts
Per https://github.com/apollographql/apollo-client/issues/6390, the extra `| {}` makes certain semantically correct patterns that used to be okay in Typescript 3.7 illegal in 3.9. The difference between the two definitions of `optimisticResponse` in this file appears to have been a simple oversight when they were added in https://github.com/apollographql/react-apollo/pull/3257.
=> Change `optimisticResponse` type to be consistent and less restrictive.

CHANGELOG.md, package-lock.json, package.json, src/react/data/QueryData.ts, src/react/hooks/__tests__/useQuery.test.tsx
`QueryData` stores last used options to help decide when it should re-run. If new options (when compared against the previously stored last options) are found, `QueryData` will make sure the new options are passed into Apollo Client for processing. When `onCompleted` and/or `onError` options are set however, `QueryData` thinks the options received on each render are new as these callback functions don't have a stable identity. This can then lead to infinite re-renders.
This commit adjusts the `QueryData` option equality check to ignore option callbacks. During normal use of `useQuery` it should be okay to ignore callbacks like this, as they don't normally change between renders.
Fixes #6301
=> Ignore option callbacks when deciding to update a query

CHANGELOG.md, src/react/data/MutationData.ts, src/react/types/types.ts
As far as I can tell, whenever a MutationResult is provided to the user of
useMutation (or the component or HOC), it always contains a `client`; eg,
OperationData.refreshClient checks this invariant.
MutationResult is also used to type an internal state variable used by
MutationData and useMutation; this one doesn't contain a `client`. This PR
changes that variable to different type without `client`, and the actual exposed
MutationResult now has a non-optional `client`. This makes it match
`QueryResult`.
Now TypeScript consumers of `useMutation` don't need to check to see if `client`
exists before using it.
=> react: MutationResult.client is always set

README.md
Super minimal README change to point to the correct NPM badge.
=> Update npm badge link to @apollo/client

packages/apollo-client/src/__tests__/client.ts, packages/apollo-client/src/core/QueryManager.ts, packages/apollo-client/src/core/__tests__/QueryManager/index.ts
This is the same as #6261, except with the target branch set to version-2.6 in the hopes that we can get a 2.6 release with this included. Our team is not ready to transition to v3, but we still need this bug fixed.
Please let me know if this isn't typically how things are done here.
=> Fix: queryDeduplication from context

config/rollup.config.js
This partially reverts commit 627bd1b983b3084f05da6b7e8c92db294c3e3a8e from PR #6656.
PR #6656 removed a function called `prepareESM`, which was no longer needed for the sake of running `rollup-plugin-invariant`, but which had another benefit: Rollup would replace imports/exports like
```js
// Example exports from ./dist/index.js:
export * from './core'
export * from './react'
```
with their fully-expanded (and file-extensioned) equivalents:
```js
...
export { makeVar } from './cache/inmemory/reactiveVars.js';
export { defaultDataIdFromObject } from './cache/inmemory/policies.js';
export { InMemoryCache } from './cache/inmemory/inMemoryCache.js';
export { ApolloClient } from './core/ApolloClient.js';
...
```
Although this may look like more code, it effectively saves the bundler/browser …
=> Process ESM .js modules in ./dist with Rollup, again.

CHANGELOG.md, src/react/ssr/getDataFromTree.ts
We've found `React.renderToString` / `React.renderToStaticMarkup` is a) very expensive and b) blocking, so we're looking to replace it [with a non-blocking async version](https://github.com/richardscarrott/react-render-to-string-async).
However, the most costly call site is in `getDataFromTree` due to the recursive nature, so it would be great if Apollo Client would support async render functions -- I don't believe there will be any performance penalty for those using sync functions as it's already running in a microtask.
=> Support async render function in getDataFromTree / getMarkupFromTree

src/utilities/policies/pagination.ts
Fixes #6611, thanks to this astute comment from @fracmak: https://github.com/apollographql/apollo-client/issues/6611#issuecomment-662676848
Returning `undefined` from a field read function indicates to the `StoreReader` that the field is missing, and usually means the query will be (re)fetched from the server. When we haven't yet written any data to a field that's paginated by `relayStylePagination`, requesting data from the server is almost always better than providing any kind of default data, so we should avoid using `makeEmptyData()` as a default value for the `existing` parameter.
=> Avoid defaulting to empty data in relayStylePagination read function.

docs/source/data/mutations.mdx
Prevent tripping over some common gotchas with updating the cache after mutations.
Based on community feedback from: #1701, https://github.com/apollographql/react-apollo/issues/1251, and [StackOverflow](https://stackoverflow.com/a/45536592/1269037).
=> docs: add cache update gotchas

src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
Although the `__typename` of the root query, mutation, and subscription types are almost always `Query`, `Mutation`, and `Subscription`, respectively, it is possible to declare different names for those root types in your schema, which will affect queries like
```gql
query { __typename }
```
This query isn't normally very remarkable or useful, except that it happens to be the smallest legal GraphQL query.
Note that a configuration like
```ts
new InMemoryCache({
RootQuery: {
queryType: true,
},
},
})
```
is necessary to let `InMemoryCache` know that `RootQuery` is the name of the root query type, rather than `Query`. This non-default behavior is not something the cache can safely figure out without some help.
Thankfully, we have been very careful not to hard-code the …
=> Keep policies.rootIdsByTypename unique by ID as well as __typename.

src/core/QueryManager.ts, src/core/__tests__/QueryManager/index.ts
Closes #3631 
This PR was initially created by @KrumTy [4 months ago](https://github.com/apollographql/apollo-client/pull/5944), but had not been rebase for quite some time, and was missing a type definition around the test parameters. This is a bug that's been affecting myself and others, and wanted to make sure this fix got in.
=> fix(QueryManager): Allow consumers to handle promise rejection when waitRefetchQueries is enabled

CHANGELOG.md, src/core/ObservableQuery.ts, src/core/QueryInfo.ts, src/core/QueryManager.ts, src/core/__tests__/ObservableQuery.ts, src/core/__tests__/QueryManager/index.ts, src/core/__tests__/fetchPolicies.ts, src/core/index.ts, src/core/types.ts, src/react/components/__tests__/client/Query.test.tsx, src/react/hoc/__tests__/mutations/recycled-queries.test.tsx, src/react/hoc/__tests__/queries/observableQuery.test.tsx, src/react/hoc/__tests__/queries/skip.test.tsx
The crucial commit is the final one, which fixes #6659 and #6686 by making the `getCurrentResult` method of `ObservableQuery` return a result with `loading: false` when the cache provides complete data, assuming the `FetchPolicy` is `cache-first` or `cache-only` (the two policies that allow for non-loading results from the cache).
The general principle here is that `getCurrentResult` should return either the result most recently delivered to the `ObservableQuery`, or (if no result has been delivered yet) the next result that will be delivered. In cases where the cache is already primed with the necessary data (perhaps by a parent UI component), that next result can have `loading: false`, so it's important that `getCurrentResult` also returns a `loading: false` result in those cases.
Since …
=> Refactor ObservableQuery#getCurrentResult to reenable immediate delivery of warm cache results.

CHANGELOG.md, docs/source/caching/cache-field-behavior.md, src/__tests__/ApolloClient.ts, src/__tests__/fetchMore.ts, src/__tests__/optimistic.ts, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts, src/core/__tests__/QueryManager/index.ts
This PR introduces two minor improvements for `merge` and `keyArgs` functions in [field policies](https://www.apollographql.com/docs/react/caching/cache-field-behavior/).
First, if you need to write a custom [`keyArgs`](https://deploy-preview-6714--apollo-client-docs.netlify.app/docs/react/caching/cache-field-behavior/#specifying-key-arguments) function (unusual), you can now access the variables of the current read/write operation through `context.variables`.
Second, you can now write
```ts
new InMemoryCache({
Book: {
fields: {
author: {
merge: true,
},
},
},
},
})
```
as a shorthand for
```ts
new InMemoryCache({
Book: {
fields: {
author: {
merge(existing, incoming, { mergeObjects }) {
return mergeObjects(existing, incoming);
},
},
},
},
},
})
```
to …
=> Ergonomic improvements for field policy merge and keyArgs functions.

docs/shared/query-options.mdx, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/__tests__/ObservableQuery.ts, src/core/watchQueryOptions.ts, src/react/hoc/__tests__/queries/loading.test.tsx, src/react/hoc/__tests__/queries/skip.test.tsx, src/react/types/types.ts
PR #6353 seemed like a clever zero-configuration way to improve the default behavior of the `cache-and-network` and `network-only` fetch policies. Even though the word "network" is right there in the policy strings, it can be surprising (see #6305) to see network requests happening when you didn't expect them.
However, the wisdom of #6353 was contingent on this new behavior of falling back to `cache-first` not creating problems for anyone, and unfortunately that hope appears to have been overly optimistic/naive: https://github.com/apollographql/apollo-client/issues/6677#issuecomment-664212051
To keep everyone happy, I think we need to revert #6353 while providing an easy way to achieve the same effect, when that's what you want. The new `options.nextFetchPolicy` option allows updating …
=> Revert PR #6353 and support options.nextFetchPolicy instead.

CHANGELOG.md, src/__tests__/__snapshots__/exports.ts.snap, src/__tests__/client.ts, src/core/ApolloClient.ts, src/core/Reobserver.ts, src/react/data/MutationData.ts, src/utilities/common/__tests__/compact.ts, src/utilities/common/compact.ts, src/utilities/index.ts
Should fix #5978, using an approach inspired by https://github.com/trojanowski/react-apollo-hooks/pull/77.
There may be other places in the library where we should be compacting options before merging them together, but the changes in this PR are a good start.
=> Avoid clobbering default options with undefined values.

src/utilities/testing/itAsync.ts
A safer way to solve https://github.com/apollographql/apollo-client/pull/6576#issuecomment-664510739, given that 458960673148b70051315a4c0e73f9f22d749e2d had to be reverted. This change makes it safe to import the `@apollo/client/testing` entry point in environments that don't define `global.it`.
=> Avoid evaluating `it` unless/until itAsync called.

src/core/index.ts
These types were lost in #6656 when I switched from
```ts
export * from '../cache'
```
to using named exports. There are some `@apollo/client/cache` exports that I wanted to omit from `@apollo/client/core` (like `cacheSlot`), but I definitely did not intend to omit these types!
Fixes #6723.
=> Re-export cache types from @apollo/client/core, again.

src/link/schema/index.ts
Closes #6730.
I chose to use the `Promise` API instead of `async`/`await` because `async` functions tend to grow large when compiled by TypeScript.
=> Allow SchemaLink.Options.context function to be async.

docs/source/api/core/ApolloClient.mdx
Updated ApolloClient API page to reflect the changes to the packages and imports as a result of Apollo Client v3.0. The current, pre-PR, pages still show the old packages.
=> Updated ApolloClient API guide to reflect v3 API

docs/source/caching/advanced-topics.mdx
`@apollo/cache` package does not exists.
Also previous examples are importing `InMemmoryCache` from `@apollo/client`
Thanks :heart:
=> Fix wrong import in cache persintence docs

CHANGELOG.md, src/react/data/QueryData.ts, src/react/hoc/__tests__/queries/skip.test.tsx, src/react/hooks/__tests__/useQuery.test.tsx
When skip is set to true but other updated options have been passed into `useQuery` (like updated variables), `useQuery` will still make a network request, even though it will skip the handling of the response. This commit makes sure `useQuery` doesn't make unnecessary `skip` network requests.
Fixes #6670
Fixes #6190
Fixes #6572
=> Avoid making network requests when skip is true

package-lock.json, package.json, src/__tests__/ApolloClient.ts, src/cache/core/cache.ts, src/cache/core/types/Cache.ts, src/cache/core/types/DataProxy.ts, src/cache/inmemory/__tests__/__snapshots__/cache.ts.snap, src/cache/inmemory/__tests__/cache.ts, src/core/ApolloClient.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/Reobserver.ts, src/core/index.ts, src/core/types.ts, src/core/watchQueryOptions.ts, src/react/components/types.ts, src/react/data/QueryData.ts, src/react/hoc/types.ts, src/react/hooks/useLazyQuery.ts, src/react/hooks/useMutation.ts, src/react/hooks/useQuery.ts, src/react/hooks/useSubscription.ts, src/react/hooks/utils/useBaseQuery.ts, src/react/types/types.ts
Hi! 
This PR adds support for [typed-document-node](https://github.com/dotansimha/graphql-typed-document-node) interface as part of the core API and React support.
The idea behind it is to have `TData` and `TVariables` burnt into the `DocumentNode`, and allow TypeScript to automatically infer the result type and variables type, based on the `query` object passed. 
1. TypeScript types can be burnt into `DocumentNode` instead of being separated, and specified in each use.
2. No need to specify any types manually, it's being defined once when `TypedDocumentNode` is declared, and then inferred automatically by TS.
3. Simplifies integration of TypeScript and GraphQL.
4. [I also wrote an article with some examples here](https://the-guild.dev/blog/typed-document-node)
It makes integration of …
=> feature: added support for automatic type inference with `typed-document-node`

package-lock.json, package.json
Related: https://github.com/apollographql/apollo-client/pull/6720#issuecomment-669009520
@benjamn this is just a cleanup for the library, the `core` package has zero deps now and contains only the `d.ts` for the signature.
=> Bump `@graphql-typed-document-node/core` to v3

src/core/QueryInfo.ts
Ran into a scenario as described by @benjamn here: https://github.com/apollographql/apollo-client/blob/master/src/core/QueryInfo.ts#L237
where queries were feuding over a piece of data in the cache, causing an infinite loop of network requests. Normally this mechanism would have prevented them from continuing on in that loop because they were returning the same network result data every time, however, our Apollo server has tracing extensions applied as described here: https://github.com/apollographql/apollo-tracing
which causes this check to fail:
https://github.com/apollographql/apollo-client/blob/master/src/core/QueryInfo.ts#L238
since the result objects include the extensions and the extensions include unique time sensitive data like query durations and start/end time. The simple fix …
=> Settle Feuds with Data

docs/source/local-state/reactive-variables.mdx
`makeVar` was originally being used as `cache.makeVar` which is using the old import style which is no longer in Apollo 3. This should instead just be invoked as `makeVar` because it is imported as `import { makeVar } from "@apollo/client";`
(Checklist seems to not apply as this is a documentation change)
=> Update import for `makeVar` in documetation

CHANGELOG.md, src/core/QueryInfo.ts
When application code evicts an object or its fields from the cache, and those evictions trigger network requests, the network data is often vital for repairing the damage done by the eviction, even if the network data look exactly the same as the previously-written data.
In other words, after any cache eviction, we should disable the logic introduced in PR #6448 to stop query feuds. This exception is reasonable because feuding queries only write additional data into the cache, rather than evicting anything, so we can safely assume evictions do not contribute to a cycle of competing cache updates.
I freely admit the method of counting evictions that I've implemented here is a bit of a hack, but it works for any `ApolloCache` implementation, without requiring the public `ApolloCache` API …
=> Disable feud-stopping logic after any cache eviction.

docs/source/data/error-handling.mdx
Errors are saved in memory for use by an application's UI, but they are not stored in the actual cache itself. The original wording here leads people to believe they are, so this PR tweaks the wording a bit.
Related to: #4806
=> Adjust wording to stop misleading "errors stored in cache" concept

CHANGELOG.md, src/__tests__/optimistic.ts, src/cache/core/types/DataProxy.ts, src/cache/inmemory/inMemoryCache.ts, src/core/ObservableQuery.ts, src/core/QueryInfo.ts, src/core/__tests__/ObservableQuery.ts
While all four commits are worthwhile and relevant, the key change is in the third commit (97f3caf57ded838c840bf33ae069d46af11ef247):
> ### Avoid full reobservation for broadcasts from optimistic transactions.
>
> I first attempted to solve this bug in #6419, but that approach was
flawed, and we ultimately reverted it in #6493. Both of these changes
happened shortly before the AC3 launch (`rc.3` and `rc.9`, respectively).
>
> The key to this solution is that `diff.fromOptimisticTransaction` is only
ever set by the `InMemoryCache` broadcast code, when we know that we've just
performed an optimistic transaction, and we're broadcasting to a query
watcher that requested `optimistic` data. The `QueryInfo` class receives this
broadcast, and uses `diff.fromOptimisticTransaction` to decide …
=> Avoid full reobservation for optimistic mutation results.

examples/bundling/no-tree-shaking/rollup-ac2/package-lock.json, examples/bundling/no-tree-shaking/rollup-ac2/package.json, examples/bundling/no-tree-shaking/rollup-ac3-no-react/package-lock.json, examples/bundling/no-tree-shaking/rollup-ac3-no-react/package.json, package-lock.json, package.json
Should resolve [this security vulnerability](https://github.com/advisories/GHSA-hxcc-f52p-wc94) reported in `serialize-javascript` (a dependency of `rollup-plugin-terser`).
=> Update terser and rollup-plugin-terser to latest versions.

CHANGELOG.md, docs/source/local-state/managing-state-with-field-policies.mdx, src/__tests__/__snapshots__/exports.ts.snap, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/reactiveVars.ts, src/react/hooks/__tests__/useReactiveVar.test.tsx, src/react/hooks/index.ts, src/react/hooks/useReactiveVar.ts
This PR implements a React hook called `useReactiveVar` (requested in #6818), which can be used to read from a [reactive variable](https://www.apollographql.com/blog/local-state-management-with-reactive-variables/) in a way that allows the React component to rerender if/when the variable is next updated.
Previously, the only way for a reactive variable to trigger a React component rerender was through the use of `useQuery`. As the tests included in this PR demonstrate, you don't have to be using `useQuery` (or GraphQL at all) to benefit from the reactivity that `ReactiveVar<T>` provides.
Implementing `useReactiveVar` required generalizing the `ReactiveVar<T>` API to allow arbitrary listeners (not just `InMemoryCache` objects), ~but fortunately the existing cache broadcast logic fits …
=> Implement useReactiveVar hook for consuming reactive variables in React components.

CHANGELOG.md, src/__tests__/client.ts, src/core/QueryInfo.ts
Should help with #6888, which demonstrates that `===` disagrees with `equal` in some important cases, even though the cache is often able to provide `===` results when nothing has changed.
=> Check structural equality in QueryInfo#setDiff.

CHANGELOG.md, src/__tests__/client.ts, src/core/ObservableQuery.ts, src/core/QueryManager.ts, src/core/Reobserver.ts, src/core/watchQueryOptions.ts
When we introduced `options.nextFetchPolicy` in #6712, it could only be a string, so you needed to have some way of also knowing the current `fetchPolicy`, in order to be sure `nextFetchPolicy` was appropriate.
Since there has been some interest in setting `defaultOptions.watchQuery.nextFetchPolicy` as a global option (e.g. https://github.com/apollographql/apollo-client/pull/6712#issuecomment-672578444), we want to be sure that's possible without making blind guesses about the current `options.fetchPolicy`. To that end, `nextFetchPolicy` can now be a function that takes the current `FetchPolicy` (which defaults to `cache-first`) and returns a new `FetchPolicy` based on the current one (possibly leaving it unchanged). For example, this allows you to transition from `cache-and-network` or …
=> Improvements to options.nextFetchPolicy.

CHANGELOG.md, src/core/QueryInfo.ts, src/core/__tests__/QueryManager/index.ts
Analogous to #6817, but for `cache.modify` in addition to `cache.evict`. Fixes #6896.
=> Consider cache.modify a destructive method, like cache.evict.

CHANGELOG.md, CONTRIBUTING.md, docs/gatsby-config.js, docs/source/data/fragments.md, docs/source/data/queries.mdx, docs/source/migrating/apollo-client-3-migration.md
Part of the transition promised in #6774.
=> Replace references to master branch with main.

docs/source/caching/cache-interaction.md
Fixed grammatical error adding the word "to" to 'Combining reads and writes' section of the cache docs.
=> Grammatical update to cache-interaction.md 

src/utilities/policies/pagination.ts
This is a simple fix for an issue with the relayStylePagination around this piece of code
```typescript
const incomingEdges = incoming.edges.slice(0);
if (incoming.pageInfo) {
updateCursor(incomingEdges, 0, incoming.pageInfo.startCursor);
updateCursor(incomingEdges, -1, incoming.pageInfo.endCursor);
}
```
where if the server returns pageInfo, but an empty edges list, it'll crash in the updateCursor code because it assumes edges exist.
=> Fix crash when pageInfo and empty edges are given to relayStylePagination

CHANGELOG.md, src/cache/inmemory/__tests__/__snapshots__/writeToStore.ts.snap, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/policies.ts
Although "Mutation" and "Subscription" are technically the default names for the root mutation and subscription types, there should never be any need to refer to those objects, read from them, or write to them, outside the normal process of sending and receiving mutations and subscriptions.
If you think those use cases have any value, #6911 will quickly convince you that the downsides of monopolizing types like `Subscription` and `Mutation` (e.g. assuming they are always singletons) dramatically outweigh the benefits.
In fact, it's not even possible to request the `__typename` field for the root `Subscription` object, according to the GraphQL specification: https://spec.graphql.org/June2018/#sec-Single-root-field
In particular, whereas
```graphql
query { __typename }
```
can be used to …
=> Restrict root object identification to ROOT_QUERY.

docs/source/caching/cache-interaction.md
As someone new to apollo it took me a bit to figure out the best way of accessing the instance of `client` within a component. I think `useApolloClient` would be worth mentioning here. 
The other places I see this hook mentioned are in the [local-resolvers](https://www.apollographql.com/docs/react/local-state/local-resolvers/#updating-local-state) section and the [Apollo Basics > 8. Update data with mutations](https://www.apollographql.com/docs/tutorial/mutations/#update-data-with-usemutation) sections.
=> Mention useApolloClient hook in caching docs

CHANGELOG.md, docs/source/api/cache/InMemoryCache.mdx, docs/source/caching/cache-interaction.md, package.json, src/cache/core/types/common.ts, src/cache/inmemory/__tests__/__snapshots__/cache.ts.snap, src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/cache.ts, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/types.ts
This PR brings the [`options.storage`](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#fieldpolicy-api-reference) object from `read` and `merge` functions to `cache.modify` functions, improving consistency between those APIs.
Also, `cache.modify` modifier functions can now return `details.INVALIDATE` (similar to `details.DELETE`) to invalidate the current field, causing affected queries to rerun, even if the field's value is unchanged. Previously, changing or deleting the field's value was the only way to invalidate the field.
=> Improvements for cache.modify: details.storage and details.INVALIDATE

CHANGELOG.md, src/core/ObservableQuery.ts, src/core/types.ts
Fixes #6939.
This change snuck in with 144155c5b16dd36f052d8f7f9401bde51162b8b4, which was part of the effort in #6080 to reenable TypeScript strict null checks.
The consequences of this change were likely hidden until the `ApolloCurrentQueryResult` and `ApolloQueryResult` types were unified in 513d733cf0162c86d2b7d56547c20bb03287a472, which was first released in @apollo/client@3.1.0.
As I explained in https://github.com/apollographql/apollo-client/issues/6993#issuecomment-689750542, this change should be backwards compatible, since it strictly reduces the number of possible `data` values that need to be handled.
=> Make ApolloQueryResult.data field non-optional again.

docs/shared/mutation-result.mdx
Adds additional options to the documentation according to the interface `MutationFunctionOptions`
```ts
export interface MutationFunctionOptions<
TData = any,
TVariables = OperationVariables
> {
variables?: TVariables;
optimisticResponse?: TData | ((vars: TVariables) => TData);
refetchQueries?: Array<string | PureQueryOptions> | RefetchQueriesFunction;
awaitRefetchQueries?: boolean;
update?: MutationUpdaterFn<TData>;
context?: Context;
fetchPolicy?: WatchQueryFetchPolicy;
}
```
=> docs: update MutationOptions

src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/policies.ts, src/utilities/policies/pagination.ts
Currently if you try to query relay connection metadata with no arguments
```
query todos{
totalCount
}
```
And then query for the edges/data
```
query todos{
totalCount
edges {
node {
title
}
}
}
```
The cache will never have any todo items and both ```data``` and ```error``` returned by the cache will always be undefined.
This attempts to fix this.
=> allow querying connection metadata and then subsequent data in relayStylePagination

CHANGELOG.md, src/cache/inmemory/__tests__/__snapshots__/fragmentMatcher.ts.snap, src/cache/inmemory/__tests__/fragmentMatcher.ts, src/cache/inmemory/helpers.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/readFromStore.ts, src/cache/inmemory/writeToStore.ts
Easily the biggest breaking change for fragment matching in Apollo Client 3.0 was the removal of the `FragmentMatcher` abstraction (#5073), along with its subclasses `HeuristicFragmentMatcher` and `IntrospectionFragmentmatcher` (#5684), which were replaced by the declarative [`possibleTypes`](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) configuration.
The `HeuristicFragmentMatcher` was so named because it attempted to perform fragment matching without any actual knowledge of supertype/subtype relationships in your schema (for example, abstract interfaces implemented by concrete object subtypes, or unions with multiple alternative member types), checking instead whether all the fields of a given fragment were present in the result …
=> Bring back heuristic fragment matching, with a twist.

src/react/data/QueryData.ts
Solves #6816, #6796
If `skip` option is true at the first rendering, the `initializeObservableQuery` will not be triggered. And even if the `skip` value changes to false later, calling `refetch` throws the following error:
```
Uncaught TypeError: Cannot read property 'refetch' of undefined
at QueryData._this.obsRefetch
```
=> fix: Initialize query on updateObservableQuery even if skip is true

CHANGELOG.md, src/__tests__/__snapshots__/mutationResults.ts.snap, src/__tests__/mutationResults.ts, src/core/QueryInfo.ts, src/core/QueryManager.ts, src/core/watchQueryOptions.ts
Using the default `ErrorPolicy` of "none" for queries means no data will be written to the cache when a GraphQL result has errors.
Queries can use `errorPolicy: "ignore"` and `errorPolicy: "all"` to ensure data is written to the cache in spite of GraphQL errors, but mutations and subscriptions were previously limited to the default policy, "none".
This commit makes mutations and subscriptions respect the non-default "ignore" and "all" `ErrorPolicy` values, just as queries do, hopefully addressing #6965.
Since these changes did not cause any tests to fail, clearly we need more and better tests of non-default `ErrorPolicy` usage by mutations and subscriptions.
=> Respect errorPolicy for mutation and subscription results.

docs/static/_redirects
this PR adds some redirects for old 2.0 links - I'm thinking that maybe instead of inlining everything like I did that maybe all the redirects I added should go in their own new section. Thoughts?
cc @StephenBarlow and @abernix
=> adds missing redirects for old 2.0 pages

src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/policies.ts, src/utilities/policies/pagination.ts
Right now.  If you are using relayStylePagination and you query the connection metadata(eg. totalCount) and then query edges that have an ```id``` field, the edges will always be an empty array(see test change).
I have found that this is due to the ```canRead``` in the read function of relayStylePagination.  This attempts to fix the issue by removing the canRead call.  Not sure if this is the correct approach but it seems to work in my case.
Fixes #7026.
=> Fix relayStylePagination so it works even if edges have id's

CHANGELOG.md, src/core/QueryManager.ts, src/core/__tests__/QueryManager/index.ts
If `returnPartialData` is set to `true` for a query, disable the `QueryManager` `Missing cache result fields` warning, since developers have explicitly stated they want to work with partial data.
Fixes #7040
=> Disable missing cache fields warning when using returnPartialData

package.json
This marks the `subscriptions-transport-ws` as an optional peer dependency. Given that installation of this package is mentioned only on the [Subscriptions](https://www.apollographql.com/docs/react/data/subscriptions/) page, and that page opens with:
> "In the majority of cases, your client should not use subscriptions to stay up to date with your backend."
It seems then that the majority of users then should not require this package, and having it be a warning when installing the packages is misleading. Additionally, starting with NPM 7+, peer dependencies will be installed by default if not marked as optional and so aiming to avoid having a package added to the stack that is not actually needed by majority of use cases.
=> mark subscriptions-transport-ws peerDependency as optional

CHANGELOG.md, package.json, src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/policies.ts
Motivating discussion: https://github.com/apollographql/apollo-client/issues/6949#issuecomment-685192249
JavaScript developers will be familiar with the idea of [_inheritance_](https://en.m.wikipedia.org/wiki/Inheritance_(object-oriented_programming)) from the `extends` clause of `class` declarations, or possibly from dealing with prototype chains created by `Object.create`.
Here's how type policy inheritance works for `InMemoryCache`:
```ts
const cache = new InMemoryCache({
possibleTypes: {
Reptile: ["Snake", "Turtle"],
Snake: ["Python", "Viper", "Cobra"],
Viper: ["Cottonmouth", "DeathAdder"],
},
Reptile: {
// Suppose all our reptiles are captive, and have a tag with an ID.
keyFields: ["tagId"],
fields: {
// Scientific name-related logic can be shared among Reptile …
```
=> Support inheritance of typePolicies, according to possibleTypes.

CHANGELOG.md, docs/source/caching/cache-field-behavior.md, package-lock.json, package.json, src/cache/inmemory/__tests__/policies.ts, src/cache/inmemory/entityStore.ts, src/cache/inmemory/helpers.ts, src/cache/inmemory/policies.ts, src/cache/inmemory/types.ts, src/cache/inmemory/writeToStore.ts
If you've ever dealt with the warnings introduced by #6372, you either reconfigured the object type to be normalized, or you had to go find a bunch of fields that might hold an object of the given type, then configure a `merge` function (or `merge: true`) for those fields.
While normalization is still the preferred strategy in most cases, and `merge: true` (introduced by #6714) has made the second option a little easier, it's still not as easy as it could be to say that a specific object type can be safely merged.
In practice, the intuition about merge safety often concerns only the type of the object, and doesn't really have anything to do with the parent field that holds the object. To handle this common case, this PR allows placing a single `merge` configuration in a type policy, …
=> Allow custom merge functions (including merge:true and merge:false) in type policies.

CHANGELOG.md, src/cache/inmemory/__tests__/__snapshots__/writeToStore.ts.snap, src/cache/inmemory/__tests__/writeToStore.ts, src/cache/inmemory/writeToStore.ts
While it is possible to write a custom `merge` function that handles updates for scalar field values, we should treat scalar data as opaque by default, without displaying `Cache data may be lost...` warnings (#6372) that nudge the developer to write an unnecessary `merge` function.
In this context, scalar data means any subtree of a `GraphQL` result object for which the corresponding field in the query does not have a selection set. In particular, JSON data may look like any other GraphQL object, but it should be treated as an opaque value if the query does not apply a nested selection set to the field that holds the JSON data.
Should fix #7071.
=> Avoid warning about clobbering scalar fields.

docs/source/caching/cache-interaction.md
The current docs don't include an example that the fragment query should have it's full key in it, that includes the object type.
Referencing this chat: https://spectrum.chat/apollo/apollo-client/why-doesnt-client-readfragment-work~f405dc79-57dc-412f-b0d2-7262f4bb9ab5
=> add type example in id for fragment query

CHANGELOG.md, docs/shared/query-result.mdx, package.json, src/react/components/__tests__/client/__snapshots__/Query.test.tsx.snap, src/react/data/QueryData.ts, src/react/hooks/__tests__/useLazyQuery.test.tsx, src/react/hooks/__tests__/useQuery.test.tsx, src/react/types/types.ts
Alongside their returned `data` property, `useQuery` and `useLazyQuery` now also return a `previousData` property. Before a new `data` value is set, its current value is stored in `previousData`. This allows more fine-grained control over component loading states, where developers might want to leverage previous data until new data has fully loaded.
@benjamn just a heads up that I did look into moving the `previousData` handling up the chain into the AC `core` itself. The amount of work needed to get this functionality in place would have been more substantial however (as the `lastResult` tracking we’re doing in `ObservableQuery` doesn’t quite line up with what we’re looking for here), so I’ve left it in the React layer for now (where we were already tracking `previousData`, but just not …
=> Provide a previousData property in useQuery/useLazyQuery results
