apollographql/apollo-client

CHANGELOG.md
docs/source/caching/cache-interaction.md
src/cache/core/cache.ts
src/cache/core/types/Cache.ts
src/cache/core/types/DataProxy.ts
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/inMemoryCache.ts

Closes https://github.com/apollographql/apollo-feature-requests/issues/1, by making `cache.read` no longer throw under any circumstances. This is a long-standing feature request that I partially addressed in #5930, but this commit goes all the way.
Since the current behavior (sometimes returning `T`, sometimes `null`, and sometimes throwing) has been in place for so long, we do not make this change lightly, and we should state precisely what is changing: **in every case where `cache.read` would previously throw a `MissingFieldError`, it will now return `null` instead.** We believe this change will be backwards-compatible because `null` was already a possible return value, so existing code should be prepared to handle `null`. However, this hypothesis will need to be verified empirically, …

Ensure InMemoryCache#read{,Query,Fragment} always return T | null.

---

CHANGELOG.md
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/entityStore.ts

> Note: this PR builds on #7098.
This change means the existence of root objects like `ROOT_QUERY` and `ROOT_MUTATION` in the `InMemoryCache` will no longer depend on whether other queries/mutations have previously written data into the cache.
This matters because (until just recently: #7098) `cache.read` would return `null` for a completely missing `ROOT_QUERY` object, but throw missing field errors if `ROOT_QUERY` existed but did not have the requested fields:
```ts
const cache = new InMemoryCache(); // empty
const query = gql`query { some fields }`;
// Returns null, as before:
const result = cache.readQuery({ query });
// Before PR #7098, this write would cause the ROOT_QUERY object
// to be created, changing the behavior of cache.readQuery below.
cache.writeQuery({
query: gql`query { …
```

Provide default empty StoreObject for root IDs like ROOT_QUERY.

---

CHANGELOG.md
src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap
src/cache/inmemory/__tests__/policies.ts
src/utilities/policies/pagination.ts

Idea: https://github.com/apollographql/apollo-client/issues/7088#issuecomment-700752196
This commit undoes the `TEdgeWrapper` logic I added in f41e9efc9e061b80fe5019456c049a3c56661e87 in #7023, while still preserving cursor strings taken from `incoming.pageInfo`.
Changing the shape of the internal data stored by `relayStylePagination` fields was too much of a breaking change for the `@apollo/client@3.2.1` patch release, because it had the potential to break existing `cache.modify` code operating on `relayStylePagination`-managed fields (as reported by @anark in #7088).

Undo TEdgeWrapper approach for relayStylePagination.

---

package-lock.json
package.json

See https://github.com/benjamn/wryware/pull/21 for explanation and motivation. Should help with #6771, #6803, #6688, #6378, and #7081, and possibly other regressions that began with @apollo/client@3.1.0.

Update @wry/equality to improve undefined property handling.

---

src/link/schema/__tests__/schemaLink.ts
src/link/schema/index.ts

- ~If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes~
Please see the inline comments. I also fixed some tests that I think didn't quite do what they looked like.

Fix schema link to return errors for unknown queries

---

CHANGELOG.md
src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts

As suggested by @tadhglewis in #6973.
The [`keyArgs: ["someArg", "anotherArg"]` configuration for field policies](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#specifying-key-arguments) should be able to include arguments that are _optional_, while still specifying an ordering of all possible key arguments for serialization purposes.
When an optional argument is not provided, it will simply not be included in the serialized `storeFieldName` suffix, and no exception will be thrown.
We cannot safely do the same thing for `keyFields: [...]` in type policies, since a consistent set of primary key fields (for a given `__typename`) is required to (re)identify objects over time.

Make keyArgs tolerant of optional arguments.

---

src/link/http/__tests__/HttpLink.ts
src/link/http/createHttpLink.ts
src/link/http/selectHttpOptionsAndBody.ts

Unused variables are very likely to trigger server-side validation errors, thanks to the [All Variables Used](https://spec.graphql.org/draft/#sec-All-Variables-Used) validation rule.
Since this rule renders unused variables all but useless in GraphQL requests, we (namely @hwillson and I) are increasingly convinced that `HttpLink` should strip unused variables by default, with an option to prevent the stripping in unusual scenarios where your server deviates from the GraphQL specification by not strictly enforcing validation rules.
This automatic stripping of unused variables has the benefit of allowing developers to provide "too many" variables to their queries, knowing `HttpLink` will save them from needless validation errors, automatically sending only the variables that are used, while …

Support includeUnusedVariables option for HttpLink.

---

docs/shared/query-result.mdx

Adds numbers to the query results according to https://github.com/apollographql/apollo-client/blob/main/src/core/networkStatus.ts

docs: add networkStatus numbers

---

CHANGELOG.md
src/__tests__/client.ts
src/__tests__/fetchMore.ts
src/__tests__/mutationResults.ts
src/__tests__/optimistic.ts
src/core/__tests__/fetchPolicies.ts
src/link/core/ApolloLink.ts
src/utilities/testing/mocking/__tests__/MockedProvider.test.tsx
src/utilities/testing/mocking/__tests__/__snapshots__/MockedProvider.test.tsx.snap
src/utilities/testing/mocking/mockLink.ts
src/utilities/testing/mocking/mockQueryManager.ts

Ensure `MockLink` (used by `MockedProvider`) returns all errors through the Link's `Observable`, instead of throwing some errors (like `No more mocked responses for the query ...`) leading to uncaught exceptions. All errors are now available via the `error` property of a result, and `MockLink` will no longer trigger any uncaught exceptions.
Fixes #6559 
**Please note:** Returning all errors through the Link's `Observable` was the default behavior in Apollo Client 2.x. We changed it for 3, but the change has been problematic for those looking to migrate from 2.x to 3. We've decided to change this back with the understanding that not many people want or are relying on `MockLink`'s throwing exception approach. If anyone is relying on this functionality, it can be re-created by leveraging …

MockLink tweaks to avoid uncaught exceptions

---

CHANGELOG.md
src/utilities/policies/pagination.ts

This makes the field policy returned by [`offsetLimitPagination`](https://github.com/apollographql/apollo-client/blob/ec5c2edf3631ce93200585d9dcc2a3a2086c353f/src/utilities/policies/pagination.ts#L27) tolerant of a missing `args.offset`, by defaulting it to `0`. Motivating discussion: https://github.com/apollographql/apollo-client/issues/7135#issuecomment-706415063.

Default args.offset to 0 in offsetLimitPagination.

---

src/core/QueryInfo.ts

Fixes #7138
See previous similar fixes for `cache.evict` (#6817) and `cache.modify` (#6898)

Consider cache.reset a destructive method

---

src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts

Fixes #6154, Fixes #7113, Fixes #7145

reFetchObservableQueries should not refetch skipped queries

---

CHANGELOG.md
package-lock.json
package.json
src/cache/inmemory/inMemoryCache.ts

Inspired by @kamilkisiela's [comment](https://github.com/apollographql/apollo-client/issues/7149#issuecomment-707010340), but building on the new `optimistic.forget` method that I added in https://github.com/benjamn/optimism/pull/84. 
Should fix #7149 and #7086.

Update optimism and fix potential cache.watch memory leak.

---

CHANGELOG.md
src/utilities/observables/Concast.ts

Fixes #6985
Cleanup observers were blocking `removeObserver` from executing `this.sub.unsubscribe()`. Therefore some queries were left hanging until completion. This patch puts the observers that should not block unsubscription into a separate set, `shadowObservers`.

Fix cleanup observer blocking unsubscribe (#6985)

---

src/core/QueryManager.ts

Hi guys,
this PR, through a small refactor, allows you to export the functions that implement the cache update logics following a mutation.
The main changes:
* creation of the public method `generateUpdateQueriesInfo` in QueryManager
* removal of the generateUpdateQueriesInfo constant within the mutate function
* creation & export of the `markMutationOptimistic` function
* refactor & export of the `markMutationResult` function, the main change is the addition of the queryManager parameter in order to use the generateUpdateQueriesInfo function
This is the PR of my comment to the issue [Apollo Client 3.0 Roadmap](https://github.com/apollographql/apollo-feature-requests/issues/33#issuecomment-556297370)
> Hi guys,
> I would like to propose you to export the function …

Refactor markMutationResult to be a method of QueryManager

---

docs/source/development-testing/testing.mdx

This covers some non-exhaustive documentation about how you must explicitly
configure your `cache` when using `<MockedProvider>` if that cache is
using complex configurations such as `possibleTypes` and `typePolicies`.

Add testing docs for fragment, typePolicies, possibleTypes

---

docs/source/integrations/react-native.md

- `graphql` is a required peer dep
- the previous example links were broken, and I can no longer find them under the `apollographql` org

Update react-native.md install and examples

---

src/__tests__/local-state/export.ts
src/__tests__/local-state/general.ts
src/cache/inmemory/policies.ts
src/core/LocalState.ts
src/link/batch/__tests__/batchLink.ts
src/link/core/__tests__/ApolloLink.ts
src/link/core/types.ts
src/link/http/selectHttpOptionsAndBody.ts
src/link/persisted-queries/index.ts
src/link/schema/index.ts
src/utilities/graphql/__tests__/fragments.ts
src/utilities/graphql/__tests__/getFromAST.ts
src/utilities/graphql/__tests__/transform.ts
src/utilities/graphql/directives.ts
src/utilities/graphql/transform.ts
src/utilities/testing/mocking/mockLink.ts

Fixes #7184 (and https://github.com/ardatan/graphql-tools/issues/1790)

Avoid all sub-package imports from graphql npm package.

---

docs/source/caching/advanced-topics.mdx
docs/source/why-apollo.mdx

The `apollo-cache-persist` package has been updated to work with Apollo Client 3, but it has a new package name (not unlike our renaming from `apollo-client` to `@apollo/client`).
I've seen multiple folks installing the older `apollo-cache-persist` with `@apollo/client` and noticing problems, so I want to make sure the docs recommend the new package instead.

Update references to apollo-cache-persist to apollo3-cache-persist.

---

docs/source/caching/advanced-topics.mdx

When copy pasting this code I noticed it isn't valid js and not in line with the types in the code. This will fix it for future copy pasters

Fix typo in writeQuery documentation

---

src/core/ObservableQuery.ts
src/react/data/QueryData.ts
src/react/hooks/__tests__/useQuery.test.tsx

Issue #7206
Cleanup logic is done on `unsubscribe` but when `skip: true` the component never starts a subscription.
I got the bottle over 3 years ago when Apollo was in very early stage, thank you once again :)

ObservableQuery and QueryInfo stays forever on skip:true

---

docs/shared/query-result.mdx

Fixed broken link `advanced/subscriptions` to `data/subscriptions`.

Fixed broken link to subscriptions

---

codemods/ac2-to-ac3/imports.js

This simply adds `react-apollo` to the import.js for transformations. I'm not sure why it wasn't included, I added it to mine and transformed over 100+ js files and it worked fine

Add older 'react-apollo' to transform imports

---

docs/source/local-state/reactive-variables.mdx

Do we want to recommend/model this convention? It's used in the examples on this page: https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies/
Alternatives are no recommendation on naming, or a different rec, like `reactiveCartItem`.

Use "Var" suffix for reactive variable names

---

CHANGELOG.md
src/__tests__/ApolloClient.ts
src/core/index.ts
src/core/watchQueryOptions.ts

Merge QueryBaseOptions, QueryOptions, and ModifiableQueryOptions into one type.

---

src/utilities/policies/__tests__/relayStylePagination.test.ts
src/utilities/policies/pagination.ts

When using `relayStylePagination` it's possible that the edges are not requested. In my specific case the api I'm integrating with incorrectly returns an empty list of `edges` in some cases.
The `pageInfo` however **does** contain correct `endCursor` and `startCursor` values. 
The problem with the way that `relayStylePagination` is implemented is that the `startCursor` and `endCursor` will be overridden with an empty string `""` instead of honoring the `pageInfo` sent by the API.
This change includes a test showing the problem (932bcfb) which fails with the state I am seeing:
```
expect(received).toEqual(expected) // deep equality
- Expected  - 2
+ Received  + 2
Object {
"edges": Array [],
"pageInfo": Object {
-     "endCursor": "xyz",
+     "endCursor": "",
"hasNextPage": true, …
```

relayStylePagination honor pageInfo startCursor and endCursor

---

src/react/data/QueryData.ts

This is to fix the unexpected crashes when `obsRefetch` is invoked while `currentObservable` is not available, especially when being used with hot-reloading features, e.g. [Fast Refresh](https://reactnative.dev/docs/fast-refresh).

optionally-chained currentObservable to avoid unexpected crash

---

docs/source/data/queries.mdx

This PR simplifies [the useLazyQuery example of the Queries section](https://www.apollographql.com/docs/react/data/queries/#executing-queries-manually) as the same as [the useLazyQuey example of the Hook section](https://www.apollographql.com/docs/react/api/react/hooks/#example-3).
Some people may think they should do the same when they use useLazyQuery as the example of Queries section but I don't see any benefit in it, so I think the extra state for a dog should be removed.

Simplify the useLazyQuery example of the Queries section

---

src/react/data/QueryData.ts

Follow-up to #7205, per my comment https://github.com/apollographql/apollo-client/issues/7254#issuecomment-718977276.
Instead of tearing down `queryData.currentObservable` only when `queryData.getOptions().skip` is true in `removeQuerySubscription` (which was the idea of #7205), I split the tear-down functionality into a separate private method (`removeObservable`), which works regardless of the `skip` status, and is called everywhere `removeQuerySubscription` is called, except in `resubscribeToQuery`, where we specifically want to preserve `this.observableQuery`.

Call this.currentObservable.tearDownQuery more consistently.

---

package.json
src/__tests__/client.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/reactiveVars.ts

Each reactive variable must remember any caches previously involved in reading its value, so those caches can be notified if/when the variable value is next modified.
To prevent reactive variables from retaining references to caches that no longer need to be notified, we can preemptively remove the cache from the memory of all of its associated reactive variables whenever all of its watches have been cancelled, since not having any active `cache.watches` means `cache.broadcastWatches` has nothing to do.
This change should prevent memory leaks when lots of caches are created and discarded by the same process, as in the server-side rendering use case described by @manojVivek in #7274.

Prevent reactive variables from retaining unwatched caches.

---

docs/shared/mutation-options.mdx

useMutation allows for the use of `errorPolicy` it is however undocumented.

Update useMutation docs

---

CHANGELOG.md
src/cache/inmemory/__tests__/__snapshots__/entityStore.ts.snap
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/writeToStore.ts

Partial solution for #7323, as we still need to decide the best way to persist retainment counts for non-`ROOT_*` entity objects written directly with `cache.writeFragment`.

Always consider ROOT_{QUERY,MUTATION,...} IDs to be GC roots.

---

CHANGELOG.md
package-lock.json
package.json

This reverts commit 2809d6d14fa142247fb8b7ccd21137902d59cdac, hopefully fixing issue #7337. The problem is not the `@types/node` version, as conjectured in #7335, but the incompatibility between the version of `@types/node` used by Angular and the major update of `symbol-observable`, which is a non-dev dependency of `@apollo/client`:
```
ERROR in node_modules/@apollo/client/node_modules/symbol-observable/index.d.ts:6:14 - error TS2717: Subsequent property declarations must have the same type.  Property 'observable' must be of type 'symbol', but here has type 'unique symbol'.
6     readonly observable: unique symbol;
~~~~~~~~~~
node_modules/@types/node/globals.d.ts:146:14
146     readonly observable: symbol;
~~~~~~~~~~
'observable' was also declared here.
```

Revert "chore(deps): update dependency symbol-observable to v3 (#7299)"

---

src/core/QueryInfo.ts
src/core/QueryManager.ts

An unexpected behaviour in my React app revealed some kind of leak in the `QueryInfo` object. One of my component consuming `useQuery` was mounted, then almost immediately unmounted. Mounting back this component led to an infinite query loop. Following the red thread, I've found out that the `QueryManager.removeQuery` was called when the component was unmounted BEFORE receiving the result. What happened in that case was that `QueryInfo.markResult` was called even when `QueryInfo` object was detached, thus keeping the `QueryInfo` object still configured to react to cache updates. In my case, as I'm using a `network-only` fetch policy, mounting back the component led to executing another instance of the same query, updating the cache, then triggering re observability of the previous …

Fix query info cache leak

---

docs/source/networking/advanced-http-networking.md

I added two examples for response manipulation, one that is synchronous and the other requires async/await. This is crucial since I could not find any documentation on how to manipulate the response in an asynchronous manner, which led me to edit the docs.
See https://github.com/apollographql/apollo-client/issues/7328

Docs: Modifying the response data examples (async/await)

---

CHANGELOG.md
src/react/data/QueryData.ts
src/react/ssr/__tests__/useQuery.test.tsx

Fixing https://github.com/apollographql/apollo-client/issues/6342
When `skip` is set to true on SSR, `useQuery` skips a network request. But firing `renderToString`.
only small bugfix

Avoid adding QueryPromise when skip is true on SSR

---

CHANGELOG.md
src/core/QueryInfo.ts
src/react/hooks/__tests__/useQuery.test.tsx

As the reproduction in #7346 demonstrates, it was possible for the `QueryInfo#notify` timeout set in `QueryInfo#setDiff` on behalf of an earlier `loading: true` result to fire _after_ the final `loading: false` result had been recorded in `QueryInfo#markResult`, which could lead to unnecessary network requests when using a `FetchPolicy` of `cache-and-network` or `network-only`, especially when there are multiple `useQuery` calls in the same React component.
This PR fixes that problem by canceling the timeout in `QueryInfo#markResult` and `markError`, since those methods are called by code that delivers the results through other mechanisms.

Cancel queryInfo.notifyTimeout when marking final results.

---

CHANGELOG.md
package.json
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/reactiveVars.ts

In the context of a larger cache read operation, accessing a reactive variable automatically associates the variable with the cache, so future updates to the variable can be broadcast to the cache.
Outside this context, it may not be possible for the variable to discover the currently active cache. For example, there is no currently active cache in asynchronous `ApolloLink` code (#7338).
Since we recently added a `reactiveVar.forgetCache(cache)` method in #7279, I think it makes sense to have a manual way to do the opposite, which I have decided to call `reactiveVar.attachCache(cache)`.
Although this attachment is manual at the moment, in a hypothetical future where the client/cache manage the persistence of reactive variables, it should be easy to attach the appropriate cache to those …

Allow manually associating caches with reactive variables.

---

src/core/ObservableQuery.ts

Hi @benjamn 
This PR should ensure that even if `ObservableInfo` remains in memory, it won't hold a reference to user-object `context` after tear-down. 
The background is a memory-leak we are chasing in a large-scale app. I think the existence of the `context` reference in Apollo just makes it harder to detect, since it retaining it with no reason. 
I think even in a use-case of `subscribe` over a `watchQuery` observable, without `unsubscribing` reproduces that, since Apollo isn't removing the `ObservableQuery` while there are subscribers.

Make sure to clean `context` during tearDownQuery

---

CHANGELOG.md
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/policies.ts

Implementing the idea I described in https://github.com/apollographql/apollo-client/issues/7324#issuecomment-730017281.

Restrict field name over-invalidation to fields without keyArgs.

---

CHANGELOG.md
src/link/core/ApolloLink.ts

This new parameter could be considered a breaking change (in Apollo Client v3.3) for existing code that called `ApolloLink#onError` directly with only one argument (the error). Fortunately, the implementation of `onError` already tolerates the possibility that `observer` may not be provided, so we can fix this with a TypeScript-only tweak.

Make ApolloLink#onError observer parameter optional.

---

src/utilities/observables/Concast.ts

This is an initial attempt to address the problems I speculated about in https://github.com/apollographql/apollo-client/issues/6520#issuecomment-736899757.
Theory: in the Hermes JS engine (used by React Native on Android), [`Symbol.species` is not defined](https://github.com/facebook/hermes/blob/master/doc/Features.md#excluded-from-support), so `Object.defineProperty` was not called by this code, but perhaps `Concast["@@species"]` was getting set somewhere else by a polyfill library, causing the `zen-observable` library to fall back to `"@@species"` in [`getSpecies`](https://github.com/zenparsing/zen-observable/blob/328fb66a99242900c0fd4a330e9ff66ecfa3a887/src/Observable.js#L29-L38) instead of safely ignoring the nonexistent `Concast[Symbol.species]` property.
If that theory is correct, …

Set Concast["@@species"] = Observable as well as Symbol.species.

---

CHANGELOG.md
package-lock.json
package.json

Includes this `ts-invariant` PR: https://github.com/apollographql/invariant-packages/pull/53
This update may also help with issues like #7406, where a _patch_ version update (from 0.5.0 to 0.5.1) is apparently not enough to force a dependency like `ts-invariant` with multiple conflicting version constraints (from `@apollo/client` and `graphql-tools`) to be updated, since version 0.5.0 is still semantically compatible with the desired minimum version 0.5.1, so `ts-invariant` remains outdated after updating `@apollo/client`, despite the new version being clearly mandated in `@apollo/client/package.json`.
After updating the _minor_ version of `ts-invariant` in package.json (to ^0.6.0), there should be no risk of `@apollo/client` incorrectly resolving the older `ts-invariant@0.5.0` version, …

Update ts-invariant to avoid CSP-violating Function fallback.

---

src/core/ApolloClient.ts
src/core/index.ts

Fixes #7447 and #7453, since React Native polyfills the console object without providing a `console.debug` method.
Since this message is promotional, I did not feel comfortable using `invariant.warn`, but our default log level of "warn" would have hidden the message unless [`setLogVerbosity("log")`](https://github.com/apollographql/apollo-client/pull/7226) was called.
Since this is the only use of `invariant.log` in the codebase, I believe it's acceptable to lower the default verbosity level to "log" to allow this particular message to be displayed (otherwise, `invariant.log` messages are effectively useless). You can use `setLogVerbosity("warn")` to exclude these `invariant.log` messages if you like.

Replace stray console.debug with invariant.log.

---

docs/source/api/core/ApolloClient.mdx
src/__tests__/client.ts
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts

Relevant issue:
https://github.com/apollographql/apollo-client/issues/7410
This is a WIP, I still need to write tests. But I wanted to start the convo about how this would look.

Feature: add ability to refetch certain queries imperatively

---

src/core/ApolloClient.ts

As suggested by @jcreighton: https://github.com/apollographql/apollo-client/pull/7454#discussion_r540628949
I've tested this manually in both Firefox and Chrome, with/without the extension installed.

Suggest Firefox Apollo DevTools as well as Chrome.

---

config/jest.config.js

Every time I build [`docs/`](https://github.com/apollographql/apollo-client/tree/main/docs) locally, my Jest tests go all haywire because Jest tries to find/run tests in `docs/.cache/`. I'm tired of debugging that problem over and over every few weeks, so I think we should explicitly restrict Jest to the only directory that's supposed to have any tests in it, `src/`.

Simplify config/jest.config.js to consider only src/ directory.

---

src/core/ApolloClient.ts

This PR is a fix for the errors that occur during SSR.

fix 'window is not defined'

---

CHANGELOG.md
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts

Thanks to @zaguiini for tracking this regression (#7443) back to my type/field policy inheritance PR #7065 (and my commit c696b9ab62152fbeb2ea684031c148b1ce7a09d4 in particular).

Fix queryType:true, mutationType:true, and subscriptionType:true type policies.

---

CHANGELOG.md
src/react/data/OperationData.ts
src/react/data/QueryData.ts
src/react/ssr/__tests__/useQuery.test.tsx

PR #7310 introduced a regression that causes skipped SSR queries to always set `loading` to `true`, which doesn't match the behavior of `useQuery()` on the client and can result in hydration mismatches.
The problem is that `skip: true` was being treated as equivalent to `ssr: false`, but they're not actually equivalent. I think the correct solution is to let `this.getQueryResult()` provide a suitable result when `skip` is truthy, which ensures that skipped SSR queries will get the same result as skipped non-SSR queries.
An alternative approach would be to simply back out the changes from PR #7310, but then we'd lose the benefit of avoiding the unnecessary `QueryPromise` when `skip` is truthy.
Fixes #7380 (note that this issue's title and description are inaccurate, but its comments …

Fix `skip` causing `loading` to always be `true` during SSR

---

CHANGELOG.md
src/react/hooks/__tests__/useReactiveVar.test.tsx
src/react/hooks/useReactiveVar.ts

Fixes #7509. Because StrictMode renders functional components twice, duplicate listeners were added to `onNextChange`. The trickier part of this is that it doesn't cause inconsistent results until the priority of the update is affected (in the reproduction, returning an unresolved Promise from the button's `onClick` handler resulted in a different priority level in React so the associated duplicate listeners were interleaved with other work resulting in a strange result). We now set `onNextChange` **only** on the initial mount and when the reactive var's value has changed.

Avoid duplicate listeners when using useReactiveVar with React.StrictMode

---

package-lock.json
package.json
src/utilities/observables/Observable.ts

Apollo Client currently uses the `Observable` implementation provided by the [`zen-observable`](https://www.npmjs.com/package/zen-observable) npm package, since it is small and works well for our needs. Although `zen-observable` itself is not written in TypeScript, we use the companion package [`@types/zen-observable`](https://www.npmjs.com/package/@types/zen-observable) to provide types.
We are actively considering switching from `zen-observable` to RxJS (#5749), though it remains to be seen how much of a breaking change that will be (and thus whether it makes sense for a minor or major version update).
In the meantime, several issues (most recently #5961) have been opened pointing out that `zen-observable` effectively does not support importing its code as ECMAScript modules, even …

Revive zen-observable-ts wrapper for zen-observable package.

---

CHANGELOG.md
config/rollup.config.js

As I explained in https://github.com/apollographql/apollo-client/issues/7523#issuecomment-754131520 and https://github.com/apollographql/apollo-client/pull/6660#pullrequestreview-561244137, we are unfortunately stuck with the convention of using `process.env.NODE_ENV` to restrict development-only code from running in production, because JS minifiers (in the React ecosystem, at least) look for that exact expression and replace it with a string literal like `"development"` or `"production"`, which allows the unused code to be stripped from production bundles, for significant savings in bundle size, and better performance in production (due to running less code).
That system works well for client-side code, which tends to be minified in a way that strips out the `process.env.NODE_ENV` …

Cheapen process.env.NODE_ENV lookups in CommonJS bundles.

---

package-lock.json
package.json
src/utilities/observables/Observable.ts
src/utilities/observables/__tests__/Observable.ts

Now that the `zen-observable-ts` package has the ability to export `Observable` as a native ECMAScript `class` (#7615), we need to be careful when extending `Observable` using classes (like `ObservableQuery` and `Concast`) that have been compiled to ES5 constructor functions (rather than native classes), because the generated `_super.call(this, subscriber)` code throws when `_super` is a native class constructor (#7635).
Rather than attempting to change the way the TypeScript compiler transforms `super(subscriber)` calls, this commit wraps `Observable.call` and `Observable.apply` to work as expected, using `Reflect.construct` to invoke the superclass constructor correctly, when the [`Reflect`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construc …

Support subclassing Observable with non-class constructor functions.

---

CHANGELOG.md
src/react/hooks/__tests__/useReactiveVar.test.tsx
src/react/hooks/useReactiveVar.ts

Fixes #7609. Because #7581 amended `useReactiveVar` to set the `onNextChange` handler in a useEffect, an end user could see inconsistent data if updating a reactive var in a useEffect higher in the component tree. That change wouldn't be caught lower in the tree as `onNextChange` wouldn't be set yet. (useEffect is called during the commit phase and also in order from top to bottom.) This PR adds an additional check for a change in the value, scheduling an update if the value has changed.

Recheck reactive variable's value in commit phase

---

CHANGELOG.md
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/reactiveVars.ts

Fixes a bug introduced by #7279, which was triggered by calling `this.cancel()` before re-`watch`ing in the [`QueryInfo#updateWatch`](https://github.com/apollographql/apollo-client/blob/541d333c524c0d1384e1d51c81d1c5cf668ac2e8/src/core/QueryInfo.ts#L257-L258) method, causing `cache.watches.size` to drop to zero temporarily, thereby invoking `forgetCache(cache)`. When this happened, reactive variables would stop broadcasting updates to the forgotten cache, even though the unwatching was only momentary, and would not begin broadcasting again until the association was reestablished by other means.
This new implementation uses a `WeakMap` to remember associations between caches and sets of reactive variables, which makes it possible to recall those associations later, provided the cache has …

Reactivate reactive variables when InMemoryCache acquires first watcher.

---

CHANGELOG.md
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/core/ObservableQuery.ts
src/core/__tests__/ObservableQuery.ts
src/utilities/index.ts
src/utilities/observables/Concast.ts
src/utilities/observables/Observable.ts
src/utilities/observables/__tests__/subclassing.ts
src/utilities/observables/subclassing.ts

I landed #7403 on the `release-3.4` branch instead of `main` because I wasn't sure at the time if it would help fix the problem I described in https://github.com/apollographql/apollo-client/issues/6520#issuecomment-736899757. Since then, multiple folks have commented that it did help, so I think it makes sense to backport this change to `main` (3.3.x).
While I was at it, I applied the same logic to `ObservableQuery` (the other `Observable` subclass that Apollo Client uses), and added some regression tests of the `Symbol.species` logic for both `Concast` and `ObservableQuery`.

Backport v3.4 Symbol.species fix for Concast and ObservableQuery.

---

src/__tests__/__snapshots__/exports.ts.snap
src/cache/index.ts

https://github.com/apollographql/apollo-client/issues/7639
Libraries that build on top of Apollo Client's cache may want access to advanced utilities and methods within the Apollo Client codebase, but cannot do so today without failing to run in a node environment due to the lack of transpilation to cjs.
Adds a few more entities to the export list of the `@apollo/client/cache` to ensure that these entities are accessible from a cjs context.

fix: export more from /cache

---

docs/source/development-testing/testing.mdx

Fixes a typo I found in the testing document. 
https://en.wikipedia.org/wiki/Shiba_Inu
Thank you Apollo team for the great work! 
~~- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)~~
~~- [ ] Make sure all of the significant new logic is covered by tests~~

doc: Fix Typo in Testing React components document(Shibe is Shiba)

---

docs/source/data/error-handling.mdx

The intention in the modified example is to iterate over an array and call `console.log` once per array element. Using `.map` makes no sense in this case as there is no intention to create a new array.

Change example to use forEach instead of map

---

docs/package-lock.json
docs/package.json

Closes #7473, if nothing breaks.
This dependency was added in bf9d073fec8512225aec6e03427348260783c325 as part of #6429. Back then, `gatsby` and `gatsby-cli` depended on the `ink` package, but I can't find any current usage of the `ink` package outside of the `devDependencies` of those Gatsby packages, so I believe it should be safe to remove it, now.

Attempt to remove ink dependency from docs/package.json.

---

CHANGELOG.md
src/core/QueryManager.ts

Allows for the consumer of the subscription to specify whether there should be de-duplication or not. This keeps the backwards compatible behavior of `false`, so it shouldn't introduce any kind of breaking behavior.

Allows for subscriptions to be de-duped

---

CHANGELOG.md
src/link/persisted-queries/__tests__/index.ts
src/link/persisted-queries/index.ts

The second request after error with full graphql queries should be a POST request. Because there may be more than the limit for a GET request
If using automatic persisted queries, when first request did not find cache (return "PersistedQueryNotFound"). Then second request goes through GET method and if request is big, it falls on limit. The second request must use the POST method

Ensure POST request when sending full query with persisted queries link.

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/core/watchQueryOptions.ts
src/react/data/QueryData.ts
src/react/hoc/__tests__/queries/api.test.tsx
src/react/hoc/types.ts
src/react/types/types.ts

Updating typing to match current behaviour of [merging fetchMore variables with initial variables](https://github.com/apollographql/apollo-client/blob/main/src/core/ObservableQuery.ts#L264-L267).
It's actually [used in test](https://github.com/apollographql/apollo-client/blob/main/src/__tests__/fetchMore.ts#L272-L273)
I don't know if Pick had a different behaviour in past TS version, but [from the documentation](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype), Partial is the util to use in that case
NIT: my IDE also warned me about an outdated JS doc for setVariables

Use Partial<TVariables> typing for fetchMore variables, rather than Pick<TVariables, K>

---

docs/source/data/subscriptions.mdx

I Was facing the error on client after following the subscription setup guide on your docs : 
`ws://localhost:4000/' failed: Error during WebSocket handshake: Unexpected response code: 400`
Seems that more people were facing the same issue : 
https://github.com/apollographql/apollo-client/issues/4778
Adding `graphql` to subscription uri solved it for many, myself included and therefore the PR to add this to docs :)

Add /graphql query path to all URIs in subscriptions docs.

---

CHANGELOG.md
scripts/memory/tests.js
src/core/ObservableQuery.ts

The deletion of `observableQuery.options.context` introduced by #7276 was a blunt solution to a hypothetical problem, so I agree with @francisu that it should be reverted if/when it causes anyone any problems: https://github.com/apollographql/apollo-client/pull/7276#issuecomment-776144217
Thanks to #7661, we now have a system for programmatically testing garbage collection of discarded objects, so we can actually enforce the expectation that the whole `ObservableQuery` is garbage collected after the last subscriber is removed (which tears down the `ObservableQuery` and removes it from the `QueryManager`).

Revert #7276, but test garbage collection of ObservableQuery.

---

CHANGELOG.md
src/react/hooks/utils/useBaseQuery.ts

PR #7655 changed this code so that the `Promise.resolve().then(forceUpdate)` branch was not taken when `queryDataRef.current` was falsy, so `forceUpdate()` was called immediately instead (the `else` branch).
As #7713 demonstrates, the `Promise` delay is important to avoid calling `forceUpdate()` synchronously during the initial render, which can lead to an infinite rendering loop.
To preserve the intent of #7655, we now do the `queryDataRef.current` check inside the `Promise` callback, since the component could have been unmounted before the callback fired.
Remaining work:

Fix useLazyQuery forceUpdate loop regression.

---

CHANGELOG.md
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/policies.ts
src/cache/inmemory/types.ts

Previously, you could allow `InMemoryCache` to merge non-normalized data using the `merge: true` configuration (see #6714 and #7070), but the merged objects had to be consistently non-normalized, since attempting to merge a normalized `Reference` with a non-normalized object would give preference to the reference, ignoring the object.
This PR fixes #7642 in both directions:
* merging an incoming non-normalized object with an existing `Reference` now updates the normalized data behind the reference, leaving the field holding the `Reference`, and
* merging an incoming `Reference` with an existing non-normalized object updates the normalized data behind the reference (as above), but, for any fields that overlap, the normalized field data takes precedence over the non-normalized field data. …

Allow merge:true to merge references with non-normalized objects, and vice-versa.

---

CHANGELOG.md
src/link/persisted-queries/__tests__/react.tsx
src/react/components/Mutation.tsx
src/react/components/Query.tsx
src/react/components/Subscription.tsx
src/react/context/ApolloConsumer.tsx
src/react/context/ApolloContext.ts
src/react/context/ApolloProvider.tsx
src/react/hoc/hoc-utils.tsx
src/react/hoc/mutation-hoc.tsx
src/react/hoc/query-hoc.tsx
src/react/hoc/subscription-hoc.tsx
src/react/hoc/withApollo.tsx
src/react/hooks/useApolloClient.ts
src/react/ssr/getDataFromTree.ts
src/utilities/testing/mocking/MockedProvider.tsx

Fixes #7741
Using `import React from 'react'` causes issues when the import makes
its way into the d.ts file. Users without `esModuleInterop: true` or
`allowSyntheticDefaultImports: true` (or `skipLibCheck: true`) in
their tsconfig files will get errors from typescript about not being
able to default-import using that syntax.
This PR fixes the specific imports that would cause issues due to
their types being re-exported in `@apollo/client`'s types.

Prefer `import * as` for imports whose types are re-exported

---

docs/source/data/error-handling.mdx

I was a bit confused by the text here because it sounded like it was saying that GraphQL errors are treated literally the same as network errors (ie, they would actually show up on `error.networkError` somehow). The description above the table was more explicit, but it didn't actually say what the default policy was, so I wasn't sure that the clearer description actually described `none`.

docs: make error policy 'none' description clearer

---

CHANGELOG.md
src/utilities/observables/__tests__/asyncMap.ts
src/utilities/observables/asyncMap.ts

Might help with #7806, based on the presence of `asyncMap` in the stack trace.
@SubZane If you have a chance to try hacking this change into your app's version of `asyncMap`, I'd be curious to know if it helps catch/handle the error (rather than letting it become an unhandled rejection).

Improvements to asyncMap Observable utility function.

---

CHANGELOG.md
package.json
src/cache/core/cache.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/inMemoryCache.ts
src/core/QueryManager.ts

As new methods have been added to `ApolloCache` and `InMemoryCache`, we have found it convenient in many cases (e.g. `cache.evict` and `cache.modify`) to use a method signature that accepts named options, rather than positional parameters. Named options are easier to extend in the future, and less cumbersome when some of the options might be omitted.
This awkwardness of positional parameters affects the two existing transaction-related methods of `InMemoryCache`:
```ts
cache.performTransaction(cache => {...}, id?);
cache.recordOptimisticTransaction(cache => {...}, id);
```
Instead of adding new functionality to these methods by introducing new positional parameters, I would very much prefer to switch to named options, but I was previously concerned that introducing a new transaction …

Introduce new cache.batch(options) method for InMemoryCache.

---

CHANGELOG.md
src/core/QueryManager.ts
src/core/__tests__/fetchPolicies.ts

Fixes #7611 & #6998. While we want to force delivery for an incomplete cache result with `loading: true`, we should preserve the `no-cache` fetchPolicy. ~~An additional check has been added to avoid resetting the fetch policy to "cache-and-network" when it's set to "no-cache".~~ Thanks to @benjamn's feedback below, the "`notifyOnNetworkStatusChange` changes the fetch policy" trickery has been removed. The logic behind that is still valid but it's now centralized in `fetchQueryByPolicy`'s `switch` statement. This means fetch policies are now preserved even with `notifyOnNetworkStatusChange` set.

Preserve no-cache fetchPolicy with notifyOnNetworkStatusChange

---

CHANGELOG.md
src/utilities/testing/mocking/MockedProvider.tsx

Remove  `children` type override and add `React.isValidElement` to properly cast `React.ReactNode` to `React.ReactElement`
Fixes: https://github.com/apollographql/apollo-client/issues/7825

Remove  `children` type override

---

package-lock.json
package.json

To bring in the changes outlined in https://github.com/apollographql/invariant-packages/pull/91 (I don't think we need to mention this in the `CHANGELOG` but let me know otherwise).
Closes #7845.

Bump to the latest version of ts-invariant

---

CHANGELOG.md
docs/shared/subscription-options.mdx
src/react/data/SubscriptionData.ts
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/types/types.ts

Fixes #7824. This PR adds context to useSubscription's options.

Add missing `context` option to `useSubscription`

---

src/__tests__/client.ts
src/cache/core/types/Cache.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/inMemoryCache.ts

I'll be the first person to admit I don't love the complexity added by the `CacheGroup` concept I introduced in #5648, but it remains useful for separating result caching (#3394) dependencies into two distinct groups: optimistic and non-optimistic.
This separation is important because it allows cache readers who only care about non-optimistic data to continue to benefit from `InMemoryCache` result caching even while optimistic cache updates are taking place, because the optimistic dependencies that get invalidated by optimistic cache writes are tracked in a separate `CacheGroup` from the group used to track the non-optimistic dependencies registered by non-optimistic reads.
In the process of writing tests for #7827, I realized this `CacheGroup` story had a missing piece (or two):
During …

Simplify EntityStore CacheGroup logic to improve InMemoryCache result caching.

---

src/__tests__/fetchMore.ts
src/core/__tests__/QueryManager/index.ts
src/react/hooks/__tests__/useQuery.test.tsx

👋 Just getting my feet wet by squashing a couple warnings which were emitted when running tests. I started to look into squashing the React warnings as well, but it looks like that is a little bit more involved and there seems to be multiple efforts to do this already (https://github.com/apollographql/apollo-client/pull/7745). Happy to be joining Apollo! No pressure to merge.

squash some console warnings in tests

---

src/utilities/observables/Observable.ts

Should fix #7839.
I find it surprising that setting `Observable.prototype['@@observable']` is necessary in addition to setting `Observable.prototype[Symbol.observable]` (which `zen-observable` already [does](https://github.com/zenparsing/zen-observable/blob/328fb66a99242900c0fd4a330e9ff66ecfa3a887/src/Observable.js#L3-L12)), but if you comment out
```ts
prototype[fakeObsSymbol] = function () { return this; };
```
and run our test suite, you will see failures:
```
FAIL  core/__tests__/QueryManager/index.ts (20.796 s)
● QueryManager › supports interoperability with other Observable implementations like RxJS
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
577 |     });
578 | 
> 579 |     const observable = …
```

Remove global Observable<T>["@@observable"] method declaration.

---

CHANGELOG.md
src/core/QueryManager.ts

Similar to the effort in https://github.com/apollographql/apollo-client/pull/7146, but this also applies that logic when refetching queries following a mutation.

Prevent skipped/observerless `ObservableQuery`s from being refetched by `refetchQueries`

---

package.json

Currently, the homepage link takes devs to `apollographql.com`. This PR changes the homepage link to the docs.

Update homepage link to react docs

---

CHANGELOG.md
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts
src/cache/inmemory/writeToStore.ts

Previously the function was not allowed to return false even though false is supported

Allow keyFields and keyArgs functions to return false

---

CHANGELOG.md
package.json
src/cache/core/types/Cache.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts
src/core/types.ts
src/core/watchQueryOptions.ts
src/react/hooks/__tests__/useMutation.test.tsx
src/react/types/types.ts

Building on #7819, this PR implements the `reobserveQuery` option I described in https://github.com/apollographql/apollo-client/issues/7060#issuecomment-698026089, which allows mutations to override the refetching logic for any watched queries invalidated by the mutation `update` function.
The word "invalidated" is important here, since it means `reobserveQuery` will fire for any queries affected by cache writes, even if the result of the query does not end up changing. This is why it was previously difficult to make use of the `INVALIDATE` sentinel object added in #6991, as reported in #7060. Using `cache.modify` and `INVALIDATE` in the mutation `update` function should work smoothly with `reobserveQuery`, hopefully resolving #7060.
Similar functionality is achievable using just …

Support options.reobserveQuery callback for mutations.

---

src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts

When an `options.onDirty` callback is provided to `cache.batch` (#7819), we want to call `onDirty` with only the `Cache.WatchOptions` objects that were directly affected by `options.transaction`, so it's important to broadcast watches _before_ the transaction, to flush out any pending watches waiting to be broadcast.
See provided tests for an example where this matters.

Broadcast watches before transaction when onDirty provided.

---

package.json
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts

PR #7904 was an important change to make sure the `cache.batch` `onDirty` function gets called for all/only those watchers actually affected by the `batch` operation, and not for any other cache watchers that happen to be waiting to receive a broadcast.
However, in my initial implementation of this functionality, unrelated watchers would receive pending broadcasts immediately before the `cache.batch` transaction, which might be surprising because those unrelated broadcasts appear to be triggered by calling `cache.batch`, but are not included in the `onDirty` set.
Instead, I think we can make #7904 "silent" in the sense that the unrelated cache watchers are properly excluded from the `onDirty` set (since we call `broadcastWatches` before the transaction, as before), but they do not …

Handle already-dirty watches more gracefully in cache.batch.

---

CHANGELOG.md
src/core/QueryInfo.ts

The original `stop` method does not clear the pending `notifyTimeout`. When a query is stopped in the same tick and right after a cache update sets the `notifyTimeout`, the query is not removed correctly, as the `notifyTimeout` callback will recreate the `QueryInfo`. This might lead to undesired behavior, as queries are executed that should have been stopped already.
I could not find a suitable test to extend / was unsure how to add a new test for this.
Might be related to https://github.com/apollographql/apollo-client/issues/6888

Cancel the pending notify timeout when stopping a query

---

docs/source/api/react/hooks.mdx

Not 100% sure this is considered a typo, but the fact that there was no opening parenthesis bugged me for a couple of seconds.
Thank you Apollo team for the amazing work!

Fix typo in `useLazyQuery` API - React section

---

CHANGELOG.md
src/react/data/SubscriptionData.ts
src/react/hooks/__tests__/useSubscription.test.tsx
src/utilities/testing/mocking/mockSubscriptionLink.ts

Fixes to some infinite rendering loop bugs

---

docs/source/get-started.mdx

I've noticed, that `<ApolloProvider` has _client_ prop, but it is not defined anywhere. So, hope I did it right.

docs: Fix 'get started' docs

---

CHANGELOG.md
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/QueryManager/index.ts

`fetchQueryByPolicy` currently always increments `queryInfo.lastRequestId`, even when a new request is not necessary and results are instead read directly from cache.
An example way to trigger this bug:
```
git clone https://github.com/dannycochran/usequery/tree/refetchPolicy
cd usequery
npm install
npm run start
```
Then, try deleting an item. You’ll notice in the network tab the mutation fires successfully and so does the refetch query with the correct results of one less bid item. However, the Apollo cache doesn’t update so 4 items will remain. Subsequent deletes / adds work just fine.
The cache is not updating because we are updating `fetchPolicy` manually from our useQuery invocation, which triggers `fetchQueryByPolicy`, but the result ends up just reading from cache. However, since …

only increment lastRequestId when using links to get results

---

CHANGELOG.md
src/core/QueryManager.ts
src/react/hooks/__tests__/useQuery.test.tsx

After discussions with @Akryum in PR #7810 and with the client team, I/we believe the benefit of restoring the Apollo Client 2.x `refetch` behavior (that is, refetching overwrites existing field data), for the specific case of custom `merge` functions (see https://github.com/apollographql/apollo-client/issues/7491#issuecomment-772115227), outweighs the risk of breaking applications that somehow depend on custom `merge` functions combining refetched data with existing data, especially since those applications can easily recover the previous AC3 behavior by passing `refetchWritePolicy: "merge"` on a per-query basis, or as a client-wide default using `defaultOptions.watchQuery`:
```ts
new ApolloClient({
defaultOptions: {
watchQuery: {
// We recommend "overwrite" instead of "merge", but …
```

Change default refetchWritePolicy to "overwrite" rather than "merge".

---

CHANGELOG.md
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts
src/core/index.ts
src/core/types.ts
src/core/watchQueryOptions.ts
src/react/components/types.ts
src/react/data/MutationData.ts
src/react/hoc/__tests__/mutations/queries.test.tsx
src/react/hoc/__tests__/mutations/recycled-queries.test.tsx
src/react/hoc/mutation-hoc.tsx
src/react/hoc/types.ts
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts
src/react/types/types.ts

This PR implements an enhancement discussed in #7843. A mutation's `update` function now receives an optional third argument with the context and variables provided to the original function.

Provide variables and context to update function

---

CHANGELOG.md
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/QueryManager/index.ts

PR #7956 by @dannycochran originally landed on the `release-3.4` branch (so we could test it in a beta release), but the changes are worthwhile and backwards compatible for the `@apollo/client@3.3.x` release line as well, which is currently published from the `main` branch.

Backport PR #7956 from release-3.4 to main branch.

---

CHANGELOG.md
src/react/data/QueryData.ts
src/react/ssr/__tests__/__snapshots__/useQuery.test.tsx.snap
src/react/ssr/__tests__/useQuery.test.tsx

This failing test was inspired by a reproduction provided by @bwhitty. The bug it demonstrates is that, during server-side rendering, `useQuery` always returns a `loading: true` result when first called, even if the cache already contains the necessary data to provide a final `loading: false` result.

Add/fix failing test of reading cache data immediately during server-side rendering.

---

CHANGELOG.md
src/react/data/MutationData.ts
src/react/hooks/__tests__/useMutation.test.tsx

Fixes #7754. When an `onError` handler is provided, the mutation promise returned `undefined` when it should return a result. We now return a result with `data` and `errors`.

Prevent `undefined` mutation result in useMutation

---

CHANGELOG.md
src/cache/inmemory/reactiveVars.ts
src/react/hooks/__tests__/useReactiveVar.test.tsx
src/react/hooks/useReactiveVar.ts

Fixes
#6699 (maybe)
#7694 
#7896
#8012
A race condition with useEffect was causing stale renders of values when reactivevars were called multiple times synchronously.

Fixes #8012 where a race condition with useEffect was causing stale renders of values.

---

README.md

We're planning to add a "Who is Apollo" section to most of our project READMEs, so this is the first of  few similar commits across our different projects.

Extend main README with a "Who is Apollo?" section

---

CHANGELOG.md
src/link/batch-http/batchHttpLink.ts
src/link/batch/__tests__/batchLink.ts
src/link/batch/batchLink.ts
src/link/batch/batching.ts

By default, `@apollo/client/link/batch-http` throttles requests using `batchInterval`. E.g. the queue of batched requests will fire every `batchInterval` milliseconds.
It may be desirable to instead debounce those requests so every new inbound request resets the timer. For instance, many mutations which are firing frequently from editing a table.
This PR introduces a simple `debounce` boolean to the http-batch-link and batch-link.

support "debounce" for the batch link

---

src/react/hooks/useReactiveVar.ts
src/react/ssr/__tests__/useLazyQuery.test.tsx
src/react/ssr/__tests__/useReactiveVar.test.tsx

Fixes #8124. Is this all we have to do? They mentioned hydration mismatches but that they’re not sure if it’s because of the new changes.

use an “isomorphic” effect to squelch server warnings

---

CHANGELOG.md
src/react/hooks/useReactiveVar.ts

While rereading the code @jcreighton added in #7652, I remembered it's safe to access a reactive variable `rv` by calling `rv()` in a `useEffect` callback (without going through `useReactiveVar`).
Taking advantage of this insight, we should be able to compare the latest variable value to the previous `value` _before_ deciding whether to call `rv.onNextChange(setValue)` in the effect callback function, if/when that callback fires. If the values already disagree, we can skip listening and just call `setValue` right away.
In React `<StrictMode>`, there will be two initial `rv()` values generated prior to the `useIsomorphicEffect` callback (which may never fire), but those values should always be the same, unless the reactive variable somehow gets updated in between the double renders. I …

Recheck `rv()` against previous `value` in `useEffect` callback in `useReactiveVar`

---

CHANGELOG.md
src/cache/inmemory/__mocks__/optimism.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/readFromStore.ts

Per the conversation in https://github.com/apollographql/apollo-feature-requests/issues/289, this PR is proposing two changes:
1. Add `resultCachMaxSize` config
This will allow customizing the max size of caches used for `resultCaching`.
`const cache = new InMemoryCache({ resultCachMaxSize: 5000 });`
2. Add automatic clean up for the caches in `executeSelectionSet` and in `executeSubSelectedArray` upon eviction of related entries.

add resultCacheMaxSize

---

docs/source/data/fragments.md

There is no RepoInfo.fragments.entry in the above example, I think it is referring to EntryInfo.fragments.entry

Correcting typo in example

---

src/core/QueryInfo.ts
src/core/__tests__/ObservableQuery.ts
src/utilities/testing/subscribeAndCount.ts

Revisiting PR #6891, which was reverted by commit c2ef68f9561b807df808a08a384032f574818c11.
With the introduction of canonical cache results (#7439), the strict equality check in `setDiff` is about to become mostly synonymous with deep equality checking (but much faster to check), so we need to deal with the consequences of #6891 one way or another.
As evidence that this change now (after #7439) has no observable impact, notice that we were able to switch back to using `!equal(a, b)` without needing to fix/update any failing tests, compared to the handful of tests that needed updating in #6891.
However, by switching to deep equality checking, we allow ourselves the option to experiment with disabling (or periodically clearing) the `ObjectCanon`, which would presumably lead to broadcasting …

Check structural equality in QueryInfo#setDiff, again.

---

CHANGELOG.md
config/prepareDist.js
package.json

Should fix #8168 and #5686.
The only side-effectful file we previously advertised was the [`fixPolyfills.native.js`](https://github.com/apollographql/apollo-client/blob/main/src/cache/inmemory/fixPolyfills.native.ts) module within `@apollo/client/cache`, but that file should be used only in React Native, whose Metro bundler does not perform tree-shaking or dead code elimination, which means we never really needed to defend that file from tree-shaking in the first place. In other words, I believe we can get away with putting `"sideEffects": false` in _all_ of our `package.json` files, for simplicity (as correctly conjectured by @nwalters512 in #8168).
Background explanation of the `"sideEffects": false` convention: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-fre …

Mark all generated package.json files as "sideEffects": false.

---

src/core/index.ts

Seems to fix #8217, judging from the provided reproduction. Presumably this is because using ECMAScript `export...from` syntax means we don't have to import anything into the scope of the `index.ts` module, which makes the whole situation easier for the tree-shaker to reason about.

Re-export graphql-tag exports directly, without destructuring.

---

package-lock.json
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/cache/index.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/object-canon.ts
src/cache/inmemory/policies.ts
src/utilities/graphql/storeUtils.ts

Fixes #8185, though I would say this removal is more for ESM-friendliness than for performance, as I explain below.
> Note: I am expecting tests to fail for the first commit, demonstrating the importance of using a stable serialization strategy for field arguments.
Although `fast-json-stable-stringify` has done its job well, it only provides a `"main"` field in its `package.json` file, pointing to a CommonJS entry point, and does not appear to export any ECMAScript modules.
Thanks to our conversion/abandonment of `fast-json-stable-stringify` and other CommonJS-only npm dependencies (`zen-observable` in #5961 and `graphql-tag` in #6074), it should now (after this PR is merged) be possible to load `@apollo/client/core` from an ESM-aware CDN like jsdelivr.net or jspm.io:
```html
<script …
```

Remove dependency on `fast-json-stable-stringify`

---

CHANGELOG.md
src/__tests__/__snapshots__/exports.ts.snap
src/__tests__/client.ts
src/__tests__/refetchQueries.ts
src/cache/core/cache.ts
src/cache/core/types/Cache.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/inMemoryCache.ts
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/QueryManager/index.ts
src/core/types.ts
src/core/watchQueryOptions.ts
src/react/hooks/__tests__/useMutation.test.tsx
src/react/types/types.ts
src/utilities/common/makeUniqueId.ts
src/utilities/graphql/storeUtils.ts
src/utilities/index.ts
src/utilities/types/IsStrictlyAny.ts

As promised in https://github.com/apollographql/apollo-client/issues/7878#issuecomment-805320556 and https://github.com/apollographql/apollo-client/pull/7827#issuecomment-805321246, this PR turns the `client.refetchQueries` method into a one-stop solution for refetching queries (without having to perform a mutation), tying together several previous ways of triggering refetches into a single, flexible API.
This is the last major piece of new functionality that we plan to add to Apollo Client v3.4, and is intended to complement similar functionality added to mutations (`options.onQueryUpdated`, previously called `options.reobserveQuery`) in #7827, and builds on the `cache.batch` primitive added to `InMemoryCache` in #7819. If this PR is merged, it should conclude the implementation of the …

Improve standalone client.refetchQueries method to support automatic detection of queries needing to be refetched.

---

src/cache/inmemory/__tests__/object-canon.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/helpers.ts
src/cache/inmemory/object-canon.ts
src/cache/inmemory/readFromStore.ts

As promised in https://github.com/apollographql/apollo-client/pull/8222#discussion_r633891466, a more general implementation of `ObjectCanon` is coming (after Apollo Client v3.4), so I think it would be wise to restrict the functionality of the current implementation to match what I have planned.
First, I want to reserve the `isCanonical` method to return `true` for anything that doesn't need to be (further) canonized, including primitive values. To that end, the `isKnown` method now returns `true` only for _objects_ previously returned by `canon.admit`.
Second, the future implementation will allow full customization of canonization by object `prototype`, but will only canonize arrays and plain objects by default. To that end, I've restricted `ObjectCanon` canonization to objects whose …

Restrict ObjectCanon prototypes to {Array,Object}.prototype and null.

---

CHANGELOG.md
package.json
src/cache/core/types/common.ts
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/readFromStore.ts
src/core/ObservableQuery.ts
src/errors/index.ts
src/react/hooks/__tests__/useQuery.test.tsx

“Fixes“ #8063 by exposing missing field errors.

pass along missing field errors to the user

---

docs/source/data/error-handling.mdx

Based on feedback from this forum post: https://community.apollographql.com/t/error-policy-in-apollo-client-react-seems-doesnt-work/160

Clarify that partial results are specific to resolver errors

---

CHANGELOG.md
src/__tests__/__snapshots__/mutationResults.ts.snap
src/__tests__/mutationResults.ts
src/__tests__/optimistic.ts
src/core/QueryManager.ts
src/core/watchQueryOptions.ts
src/react/components/Mutation.tsx
src/react/components/Query.tsx
src/react/components/Subscription.tsx
src/react/hoc/__tests__/mutations/queries.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/types/types.ts

Fixes #7665 by allowing [field policy `read` functions](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-read-function) to run for fields within mutation results, making it easier for mutation result data to use custom scalar types (to borrow @stephenh's use case from #7665).
In order to keep each `ROOT_MUTATION` write isolated from others that might be happening at the same time, this PR also removes the temporary `ROOT_MUTATION` object from the cache immediately after the `update` function runs, so information like arguments passed to mutation root fields will not be retained in the cache longer than need be, thereby resolving #3592. To be clear, the Apollo Client team does not believe the previous behavior of leaving `ROOT_MUTATION` in the cache created any …

Various improvements to ROOT_MUTATION caching

---

CHANGELOG.md
src/utilities/testing/index.ts

This addresses a regression that happened when AC 3 was launched.
Fixes #6540

Re-export the MockedResponse ResultFunction type

---

config/rollup.config.js
package-lock.json
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/cache/inmemory/entityStore.ts
src/cache/inmemory/helpers.ts
src/cache/inmemory/object-canon.ts
src/cache/inmemory/policies.ts
src/cache/inmemory/readFromStore.ts
src/core/QueryManager.ts
src/core/index.ts
src/utilities/common/maybeDeepFreeze.ts
src/utilities/common/mergeDeep.ts
src/utilities/common/objects.ts
src/utilities/graphql/storeUtils.ts
src/utilities/index.ts

It appears our closing of this old [@renovate PR to update Rollup to v2](https://github.com/apollographql/apollo-client/pull/6033) caused @renovate to stop opening PRs to update Rollup to any v2.x.y version, so our version of Rollup has been out of date since then.
Though obviously not ideal, this major version lag hasn't been a problem for us because Rollup v1 still works very well, and we use it only to generate CommonJS bundles, which is a relatively stable build target (CommonJS hasn't changed much lately). We rely on other tools like `tsc` for critical stuff like TypeScript compilation, and we have numerous ways to verify the output of our build system. With that said, Rollup v2 has some great new features that I'm looking forward to trying, such as `output.inlineDynamicImports`!
To …

Update rollup to version 2.50.5

---

src/__tests__/client.ts
src/__tests__/refetchQueries.ts
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts
src/core/types.ts
src/core/watchQueryOptions.ts
src/react/types/types.ts

This feature is to help create a workaround for this comment:
https://github.com/apollographql/apollo-feature-requests/issues/272#issuecomment-794296626
By exposing the current observable queries, consumers can look at all their "refetchQueries" for a mutation, and if any of them aren't in the result of "getObservableQueries()", they can figure out how to ensure those queries are re-fetched on subsequent mounts.
This logic was already being done by query manager for its own internal handling of "refetchQueries" logic, so we are just exposing a small piece of that here.

add public method to retrieve all current observable queries

---

CHANGELOG.md
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts

Fix https://github.com/apollographql/apollo-client/issues/7535
This PR deep-merge `toBeAdded` typePolicies instead of shallowly merging them
cc @brainkim

Deep merge toBeAdded type policies

---

CHANGELOG.md
package.json
src/cache/inmemory/__tests__/__snapshots__/writeToStore.ts.snap
src/cache/inmemory/__tests__/writeToStore.ts
src/cache/inmemory/writeToStore.ts

Fixes #8370 by postponing all `context.store.merge` updates until after all `processSelectionSet` work is done, performing the store updates at the end of `StoreWriter#writeToStore`, whereas previously those updates happened at the end of each `StoreWriter#processSelectionSet` call.
The postponement of store updates gives the `StoreWriter` a chance to merge together multiple partial objects representing the same logical object (possibly matched by different fragments along different query paths), before running `merge` functions with `applyMerges`.
Previously, those partial objects would be merged separately into `context.store`, so later objects might replace earlier objects in cases where the objects are unidentifiable/non-normalized, and there was no `merge` function (or `merge: true` …

Merge incoming fragment fields before running `merge` functions and updating the `EntityStore`

---

CHANGELOG.md
config/helpers.ts
package-lock.json
package.json
src/__tests__/client.ts
src/__tests__/graphqlSubscriptions.ts
src/__tests__/local-state/resolvers.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/core/ObservableQuery.ts
src/core/__tests__/QueryManager/index.ts
src/link/http/__tests__/HttpLink.ts
src/link/http/__tests__/checkFetcher.ts
src/link/http/__tests__/helpers.ts
src/link/retry/__tests__/retryLink.ts
src/react/components/Query.tsx
src/react/hoc/__tests__/queries/errors.test.tsx

Closes #6886.
As of this writing, `@apollo/client@beta` should support [`typescript@3.7`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) and later, by avoiding any type system features in `.d.ts` files that are not understood by TS 3.7.
Until this PR, we have been using `typescript@3.9.9` to build `@apollo/client` and run its tests, ensuring compatibility with that version of TypeScript (v3.9.9), at the very least.
Despite the upgrade to v4.3.3 in this PR, we intend to continue supporting older v3.x versions of `typescript`, unless there is a compelling reason to use recently added syntax in externally visible type declarations. One such compelling feature: TypeScript v3.8 would be required to support [type-only `import type { ... } from ...` …

Update typescript to v4.3.3

---

config/entryPoints.js
config/prepareDist.js
src/__tests__/__snapshots__/exports.ts.snap
src/cache/index.ts
src/core/index.ts
src/errors/index.ts
src/link/core/index.ts
src/react/index.ts
src/testing/index.ts
src/utilities/globals/DEV.ts
src/utilities/globals/index.ts
src/utilities/index.ts

Inspired by discussion with @abdonrd: https://github.com/apollographql/apollo-client/pull/8347#issuecomment-863260093
Find/replace string transforms aside, I caught and fixed a real bug in this PR, which was that a webpack production build _without_ any special handling for `__DEV__` would fail to include the `__DEV__` polyfill (presumably due to tree-shaking), leading to `ReferenceError` exceptions within `@apollo/client` code. Although we recommend using a minifier to inline `__DEV__` as a boolean constant, it's important that everything works without configuring inlining (or anything else) in a build step. This PR restores that principle. Configuring your minifier to inline `__DEV__` should be merely an optimization opportunity, not a hard requirement.
Verified using our [reproduction …

Protect `__DEV__` from mis-minification / aggressive tree-shaking

---

docs/source/data/subscriptions.mdx

Replace `COMMENT_QUERY` with `COMMENTS_QUERY` for the "Subscribing to
updates for a query" section.

Fix typo for the "Subscriptions" chapter

---

src/__tests__/__snapshots__/exports.ts.snap
src/cache/inmemory/object-canon.ts
src/utilities/common/canUse.ts

I noticed that `canUseWeakMap` is being used for `WeakSet` feature detection. We still support IE11 (😭) and in that environment `canUseWeakMap` is `true` but `WeakSet` is [not supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#browser_compatibility). Thanks!

Fix `WeakSet` feature detection in `ObjectCanon`

---

CHANGELOG.md
src/react/hooks/utils/useBaseQuery.ts

This change would fix the occurrence of the warning "Can't perform a React state update on an unmounted component" using `useQuery` in React.StrictMode.
#6209
best regards

Do not forceUpdate if consuming component is not mounted

---

src/react/types/types.ts

Fixes https://github.com/apollographql/apollo-client/issues/8407
I’m leaving this open so I can do a quick comparison of the old and new types to see if other things have changed in a backwards-incompatible way.

Fix backwards-incompatible changes to types

---

src/react/components/__tests__/client/Mutation.test.tsx
src/react/hoc/__tests__/mutations/queries.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx

Building on #7745, this PR means that `npm test` no longer spits out any red error text:

Squash remaining "not wrapped in act(...)" error messages in React-related tests

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/core/__tests__/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx

Appears to fix #7978, by always giving the cache a chance to provide an up-to-date result for the given options, rather than relying on `observableQuery.lastResult`, which may be stale.
Note that [`QueryInfo#getDiff`](https://github.com/apollographql/apollo-client/blob/ea0d6b06153726389c2509bb7756617b29515258/src/core/QueryInfo.ts#L162-L164) knows how to handle `fetchPolicy: "no-cache"`, so it's safe to call even in that case.

Make `ObservableQuery#getCurrentResult` always call `queryInfo.getDiff()`

---

CHANGELOG.md
src/cache/inmemory/__tests__/policies.ts
src/utilities/policies/__tests__/relayStylePagination.test.ts
src/utilities/policies/pagination.ts

Should fix #8267, taking inspiration from @migueloller's suggestion in https://github.com/apollographql/apollo-client/issues/8267#issue-895915003.

Prefer `existing.pageInfo` cursors in `relayStylePagination` field policy `read` functions

---

CHANGELOG.md
src/link/http/__tests__/selectHttpOptionsAndBody.ts
src/link/http/selectHttpOptionsAndBody.ts

Should fix #8447, by preferring the _last_ (according to `Object.keys(headers)`) header among multiple headers whose names are case-insensitively equivalent.
I'm a little worried this could be a user-visible change in some (HTTP-specification-violating) situations. If so, we can easily retarget this PR to the `release-3.4` branch, and make a clear note of it in `CHANGELOG.md`.

Normalize user-provided HttpLink headers by lower-casing their names.

---

docs/source/data/subscriptions.mdx

I think we cannot use this syntax as data is at first undefined, at least it does not work on my side and the proposed syntax works.
Am I missing something or was something wrong with the example ?

Update Documentation of execution of subscription example

---

CHANGELOG.md
config/processInvariants.ts
package-lock.json
package.json
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts

Implementing the plan I described in https://github.com/apollographql/apollo-client/issues/8442#issuecomment-878418870, building on https://github.com/apollographql/invariant-packages/pull/155.
Here's where [`setLogVerbosity("log")`](https://github.com/apollographql/apollo-client/blob/5b76276e9dfa1d19ee91d043ceb76b5a1d0dbe87/src/core/index.ts#L86-L92) is called by default. Note that all `invariant.*` log messages (of any level) are always hidden in production, so the `setLogVerbosity` configuration matters only in development.

Suppress `Missing cache result fields...` warnings unless `setLogVerbosity("debug")` configured

---

docs/source/local-state/managing-state-with-field-policies.mdx

This has been a pretty large source of confusion when people move from local resolvers to field policies. We'll probably want to expand on this much further, and show people how to switch from using `mutate` / `useMutation` with `@client` to equivalent `writeQuery` / `writeFragment` / reactive variable functionality, but this quick note will hopefully serve as a start to help clarify things.

Note that mutate/useMutation with @client is not supported in AC3

---

src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/__tests__/writeToStore.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/policies.ts
src/cache/inmemory/writeToStore.ts

PR #7778 (first released in `@apollo/client@3.4.0-beta.12`) allowed [`merge: true`](https://github.com/apollographql/apollo-client/pull/6714) to combine `Reference` objects (which refer to normalized `StoreObject` entities by ID) with non-normalized `StoreObject` objects.
When these mixed `Reference`/`StoreObject` merges happen (e.g. in the `mergeObjects` function), the `StoreWriter#applyMerges` method returns a `Reference` rather than a `StoreObject`, which was a new possibility not adequately handled by the calling code in PR #7778. In particular, `applyMerges` returning a `Reference` could result in calling `store.merge(dataId, fields)` when `isReference(fields)`, allowing `__ref` properties to end up as fields in the normalized `StoreObject`. These stray `__ref` properties could later …

Multiple (3) lines of defense against merging `{ __ref }` objects into normalized `StoreObject` entities

---

package-lock.json

If you're using the latest/LTS version of `npm`, [which currently means v7](https://www.npmjs.com/package/npm?activeTab=versions), you shouldn't have to contend with `npm` rewriting `package-lock.json` whenever you run `npm i` in your local repository.
Since we actively merge from `main` into whatever release branch is currently active ([`release-3.5`](https://github.com/apollographql/apollo-client/pull/8554) right now), it seems important for `main` to be using the same format for `package-lock.json` as the release branch, which is why this PR targets `main` rather than `release-3.5`.
The `package-lock.json` file is [never published to npm](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson), so this change should not have any …

Update package-lock.json to "lockfileVersion":2 for npm v7

---

CHANGELOG.md
src/cache/inmemory/object-canon.ts

May help with #8557, because initializing `let stringifyCanon = new ObjectCanon` in module scope led to evaluating the `__DEV__` global variable before it had been polyfilled (that's my current theory, at least).
Background reading:
* `__DEV__`: #8347
* `canonicalStringify`: #8222

Delay initializing `stringifyCanon` until `canonicalStringify` used.

---

docs/source/api/link/apollo-link-retry.md

Added a line to indicate `RetryLink`'s `attempts` function can return either a `boolean` or a `Promise` which resolves to a `boolean`. Fixes #8219.
Also added code styling to the word "boolean" to match other Apollo docs style.

Update docs for `RetryLink`'s `attempts` function (fixes #8219)

---

CHANGELOG.md
src/react/types/types.ts

Commit 3f2eee7e8d6a4874120b6c84707b565ebcdaa349 in #7902 added a number of new type parameters to existing types, without always providing a default.
Should alleviate #8572.

Use more default type parameters for mutation-related types in `react/types/types.ts`

---

CHANGELOG.md
src/react/data/QueryData.ts
src/react/hooks/__tests__/useQuery.test.tsx

Fix ssr: false causing queries to hang

---

CHANGELOG.md
config/prepareDist.js

We currently define only `engines.npm` in the root `package.json` file (as of 68d9cabab976a4ca659e161ec52ea1700aab8496 or `@apollo/client@3.4.2`), so that's all that's being hidden when we `delete packageJson.engines` here.
We can carve out exceptions for other `engines` constraints in the future if we need to, but for now we don't need any of them, so we can just delete the whole `engines` section.
Should fix #8577, if my theory in https://github.com/apollographql/apollo-client/issues/8577#issuecomment-891949871 is correct.

Remove `"engines"` section from `dist/package.json` before publishing

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts

The `invariant` in the first commit is expected to fail, and serves as a minimal regression test for issue #8586.
This refactoring ensures `observableQuery.queryId` ends up the same as `observableQuery.queryInfo.queryId`, which is relevant in cases when we choose a specific query ID string before creating the `QueryInfo` and `ObservableQuery` objects.
Ensuring that `queryInfo.queryId === queryInfo.observableQuery.queryId` (another way of saying the same thing) also fixes the `invariant` failures I deliberately introduced in the first commit.
This inconsistency between IDs was the cause of issue #8586, a double registration bug for mutation `refetchQueries` specified using the legacy one-time `refetchQueries: [{ query, variables }]` style.
Another (recommended) way to work around that …

Fix double registration bug for mutation `refetchQueries` specified using legacy one-time `refetchQueries: [{ query, variables }]` style

---

CHANGELOG.md
src/react/data/QueryData.ts
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/utils/useBaseQuery.ts

Fixes situations where the observable query changes and we don’t subscribe to the new one. All this code is in the process of being heavily refactored (I’m currently chasing down QueryData in a track suit with a machete), so this is a band-aid.
Potentially fixes:
- https://github.com/apollographql/apollo-client/issues/8584
- https://github.com/apollographql/apollo-client/issues/8582
- https://github.com/apollographql/apollo-client/issues/8575

Fix useQuery stalling when observable queries change due to query changes

---

CHANGELOG.md
src/__tests__/__snapshots__/exports.ts.snap
src/link/http/__tests__/HttpLink.ts
src/link/http/createHttpLink.ts
src/utilities/index.ts

This should help with a variety of strategies for instrumenting `window.fetch`, as discussed in issue #7832.

Reevaluate `window.fetch` each time `HttpLink` uses it, if not configured using `options.fetch`

---

CHANGELOG.md
config/rollup.config.js
package.json
scripts/memory/tests.js

Restore `@apollo/client/apollo-client.cjs.js` CommonJS bundle for older bundlers

---

CHANGELOG.md
src/core/QueryManager.ts
src/core/watchQueryOptions.ts

These are the changes I was suggesting in my comments on PR #8595:
* https://github.com/apollographql/apollo-client/pull/8595#pullrequestreview-724460852
I believe this addition of `MutationFetchPolicy` is a backwards-compatible change, since it amounts to replacing a type that could only be `"no-cache" | undefined` with a strictly additive superset: `"network-only" | "no-cache" | undefined`.
I don't expect anyone to want/need to pass `fetchPolicy: "network-only"` explicitly, but I think it makes sense to be explicit about the default mutation `fetchPolicy` behavior, and its relationship to the `"no-cache"` alternative.

Clarify mutation `fetchPolicy` options using `MutationFetchPolicy` union type

---

CHANGELOG.md
src/cache/inmemory/__tests__/writeToStore.ts
src/cache/inmemory/writeToStore.ts
src/react/hooks/__tests__/useQuery.test.tsx

The regression test is expected to fail, as I merely copy/pasted/tweaked the code provided by @Grmiade in  #8600.
This PR fixes a bug I introduced in #8372 in `@apollo/client@3.4.0-rc.7`. In #8372, I introduced code that saved a reference to the current `MergeTree` object in `context.incomingById`, but I did so without thinking carefully about [the recycling system we use for `MergeTree` objects](https://github.com/apollographql/apollo-client/pull/7070#discussion_r494646474), which allows _empty_ `MergeTree` objects to be reused for other unrelated parts of the result tree. In some situations, this reuse can lead to the original field seeming to have a `merge` function, just because some future user of the recycled `MergeTree` populates it with unrelated information by the time it gets …

Fix accidental reuse of recycled `MergeTree` objects in `StoreWriter` class used by `InMemoryCache`

---

.github/dependabot.yml
examples/bundling/no-tree-shaking/rollup-ac2/package-lock.json
examples/bundling/no-tree-shaking/rollup-ac3/package-lock.json
examples/bundling/tree-shaking/rollup-ac2/package-lock.json
examples/bundling/tree-shaking/rollup-ac3-no-react/package-lock.json
examples/bundling/tree-shaking/rollup-ac3/package-lock.json
package-lock.json

Batching updates from the following @dependabot PRs, with some additional configuration adjustments:
* #8623
* #8624
* #8625
* #8627
* #8628
We use @renovate-bot  for routine dependency updates, but @dependabot will sometimes open PRs for security updates. When this happens, we'd like it to use `npm@7.x` to preserve the `"lockfileVersion": 2` format of `package-lock.json` files.

Batched `path-parse` security updates for examples/bundling applications

---

docs/source/caching/advanced-topics.mdx
docs/source/local-state/client-side-schema.mdx
docs/source/performance/performance.mdx

I intend to do a pass on the `@connection` and `fetchMore` sections of the caching advanced topics article soon, but figure these are lower-lift edits that can go together

Copyedits to various AC docs

---

CHANGELOG.md
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts

Following @habovh's steps from #8639, expecting failure for the first commit.
I'll push more commits to fix the problem soon.

Fix error thrown by nested `keyFields: ["a", ["b", "c"], "d"]` syntax when some of the fields are aliased

---

CHANGELOG.md
package.json
src/__tests__/client.ts
src/core/ObservableQuery.ts
src/core/__tests__/ObservableQuery.ts
src/react/data/QueryData.ts
src/react/hooks/__tests__/useQuery.test.tsx

PR #8422 (released in `@apollo/client@3.4.0-rc.15`) attempted to solve issue #7978 (reported by @dylanwulf) by relying on `queryInfo.getDiff()` to obtain results appropriate for the current `variables`, rather than blindly relying on the `lastResult` stored by the `ObservableQuery` (which may have been obtained using different `variables`).
While this solution appeared to resolve #7978, it introduced a new bug (reported in #8620 by @maxsalven) because the following code now runs unconditionally:
https://github.com/apollographql/apollo-client/blob/bd03ff048ecaf4ddc7aeb2906bf0bdfb2eb695d8/src/core/ObservableQuery.ts#L205-L208
Whenever `!(diff.complete || this.options.returnPartialData)`, this code clobbers `result.data` with `void 0`, even though `result.data` might provide useful …

Avoid voiding `result.data` in `ObservableQuery#getCurrentResult` when `!diff.complete`

---

CHANGELOG.md
src/core/QueryManager.ts
src/utilities/observables/Concast.ts

Inspired by @cornedor's comment https://github.com/apollographql/apollo-client/issues/7608#issuecomment-882418482.
Should help with some instances of issue #7608, specifically those with global unhandled promise rejection errors.
I don't know if this is the full solution, but I believe it is helpful and safe to introduce a delay before unsubscribing from the underlying observable, giving other `Concast` subscribers a chance to subscribe, thereby saving the `Concast` from needing to be cancelled, while still quickly unsubscribing if there are no new subscribers within 10ms.

Use `setTimeout` instead of `Promise.resolve().then(...)` to delay `Concast` cancellation

---

CHANGELOG.md
config/checkDEV.ts
config/entryPoints.js
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/cache/index.ts
src/core/index.ts
src/errors/index.ts
src/link/core/index.ts
src/link/http/index.ts
src/link/persisted-queries/index.ts
src/link/utils/index.ts
src/react/context/index.ts
src/react/data/index.ts
src/react/hoc/index.ts
src/react/hooks/index.ts
src/react/index.ts
src/react/parser/index.ts
src/testing/index.ts
src/utilities/globals/index.ts
src/utilities/index.ts

This PR started out as a quick fix for #8674, but in the process I realized the best way to prevent `ReferenceError`s for `__DEV__` once and for all is to write a build step that examines compiled `dist/` code for usage of `__DEV__`, and enforces that the corresponding entry point `index.js` file imports and calls `checkDEV()`.
To test these changes using a published version of `@apollo/client`, I merged this PR branch into `release-3.5` and published `@apollo/client@3.5.0-beta.7` with this PR included. From my testing, this version works as before with ESM-aware CDNs like [esm.run](https://esm.run). In particular, the following code works in a browser console:
```js
await import("https://esm.run/@apollo/client@3.5.0-beta.7/core")
```
See #8266 for more background on why this matters …

Enforce that `__DEV__` is polyfilled in every entry point that uses it

---

CHANGELOG.md
package-lock.json
package.json
src/core/__tests__/QueryManager/links.ts
src/core/__tests__/QueryManager/recycler.ts
src/link/context/index.ts
src/link/core/ApolloLink.ts
src/link/http/__tests__/HttpLink.ts
src/link/persisted-queries/index.ts
src/link/retry/retryLink.ts
src/react/types/types.ts

This update includes https://github.com/apollographql/zen-observable-ts/pull/152, and should fix issue #8688 because Apollo Client no longer generates code in `dist/**/*.d.ts` files with type references to the `@types/zen-observable` package:
```ts
/// <reference types="zen-observable" />
```
With these references gone, consumers of `zen-observable-ts` should not need to add `@types/zen-observable` as a dependency. In fact, the `@types/zen-observable` package is no longer involved at all. Thus, #8688 should be fixed.
Since this could be a disruptive type-level change for anyone who was previously depending on the global declaration of the `ZenObservable` namespace, I'm targeting the `release-3.5` branch so we can test before releasing.

Update `zen-observable-ts` to eliminate transitive dependency on `@types/zen-observable`

---

CHANGELOG.md
package.json
src/cache/core/__tests__/cache.ts
src/cache/core/cache.ts
src/cache/core/types/Cache.ts
src/cache/core/types/DataProxy.ts

Hi,
We love apollo client in our company and use it for all of our state management needs in our project.
With the help of graphql-code-generator, we're able to write 100% type-safe state management code, whether it's from server or client only schema and we quite like using the schema as the layer of abstraction for our state's structure.
This PR is about two helper methods we've been using for quite some time, they're just a more concise way to do common operations, like reading from state, modifying it then writing it back, I hope you find it useful for other users too.
From the example in the docs, this PR allows rewriting this logic:
```typescript
const data = client.readQuery({ query });
client.writeQuery({
query,
data: {
todos: [...data.todos, myNewTodo],
},
});
```
Into: …

Add `updateQuery` and `updateFragment` methods to `ApolloCache`

---

docs/static/_redirects

This branch fixes redirects since we changed the way that docs were deployed in https://github.com/apollographql/apollo-client/pull/8672

docs: Remove path prefixes for docs redirects

---

src/__tests__/__snapshots__/exports.ts.snap
src/link/persisted-queries/index.ts

Exported PersistedQueryLink namespace so `Options` can be imported and used.

Export PersistedQueryLink namespace

---

CHANGELOG.md
src/utilities/globals/index.ts

Actually using `checkDEV` by calling it (instead of just re-exporting it) appears to fix the reproduction provided in this comment by @lauraseidler: https://github.com/apollographql/apollo-client/issues/8674#issuecomment-911417247
I would have thought the `"sideEffects": true` configuration in `@apollo/client/utilities/globals/package.json` would be enough to keep the modules in `@apollo/client/utilities/globals/*` from being tree-shaken, but apparently Vite is clever enough to second-guess that guidance when it comes to uncalled function declarations like `checkDEV`.
Thankfully, we can get away with calling `checkDEV()` just this once, in the module that declares/exports it.

Guide tree-shaking by calling `checkDEV()` in `utilities/globals/index.ts`

---

CHANGELOG.md
src/utilities/policies/__tests__/relayStylePagination.test.ts
src/utilities/policies/pagination.ts

Building on #7949 by @bubba, and hopefully fixing #7822.

Improve handling of falsy `existing` and/or `incoming` parameters in `relayStylePagination`

---

docs/source/api/link/apollo-link-error.md

Converting the `map` funtion shown at `ErrorLink` to `forEach` in order to avoid confusion. Since the `graphQlErrors` will be `undefined` as we are not returning anything inside the `map`, which can be "tricky" for people unfamiliar with `map`.

docs: changing map function to forEach at ErrorLink example

---

.circleci/config.yml

Upstream Node.js bug https://github.com/nodejs/node/issues/40030 has been fixed in [Node.js v16.9.1](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#2021-09-10-version-1691-current-richardlau). This bug has recently been causing frequent spurious test failures for Apollo Client. [A](https://app.circleci.com/pipelines/github/apollographql/apollo-client/11547/workflows/4027b7e7-b8bd-4cf1-8927-f08921a4c577/jobs/83124) [few](https://app.circleci.com/pipelines/github/apollographql/apollo-client/11571/workflows/3e78ba11-0e51-4f4f-92dd-e732c53716d2/jobs/83167) [examples](https://app.circleci.com/pipelines/github/apollographql/apollo-client/11536/workflows/55d29d9f-b4a7-4803-80bb-e3891946960d/jobs/83106).
Failure message, for posterity:
```
```
CircleCI ships docker …

Pin CircleCI container to `cimg/node:16.8` until 16.9.1 available

---

src/react/hooks/useQuery.ts

---
`useQuery` was clearly rewritten completely from 3.4 to 3.5, but its  signature changed from
```ts
function useQuery<TData = any, TVariables = OperationVariables>(/*...*/): QueryResult<TData, TVariables>;
```
to 
```ts
function useQuery<TData = any, TVariables = OperationVariables>(/*...*/): QueryResult<TData>;
```
This causes the `TVariables` type arg to be thrown away, and then defaulted to `OperationVariables` in `QueryResult`.  This causes assignability issues in TS in some cases. The issue can be demonstrated with a trivial generic hook that wraps a query hook:
```ts
type DumbQuery = { foo: string };
type DumbVariables = { bar: number };
const DumbDocument = gql`
query Dumb($bar: Int!) {
dumb(bar: $bar) {
foo
}
}
`;
function useDumbQuery(baseOptions: QueryHookOptions<DumbQuery, …
```

Restore TVariables to useQuery return type

---

CHANGELOG.md
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/react/context/ApolloContext.ts
src/utilities/common/canUse.ts
src/utilities/observables/subclassing.ts

Should fix #8790, by allowing multiple copies of `@apollo/client` (uncommon) to share the same `React.createContext[contextKey]` object.
A lot has changed since #7371, but I am not worried about `React.createContext` being undefined, because (in this module, `ApolloContext.ts`), the `React` object is now a namespace object (thanks to `import * as React from 'react'`), and we call `React.createContext` unconditionally within `getApolloContext` already, so `React.createContext` must be defined when `getApolloContext` is called, or this code would be totally broken.
This implementation uses `React.createContext[contextKey]` instead of `React[contextKey]` (as in #7371) because the `React` namespace object is likely frozen/non-extensible, whereas `React.createContext` is an ordinary function …

Associate Apollo context with `React.createContext` (instead of using a local `WeakMap`) again

---

CHANGELOG.md
package.json
src/cache/core/types/common.ts
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/readFromStore.ts
src/core/ObservableQuery.ts

In the (somewhat pathological but also entirely plausible) example in #8707, more than 60% of cache read time is spent creating `MissingFieldError` objects, in part because an unnecessary `InvariantError` is created and then used only for its `message`; in part because the `MissingFieldError` class inherits from `Error`, which makes `super(message)` initialization expensive; but also (in large part) because there are just so many error objects (tens of thousands).
This pull request needs more work to minimize breaking changes for anyone using the `MissingFieldError` type directly, but it offers an extremely appealing solution to the performance problems enumerated above: **What if we reported only one, combined `MissingFieldError` per cache read?**
On a personal note, I'm leaving for a …

Report single `MissingTree` instead of large `MissingFieldError[]` array for incomplete cache reads

---

CHANGELOG.md
src/cache/core/__tests__/cache.ts
src/cache/core/cache.ts
src/cache/core/types/Cache.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts
src/core/QueryInfo.ts

Since `cache.updateQuery` and `cache.updateFragment` (#8382) run user-provided code (the `update` function), there could end up being multiple cache write operations within a single update, which would trigger `broadcastWatches` separately, unless we apply batching.
Fortunately, the `ApolloCache` class already has a tool for `broadcastWatches` batching: `cache.batch` (introduced by #7819 in AC3.4). However, the exercise of using `cache.batch` for this purpose led me a useful improvement for that API, which I describe below.
The `cache.batch` API followed its predecessor `cache.performTransaction(cache => ...)` in _not_ returning the result of the transaction function (the `options.update` function for `cache.batch`), which makes the following code harder to write:
```js
// This is what I …
```

Use `cache.batch` within `cache.updateQuery` and `cache.updateFragment`

---

CHANGELOG.md
src/react/hoc/subscription-hoc.tsx

Bug fix: rename `componentDidUpate` to `componentDidUpdate` in subscription-hoc.tsx
`shouldResubscribe` option does not work because of this.

Bug fix in subscription-hoc

---

.circleci/config.yml

Unpin `circleci/node` container version and update to Node.js v16.9.1

---

CHANGELOG.md
src/utilities/observables/subclassing.ts

May fix #8809, since this line was added in `@apollo/client@3.4.12`, and seems to be the only change that could explain the appearance of `require('..')` in `@apollo/client/utilities/utilities.cjs.js`, as noticed by @ianhe8x.
Both styles of import _should_ work, but we can be more explicit/precise when the import does not cross entry points.

Fix `canUseSymbol` import between internal `src/utilities` modules

---

CHANGELOG.md
src/utilities/common/__tests__/maybeDeepFeeze.ts
src/utilities/common/maybeDeepFreeze.ts

This PR fixes #6813 by ignored TypedArrays when freezing objects.

Ignore TypedArrays when freezing object

---

CHANGELOG.md
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts

This may help with memory management during SSR (provided `cache.reset()` is called), per my comment https://github.com/apollographql/apollo-client/issues/7942#issuecomment-916450312.
Reusing the same cache between SSR requests is typically not what we recommend, since creating a new client/cache for each request is such an easy and effective way to prevent data from leaking between requests from different users/clients.
However, if you're careful to reset the cache each time, or you have non-SSR reasons for resetting the cache, it seems reasonable to expect the `cache.watches` to be emptied after the reset.

Clear `InMemoryCache` watches when `cache.reset()` called

---

CHANGELOG.md
src/__tests__/refetchQueries.ts
src/core/QueryManager.ts

The example code I provided in https://github.com/apollographql/apollo-client/issues/5419#issuecomment-908398224 should work even if `QueryIWantToRefresh` currently has no observers:
```ts
client.refetchQueries({
include: ["QueryIWantToRefresh"],
// ... other options...
})
```
I suspect the `oq.hasObservers()` check removed by this PR explains at least some instances of issue #5419, but I also believe there's value in refetching observerless queries (at the developer's explicit request), so _future_ subscribers can immediately receive the most recent result or error.
Alternatively, when performing a mutation, this same line of reasoning applies to the `refetchQueries: [...]` option:
```ts
client.mutate({
// ... other options...
refetchQueries: ["QueryIWantToRefresh"],
})
```
If you really …

Stop excluding observerless queries from `refetchQueries` selection

---

CHANGELOG.md
scripts/memory/tests.js
src/cache/core/types/DataProxy.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/__tests__/optimistic.ts
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/__tests__/readFromStore.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/readFromStore.ts
src/core/QueryInfo.ts
src/core/__tests__/QueryManager/index.ts
src/core/watchQueryOptions.ts
src/react/hooks/__tests__/useQuery.test.tsx

Making `InMemoryCache` result canonization (#7439) _opt-in_ instead of opt-out (as it currently is) should prevent the surprises of shared object references reported in #8717, and fixes the apparent memory leak in #8784, as confirmed using @CollinMonahanLab49's reproduction.
Given that canonization was a headline feature of v3.4, shipping this PR would be something of a retraction, but I believe it's the simplest way to prevent surprise and encourage using canonization (only) where it's actually useful.
Code that benefits from canonization can continue using it! In fact, there are multiple ways to override the new default behavior, with different scopes:
```ts
// This cache will canonize everything by default, unless
// specific reads request canonizeResults:false.
const cache = new …
```

Disable `InMemoryCache` canonization by default to prevent unexpected memory growth/sharing, with options to reenable

---

CHANGELOG.md
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts

As @aj-foster noticed in #8831, `canonizeResults` (and also `returnPartialData`!) were missing from this `cache.diff` call.
Instead of enumerating the missing properties explicitly, we can take advantage of the overlap between `WatchOptions` and `DiffOptions` to pass _all_ relevant properties through, so this kind of mistake won't happen again.
Fixes #8831.

Ensure `cache.broadcastWatch` passes all relevant `WatchOptions` to `cache.diff`

---

src/cache/index.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/__tests__/diffAgainstStore.ts
src/cache/inmemory/helpers.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/policies.ts
src/cache/inmemory/readFromStore.ts
src/cache/inmemory/types.ts
src/core/__tests__/QueryManager/index.ts

The `shouldCanonizeResults` helper function introduced in #8822 was defined in `inMemoryCache.ts` but also used in `readFromStore.ts`. Since these two modules already mutually import TypeScript types from each other, the addition of a concrete/value export caused Rollup to begin displaying a warning about the new dependency cycle:
```
dist/cache/index.js → dist/cache/cache.cjs.js...
(!) Circular dependency
dist/cache/inmemory/inMemoryCache.js -> dist/cache/inmemory/readFromStore.js -> dist/cache/inmemory/inMemoryCache.js
created dist/cache/cache.cjs.js in 271ms
```
Dependency cycles in JavaScript are generally harmless and often unavoidable, but we can simplify the work of bundlers like Rollup by eliminating the cycles that are avoidable (as this one is).

Refactor to avoid import cycle between `inMemoryCache.ts` and `readFromStore.ts`

---

CHANGELOG.md
src/cache/core/cache.ts
src/cache/core/types/Cache.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/inMemoryCache.ts

As reported in issue #8851 by @tm1000, PR #8826 (shipped in v3.4.14) was a breaking change for code expecting `cache.watches` to be restarted after `cache.reset()` is called.
This commit establishes a small but extensible `Cache.ResetOptions` API for the `cache.reset` method, which allows the handling of watches to be configured via `options.discardWatches`, which defaults to `false`, thus restoring the behavior of `cache.reset()` from before #8826.
If you need the behavior introduced by #8826, you can now opt (back) into that behavior by calling
```ts
cache.reset({ discardWatches: true })
```

Require `cache.reset({ discardWatches: true })` to clear `cache.watches`

---

src/errors/index.ts
src/link/error/index.ts

The problem:
Application-wide networkError error handler fails with error:
```
TS2322: Type 'Error | ServerParseError | ServerError | null' is not assignable to type 'Error | ServerParseError | ServerError | undefined'.   Type 'null' is not assignable to type 'Error | ServerParseError | ServerError | undefined'. 
```
Seems to be due to:
`ApolloError` networkError have `Error | ServerParseError | ServerError | null` type:
```ts
export declare class ApolloError extends Error {
message: string;
graphQLErrors: ReadonlyArray<GraphQLError>;
networkError: Error | ServerParseError | ServerError | null;
```
But the same networkError in ErrorResponse have `Error | ServerError | ServerParseError` type:
```ts
export interface ErrorResponse {
graphQLErrors?: ReadonlyArray<GraphQLError>;
networkError?: …
```

Align NetworkError and GraphQLErrors types

---

CHANGELOG.md
package.json
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useMutation.ts
src/react/types/types.ts

Some quick features we might shove into 3.5 release

---

CHANGELOG.md
src/utilities/globals/fix-graphql.ts

To import `graphql` (and its internal `instanceOf` function) for the first time with `process.env.NODE_ENV` safely polyfilled, PR #8347 selected a somewhat arbitrary export of the `graphql` package that uses `instanceOf`, specifically the `isType` function exported by [`graphql/type/definition`](https://github.com/graphql/graphql-js/blob/0c7165a5d0a7054cac4f2a0898ace19ca9d67f76/src/type/definition.ts#L70-L81).
As revealed by issue #8705, importing `isType` was a bad choice, since it depends on a bunch of other code within the `graphql` package, unnecessarily increasing minified+gzip bundle size by approximately **3.4kB**.
A better choice is the `Source` constructor, which is already imported thanks to other necessary imports, and also imports/uses `instanceOf`.

Avoid unnecessarily importing `isType` from `graphql` package

---

CHANGELOG.md
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/QueryManager/index.ts

Follow-up to PR #8852, inspired by discussion #8872 started by @KeithGillette. Depending on the discussion, we may need to make additional changes to align the various store-resetting/clearing operations, so I've left this PR as a draft for now.

Make `client.{reset,clear}Store` pass appropriate `discardWatches` option to `cache.reset`

---

CHANGELOG.md
src/cache/inmemory/policies.ts

Allows `FieldFunctionOptions` definition to be passed down to `FieldPolicy`, `FieldReadFunction` and `FieldMergeFunction` so it can be manually defined by the developer.
Would allow `apollo-client-helpers` plugin to specify TArgs for each `FieldPolicy`, [currently defined as `any`](https://github.com/VictorGaiva/graphql-code-generator/blob/816e93c05e5ea54cb7e5b57a84f1f9ee06912aad/packages/plugins/typescript/apollo-client-helpers/src/index.ts#L43).

Allow `FieldFunctionOptions` to be passed as Type Argument for `FieldPolicy`

---

docs/package-lock.json
docs/package.json
netlify.toml

Our docs `typedoc` version has fallen behind and has recently started throwing `Maximum call stack size exceeded` errors when trying to generate types via `npm run types`. This was likely caused by a recent `typescript` update (e.g. #8926), but regardless updating to a current version of `typedoc` fixes the issue. Note that the `typedoc` `--ignoreCompilerErrors` option was removed in version 0.20, so this commit also removes it from the docs scripts.

Update typedoc to fix "Maximum call stack size exceeded" errors

---

package-lock.json
package.json
src/__tests__/ApolloClient.ts
src/core/QueryManager.ts
src/link/core/types.ts
src/link/http/__tests__/HttpLink.ts
src/link/schema/index.ts
src/react/components/__tests__/ssr/server.test.tsx
src/react/hoc/__tests__/queries/errors.test.tsx
src/react/hoc/__tests__/ssr/server.test.tsx
src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap
src/utilities/common/errorHandling.ts
src/utilities/graphql/fragments.ts
src/utilities/graphql/transform.ts

Allows for `graphql@16` to be used with Apollo Client.
Fixes:
- https://github.com/apollographql/apollo-client/issues/8991

Upgrade GraphQL to 16

---

CHANGELOG.md
package.json
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts

Apollo Studio is relying on the identity of the `execute()` function of `useMutation()` to be the same in a couple places. This appears to have changed between 3.4 and 3.5. This PR restores the old identity behavior.

Fix useMutation returning different execute functions for the same options

---

package-lock.json
package.json
src/react/components/__tests__/client/Mutation.test.tsx
src/react/components/__tests__/client/Query.test.tsx
src/react/components/__tests__/client/Subscription.test.tsx
src/react/hoc/__tests__/client-option.test.tsx
src/react/hoc/__tests__/fragments.test.tsx
src/react/hoc/__tests__/mutations/queries.test.tsx
src/react/hoc/__tests__/mutations/recycled-queries.test.tsx
src/react/hoc/__tests__/queries/api.test.tsx
src/react/hoc/__tests__/queries/errors.test.tsx
src/react/hoc/__tests__/queries/index.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hoc/__tests__/queries/observableQuery.test.tsx
src/react/hoc/__tests__/queries/polling.test.tsx
src/react/hoc/__tests__/queries/reducer.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx
src/react/hoc/__tests__/queries/updateQuery.test.tsx
src/react/hoc/__tests__/shared-operations.test.tsx
src/react/hoc/__tests__/subscriptions/subscriptions.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useReactiveVar.test.tsx
src/testing/react/__tests__/MockedProvider.test.tsx
src/testing/react/__tests__/mockSubscriptionLink.test.tsx

In order to use `@testing-library/react` with React 18 you'll need to use the 13.x alpha. This PR is an intermediate step that updates `@testing-library/react` to the latest stable release.
Biggest change was required for 10.0.0 where we deprecated `wait` in favor of `waitFor`. Tests not having an explicit expectation on `wait` broke. Generally, `waitFor` should always contain a condition since the number of macro or microtask is not guaranteed.
There are still some occasional "missing act" warnings. Not sure what your policy on these warnings is.
/cc @brainkim

Update `@testing-library/react` to latest stable version

---

CHANGELOG.md
config/resolveModuleIds.ts

This reverts commit 60e18e95b366c845501fc30f5e607ab5bf9d2035 from PR #8396.
In theory, commit 60e18e95b366c845501fc30f5e607ab5bf9d2035 should have made it easier to consume `@apollo/client` ESM modules in a browser environment, by rewriting non-relative imported module identifiers like
```js
import { useState } from "react"
```
to
```js
import { useState } from "react/index.js"
```
effectively bypassing `react/package.json` and its `"main"` field (which is not understood by browsers). Of course, the `react` package doesn't actually export ESM modules, and therefore can't be used natively in the browser anyway, so the rewriting doesn't help in this case.
Not helping would be one thing, but unfortunately this change introduces more problems for bundlers that expect to find a `package.json` …

Revert `normalizeNonRelativeId` changes in `config/resolveModuleIds.ts`

---

.vscode/launch.json
CHANGELOG.md

Without this change having open e.g. `src/react/hoc/__tests__/mutations/queries.test.tsx` running "Jest Current File" from VSCode's "Run and Debug" would result in `/usr/bin/node ./node_modules/.bin/jest queries.test --config ./config/jest.config.js`. However, this would match multiple files (here `src/react/hoc/__tests__/mutations/recycled-queries.test.tsx` and `src/react/hoc/__tests__/mutations/queries.test.tsx`.
With this change we ensure that only a single file is run.

chore: Ensure only current file is run with VSCode debugger

---

package-lock.json
package.json
src/link/persisted-queries/__tests__/react.tsx
src/react/components/__tests__/client/Mutation.test.tsx
src/react/components/__tests__/client/Query.test.tsx
src/react/components/__tests__/ssr/getDataFromTree.test.tsx
src/react/components/__tests__/ssr/server.test.tsx
src/react/hoc/__tests__/queries/errors.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hoc/__tests__/queries/observableQuery.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx
src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
src/react/hoc/__tests__/ssr/server.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/react/ssr/RenderPromises.ts
src/react/ssr/__tests__/useLazyQuery.test.tsx
src/react/ssr/__tests__/useQuery.test.tsx
src/useSyncExternalStore.d.ts

This PR reimplements `useQuery()`/`useLazyQuery()` with the proposed `useSyncExternalStore()` API, in preparation for React 18.
One note, the peer dependencies are likely to be all busted.

Use `useSyncExternalStore()`

---

CHANGELOG.md
package.json
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts

“Fixes” https://github.com/apollographql/apollo-client/issues/8793
Let me know if you want less snarky unit test names

accept onError and onCompleted in the useMutation execution function

---

CHANGELOG.md
config/resolveModuleIds.ts

From `@apollo/client@3.5.0` until my recent PR #9073 (v3.5.3), non-relative imported module identifiers like `ts-invariant/process` were rewritten during the build process (during `npm run resolve`) to include a specific module with a file extension (not a directory), producing in this example `ts-invariant/process/index.js`.
That rewriting was the wrong choice in general (for example, it would rewrite `graphql` to `graphql/index.mjs`), so PR #9073 disabled the rewriting for all non-relative imports.
However, the specific replacement of `ts-invariant/process` with `ts-invariant/process/index.js` is still useful to prevent the strange webpack 5-specific error
```
The request 'ts-invariant/process' failed to resolve only because it was resolved as fully specified
```
which apparently …

Resolve `ts-invariant/process` module identifier again in `config/resolveModuleIds.ts`

---

CHANGELOG.md

In #8396 (first released in `@apollo/client@3.5.0-beta.0`), we adopted the Node.js [recommendation](https://nodejs.org/api/packages.html#determining-module-system) to specify `"type": "module"` in `package.json`, so all `.js` modules within the `@apollo/client` package will be interpreted (correctly) as ECMAScript modules. Since we also provide various CommonJS bundles for consumption by Node.js and older bundlers, those CommonJS bundles now have a `.cjs` file extension, rather than `.cjs.js`, so Node.js won't misinterpret them as ECMAScript modules.
Unfortunately, as I was first made aware by @SimenB in https://github.com/apollographql/zen-observable-ts/pull/156#issuecomment-931102197, switching to a `.cjs` file extension for CommonJS bundles can cause problems for React Native's Metro …

Provide React Native `.cjs` workaround in `CHANGELOG.md`

---

CHANGELOG.md
src/__tests__/__snapshots__/exports.ts.snap
src/link/batch-http/batchHttpLink.ts
src/link/http/__tests__/selectHttpOptionsAndBody.ts
src/link/http/createHttpLink.ts
src/link/http/index.ts
src/link/http/selectHttpOptionsAndBody.ts

As pointed out by @SimenB in https://github.com/apollographql/apollo-client/pull/8699#discussion_r754123804, adding an additional positional argument (`printer: Printer`) to the publicly-exported `selectHttpOptionsBody` helper function was a breaking change for direct consumers of that function. This PR restores `selectHttpOptionsBody` to its previous signature (defaulting to `defaultPrinter`), using the new `selectHttpOptionsBodyInternal` function for the bulk of the implementation.

Undo breaking change to `selectHttpOptionsBody` signature

---

docs/package.json
netlify.toml

For the time being, the documentation team is sticking to npm@6 for managing the `docs/` directories of our various projects, which mostly entails sticking with `lockfileVersion:1` in `docs/package-lock.json`, instead of `lockfileVersion:2` (like `./package-lock.json`).
Apollo Client itself welcomes contributors using the latest versions of Node.js and npm, so we've switched to `lockfileVersion:2` in the root `package-lock.json` file, even defending it from reversion with checks like #9068.
However, when Netlify attempts to run npm@6 in the root directory of the `apollo-client` repository, the newer `lockfileVersion:2` in `package-lock.json` causes failures on `npm install` like [this one](https://app.netlify.com/sites/apollo-client-docs/deploys/619d49161cd5b80007973178).
~Reading over PR …

Prevent npm@6-related Netlify failures on `release-3.6` branch

---

docs/source/caching/cache-interaction.mdx

The type of `updateQuery`'s update function is:
```ts
(data: TData | null) => TData | null | void
```
Which (I think) means that it shouldn't return `{ data: { todos: [...] } }` but just `{ todos: [...] }`.
Basically, the return signature in the `InMemoryClass` API docs is the correct one: https://www.apollographql.com/docs/react/api/cache/InMemoryCache/#updatequery.

Fix return of updateQuery's update function

---

src/react/components/__tests__/client/Query.test.tsx
src/react/hoc/__tests__/queries/index.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useMutation.ts
src/react/hooks/useQuery.ts

Review by commit.
Moves a bunch of logic directly in the render function where side effects shouldn’t be done, but we’re doing it because `useEffect()` is just not to be trusted.
Fixes #9111, #9135

3.5 hotfixes

---

package-lock.json
package.json

We use [`recast`](https://www.npmjs.com/package/recast) in our build scripts (specifically [`config/processInvariants.ts`](https://github.com/apollographql/apollo-client/blob/main/config/processInvariants.ts), [`config/resolveModuleIds.ts`](https://github.com/apollographql/apollo-client/blob/main/config/resolveModuleIds.ts), and some of our [codemods](https://github.com/apollographql/apollo-client/tree/main/scripts/codemods), to parse and transform JavaScript without altering the formatting of unmodified code.
I'm the author of `recast` and its underlying library [`ast-types`](https://www.npmjs.com/package/recast), and I've recently been updating dependencies and implementing new type definitions and pretty-printer cases for AST node types added to TypeScript/Flow/Babel in the past few …

Update `recast` AST transform tool to version 0.21.0

---

docs/source/data/queries.mdx

Was brushing up on the basics and noticed that the docs say that if there's an error, the `error` prop returned by `useQuery` is set to `true` which isn't correct I believe. `error` is set, but to an informative object, not a Boolean value.

Correct the type of `error` in "Inspecting error states"

---

package-lock.json
package.json
src/utilities/globals/global.ts

PR https://github.com/apollographql/invariant-packages/pull/233 took care of `Function(...)` usage within the `ts-invariant/process` package, so this PR updates `ts-invariant` to the latest version.
Additionally, there was one similar bit of code using `Function(...)` within the `@apollo/client` package, so this PR cleans that up in way similar to the `ts-invariant` changes.
Unless I'm mistaken about the cause of #9128 (static misanalysis reporting false positives), this PR should fix that issue.

Obfuscate `Function(...)` fallback to thwart static misanalysis

---

CONTRIBUTING.md

Removed from ` contributing.md ` `npm run watch` because `watch` is removed from `package.json`.

remove documentation on npm run watch since watch is no longer in package.json

---

docs/source/api/link/apollo-link-rest.md

I'm trying to work out how to do something complex, and found this language alienating because being new to Apollo/Rest Link, there's nothing straightforward about it 😅
The paragraph works fine without it so I propose to remove it entirely.
- [✔] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [✔] Make sure all of the significant new logic is covered by tests

Remove unnecessary language

---

CHANGELOG.md
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

Fixes regression caused by:
https://github.com/apollographql/apollo-client/commit/f1a9770b2b6f0e30fb89424eea0306afd4f48216#diff-fb7fa652de6d84c08b87344a06a4d120b664c6e8bf491d16575794c755141477R136-R142
I tested this on 3.4.0 and it works as expected. This broke on 3.5.x. I think it's also related to [this issue](https://github.com/apollographql/apollo-client/issues/9111) but for queries.
I also wrote the tests and confirmed that tests were failing prior to my change.

fix: onCompleted not updating regression

---

CHANGELOG.md
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

This PR is intended to solve the issue of default options in client not setting the correct fetch policy in useQuery.
when user doesn't set a fetch policy option in useQuery, it is defaulted to `cache-first` before it attempts to use the default fetch policy that is set in by the client.
the fetch policy hierarchy currently is:
1. user define fetch policy as parameter in useQuery
2. default to `cache-first` in useQuery
_it completely ignores default fetch policy from the client_
with this PR it will be:
1. user define fetch policy as parameter in useQuery
2. user define fetch policy as default value in client
3. default to `cache-first` in useQuery
fixes apollographql/apollo-client#9105
fixes apollographql/apollo-client#2555

Fix `defaultOptions` not being used by `useQuery`

---

src/react/hooks/useLazyQuery.ts
src/react/types/types.ts

I forked the repo because I was going to improve the error message of MockProvider,
but I realized that the latest version will give enough details, so I do not need to improve anything.
I walk around and I found one TODO, so I thought I will help with that.

Correct useLazyQuery types

---

src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/useSubscription.ts

This bug triggered a regression in our application after updating from Apollo Client 3.3.21 to 3.5.7.
The unit test testing the `skip` flag wasn't actually working correctly. It didn't fail when `skip` was set to `false`.
I've updated it to make sure no subscription is being executed by spying on `onSetup` callback of the link instead of the `onSubscriptionData` one on the hook which isn't called anyway since `simulateResult` isn't called as part of the test. I also extended the test to make sure no subscription is being executed when variables are changing.
The final version of the test was verified to fail on `main` branch.
I wasn't sure if I shall extend the existing test or add a new one. Let me know if a new test case for the update case is preferred.

Fix `useSubscription` executes skipped subscription if input changes

---

src/core/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx

Fixes #8715, fixes #9169, fixes #9291, fixes #9334 (dupes).
Introduced in #8642.

Fix partial data appearing in `useQuery()` when `notifyOnNetworkStatusChange` is `true`.

---

CHANGELOG.md
config/entryPoints.js
docs/gatsby-config.js
docs/source/api/link/apollo-link-subscriptions.md
docs/source/api/link/apollo-link-ws.md
docs/source/api/react/hoc.mdx
docs/source/data/subscriptions.mdx
package-lock.json
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/__tests__/exports.ts
src/link/subscriptions/__tests__/graphqlWsLink.ts
src/link/subscriptions/index.ts
src/link/ws/__tests__/webSocketLink.ts

Apollo Client currently contains `WebSocketLink` in
`@apollo/client/link/ws` which uses the `subscriptions-transport-ws`
library. That library is no longer actively maintained, and there is an
improved fork called `graphql-ws`.
The two libraries use different protocols so a different client link is
required for `graphql-ws`. (While the WebSocket protocol does allow for
subprotocol negotiation, neither server implementation supports this in
a practical way.)
This PR adds a new link `GraphQLWsLink` in
`@apollo/client/link/subscriptions`. Its constructor arguments are the
same as the `createClient` function in `graphql-ws` (or it can take a
`Client` object returned from that function), and you need to install
the optional peer dep `graphql-ws` instead of
`subscriptions-transport-ws`. Once …

New GraphQLWsLink for graphql-ws subscriptions library

---

src/link/batch-http/__tests__/batchHttpLink.ts
src/link/batch/__tests__/batchLink.ts
src/link/batch/batching.ts

After an operation has been subscribed to, and so queued, it is possible
to unsubscribe from it, and it will be removed from the queue.
Unsubscribing will not impact the debounce, so other operations, if any, will
not be delayed by an unsubscription.
If a batch of operation is already in flight, and all operations are unsubscribed
then the entire XHR will be cancelled. If only some operations are unsubscribed
the XHR will be left untouched.

Batch link can cancel operations that are in queue or in flight

---

package-lock.json
package.json
src/core/ObservableQuery.ts
src/react/components/__tests__/client/Mutation.test.tsx
src/react/components/__tests__/client/Query.test.tsx
src/react/components/__tests__/ssr/getDataFromTree.test.tsx
src/react/components/__tests__/ssr/server.test.tsx
src/react/hoc/__tests__/queries/errors.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hoc/__tests__/queries/observableQuery.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx
src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
src/react/hoc/__tests__/ssr/server.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/useApolloClient.ts
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/react/hooks/useSubscription.ts
src/react/ssr/RenderPromises.ts
src/react/ssr/__tests__/useLazyQuery.test.tsx
src/react/ssr/__tests__/useQuery.test.tsx
src/react/types/types.ts

We are considering an accelerated release schedule for Apollo Client v3.6, which will include low-risk/additive changes from `release-3.6`, while postponing experimental changes depending on React 18 (which has not been finalized) to the next minor release, v3.7. This PR represents the current `release-3.6` branch with PR #8785 reverted (see below for details). Specifically, this PR reverts commit 7f0d459c7b3b94c5de1561433c006a6efa017007 (#8785) and follow-up commit 5328dae6756fab6f8f27e8855cfb7ad5932ec03c.
If/once this PR looks good (note: we can manually drop any changes we don't like), we can merge it into `release-3.6`, then create a new `release-3.7` branch from `release-3.6`, and cherry-pick the inverse of this commit onto that new branch, effectively recreating the …

Temporarily revert `useSyncExternalStore` changes (#8785).

---

CHANGELOG.md
config/entryPoints.js
docs/gatsby-config.js
docs/source/api/link/apollo-link-subscriptions.md
docs/source/api/link/apollo-link-ws.md
docs/source/api/react/hoc.mdx
docs/source/data/subscriptions.mdx
package-lock.json
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/__tests__/exports.ts
src/link/subscriptions/__tests__/graphqlWsLink.ts
src/link/subscriptions/index.ts
src/link/ws/__tests__/webSocketLink.ts

This PR back-ports the new `GraphQLWsLink` contributed by @glasser in #9369 for release in the next Apollo Client patch version, 3.5.10.

Backport PR #9369 to `main` branch for `GraphQLWsLink` and `@apollo/client/link/subscriptions`

---

docs/source/migrating/apollo-client-3-migration.mdx

Added a section to the `@apollo/react-hooks` section that details two breaking changes that I encountered whilst upgrading a v2 app to v3. I believe calling out these changes will save other developers a lot of time debugging apps after they have migrated to v3.
~- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)~
~- [ ] Make sure all of the significant new logic is covered by tests~

Added "Breaking Changes" to @apollo/react-hooks section

---

CHANGELOG.md
package.json
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/options.ts
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/react/types/types.ts

A pretty serious limitation of the `useQuery(query, options)` API is that it encourages passing a fresh bag of `options` as the second parameter every time the component (re)renders, potentially overwriting previous options from previous renders, with no way to tell which options should be taken merely as default values and which should override existing options. This ambiguity becomes especially problematic when options like `options.fetchPolicy` are updated elsewhere, but that work is undone the next time `useQuery(query, { fetchPolicy: <original policy> })` is called:
```ts
useQuery(QUERY, {
// Was this just a default value, or should it become the new fetch policy?
// With the current useQuery API, there's no safe way to guess!
fetchPolicy: "cache-and-network",
})
```
A more minor …

Allow passing  function to `useQuery` for finer-grained `options` control

---

CHANGELOG.md
package.json
src/__tests__/client.ts
src/__tests__/fetchMore.ts
src/core/ObservableQuery.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts

This PR implements a variation on the idea I sketched in https://github.com/apollographql/apollo-client/issues/6916#issuecomment-901466918, ~without doing too much violence to our existing test suite~. I did end up making a number of adjustments to tests that this PR initially caused to fail, but I'm confident they are nonviolent (that is, they test the same things in a more robust/realistic way).
Previous attempts to solve #6916 stalled in part because the number of test failures felt indicative of potential backwards incompatibility. Now that I've worked through all the failing tests in this PR, I believe they are mostly just fragile/flaky/timing-sensitive tests, though of course it would be great to validate that hope with beta testing.
In short, `fetchMore` should (now) be able to …

Avoid full reapplication of `cache-and-network` and `network-only` fetch policies after successful `fetchMore`

---

CHANGELOG.md
src/__tests__/client.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/fetchPolicies.ts
src/core/watchQueryOptions.ts
src/react/components/__tests__/client/Query.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/index.ts
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/react/types/types.ts

Building on #9563 and taking inspiration from #9459, this refactoring allows `useLazyQuery` to use the same `InternalState` machinery as `useQuery` (introduced in #9459), and fixes issue #9375 by making the execution function call `reobserve` (which respects the current `fetchPolicy`) instead of `refetch` (which always triggers a network request).

Refactor `useLazyQuery` to reuse `useInternalState` and make execution function call `reobserve` instead of `refetch`

---

CHANGELOG.md
src/utilities/graphql/__tests__/transform.ts
src/utilities/graphql/transform.ts

Let `addTypenameToDocument` take any `ASTNode` (including `DocumentNode`, as before)

---

package.json
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/watchQueryOptions.ts
src/react/components/__tests__/client/Mutation.test.tsx
src/react/components/__tests__/client/Query.test.tsx
src/react/hoc/__tests__/queries/errors.test.tsx
src/react/hoc/__tests__/queries/index.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts
src/react/ssr/RenderPromises.ts
src/react/types/types.ts

This PR builds on #9508, fixing the unexpected frame by transitioning to a `loading: true` result synchronously when variables change or the query is refetched.
Since we do not want to commit to making any network requests synchronously during rendering, I have come up with a new way to block all network requests, by passing a `fetchBlockingPromise: Promise<boolean>` option that intercepts a part of the request pipeline that is already safely asynchronous.
As a happy side effect, this `fetchBlockingPromise` technique should also prevent making any network requests for extra `ObservableQuery` objects created during development when using React's `<StrictMode>`, since the extra component renders are never mounted, and thus `useEffect` never fires, leaving the `fetchBlockingPromise` …

Fix extra `useQuery` result frames

---

package-lock.json
package.json

This should help with recent failures of dependency update PRs ([example](https://github.com/apollographql/apollo-client/pull/9575#issuecomment-1086610884)), by allowing `graphql@16` to be installed without violating the `peerDependencies` of the `@graphql-typed-document-node/core` package.
Adding support for `graphql@16` was the main/only feature of [`@graphql-typed-document-node/core@3.1.1`](https://github.com/dotansimha/graphql-typed-document-node/releases/tag/core%40v3.1.1). This new version is patch-compatible with our `"@graphql-typed-document-node/core": "^3.1.0"` constraint in `package.json`, but our `package-lock.json` file was enforcing the older 3.1.0 version, leading to package installation failures in CI.

Update `@graphql-typed-document-node/core` to version 3.1.1

---

package-lock.json
package.json
src/link/subscriptions/__tests__/graphqlWsLink.ts

Instead of merging one Renovate update PR after another, fixing merge conflicts and rerunning tests with each commit (leading to lots of unnecessary CI time), I'm going to try batching the updates in this PR.

Batched Renovate updates

---

src/react/hooks/useQuery.ts

This PR fixed [https://github.com/apollographql/apollo-client/issues/9623](#9623) since `useSyncExternalStore` on React 18 required 3rd parameter (getServerSnapshot) must not be undefined while on server-side rendering.
At least it eliminates crashes on NextJS v12 & React v18. I have no idea what to do better on this.
#9623

fix Missing getServerSnapshot on React 18 and Next 12

---

docs/source/api/link/apollo-link-ws.md
docs/source/data/subscriptions.mdx

The [`SubscriptionClient` constructor](https://www.npmjs.com/package/subscriptions-transport-ws) accepts a string for the subscription URL as its first argument. This PR updates our code snippet examples to match that behavior.

Fix code snippets for SubscriptionClient

---

CHANGELOG.md
src/link/persisted-queries/__tests__/index.ts
src/link/persisted-queries/index.ts

This MR fixes an issue with persistedQueries.
Servers can contain graphQLErrors, but was missing in persistedQueries. If a server returned a 400 with a 'PersistedQueryNotFound' error message, it would be treated as a networkError and disable persistedQueries.

Fix persistedQueries to pull graphqlErrors from networkErrors

---

CHANGELOG.md
src/react/hooks/useQuery.ts
src/utilities/common/mergeOptions.ts

When implementing the new `useQuery(query, { defaultOptions })` functionality in #9563, I fell under the (thankfully mistaken) impression that I needed to handle all defaulting of `WatchQueryOptions` within the `createWatchQueryOptions` method of the `InternalState` class that `useQuery` uses internally.
This PR demonstrates we can avoid that computation entirely, and rely instead on existing defaulting mechanisms (in [`watchQuery`](https://github.com/apollographql/apollo-client/blob/release-3.6/src/core/ApolloClient.ts#L291-L293)) to do the same job. The trick is to use the `defaultOptions` from `useQuery(query, { defaultOptions })` only when we first create the `ObservableQuery` (that is, only when we call `client.watchQuery`). That way, the `defaultOptions` are only relevant once, and …

Drastically simplify `useQuery` default options processing

---

src/__tests__/fetchMore.ts
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts

This PR started as a regression test for PR #9665, but one test led to another, and I found/fixed a few bugs along the way.
Issues potentially solved:

Test `skip: true` and `useLazyQuery` with `options.defaultOptions`

---

CHANGELOG.md
package-lock.json
package.json

Includes https://github.com/apollographql/invariant-packages/pull/284, fixing https://github.com/apollographql/invariant-packages/issues/279.
These warnings have been causing red herrings in (probably) unrelated issues, most recently in #9662, so it makes sense to fix this problem even if it's arguably harmless.

Update `ts-invariant` to version 0.10.2 to fix source map warnings

---

CHANGELOG.md
src/react/hooks/useQuery.ts
src/react/ssr/__tests__/useQuery.test.tsx

Test borrowed from issue #9658, thanks to @nathanmarks.
I'm expecting this test to fail at first.

Fix failing regression test for skipped SSR `useQuery` stuck in standby

---

docs/source/api/core/ApolloClient.mdx
src/core/ApolloClient.ts

A colleague has been profiling one of our apps and has found that setting `assumeImmutableResults: true` has a positive impact to performance. We noticed that this option is not in the documentation so I opened this PR. Is this intentionally undocumented? 
I also wonder, if using `InMemoryCache` is there any reason to not set `assumeImmutableResults: true`? Let me know if there's something obvious that I'm missing. Thanks!

Add missing assumeImmutableResults documentation

---

CHANGELOG.md
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts

This PR should fix the following issues:
As justification for #9669, none of our [error policies](https://www.apollographql.com/docs/react/data/error-handling/#graphql-error-policies) say anything about throwing errors; they just control whether/when the `result.data` and/or `result.error` properties will be defined. Throwing an error is similar to the default policy, `none`, but needlessly discards result properties other than `result.error`. If you want a rejected `Promise`, attach a `then` callback and throw `result.error` when it's defined.
I'm giving this justification because I am aware it stands in conflict with an issue we recently "fixed" (perhaps a bit too hastily): https://github.com/apollographql/apollo-client/issues/9142#issuecomment-1118972947

Prevent `useLazyQuery` from making duplicate requests when execution function first called

---

CHANGELOG.md
src/react/hooks/useQuery.ts
src/react/ssr/__tests__/useQuery.test.tsx

Fix issue with useQuery returning loading state in SSR with skip
Fixes https://github.com/apollographql/apollo-client/issues/9096

Fix issue with `useQuery` returning `loading: true` state during server-side rendering with `skip: true`

---

docs/source/caching/cache-field-behavior.mdx

The official documentation lacked an example and description of how to handle multiple parameters within the read() function when defining typePolicies. 
The proposed change addresses that by both showcasing that it is possible to handle multiple parameters and how to do so (using a syntax that was previously undocumented). 
I struggled for a while when it came to understanding how to handle this use case, so I am more than happy to share my findings while improving the docs with the hope of helping others that might find themselves in the same situation. 😃

Add description & example of how to handle multiple parameters in read() when declaring typePolicies.

---

docs/source/data/queries.mdx

This PR:
- takes into the consideration the changes mentioned in this PR https://github.com/apollographql/apollo-client/pull/7287. 
- runs prettier for some formatting  inconsistencies 😎

Poll interval docs update

---

docs/source/api/link/apollo-link-rest.md

Fix markdown bug where the `|` in the type is parsed as a table cell boundary.

[docs] Fix markdown bug in rest link

---

CHANGELOG.md
package-lock.json
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/react/hooks/useQuery.ts
src/react/hooks/useSyncExternalStore.ts
src/utilities/common/__tests__/canUse.ts
src/utilities/common/canUse.ts

This internalization solves several problems with the official [`use-sync-external-store/shim`](https://www.npmjs.com/package/use-sync-external-store) package:
- We can ensure `useLayoutEffect` is called only on the client, eliminating noisy warnings
- We can use our own internal mechanisms like `__DEV__` to gate development-only code
- We don't have to use an `Object.is` polyfill because we know our snapshots won't need it
- Because the `useSyncExternalStore` shim is now implemented/exported using ECMAScript module syntax, issues like #9670 should be resolved
If there was some way to selectively import the different client/server versions of the `useSyncExternalStore` hook from `use-sync-external-store/shim`, I would be happy to keep using that package, but the difficulty of making the …

Internalize `useSyncExternalStore` shim, for more control than `use-sync-external-store` provides

---

CHANGELOG.md
src/utilities/observables/Concast.ts
src/utilities/observables/__tests__/Concast.ts

Thanks to @andreialecu's investigations in #9690, I believe we may be close to solving issue #7608 once and for all! 🥳 
I can say this with confidence because this PR completely removes the pesky `Observable cancelled prematurely` error from the `Concast` implementation, so it should never again reject `concast.promise`.
Instead of terminating remaining `cleanup` observers using `this.handlers.error(...)`, I'm now using `this.handlers.complete()` (which required fixing another bug that prevented unsubscribing after `complete`).

Guarantee `Concast` cleanup without `Observable cancelled prematurely` rejection

---

docs/source/data/mutations.mdx

In the CodeSandbox example of "Mutations in Apollo Client", the correct variable name is "type" instead of "text".
https://codesandbox.io/s/mutations-example-app-final-tjoje

Correct GraphQL variable name "text" to "type"

---

CHANGELOG.md
config/helpers.ts
config/rollup.config.js
package-lock.json
package.json

We use the `.cjs` file extension for our CommonJS bundle entry points (such as `@apollo/client/core/core.cjs`) to indicate to Node.js that `"type": "module"` in `@apollo/client/package.json` does not apply to those files.
Without additional configuration of its Metro bundler, React Native refuses to resolve `.cjs` files by default, but it will attempt to append various file extensions, including the (relatively) React Native-specific ending `.native.js`. By providing a `dist/**/*.cjs.native.js` file for every existing `dist/**/*.cjs` file we ship, React Native should always have a safe fallback to find the right code.
If this works, it will completely supersede/obviate the manual advice involving `metro.config.js` we added to `CHANGELOG.md` in #9084.
There is some risk of the dual package …

Help React Native import `@apollo/client/main.cjs` and other CommonJS bundles

---

package.json
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/react/hoc/__tests__/queries/skip.test.tsx
src/utilities/observables/Concast.ts
src/utilities/observables/__tests__/Concast.ts

Replace `concast.cleanup` method with simpler `concast.beforeNext` API

---

CHANGELOG.md
package.json
src/react/hooks/useSubscription.ts

Fix #9664
React18 automatically unmounts and remounts components in StrictMode. When React remount a component, the previous state is restored. However, if the previous state is reused, the subscription will not work.
So we should recreate the necessary object when React remounts the component.
For more information on why we should not reuse the object, see https://github.com/apollographql/apollo-client/issues/9664#issuecomment-1123480304
---
Currently, Apollo Client includes React17 in its devDependencies.
I have made this fix and confirmed that it works in a sample application.
At this time, I changed Apollo Client's React version to 18.
But I confirmed that some unrelated tests failed due to the impact of updating React to 18, so I did not commit package.json.
Therefore, I have not …

Fix useSubscription bug in React v18 StrictMode (#9664)

---

CHANGELOG.md
src/utilities/policies/pagination.ts

This handles an edge case reported https://github.com/apollographql/apollo-client/issues/8708, where missing `incoming` argument is `null` or an empty value that throws TypeError when fetch call returns an error.

fix(utilities): missing incoming field handling in offsetLimitPagination

---

CHANGELOG.md
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

Based on @ValentinH's description in issue #9733, I believe we can preserve the `previousData` property even when the client or query given to `useQuery` change. Such changes are drastic enough to warrant a whole new `InternalState` object, but that doesn't mean we have to throw away everything from the old `InternalState` object (if we have one).

Preserve `previousData` even when different client or query passed to `useQuery`

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx

~This failing test demonstrates issues #9671 and #9736.~
This PR fixes a regression reported in issues #9671 and #9736, which first officially shipped in `@apollo/client@3.6.0`, or unofficially in `@apollo/client@3.6.0-beta.11`, due to my commit 8903456a2540d71e1825e78a976fa9fbf1e9711c in PR #9563.
While it might seem like a good idea to merge individual `variables` when calling `useQuery(query, { variables })` with different/new `variables`, wholesale replacement is more powerful, because it allows removing some of the variables rather than only adding new ones.
Also, replacement still allows you to spread the existing `...observable.variables` when passing the new variables, so the merging behavior is still possible. In the other direction (in the always-merge approach accidentally …

Restore pre-v3.6 `variables` replacement behavior of `ObservableQuery#reobserve` method

---

CHANGELOG.md
package.json
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts

fixes #9714
fixes #9493
Related to #9111
Since 3.5.0 there's been a bug with the `useMutation` hook from this [PR](https://github.com/apollographql/apollo-client/pull/8596/files#diff-12d1e8016a676839edfe21e2917bf5acfae3f2bb817955e21394bf88a9fd937cR95) that has been preventing us from upgrading to the latest version. 
Currently, `onCompleted` and `onError` are stale and cannot be updated while a mutation is executing. See [here](https://github.com/apollographql/apollo-client/issues/9714#issuecomment-1126292437) for example on how to reproduce this issue.
The reason for this is that `useMutation` invokes `onCompleted` and `onError` via `baseOptions` rather than directly from the `ref.current`. Due to this, it doesn't have the latest copy of the callbacks once the operation is complete.

Fix bug where onCompleted and onError are stale for useMutation. onCompleted and onError could not be changed while a mutation is executing.

---

CHANGELOG.md
src/cache/inmemory/readFromStore.ts
src/utilities/common/mergeDeep.ts

Issue #9735 appears to be due to a bug I introduced in my commit 756ab87e01e8d48eab99d82b4806f3fdefb5bf70 in PR #8734. This PR takes us (partially) back to the way things worked before that commit.
I believe I've found two complementary ways to fix this problem:
> #### [Stop using shared `DeepMerger` in `ReadContext` for `executeSelectionSet`](https://github.com/apollographql/apollo-client/pull/9742/commits/fc4a5670617399a21fde2e09132f73df2ce12bee)
>
> Premature optimization has a bad reputation already, but you can add this PR to the mountain of evidence in its disfavor.
> #### [Avoid using `Object.isFrozen` to prevent dev/prod differences](https://github.com/apollographql/apollo-client/pull/9742/commits/debe124b15dab9408b3ec431eeff0d18fc5d6009)
>
> If you revert the previous commit and …

Restrict `DeepMerger` mutable object reuse to fix subtle production-only bug

---

CHANGELOG.md
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/useLazyQuery.ts

Merge `variables` from original `useLazyQuery(query, { variables })` with `variables` passed to execution function

---

CHANGELOG.md
package.json
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/useQuery.ts

After implementing PR #9758, I noticed that `useLazyQuery` was unable to see/use any `defaultOptions.variables` passed to `useLazyQuery(query, { defaultOptions: { variables }})` (a feature introduced by PR #9563), because the `defaultOptions` only mattered when the `ObservableQuery` was first created with `client.watchQuery` (see #9665), and not when the `useLazyQuery` execution function is later called. This PR fixes that oversight, allowing `useLazyQuery` to benefit from `options.defaultOptions.variables`, and also ensures global `client.defaultOptions.watchQuery.variables` are merged at the same time.

Allow `useLazyQuery(query, { defaultOptions })` to benefit from `defaultOptions.variables`

---

docs/source/data/error-handling.mdx

Steps to reproduce
1. go to this page: https://www.apollographql.com/docs/react/data/error-handling/
2. try to expand the expansion panels 
This PR fixes a problem where the expansion panels in this docs page wouldn't expand. There seemed to be an old import reference to a deprecated component which might have been impacting the other components on this page.  The link chain code seemed to be referencing what is [documented here. ](https://www.apollographql.com/docs/react/api/link/introduction/#providing-to-apollo-client). So I just added that code in manually.
Also it seems we no longer need an important statement for components, based on this section of [docs readme](https://github.com/apollographql/docs#no-more-component-imports). 
The `Linkedchain` component no longer seems to be …

fixes expansion panel

---

CHANGELOG.md
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts

This should fix #9804 and I've also added tests to cover this use case. Thank you

fix: fixes FieldFunctionOptions return incorrect variables

---

CHANGELOG.md
config/helpers.ts
config/rewriteSourceMaps.ts
config/rollup.config.js

Fix the build config to work on Windows. 
The changes to `rollup.config.js` resulted from this discussion (almost a year ago!): https://github.com/apollographql/apollo-client/pull/8341#discussion_r657514329
The changes to `helpers.ts` and `rewriteSourceMaps.ts` were needed because the `glob` package no longer supports backslashes as path separators in v8.0: https://github.com/isaacs/node-glob/blob/main/changelog.md#80

Fix build config to work on Windows

---

CHANGELOG.md
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

Changed returned `called` value of `QueryResult` to be false, when
the `skip` parameter of `QueryHookOptions` is set to true. Otherwise,
`called` value should return true like it used to do by default.
`useQuery` [result documentation](https://www.apollographql.com/docs/react/data/queries/#called) states that `called` value should be `true` only if the query has been executed. Currently, when `useQuery` is called with option `{ skip: true }`, the value of `called` remains `true`, even though the network request hasn't been done. This was discussed in https://github.com/apollographql/apollo-client/issues/7931.
This Pull Request changes value of `called` to be based on the `skip` option - if the option was set to `true`, the `called` value will be set to `false`, which should work as …

Fix: useQuery returns called value based on skip option.

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/core/__tests__/QueryManager/index.ts

It makes sure that after a ObservableQuery is reboserved (e.g. variables are changed), it unsubscribes from stale connections (those using old variables) so they can be cancelled by the browser.
Problem example: Use `watchQuery` with an interactive `searchValue` as input. When the user types too fast and the query take longer than the debounce limit (300ms), apollo client makes new connections to the bakend with the new `searchValue`. However old connections, which are a burden to the backend, are not aborted.
Fixes #9532

fix: abort stale connection on reobserve (#9532)

---

docs/source/caching/cache-configuration.mdx

Removes the mention that this API is deprecated as we decide to not deprecate it at this time.

removes deprecation language

---

CHANGELOG.md
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/fetchPolicies.ts
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/utilities/observables/Concast.ts

Fixes issue #9765, judging by the [reproduction](https://github.com/apollographql/apollo-client/issues/9765#issuecomment-1153882328) provided by @Titozzz.
It may be worth noting that `skip: true` and `fetchPolicy: "standby"` are intended to be essentially synonymous, which is why I sometimes mention both together (like "standby/`skip:true`").

Leave `fetchPolicy` unchanged when `skip: true` (or in standby) and `nextFetchPolicy` is available

---

CHANGELOG.md
package.json
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

As described in #9794, calling a setState function (or dispatching a redux action) from inside of `onCompleted` will sometimes cause React errors to be printed to the console. This appears to be due to `onCompleted` being called during the render phase if the result is available in the cache. This PR delays execution of `onCompleted` and `onError` using `setTimeout` in order to fix this error. A new test was added which will fail without this change.
Fixes #9794

Delay execution of callback functions to fix React errors

---

docs/source/api/link/apollo-link-error.md
docs/source/data/error-handling.mdx

This PR removes two identical sections on ignoring errors in both the [Error Link](https://www.apollographql.com/docs/react/api/link/apollo-link-error/#ignoring-errors) and [Error Handling](https://www.apollographql.com/docs/react/data/error-handling/#ignoring-errors) docs as ignoring errors by setting `response.errors = null;` is no longer a recommended practice.
Closes https://github.com/apollographql/apollo-client/issues/6758

Remove Ignoring errors sections in link and error handling docs.

---

docs/source/development-testing/testing.mdx

This PR updates the Apollo Client testing docs by removing references to [`react-test-renderer`](https://reactjs.org/docs/test-renderer.html) in favor of [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/), [the UI testing library recommended in the official React docs](https://reactjs.org/docs/testing.html#tools). The goal is to improve the readability of our example tests while ensuring they pass, ideally without emitting any warnings.
These changes were the outcome of a quick look at https://github.com/apollographql/apollo-client/issues/9887: copying + pasting one of the tests from our current docs results in a warning which may cause some confusion. Other tests outright fail when copy + pasted, like the one in [Testing the Success …

Updates testing docs to use Testing Library

---

docs/source/api/cache/InMemoryCache.mdx

Closes https://github.com/apollographql/apollo-client/issues/7862
From the above issue:
> Omitting the id is like calling cache.modify({ id: "ROOT_QUERY", fields }), since ROOT_QUERY happens to be the hard-coded ID of the root query singleton object.
ID isn't a required parameter for `cache.modify`, this updates the documentation to reflect that.

Clarify that id is optional on queries in cache.modify documentation

---

src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts

This PR adds checks in two places inside of `useMutation` to verify that the component is mounted before setting state with `setResult`, which fixes https://github.com/apollographql/apollo-client/issues/9858. ~The code changes are trivial, and while I initially thought it might be possible to add some test coverage for this minor change, that's proven more difficult than anticipated.~ (see edit below)
When initially calling `createTodo` in my test component's cleanup function, I was not seeing the expected React error re: setting state on an unmounted component, but I did see the error when I called `reset` after `unmount` (which was also calling `setResult` without checking the `isMounted` boolean).
~It looks like I'm at an impasse when it comes to making assertions against component …

Add defensive isMounted checks before setting state via useMutation Hook

---

docs/source/data/refetching.mdx

onQueryUpdate callback requires the `result` and ` complete` fields. However, those fields are not defined in the callback function in the documentation.

Add onQueryUpdate missing parameters

---

package-lock.json
package.json
src/link/persisted-queries/__tests__/index.ts
src/link/persisted-queries/__tests__/react.tsx

This PR removes `jest-fetch-mock` in two test files, and from package.json, and replaces it with `fetch-mock` which we are using elsewhere. See comment https://github.com/apollographql/apollo-client/pull/9768#issuecomment-1186171304.
Closes https://github.com/apollographql/apollo-client/issues/9927.

Remove jest-fetch-mock in favor of fetch-mock, update tests

---

netlify.toml

Fixes https://github.com/apollographql/apollo-client/issues/9947
It turns out that since we were running `npx typedoc` to generate the source for the ApolloClient API ref, it started building them using the latest version of `typedoc`, which introduced some breaking changes to the format that was produced.
Now we specify `typedoc@0.22` to ensure we get the v0.22 format that our docs framework expects.

Pin TypeDoc version in Netlify command

---

netlify.toml
package-lock.json
package.json

This change fixes the URLs that show up in the API reference. The Netlify build directory, `build/repo` was being included in the filepaths of modules. For some reason, installing `typedoc` as a local dependency, rather than using it with `npx` fixes this.

Fix TypeDoc generated file paths

---

docs/source/data/subscriptions.mdx

Adds explicit clarification that we don't support subscriptions polling the client state. See the long-open issue https://github.com/apollographql/apollo-client/issues/5322 for more information.

Quick doc change to clarify subscriptions don't work in client schema

---

.npmrc
renovate.json

This PR updates `renovate.json` to ignore testing-related deps for React 17 as well as adding an `.npmrc` with `legacy-peer-deps=true` to unblock renovate automated PRs which are currently failing.

chore: update renovate config and add .npmrc

---

docs/source/caching/cache-field-behavior.mdx

This PR attempts to document the `merge :false` option on merge functions, per this [comment. ](https://github.com/apollographql/apollo-client/pull/6372#issuecomment-670593650)

Field policy merge docs

---

.circleci/config.yml
.gitignore
package-lock.json
package.json
src/link/persisted-queries/__tests__/index.ts
src/link/persisted-queries/__tests__/react.tsx

It looks like some combination of the changes in #9928 and #9942 exposed a long running issue caused by using `crypto-hash` in our `@apollo/client/link/persisted-queries` tests. `crypto-hash` spawns a thread the first time it's called, and keeps that thread alive until the end of program execution, if worker threads are available (which they are for our tests since they're running in CI via Node). Unfortunately there appears to be some kind of a race condition between `crypto-hash` `unref`ing its worker and Jest reporting a successful test suite exit, which leads to Jest reporting the following (which is seen by running jest with the `--detectOpenHandles` setting enabled):
```
Jest has detected the following X open handles potentially keeping Jest from exiting:
```
This then appears to be …

Replace crypto-hash with a custom hashing function in tests

---

ROADMAP.md

I updated our roadmap to show that `usefragment` will go in r3.7

updates roadmap

---

src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts

This includes the same fix and adapts the tests from https://github.com/apollographql/apollo-client/pull/9918 while targeting the `release-3.7` branch. The tests use `useQuery` and the new test fails if the diff in `src/react/hooks/useFragment.ts` is reverted.

Return most recent result diff from useFragment, update test

---

docs/source/caching/cache-field-behavior.mdx

Reading though the docs for the first time in a while and I noticed a paragraph that was out of place and apparently  duplicated from one that is earlier in the document.
**Original blurb:**
https://github.com/apollographql/apollo-client/blob/04537470f754e48344197ddbcb4a0446dcdc6e26/docs/source/caching/cache-field-behavior.mdx#L58-L60
**Duplicate (removed in this PR):**
https://github.com/apollographql/apollo-client/blob/04537470f754e48344197ddbcb4a0446dcdc6e26/docs/source/caching/cache-field-behavior.mdx#L117

docs: remove errant duplicated text

---

src/core/ObservableQuery.ts
src/core/watchQueryOptions.ts
src/react/hoc/__tests__/queries/polling.test.tsx

Fixes https://github.com/apollographql/apollo-client/issues/9691
Fixes https://github.com/apollographql/apollo-client/issues/6187
Adds support for the "no-cache" fetchPolicy to pollInterval.  
Most fetchPolicies don't make sense to use when polling, as users probably don't want to be polling the cache directly. As such, currently polling will overwrite the fetchPolicy with "network-only". 
However, "no-cache" is also useful for when the user wants to control whether or not their results are written to the cache, so this PR goes ahead and adds a check to allow that policy through, and a relevant test.
The check this adds looks similar to a fetchPolicy sieve in `refetch()`, and it might be worth looking into how to make that functionality a bit more generalized/cleaner.
I also went ahead …

Supports "no-cache" fetchPolicy with pollInterval

---

.github/workflows/docs-publish.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

CHANGELOG.md
docs/shared/mutation-options.mdx
src/react/components/__tests__/client/Mutation.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts
src/react/types/types.ts

Implementation of the changes originally proposed in https://github.com/apollographql/apollo-client/pull/6238, but fit for our current codebase. This PR passes mutation options into the onError and onCompleted hooks. See the previous PR for some discussion on the topic.
Tests have been updated to reflect this feature

Pass mutation options to handlers

---

package.json
src/cache/core/types/common.ts

Based on the original PR here - https://github.com/apollographql/apollo-client/pull/9126 (Thanks @matthargett!) 
Opening this to address some changes that were requested in the above PR but never got picked up by the original author.
Assuming the original review by @benjamn still stands, this should be good to go :-)
**From previous discussion:**
Some crash reporting services were not categorizing the `MissingFieldError` with other custom errors because it does not extend from the base `Error` class. This was an intentional performance fix in https://github.com/apollographql/apollo-client/pull/8734, but because that PR also ended up batching huge arrays of `MissingFieldError`s into a single `MissingFieldError`, the overhead from the super() call to Error was no longer a huge issue - so …

MissingFieldError once again extends Error

---

src/__tests__/__snapshots__/exports.ts.snap
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts

Per https://github.com/apollographql/apollo-client/issues/10074
We'll use the name `useFragment_experimental` to clarify that the useFragment hook implementation might change after the initial beta release

(Release 3.7) Rename useFragment -> useFragment_experimental

---

docs/source/config.json
docs/source/data/defer.mdx

This PR adds the initial BETA documentation for the  supporting the `@defer` directive  in Apollo Client

adds defer docs

---

docs/source/data/defer.mdx

Updates the defer message so it's more clear to a user what state this feature is in.

updates defer message

---

docs/source/data/defer.mdx

Right now our defer docs say the functionality is enabled by default. This isn't accurate as `@defer` functionality is currently only available by installing `@apollo/client@beta`. This commit makes this more clear in the docs.

Make it clear that @defer is available by installing beta

---

src/__tests__/__snapshots__/exports.ts.snap
src/utilities/graphql/__tests__/directives.ts
src/utilities/graphql/directives.ts
src/utilities/index.ts

The `hasDirectives` utility function is ambiguously named, since it behaves as if it was named `hasAnyDirectives`, even though one could also imagine wanting to check that _all_ the provided directives are present, which calls for a name like `hasAllDirectives`. This PR introduces those two helper functions and adds a bunch of unit tests.
This PR builds on the optimization of `hasDirectives` that I began in #10018 with commit https://github.com/apollographql/apollo-client/pull/10018/commits/6d3ad04126f2da0f032603213be22f643c005cab, though it seemed sufficiently unrelated to that PR to be worth separating out into a second PR.

Improvements to the `hasDirectives` utility function

---

src/react/hooks/useFragment.ts

After discussing with @benjamn today, it was determined `previousResult` can be omitted from `UseFragmentOptions`.
In documenting `UseFragmentResult` in PR https://github.com/apollographql/apollo-client/pull/10099, it seems we may be able to omit `previousResult` and `lastCompleteResult` from the result type as well. I've done some logging in our tests and don't see where they're used, but happy to add them back if they are.

chore: omit previousResult, lastCompleteResult from options/result

---

src/cache/index.ts

Simple export of `Modifers` and `Modifers` so these types can be used externally.

Export `Modifier` and `Modifiers`

---

docs/shared/useFragment-options.mdx
docs/shared/useFragment-result.mdx
docs/source/api/react/hooks-experimental.mdx
docs/source/caching/cache-interaction.mdx
docs/source/config.json
docs/source/data/defer.mdx
docs/source/data/fragments.md

Closes #10056. Adds `useFragment_experimental` documentation.
This PR:
- adds a [Hooks (experimental) page](https://deploy-preview-10099--apollo-client-docs.netlify.app/api/react/hooks-experimental) to the docs which documents AC web's first experimental hook, `useFragment_experimental`
- adds a section to the bottom of the [fragments page](https://deploy-preview-10099--apollo-client-docs.netlify.app/data/fragments/#usefragment_experimental)
- mention `useFragment_experimental` in the table at the top of the [cache interaction page](https://deploy-preview-10099--apollo-client-docs.netlify.app/caching/cache-interaction) and [section](https://deploy-preview-10099--apollo-client-docs.netlify.app/caching/cache-interaction#usefragment_experimental) that points people to the API reference for …

chore(docs): add useFragment_experimental documentation

---

src/link/batch/__tests__/batchLink.ts
src/react/hoc/__tests__/queries/index.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx

I've been noticing some test failures with these tests in particular every so often, and it's looking like they're often just being re-ran until they pass. 
The failing tests all rely on timeouts in some way, and manually lowering the timeout duration produces errors consistent with what I've been seeing. As such, I thought I'd bump up the timeouts a little so these tests pass more reliably, while still allowing unreasonably long runs to fail.

Bump up timeout time for batchLink, query and polling tests

---

docs/shared/query-options.mdx
src/react/hooks/useQuery.ts
src/react/types/types.ts

When reading the docs I was confused by the `displayName` option for the `useQuery()` query hook 
> The name of your component to be displayed in the React Developer Tools.
Since `useQuery` is a hook there is no component to set a display name to. I figured this was something that was carried over from `react-apollo` or was still used by Apollo Dev Tools or the legacy HOCs or components but from looking at the code it appears unused in those places. 
Let me know if I'm incorrect about any of this. Thanks!

remove obsolete displayName query option

---

docs/source/caching/advanced-topics.mdx

Found a couple issues with the existing `onResetStore` docs
- `componentDidUnmount` doesn't exists (`componentWillUnmount` does though)
- `this.state.reset` is always `false` and wasn't correctly being set
- It references the old `@apollo/react-hoc` module from `react-apollo`, which has not been mentioned if reading the docs in order
For this PR I also migrated to hooks since the HOCs are deprecate. Let me know if you would prefer it to be fixed up but still use the HOC. Thanks!

docs: fixup onResetStore docs, convert to hooks

---

src/cache/inmemory/inMemoryCache.ts
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/watchQueryOptions.ts
src/react/components/Query.tsx
src/react/components/Subscription.tsx
src/react/components/types.ts
src/react/hoc/graphql.tsx
src/react/hoc/mutation-hoc.tsx
src/react/hoc/query-hoc.tsx
src/react/hoc/subscription-hoc.tsx
src/react/hoc/types.ts
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/react/hooks/useSubscription.ts
src/react/ssr/RenderPromises.ts
src/react/types/types.ts
src/testing/core/subscribeAndCount.ts
src/utilities/common/cloneDeep.ts
src/utilities/common/mergeOptions.ts
src/utilities/policies/pagination.ts

Hi there! 👋
TypeScript recently added some stricter checking around unconstrained generics being incompatible with emptyish object types. The changes are only in nightly versions of TypeScript right now, but we've been exploring how open-source projects have been impacted. These are the changes necessary for apollo-client to build cleanly in TypeScript 4.8.

Cascade out type parameters for TypeScript 4.8

---

src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/useSubscription.ts
src/react/types/types.ts

Adds `onError` option to the `useSubscription` hook, similar to how it is offered on other hooks.
I've added a simple test, but wasn't able to add an error-only result, I had to send `data` as well, I'm not sure why. If there's a better way to do that, I'd love to learn.
- https://github.com/apollographql/apollo-client/issues/8338
- https://github.com/apollographql/apollo-feature-requests/issues/122

Add onError option to useSubscription hook

---

package.json
src/__tests__/__snapshots__/exports.ts.snap
src/cache/core/cache.ts
src/cache/index.ts
src/cache/inmemory/__tests__/fragmentRegistry.ts
src/cache/inmemory/__tests__/writeToStore.ts
src/cache/inmemory/fragmentRegistry.ts
src/cache/inmemory/helpers.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/readFromStore.ts
src/cache/inmemory/types.ts
src/cache/inmemory/writeToStore.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/utilities/graphql/fragments.ts
src/utilities/graphql/transform.ts
src/utilities/index.ts

When a query uses a named fragment, or when fragments use other fragments by name, [our current recommendation](https://www.apollographql.com/docs/react/data/fragments/#creating-colocated-fragments) is to `${...}`-interpolate the necessary fragment declarations into the query's `gql` template string.
While this pattern works in small examples, it gets cumbersome when there are multiple (layers of) fragments, and it's all too easy to end up duplicating fragment declarations in the resulting query, if they accidentally get interpolated twice (or more!).
This PR attempts to make this situation substantially easier, by allowing you to pre-register certain named fragments with your `InMemoryCache`, so that you can refer to them by name elsewhere, without needing to interpolate their …

Allow registering named fragments with `InMemoryCache` to support using `...FragmentName` in queries without redeclaring `FragmentName` in every query

---

docs/source/data/defer.mdx

changes the command to reference the [next RC release on NPM of 3.7](https://www.npmjs.com/package/@apollo/client/v/3.7.0-rc.0)

changes beta to next

---

package.json
src/link/http/__tests__/HttpLink.ts
src/link/http/__tests__/parseAndCheckHttpResponse.ts
src/link/http/parseAndCheckHttpResponse.ts

Fixes #8945 where not handling the response status code before parsing the response body text causes the apollo client to send a ServerParseError when it should send a ServerError.
The changes here are taken from #8974 which has been inactive for months

Fix for ServerError obscured by ServerParseError

---

docs/source/api/react/hooks-experimental.mdx

While reading through the excellent documentation of [`useFragment_experimental`](https://www.apollographql.com/docs/react/api/react/hooks-experimental/#usefragment_experimental), I noticed that the example using `useQuery` uses the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) as a way to assert that `data` can't be null in this context, which is unfortunately not the case.
I think this usage could be confusing as the code snippet mentioned JavaScript, but that operator won't have any effects outside of TypeScript as the operator is simply removed in the emitted JavaScript code. Even with TypeScript, if someone copy-paste that example, it could lead to a runtime error are we're telling the …

chore(docs): use optional chaining rather than non-null assertion

---

.circleci/config.yml

While investigating flaky tests in this repo, I came across this issue: https://github.com/facebook/jest/issues/11956
We're currently running our tests on CircleCI with the image `circleci/node:16.13.1`. Local testing showed that the heap size nearly doubled when running with Node v16.13 vs. v16.10. 
While we investigate the root cause and longer-term fixes, this PR runs our Jest tests with v16.10, which should decrease memory consumption on CI and provide an admittedly band-aid solution to some of the flakiness we've seen lately.

chore(tests): use node v16.10.0 for jest tests due to memory leaks in 16.11+

---

src/link/batch-http/batchHttpLink.ts
src/link/http/parseAndCheckHttpResponse.ts

Quick typo fix for something that was bugging me when searching for `NetworkError` in docs 😔

Fix typo in `NetworkError`

---

docs/source/api/link/apollo-link-rest.md

Added `graphql-anywhere` to the install string. `apollo-link-rest` does not work without this library installed.
Somewhat related:
https://github.com/apollographql/apollo-link-rest/issues/295

Update apollo-link-rest.md - Add graphql-anywhere to install list

---

.circleci/config.yml

Looking at [a recent job](https://app.circleci.com/pipelines/github/apollographql/apollo-client/17326/workflows/4db5bc1c-718e-4f0b-b6ec-7089b9aa8b55/jobs/94670), restoring and later saving the cached `~/.npm` directory takes 13 and 14 seconds, respectively. This job took a total of 1 minute 11 seconds, so restoring/saving the (large) `~/.npm` directory accounts for ~38% of the total time.
If removing the caching altogether does not slow anything else down by that much (~27 total seconds), then the caching was not really delivering on its intended goals, and should be removed.
[New results](https://app.circleci.com/pipelines/github/apollographql/apollo-client/17327/workflows/0c21e96a-736e-48f2-b2a9-55dea5405342/jobs/94672) after running CI on this commit/PR. Now only 1 minute 1 second …

Experiment with not caching the `~/.npm` directory during Filesize/Tests CircleCI jobs

---

docs/source/development-testing/static-typing.md

We noticed that the ["Using Apollo with TypeScript"](https://www.apollographql.com/docs/react/development-testing/static-typing/#usequery) documentation makes no mention of `TypeDocumentNode`, which we consider a best practice. It would be nice to have somewhere to point to in the official docs.
In this PR I borrowed an existing blurb from the CHANGELOG and adapted the "Typing hooks" `useQuery()` example for my purposes. 
Thanks!

docs: add TypedDocumentNode example

---

docs/source/local-state/local-resolvers.mdx

Fixes #10210
* Remove deprecation verbiage
* Retain local-only fields recommendation
* Wordsmith explanation of future plans

Update Local Resolvers docs

---

CHANGELOG.md
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts

This `useFragment` test has been failing locally for me and has even failed on `main` for otherwise innocuous commits like 2db905f79ef870eaf6f240164122f8a337a9b45d ([failing CI job](https://app.circleci.com/pipelines/github/apollographql/apollo-client/17236/workflows/a10b73ba-ecab-47e0-a7a4-a6b142aef57d/jobs/94486)).
I added this `Promise` logic in #10118 to fix another flakiness issue, but the current state seems worse (more frequent failures) than before.

Call `forceUpdate` immediately if `diff` changes between first `useFragment` call and first `cache.watch` call

---

src/react/hooks/__tests__/compareResults.test.tsx
src/react/hooks/compareResults.ts

This helper function demonstrates how we might use query syntax (and specifically a hypothetical `@nonreactive` directive) to direct the comparison of JSON result objects, ignoring certain (`@nonreactive`) parts of the objects, without modifying either object in the process.

Implement `compareResultsUsingQuery` helper function

---

src/core/QueryManager.ts
src/utilities/common/cloneDeep.ts

Fixes https://github.com/apollographql/apollo-client/issues/10202
Fixes https://github.com/apollographql/apollo-client/issues/10166
(Potentially) Fixes https://github.com/apollographql/apollo-client/issues/10132
Release `3.7-alpha.4` implemented `cloneDeep` ([commit](https://github.com/apollographql/apollo-client/commit/b4ffcb60d7302d6297e084c0d99536c890475df1)) to clone options (including `options.context.headers`!) when fetching queries, however it didn't support JS Symbols - meaning the serverRequest (an [IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage)) field of `options.context` wasn't getting cloned properly. This caused some trouble with dynamic headers, as seen in the above issues.
This PR reverts that commit as it's looking like the current state …

Revert cloneDeep-ing request headers

---

docs/source/data/defer.mdx
docs/source/data/operation-best-practices.mdx
docs/source/development-testing/developer-tooling.md

These docs links work fine as-is thanks to redirects, but fixing them to remove them from broken link reports

Fix 'broken' links

---

CHANGELOG.md
docs/source/local-state/managing-state-with-field-policies.mdx

Additional documentation for managing local state

---

docs/source/api/link/apollo-link-rest.md

https://github.com/apollographql/apollo-link-rest/pull/301 has landed and with it `apollo-link-rest` no longer has a dependency on `graphql-anywhere` 🥳
[apollo-link-rest@0.9.0-rc.2](https://www.npmjs.com/package/apollo-link-rest/v/0.9.0-rc.2) has been released and [should become the stable `0.9` release this weekend](https://github.com/apollographql/apollo-link-rest/issues/295#issuecomment-1292415605). With that, we can remove the final reference to `graphql-anywhere` in our docs outside of CHANGELOG.md.
This is ready for review and I will hold off on merging until `0.9` is released.

chore(docs): remove graphql-anywhere from apollo-link-rest doc

---

docs/source/development-testing/static-typing.md

We just merged in a PR [updating this article to support GraphQL Code Gen](https://github.com/apollographql/apollo-client/pull/10173/files), this is a PR to further polish up the rest of the article :)

Further update the TypeGen article for style

---

docs/source/local-state/reactive-variables.mdx

This PR adds examples to the docs on how to avoid some common pitfalls when using reactive vars.  It should hopefully help people get some time back when trying to triage issues with reactive vars mutations not triggering component updates in React applications.

Add array examples to reactive variable documentation

---

docs/source/data/subscriptions.mdx

In the `subscribeToMore` example in the docs, we use a mix of function components (`CommentsPageWithData` uses `useQuery` hook) and class components, like the `CommentsPage` component in this PR.
This PR updates `CommentsPage` to be a function component and replaces `componentDidMount` with `useEffect(() => ..., [])`.

docs: Update subscribeToMore example to use React hooks

---

docs/source/pagination/cursor-based.mdx

keyArgs must be set to false to properly merge multiple requests in cache when paging because "cursor" is passed in as a query variable (even though it isn't referenced in the merge function)

Exclude "cursor" argument to prevent separate cache instance

---

.changeset/shiny-balloons-matter.md
config/bundlesize.ts
src/core/QueryInfo.ts
src/react/hooks/__tests__/useQuery.test.tsx

When using `useQuery` with deferred queries that already have cache data written, the initial chunk of data returned from a server would overwrite anything in the cache, which meant cached data for deferred chunks would disappear. This primarily affected `cache-and-network` fetch policies with data written to the cache and `cache-first` fetch policies with partial data in the cache when using the `returnPartialData` option. This is now better handled by merging existing cache data with the initial deferred chunk to ensure a complete result set is still returned.

Better handle cached data with deferred queries

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

Makes a few fixes to the prerelease workflow and adds a step to both prerelease + release workflows to send a Slack message on publish.
- Updates `prerelease.yml` to use `andstor/file-existence-action@v2.0.0` for detecting `pre.json` and determining whether to enter changeset's `pre` mode.
- Enter pre mode if we're not already in it and we didn't just exit.
- Run publish if we're in pre mode and just merged a "Version packages" PR.

Changesets updates

---

.changeset/small-timers-shake.md
.prettierignore
config/bundlesize.ts
config/jest.config.js
package-lock.json
package.json
src/__tests__/__snapshots__/exports.ts.snap
src/core/ObservableQuery.ts
src/core/watchQueryOptions.ts
src/react/cache/SuspenseCache.ts
src/react/context/ApolloProvider.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/hooks/internal/__tests__/useDeepMemo.test.ts
src/react/hooks/internal/index.ts
src/react/hooks/internal/useDeepMemo.ts
src/react/hooks/useSuspenseQuery.ts

Relates to #10231 and #10286
Adds a new `useSuspenseQuery` hook to allow React apps to use Apollo with React's suspense feature. For now, this hook is exported as an experimental hook to make it clear that we are looking for feedback and iterating on it. 
This implementation in this PR focuses on baseline support for React suspense with Apollo. This does not yet support `@defer` directives, has not been tested with SSR, and does not provide a solution for the [render-as-you-fetch pattern](https://17.reactjs.org/docs/concurrent-mode-suspense.html#approach-3-render-as-you-fetch-using-suspense) . These will be covered in future PRs and alphas.
1. Ensure your `<ApolloProvider />` has a `SuspenseCache`
```tsx
import { SuspenseCache } from '@apollo/client';
// ...
<ApolloProvider …
```

`useSuspenseQuery`

---

CHANGELOG.md
config/prepareChangesetsRelease.ts
package.json

There are two changes in this PR that pave the way for our first automated Changesets release from `main`, `3.7.3`:
- Update `CHANGELOG.md` to conform to Changesets heading defaults so the GitHub bot will have a better time generating future entries (I backfilled these changes to `3.7.0` for continuity).
- Add a script that prepares the `dist` folder for a Changesets release: it copies `CHANGELOG.md` and the `.changeset` folder inside of `dist` while adding both to an `.npmignore` so that our release workflow can `cd dist` and `changeset publish` Just Works. (This has been tested locally via `npm pack`.)

Fix Changesets release workflow from default branch

---

docs/source/data/mutations.mdx

Fixed minor grammar error in help bullet point subtitle.  
- To refer to queries by name, make sure each of your app's queries has a unique name.
to
- To refer to queries by name, make sure each of your app's queries have a unique name.

Fixed minor grammar error in docs.

---

.changeset/rude-mayflies-scream.md
config/bundlesize.ts
src/__tests__/client.ts
src/core/ApolloClient.ts
src/core/LocalState.ts
src/core/QueryManager.ts
src/core/__tests__/QueryManager/links.ts
src/core/types.ts
src/link/batch-http/__tests__/batchHttpLink.ts
src/link/batch-http/batchHttpLink.ts
src/link/http/__tests__/HttpLink.ts
src/link/http/createHttpLink.ts

Closes #10303
By default, Apollo core will remove fields with an `@client` directive before it makes it to the link chain. We've now got [use cases](https://github.com/apollographql/apollo-client/issues/10228) that require the use of `@client` in the link chain. This PR adds an option to our client to allow `@client` fields to make it to the link chain. This is part of our larger effort to move local resolvers [back into the link chain](https://github.com/apollographql/apollo-client/issues/10060).
Because `@client` fields now have the possibility of making it to the link chain, the `HttpLink` and `BatchHttpLink` links have been updated to remove `@client` fields themselves. Once #10060 is done, we should be able to remove this behavior as the work to remove `@client` fields will likely …

Add the ability to allow `@client` fields to be sent to the link chain

---

.changeset/short-bikes-mate.md
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/hooks/useSuspenseQuery.ts

Closes #10384
Updates `useSuspenseQuery` to always throw network errors, regardless of the `errorPolicy` set in options. This is more in-line with how `useQuery` works when encountering a network error since the `error` is retained and the `onError` callback is called.

Always throw network errors in `useSupenseQuery` regardless of the error policy

---

.github/workflows/release.yml

This PR publishes to the `next` npm tag from `main` via Changesets, which was originally planned but did not make it into the original Changesets PR. It also logs some values that are the output of the Changesets action step.

chore: publish to next tag, echo values from changesets step

---

.changeset/metal-hats-cough.md
docs/shared/mutation-result.mdx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts

Closes #10287
Prefer calling the `onError` and `onCompleted` functions passed to the execute function returned by the `useMutation`. Currently both the callbacks passed to the execute function and the callbacks passed to the hook itself are called. According to our [docs](https://www.apollographql.com/docs/react/data/mutations#mutate), this should not happen as the options passed to the execute function should override the hook options.

Prefer the callbacks passed to the execute function returned from `useMutation`

---

.changeset/brown-tomatoes-walk.md
config/bundlesize.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts

Closes #10365
Ensure in-flight promises returned from `useLazyQuery`'s execute function are aborted when `useLazyQuery` unmounts. Currently the promise is stuck in a pending state indefinitely with no way to resolve/reject it.

Abort in-flight promises returned from `useLazyQuery` when component unmounts

---

.github/workflows/close-stale-issues.yml

See https://github.com/apollographql/apollo-client/actions/runs/3908646249/jobs/6678968482
We ran out of operations on the initial debug run. Let's increase to 100 and try again.

Increase Stale action's operations-per-run

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

The prerelease GitHub action is still failing while trying to interact with SlackBot: `steps.changesets.outputs.publishedPackages` is undefined after a prerelease, so trying to index into the array in the `parseJSON` call causes the error.
Instead of using the changesets action's output, we'll just use an existing action from the marketplace to grab the version from `package.json`. This PR also formats the Slack message using their "blocks" API.

chore: fix prerelease notification and upgrade to rich markdown

---

docs/source/api/link/community-links.md

Adds `@grafbase/live-apollo` to the community link directory. This ApolloLink enables [Live Queries](https://grafbase.com/docs/realtime/live-queries).

docs(community-links): add live query link

---

docs/source/api/react/hooks-experimental.mdx
docs/source/caching/cache-interaction.mdx
docs/source/data/fragments.md

`useFragment_experimental` was released in 3.7 so we don't need to specify `@beta` anymore 🎉

Remove beta version from useFragment docs

---

.github/workflows/close-stale-issues.yml

I've been looking over the [logs](https://github.com/apollographql/apollo-client/actions/runs/3955601813/jobs/6774029079) from the `🏓  awaiting-contributor-response` Action and found that it's working as expected.  So let's let it run for real 🚀   I'd also like to propose bumping up the `operation-per-run` value since the job exhausts itself before reaching the end of our issues.

Set Stale Action debug to false, increase operations-per-run

---

docs/source/integrations/integrations.md
netlify.toml

The previous `ignore` script of `git diff --quiet HEAD^ HEAD .` was no longer detecting changes inside of `docs`, so it was temporarily disabled causing docs previews to build on all PRs.
This PR reinstates the ignore script using the [most recent recommendation from the docs](https://docs.netlify.com/configure-builds/ignore-builds/#mimic-default-behavior), `git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF .` and bumps the `NODE_VERSION` to 18.

chore: fix netlify ignore script

---

.changeset/wicked-dots-knock.md
src/react/hooks/useFragment.ts

This PR adds default types for the `useFragment` generic definitions. This improves the experience when passing generic types directly to the `useFragment` function.
Currently, you can get proper types on `data` when using `TypedDocumentNode`. Take the following example:
```ts
const ItemFragment: TypedDocumentNode<Item> = gql`
fragment ItemFragment on Item {
text
}
`
const { data } = useFragment({ fragment: ItemFragment })
type Data = typeof data; 
// type Data = Item | undefined
```
If using the generic `gql` helper, you get `unknown` as expected:
```ts
const ItemFragment = gql`
fragment ItemFragment on Item {
text
}
`
const { data } = useFragment({ fragment: ItemFragment })
type Data = typeof data; 
// type Data = unknown
```
If, however, I want to provide my own types to `useFragment`, …

Add default values for useFragment generic types

---

.changeset/proud-months-dance.md
src/link/batch-http/__tests__/batchHttpLink.ts
src/link/http/createHttpLink.ts
src/link/http/selectHttpOptionsAndBody.ts

Narrows `headers` type as began by @alias-mac in #9042.

Fix headers type (extends #9042)

---

.github/workflows/snapshot-release.yml

This PR adds a GitHub action to automate creating "snapshot" one-off releases so that Apollo community members can test out the changes on a PR before it's merged.
If an Apollo maintainer adds a comment beginning with `/release:pr` on a PR _that already contains a changeset markdown file_, the following happens:
- the PR is checked out at its latest commit
- the code is built and changeset versions the library with the following naming convention: `0.0.0-${some tag we set}-${current timestamp on CI}`, for example `0.0.0-pr-10479-20230126204300`. This is the naming convention chosen by changesets and only the middle tag value is configurable which I set to the current PR number to make it easier to associate snapshot releases to their originating PRs
- this version number is only used for …

chore: adds changeset snapshot action

---

.github/workflows/lock.yml

Adds workflow to lock closed issues + PR that have not had new comments within the last 30 days.

chore: adds GHA workflow to lock closed + dormant issues

---

.changeset/seven-cameras-kiss.md
config/bundlesize.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/utilities/common/mergeOptions.ts

fixes #10496
Locally, many of the tests were erroring out for me - but independently of the `useLazyQuery` tests and even without my changes. So let's see what CI has to say about this.

Allow `useLazyQuery` trigger fn to change `query`

---

.changeset/funny-files-suffer.md
docs/source/api/react/testing.md
docs/source/development-testing/testing.mdx
src/core/__tests__/ObservableQuery.ts
src/testing/core/index.ts
src/testing/core/mocking/mockLink.ts
src/testing/react/MockedProvider.tsx
src/testing/react/__tests__/MockedProvider.test.tsx

Closes #5917
When using `MockedProvider` to mock responses for a component under test, there is a chance a mock is not matched when the request was made, typically due to user-error like a typo or mismatched variable. Currently this results in an error response returned from the `MockLink`. In some situations, limiting the mismatch to an error response made it difficult to debug issues with the test setup, such as when the `errorPolicy` was set to `ignore`, which discards errors returned from links. 
This PR will now log console warnings when a mock cannot be matched during a test. This should make it more obvious that there could be potential issues with the test setup.
Occasionally, an unmatched mock is expected for a test. In this case, you can disable these warnings with the newly …

Log unmatched mocks to the console for tests

---

src/__tests__/local-state/resolvers.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/QueryManager/index.ts
src/testing/core/mocking/mockQueryManager.ts
src/testing/core/mocking/mockWatchQuery.ts

While working on #10502, I noticed that `mockQueryManager` and `mockWatchQuery` both took a `reject` argument, but this argument wasn't used. For added simplicity, I simply removed this argument and updated all references to it accordingly.
These are internal testing utilities, so the breaking change to the API won't affect users.

Remove unused reject argument for mockQueryManager and mockWatchQuery

---

.github/workflows/snapshot-release.yml

This PR makes a fix to our snapshot release workflow added in https://github.com/apollographql/apollo-client/pull/10480 which fixes errors [like this](https://github.com/apollographql/apollo-client/actions/runs/4088539427/jobs/7050324587): snapshot releases are not permitted in prerelease mode, so if `pre.json` is detected, we can remove it before proceeding with the release. (This was tested on a separate changesets demo repo I created [here](https://github.com/alessbell/good-snow-tire-demo/pull/65).)
NB: the snapshot release workflow still fails on branches that exist on forks, this will be resolved in a future PR.

fix: unblock snapshot releases on branches in prerelease mode

---

docs/source/api/cache/InMemoryCache.mdx
docs/source/caching/cache-interaction.mdx

It has recently come up on [twitter](https://twitter.com/franleplant/status/1621196243727704064) that none of the docs state that `updateQuery/updateFragment` updates should be made in an immutable fashion. 
In most cases, this should be caught by the fact that the data passed into the `update` function is frozen, but depending on `strict` mode being on or off, this can still be silently fail.
This adds a note for immutability in the most relevant places and links to the new React docs, that explain how to write immutable updates & potentially use `immer` for that purpose.
Note: I'm very happy for any suggestions on how to word this better, or style it as some kind of "hint".

Add note discussing immutability to `update*` docs

---

.changeset/shaggy-bees-attack.md
src/utilities/observables/Concast.ts
src/utilities/observables/__tests__/Concast.ts

Fixes issue #10262, since `this.sources.shift()` throws when `complete` is called called before the `Promise` that should have initialized `this.sources` resolves, which can happen when the directive combination `@client @export(as: ...)` is used, because `@export` usage causes a `Promise<Observable[]>` to be passed to the `Concast` constructor instead of passing the `Observable[]` itself.
Although passing a `Promise` to the `Concast` constructor should work, we only exercise that code path in [one place](https://github.com/apollographql/apollo-client/blob/015a1ffff3febe4604956f4bb137a3111f3d8257/src/core/QueryManager.ts#L1226-L1241), and the additional wrinkle of calling `complete` before the `Promise` resolves was never tested.

Tolerate undefined `concast.sources` if `complete` called earlier than `concast.start`

---

.github/workflows/lock.yml

This PR updates the action that locks inactive closed issues and PRs to filter on created by date.
It's been running hourly but has only locked a fraction of long since closed issues, and after reading some issues on the action's repo this may have to do with how it fetches issues/PRs via GitHub API, so trying some batching here.
Currently there are [1337](https://github.com/apollographql/apollo-client/issues?q=is:issue+is:closed+created:%3C2018-01-01+) closed issues created before 2018-01-01 and only [137](https://github.com/search?q=repo:apollographql/apollo-client+is:closed+is:locked+created:%3C2018-01-01+&type=repositories) of them have been locked. Let's see if this helps, and if it does we can increment the year every day or so until the backlog is processed, then move the action to …

chore: filter issues to lock by created at date

---

.github/workflows/lock.yml

Still debugging this :) `log-output: true` hasn't been logging anything when the action runs, and looking at the action's code that indicates the search for matching issues/PRs isn't returning anything (when I run it locally, the response includes both issues and PRs as expected).
This PR cleans up the action's formatting of permissions and uses `github.token` instead of `secrets.GITHUB_TOKEN`... Hopefully this will resolve the issue with the GitHub API search.

chore: debug lock action

---

.changeset/dry-radios-help.md
.changeset/warm-rivers-develop.md
config/bundlesize.ts
src/__tests__/__snapshots__/exports.ts.snap
src/__tests__/local-state/resolvers.ts
src/cache/inmemory/helpers.ts
src/utilities/common/arrays.ts
src/utilities/graphql/__tests__/transform.ts
src/utilities/graphql/transform.ts

This refactoring of `removeDirectivesFromDocument` builds on (rebases) the work begun in PR #6322, fixing both the original issue #6311 and the related issue #10539.
At a high level, these changes reduce the number of full-document AST traversals performed by `removeDirectivesFromDocument` from 3 to 2. Future work could potentially replace the second traversal with a more targeted manual cleanup pass, to improve performance further.
In the first of those two traversals, we gather as much information as we can about the AST, including all the variable references and fragments spreads used by each operation or fragment definition. At the same time, we can safely remove subtrees annotated with removal directives like `@client`, which effectively hides those removed subtrees from the …

Refactor `removeDirectivesFromDocument` to fix AST ordering sensitivities and avoid 1/3 AST traversals

---

.github/workflows/lock.yml

Now that we've worked through the backlog, we can run this workflow daily instead of hourly.

chore: run lock workflow daily

---

.github/PULL_REQUEST_TEMPLATE.md

The link to `CONTRIBUTING.md` from `.github/PULL_REQUEST_TEMPLATE.md` works fine locally (at least from VSCode), but it doesn't work within the browser when we're typing the pull request description.
Let's make sure the link is always working.

chore: fix link to `CONTRIBUTING.md`

---

docs/source/api/link/introduction.mdx

A papercut I encountered while working on a separate subscriptions issue, and one it looks like [others have faced too](https://community.apollographql.com/t/apollolink-split-not-working-network-error-invariant-violation-request-is-not-implemented/2566).
On [Directional Composition](https://www.apollographql.com/docs/react/api/link/introduction/#directional-composition), the docs state:
> You can define this logic with the split method of an `ApolloLink` instance.
The only example we currently provide uses `RetryLink` like so:
```js
const directionalRetryLink = new RetryLink().split(
(operation) => operation.getContext().version === 1,
new HttpLink({ uri: "http://localhost:4000/v1/graphql" }),
new HttpLink({ uri: "http://localhost:4000/v2/graphql" })
);
```
`RetryLink` extends …

chore: add ApolloLink.split example

---

.changeset/clean-horses-prove.md
src/utilities/graphql/getFromAST.ts

Rather than type casting with [type assertions](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions), we can leverage [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) to narrow down the type where we already have user-defined type guards (`Array.filter`). That's equivalent, but the next step will be correctly typed, and we won't need to type cast it.

chore: narrow types of `getFromAST.ts` with type predicates

---

docs/source/api/react/testing.md

I fixed a grammar error in the documentation: from "Instead, you to specify" to "Instead, it allows you to specify". The error was in "docs/source/api/react/testing.md".

Update Documentation: Fix grammar error "Instead, you to specify"

---

package-lock.json
package.json

It looks like this dev dep is no longer needed since Apollo Client broke the `fast-json-stable-stringify` dependency (https://github.com/apollographql/apollo-client/pull/8222)

remove obsolete @types/fast-json-stable-stringify dev dep

---

src/cache/inmemory/__tests__/__snapshots__/writeToStore.ts.snap
src/cache/inmemory/__tests__/writeToStore.ts

When running the tests locally on my personal mac, one test would fail to match the snapshot because the snapshot contained invisible non-ASCII characters. Specifically, the issue was in a date string between the seconds and the meridian label.
Snapshot: `"localeString": "9/25/2020, 1:08:33 PM"`
Local output: `"localeString": "9/25/2020, 1:08:33 PM"`
You can see they appear the same, but using a character identifier will show that the [gap in the local output](https://software.hixie.ch/utilities/cgi/unicode-decoder/character-identifier?characters=+) is:
```
U+0020 SPACE character
```
Whereas the [gap in the snapshot](https://software.hixie.ch/utilities/cgi/unicode-decoder/character-identifier?characters=%E2%80%AF) contains:
```
U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX character …
```

Fix snapshot with non-ascii character

---

.changeset/odd-students-crash.md
config/bundlesize.ts
src/cache/inmemory/__tests__/policies.ts
src/cache/inmemory/policies.ts

In #10599 I suggested two typical/supported ways of configuring entity identification: [`keyFields: [...]`](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids) (preferred, `__typename`-specific) and defining a [`dataIdFromObject`](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-identifier-generation-globally) function (legacy, catch-all). 
Unless you can enforce a blanket assumption that all your types must have a single `id` field (unlikely, brittle), both approaches ultimately require listing the `__typename`s of all the types whose `keyFields` you want to configure, which can be annoying if your application uses many different entity types.
**The good news:** I think I've found a way to combine a few different …

Fix type policy inheritance involving fuzzy `possibleTypes`

---

.changeset/small-elephants-poke.md
package-lock.json
package.json

This PR upgrades to the [newly-released TypeScript v5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/).
We anticipated this upgrade to be painless after making the necessary changes to adopt `v4.9.4` in https://github.com/apollographql/apollo-client/pull/10470. So far this seems to be true 🎉 
`npx tsc --noEmit` succeeds. Additionally I'll be running our E2E tests with a snapshot release of this branch (https://github.com/apollographql/client-router-e2e-tests/pull/75) and comparing the compiled output to determine whether this can be shipped at a patch or should target our `release-3.8` branch. (Edit: we're clear to proceed at a patch version bump!)

Upgrade to TypeScript 5.0

---

.changeset/small-tomatoes-explode.md
src/cache/core/cache.ts
src/cache/inmemory/inMemoryCache.ts
src/core/ApolloClient.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/types.ts

This commit allows the default value of the [`assumeImmutableResults` option](https://www.apollographql.com/docs/react/api/core/ApolloClient/#assumeimmutableresults) to be determined by the cache (any implementation of `ApolloCache`), which allows our implementation of `InMemoryCache` to express the safety of assuming `assumeImmutableResults` is `true`, unlocking significant performance savings (fewer defensive deep copies of query results), even if `assumeImmutableResults` is not configured.
Related past PRs/context:
- https://github.com/apollographql/apollo-client/pull/4543
- https://github.com/apollographql/apollo-client/pull/5153
- https://github.com/apollographql/apollo-client/pull/9680
- [Apollo Client 2.6 blog post](https://www.apollographql.com/blog/announcement/frontend/whats-new- …

Allow `ApolloCache` implementations to specify default value for `assumeImmutableResults` client option

---

package-lock.json
package.json
src/cache/inmemory/__mocks__/optimism.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/__tests__/readFromStore.ts

Thanks to https://github.com/benjamn/optimism/pull/504, we no longer need mocking to find out the options used when wrapping functions. This mocking was introduced in #8107, when there was no better option.
Subjectively, this makes tests run a bit faster and more reliably on my machine, though I can't explain why that would be, unless the mocking was adding some kind of overhead to wrapped functions.

Remove all Jest mocking of `optimism` dependency

---

package-lock.json
package.json

Since optimism's version starts with `0.`, every version can break things, so package managers will only match `^0.16.1` to `0.16.1`, and not the newer `0.16.2`. When this happens, we end up depending on two copies of `@wry/context`.
```
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@wry/context"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@wry/context@0.6.1"
info Reasons this module exists
- "<project>#@apollo#client" depends on it
- Hoisted from "<project>#@apollo#client#@wry#context"
info Disk size without dependencies: "100KB"
info Disk size with unique dependencies: "188KB"
info Disk size with transitive dependencies: "188KB"
info Number of shared dependencies: 1
=> Found …
```

Fix optimism dependency

---

src/react/hooks/__tests__/useQuery.test.tsx

I've noticed intermittent test failures on the `main` branch lately (for example, commit https://github.com/apollographql/apollo-client/commit/cdb98ae082ae4c7da6cd6a0fd5ad8457810fceda with [output](https://app.circleci.com/pipelines/github/apollographql/apollo-client/19342/workflows/629b65e1-e06f-49b4-9156-4d25fd565c75/jobs/100103)) that seem at least partially due to the testing anti-pattern of hard-coding request counts, which can change unexpectedly when the event loop is saturated during CI testing (so more 10ms polling intervals happen than expected).

Improve flaky useQuery tests by not hard-coding request counts

---

.changeset/nine-lemons-swim.md
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts

Fixes #9755
Fixes #10174
Fixes #10198
Fixes #10520
Fixes #10533
This PR addresses a few outstanding `useLazyQuery` issues and changes the behavior introduced in #10427 when a component unmounts before a query is fully resolved.
Prior to #10427, components that unmounted before the query was resolved were stuck awaiting the promise indefinitely since promise resolution was dependent on the `useQuery` render cycle to resolve the promise. #10427 attempted to fix this by aborting the promise any time the component unmounted. This change however was a bit too [spicy 🌶️ ](https://github.com/apollographql/apollo-client/issues/10520). Aborting the promise also made it impossible for [some use cases](https://github.com/apollographql/apollo-client/issues/10533) that relied upon promise resolution …

Unmounting a component before a query is resolved via `useLazyQuery` lets the promise resolve instead of aborting the promise.

---

docs/source/migrating/apollo-client-3-migration.mdx

Closes https://github.com/apollographql/apollo-client/issues/6760.
Describes a change in behavior of the fetch policy `cache-and-network` from v2 to v3.
See: https://github.com/apollographql/apollo-client/issues/6760#issuecomment-870904729.
Link to the deployed docs page: https://deploy-preview-10714--apollo-client-docs.netlify.app/migrating/apollo-client-3-migration

chore: document change in cache-and-network behavior in v3

---

docs/source/api/link/apollo-link-retry.md

Related to discussion in https://github.com/apollographql/apollo-client/issues/6920.
Updates the docs to emphasize that Retry Link only receives network errors, and link to relevant section in the docs that describes the pattern for retrying after GraphQL errors via onError link.

chore: update Retry Link docs with reference to onError link

---

docs/source/api/link/apollo-link-subscriptions.md

https://github.com/enisdenjo/graphql-ws/pull/463
Now hosted on a proper website: https://the-guild.dev/graphql/ws.

graphql-ws documentation has moved

---

config/jest.config.js
src/react/components/__tests__/client/Query.test.tsx
src/react/hoc/__tests__/mutations/queries.test.tsx
src/react/hoc/__tests__/mutations/recycled-queries.test.tsx
src/react/hoc/__tests__/queries/errors.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx

Runs remaining HOC/Query skipped tests against React 18, closes https://github.com/apollographql/apollo-client/issues/9970.
Adds conditional assertions depending on the React version, generally in cases where we're asserting on render counts which vary between React versions.

chore: run remaining skipped tests with React 18

---

.changeset/modern-peaches-marry.md
.eslintrc
.prettierignore
config/bundlesize.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/compareResults.ts
src/core/__tests__/equalByQuery.ts
src/core/compareResults.ts
src/core/equalByQuery.ts
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/utilities/graphql/storeUtils.ts
src/utilities/graphql/transform.ts

As foretold in https://github.com/apollographql/apollo-client/issues/8694#issuecomment-1416187035, and building on work started in #10237, this PR adds support for a new query directive called `@nonreactive`, which can be used to mark query fields or fragment spreads, indicating changes to the data contained within the subtrees marked `@nonreactive` should *not* trigger rerendering, allowing parent components to fetch child data without rerendering themselves every time something changes about one/some of the children (assuming the child data is marked `@nonreactive` in the parent query).
This selective insensitivity of parent components to certain child data was originally planned to be a feature of [`useBackgroundQuery`](https://github.com/apollographql/apollo-client/pull/8783), but …

Implement a `@nonreactive` directive for selectively skipping reactive comparisons of query result subtrees

---

src/__tests__/__snapshots__/exports.ts.snap
src/core/index.ts
src/react/cache/QuerySubscription.ts
src/react/hooks/internal/__use.ts
src/react/index.ts
src/testing/react/MockedProvider.tsx
src/utilities/index.ts

With some recent PRs for Suspense, some "risky cross-entry-point" warnings were raised in the build. This PR fixes the newly introduced warnings. NOTE: This does not include the existing risky warnings on `main` since I don't know if those are intentional or not.

Fix risky cross bundle warnings for recent suspense changes

---

config/bundlesize.ts
src/__tests__/__snapshots__/exports.ts.snap
src/link/http/createHttpLink.ts
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/utilities/common/mergeOptions.ts

Resolves a few issues causing 5 type errors post-merge on `release-3.8`.

fix: type errors after merge conflict

---

src/core/ObservableQuery.ts

Makes useSuspenseQuery compatible with changes in https://github.com/apollographql/apollo-client/pull/10597.

fix: failing `useSuspenseQuery` tests

---

docs/source/data/fragments.md

Closes https://github.com/apollographql/apollo-client/issues/10185.
Link to section in deploy preview: https://deploy-preview-10780--apollo-client-docs.netlify.app/data/fragments/#registering-named-fragments-using-createfragmentregistry

docs: adds `createFragmentRegistry` docs

---

.github/workflows/release.yml
.npmrc

Just caught up on GH product announcements and noticed a new integration with GitHub Actions + npm to generate and display a package's provenance on its npm registry page ([blog post](https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/)):
> npm packages built on a cloud CI/CD system (like GitHub Actions) can now publish with provenance, meaning the package has verifiable links back to its source code and build instructions. [...] Once published, packages display provenance on the [registry website](https://www.npmjs.com/package/sigstore#provenance):
We're already publishing via GHA and can easily enable this: [npm docs](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions).
Since changesets issues the `npm publish` …

chore: generate npm provenance statements

---

.github/workflows/release.yml

https://github.com/apollographql/apollo-client/pull/10814 was missing one additional piece of configuration, without which the release workflow errors out: since `permissions` are now configured to set `id-token: write`, `contents: read` must also be set. Without it, GHA is getting a 403 error trying to fetch the repository: https://github.com/apollographql/apollo-client/actions/runs/4822021178/jobs/8588694724

fix: add permissions contents: read in release workflow

---

.github/workflows/release.yml
.npmrc

Adds necessary permissions for Changesets (`contents: write` and `pull-requests: write`) and moves `provenance=true` to be appended to `.npmrc` via the release workflow so that any manual releases won't attempt to release with provenance, which is only possible via CI/CD runner like GitHub Actions.

fix: release workflow also needs pull-requests: write permissions

---

.github/workflows/prerelease.yml
.github/workflows/snapshot-release.yml

Adding provenance config to prereleases and snapshot releases since all releases can display verified commit + release build info on their npm release page. Already verified these settings prior to `3.7.13`'s release.

chore: npm provenance for prereleases and snapshot releases

---

CHANGELOG.md

Improves guidance provided in 3.7.6 CHANGELOG.md entry.

chore: better guidance in v3.7.6 CHANGELOG entry

---

config/bundlesize.ts
src/__tests__/__snapshots__/exports.ts.snap
src/react/cache/QuerySubscription.ts
src/react/hooks/__tests__/useSuspenseQuery.test.tsx

Adds a private refetching field to `QuerySubscription` in order to allow us to differentiate between refetches for previously initialized queries and cases where errors returned in incremental chunks should be returned/not thrown.

fix: throw errors when errors are returned after calling `refetch`

---

docs/source/data/mutations.mdx

Reverts apollographql/apollo-client#9708
Fixes https://github.com/apollographql/apollo-client/issues/10827
Though the `[{ query: MY_QUERY }]` syntax is supported, it behaves differently and less intuitively than an array of query document nodes and/or operation names.  See the linked issue for more context.

Update `refetchQueries` docs with preferred syntax

---

.changeset/strange-drinks-report.md

Adds note about deprecating `suspensePolicy` option in the merged changeset.

Add additional information in changeset

---

src/react/components/__tests__/client/Mutation.test.tsx
src/react/components/__tests__/client/Query.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx

Adjusts some tests where I observed failures on CI as well as some flakiness locally.
Aimed to preserve the structure of the tests and largely did, but removed a couple of `expect` `renderCount` assertions where they seemed to not be adding value (we're already making more useful assertions on the Nth render) _and_ were flaking only in React 18. Conditional logic that made separate assertions React-version specific were equally flaky in these cases: these tests, specifically `Mutation` component tests, seem like good candidates for refactoring, but I decided against investing in a more fundamental rewrite.
I re-ran CI a few times and this branch passed every time (after the initial flake! :D which I believe I've resolved in subsequent commits...)

chore: make tests more resilient to intermittent failures

---

.changeset/grumpy-tips-know.md
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts

This should be merged after #10764 and is the second half of suggestions from #10760 and would address #10650.
It also adds a test to make sure the types actually reflect the real behaviour.

change `UseFragmentResult` to union type

---

docs/source/data/defer.mdx
package-lock.json
package.json

There's an error on docs deploys from main currently due to an old version of typedoc not having TS 5 in its range of peer dependencies. This should unblock deploys.

chore: update typedoc version to unblock docs deploys

---

docs/source/api/react/hooks-experimental.mdx
docs/source/config.json
docs/source/data/defer.mdx
docs/source/data/directives.mdx

Adds a directives page to the Apollo Client docs to centralize information about supported directives in preparation for documenting `@nonreactive` in the `release-3.8` branch.

docs: add directives page and update docs nav

---

docs/shared/useBackgroundQuery-options.mdx
docs/shared/useBackgroundQuery-result.mdx
docs/shared/useReadQuery-result.mdx
docs/shared/useSuspenseQuery-options.mdx
docs/shared/useSuspenseQuery-result.mdx
docs/source/api/react/hooks-experimental.mdx

Closes https://github.com/apollographql/apollo-client/issues/10874.

docs: adds `useBackgroundQuery` and `useReadQuery` docs

---

.changeset/small-pots-applaud.md
package-lock.json
package.json

Closes https://github.com/apollographql/apollo-client/issues/10856.
Unblocks use of alphas/snapshot releases from branches targeting `release-3.8` with Codesandbox - upstream workaround landed in `optimism@0.17.4`.

Use `optimism` 0.17.4

---

.changeset/angry-weeks-marry.md
src/link/http/__tests__/HttpLink.ts
src/link/http/parseAndCheckHttpResponse.ts

When using `@defer` if the response payload contains "---" then the query will fail with an error message such as:
ApolloError: Unterminated string in JSON at position 15378

Fix `@defer` with payload containing "---"

---

docs/source/data/defer.mdx

We recently added and released a `@defer`  directive support in GraphQL Code Generator — https://github.com/dotansimha/graphql-code-generator/pull/9196. This PR updates the Apollo Client documentation on the status of defer support in the Codegen.

Update docs on @defer directive usage with GraphQL Code Generator

---

.git-blame-ignore-revs
docs/shared/DisplayClientError.js
docs/source/errors.mdx

This adds a new page for https://www.apollographql.com/docs/react/errors
For testing this locally, check out `https://github.com/apollographql/docs` in parallel to the `apollo-client` repo and run `npm run start:local -- ../apollo-client` - the page will be available at [local url](http://localhost:3000/errors#{%22version%22:%20%220.0.0-pr-10887-20230522141246%22,%20%22message%22:%208,%20%22args%22:%20[%22foo%22,%20%22bar%22]})
Or, in the [deployed preview link](https://deploy-preview-10909--apollo-client-docs.netlify.app/errors/#{%22version%22:%20%220.0.0-pr-10887-20230522141246%22,%20%22message%22:%208,%20%22args%22:%20[%22foo%22,%20%22bar%22]})

add `errors` docs page

---

.changeset/fast-tomatoes-peel.md
.prettierignore
src/__tests__/__snapshots__/exports.ts.snap
src/__tests__/client.ts
src/cache/inmemory/inMemoryCache.ts
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/index.ts
src/utilities/graphql/DocumentTransform.ts
src/utilities/graphql/__tests__/DocumentTransform.ts
src/utilities/index.ts

Fixes #10936
Moves the `DocumentTransform` class to the `utilities` sub-package to avoid a circular dependency between the `core` and `cache` sub-packages.

Move `DocumentTransform` to `utilities` package to avoid circular dependency

---

.changeset/spicy-waves-shake.md
src/link/batch-http/batchHttpLink.ts

Fixes #10956
The `useGETForQueries` option is not supported in `BatchHttpLink`, but our TypeScript type currently allows this option. This PR removes support for that option in the TypeScript type to ensure devs trying to use this option are properly warned that the option is not supported.

Remove `useGETForQueries` option in `BatchHttpLink.Options`

---

.changeset/odd-pumpkins-care.md
src/link/batch-http/__tests__/batchHttpLink.ts
src/link/batch-http/batchHttpLink.ts
src/link/http/createHttpLink.ts
src/link/utils/__tests__/filterOperationVariables.ts
src/link/utils/filterOperationVariables.ts

Fixes a bug in https://github.com/apollographql/apollo-client/pull/10754 which caused all variables to be removed from `BatchHttpLink` requests. Added the same integration test used in `HttpLink`'s test suite.

fix: variables incorrectly removed in `BatchHttpLink`

---

.changeset/afraid-zebras-punch.md
.changeset/cold-tips-accept.md
src/cache/core/__tests__/cache.ts
src/cache/core/cache.ts
src/cache/core/types/Cache.ts
src/cache/core/types/common.ts
src/cache/inmemory/__tests__/cache.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/types.ts

This PR contains 2 changes that aim to improve the type safety of `fields` in `cache.modify`.
1. Add unique opaque types for the `DELETE` and `INVALIDATE` modifiers, so they are not `any`. This helps make [the `@typescript-eslint/no-unsafe-return` rule](https://typescript-eslint.io/rules/no-unsafe-return/) happy.
2. Add a generic type parameter for the `Modifiers` type to get type inference for `fields` names and values.
I described the changes in the commits. Look at their descriptions for more information.
Both changes only affect TypeScript types. There are no runtime changes.
I understand the 2nd commit is riskier than the first commit. I can split it into 2 PRs if you want to take longer with the review.

Improve TypeScript type-safety of `cache.modify`

---

.changeset/tasty-wasps-relate.md
src/react/cache/SuspenseCache.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/testing/matchers/index.d.ts
src/testing/matchers/index.ts
src/testing/matchers/toHaveSuspenseCacheEntryUsing.ts

I saw this and thought we could save some bundle size here by using Trie directly - with the downside that this is a bit harder to test.
@jerelmiller what are your thoughts on this? If you think this makes sense, I'll try to find a way to rewrite those failing tests.

Suspense cache: use Trie directly

---

.changeset/rude-frogs-destroy.md
.prettierignore
.size-limit.cjs
src/__tests__/__snapshots__/exports.ts.snap
src/core/QueryManager.ts
src/link/http/selectHttpOptionsAndBody.ts
src/link/persisted-queries/index.ts
src/link/subscriptions/index.ts
src/testing/core/mocking/mockLink.ts
src/testing/matchers/toMatchDocument.ts
src/utilities/graphql/print.ts
src/utilities/index.ts

This change should probably not need any new tests.

Use printed query for deduplication, cache print calls

---

.changeset/little-schools-roll.md
src/react/cache/QueryReference.ts
src/react/hooks/__tests__/useSuspenseQuery.test.tsx

This came up in [this Discord message](https://discord.com/channels/1022972389463687228/1120746279849443439/1120746279849443439)

`QueryReference`: check for `resolve`/`reject`

---

.changeset/smooth-clouds-sort.md
.size-limit.cjs
src/react/cache/QueryReference.ts
src/react/cache/SuspenseCache.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/useBackgroundQuery.ts
src/react/hooks/useSuspenseQuery.ts

Closes #10875.
Renames `QueryReference` to `InternalQueryReference` so that the `QueryReference` type name can remain unchanged, which will be referenced in userland code for apps written in TS as is probably much less confusing than any alternative :)
Also adds some basic type docs to `QueryReference` to display in IDEs that support it:
At first I thought maybe `SuspenseCache` should return a `QueryReference` when its `getQueryRef` method is called, but very quickly realized that any hook that returns a `QueryReference` should be responsible for stashing it behind the Symbol instead of within Apollo's Suspense-y internals. I hesitated to rename `queryRef` variable names > `internalQueryRef` everywhere for brevity, but if this is confusing I can make those changes too.

Hide queryRef in a Symbol in `useBackgroundQuery` return value

---

src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/index.ts
src/react/hooks/useBackgroundQuery.ts
src/react/hooks/useReadQuery.ts

To make `useReadQuery` easier to discover, this PR moves the hook to its own file under `src/react/hooks/useReadQuery.ts`.

Move use read query to own hooks file

---

renovate.json

Ignore rollup deps for now - these will either be upgraded in a v4 release or replaced with another bundling toolchain.

chore: ignore rollup deps in renovate config

---

.changeset/olive-pans-report.md
src/react/hooks/useBackgroundQuery.ts
src/react/types/types.ts

It's very likely the APIs and options provided to `useBackgroundQuery` and `useSuspenseQuery` will grow and diverge over time. Currently, the `useBackgroundQuery` hook uses the same options type that `useSuspenseQuery` does, which makes it less flexible to grow over time.
This PR introduces a new `BackgroundQueryHookOptions` type that is used for `useBackgroundQuery` to ensure the options types can grow independently of each other. 
NOTE: #10960 will need to update this new type to include `returnPartialData` and `refetchWritePolicy`, depending on which PR is merged first.

Create separate `BackgroundQueryHookOptions` type and use it for `useBackgroundQuery`

---

docs/shared/useBackgroundQuery-options.mdx
docs/source/api/react/hooks-experimental.mdx

Docs update for `useBackgroundQuery`, merge after https://github.com/apollographql/apollo-client/pull/11018 and https://github.com/apollographql/apollo-client/pull/10960 are released in a future beta.

chore: update docs for `useBackgroundQuery`

---

.changeset/sour-weeks-suffer.md
src/react/cache/QueryReference.ts
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/utilities/promises/decoration.ts

After some time away I came to realize that the behavior of `errorPolicy: 'none'` when an error is returned in an incremental chunk should be considered incorrect. `useSuspenseQuery` throws errors when error policy is none, except for this one case. This made the behavior of this error policy unpredictable.
Now all errors are thrown, regardless of whether they are in the first chunk or an incremental chunk when the `errorPolicy` is set to `none`. To get the previous behavior, set the `errorPolicy` to `all`, which also has the advantage that it keeps partial data.

Throw errors returned from incremental chunks when error policy is `none`

---

.changeset/cool-dogs-applaud.md
.size-limit.cjs
config/processInvariants.ts

This PR prevents the DevTool installation warning to be turned into a documentation link.

keep devTool warning

---

.changeset/ten-cherries-clap.md
.size-limit.cjs
src/core/ObservableQuery.ts
src/react/cache/QueryReference.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/hooks/useBackgroundQuery.ts
src/react/hooks/useSuspenseQuery.ts

Closes #10680
In the current release of the library, changes to some options passed to `useSuspenseQuery` and `useBackgroundQuery` were not applied to the underlying `ObservableQuery`. For example, if someone wanted to change the `errorPolicy` between renders, the updated `errorPolicy` was not applied on the next fetch.
This PR now adds proper behavior when changing any option on these hooks. The following options have these behaviors:
* `errorPolicy` - Apply to the next fetch
* `context` - Apply to the next fetch
* `canonizeResults` - Immediately update `data` to use canonized results
* `returnPartialData` - Apply to the next fetch
* `refetchWritePolicy` - Apply to the next `refetch`
* `fetchPolicy` - Apply to the next fetch

Handle changed suspense query options

---

.size-limit.cjs

We need this in `main` for the check in the 3.8 PR to have something to compare to.

(chore) track production build sizes in 3.7 branch

---

package-lock.json
package.json

Closes https://github.com/apollographql/apollo-client/issues/11041. See lockfile for confirmation that bumping optimism indeed removes duplicate `node_modules/optimism/node_modules/@wry/trie` transitive dependency.
Opening PR intentionally without a changeset since we're preparing for an RC and there is a code freeze in place.

chore: bumps optimism dependency to 0.17.5. Closes #11041.

---

.changeset/seven-needles-remember.md
src/utilities/graphql/operations.ts

#10509 introduced some helpers for determining the type of operation for a GraphQL query. This imported the `OperationTypeNode` from graphql-js which is not available in GraphQL 14. To maintain compatibility with graphql-js v14, this has been reverted to use plain strings.

Update operation helpers to use raw strings instead of OperationTypeNode

---

docs/source/api/react/hooks.mdx

Closes https://github.com/apollographql/apollo-client/issues/10001. See conversation on https://github.com/apollographql/apollo-client/pull/11066 for complete context.
Link to deployed preview: https://deploy-preview-11072--apollo-client-docs.netlify.app/api/react/hooks#subscriptions-and-react-18-automatic-batching

chore: add note about React 18 automatic batching to useSubscription docs

---

.changeset/calm-bears-buy.md
.size-limit.cjs
src/react/cache/QueryReference.ts
src/react/hooks/__tests__/useSuspenseQuery.test.tsx

Fixes #11085
Fixes an issue where a call to `refetch`, `fetchMore`, or changing `skip` to `false` that returned a result deeply equal to data in the cache would get stuck in a pending state and never resolve. This meant the Suspense fallback would be displayed indefinitely.

Fix stuck pending state when refetching a query that returns a result that is deeply equal to data in the cache

---

docs/source/caching/cache-interaction.mdx
docs/source/data/directives.mdx

Something I noticed while browsing another docs PR in the deployed preview.
This PR removes the "preview stage" messaging about `useFragment` and `@nonreactive` in two remaining places and adds minversion annotations.

Remove remaining preview language for `useFragment` and `@nonreactive`

---

docs/source/api/link/apollo-link-remove-typename.mdx
docs/source/config.json

Closes #11020 
Adds a docs page for the `removeTypenameFromVariables` link.
I would really appreciate some good feedback here on the structure and content. For whatever reason, I found this difficult to talk about in a way that makes sense. Any and all feedback that can be provided to improve the information on this page would be much appreciated. Thanks!

Add docs for `removeTypenameFromVariables` link

---

.github/CODEOWNERS

Updating `/docs/` codeowners to https://github.com/orgs/apollographql/teams/docs.
(Just me for now, but hopefully another team member soon!)

Update /docs codeowner to Apollo docs team

---

.changeset/honest-ads-act.md
.size-limit.cjs
src/react/components/__tests__/client/Mutation.test.tsx
src/react/components/__tests__/client/Query.test.tsx
src/react/components/__tests__/client/Subscription.test.tsx
src/react/hoc/__tests__/mutations/queries.test.tsx
src/react/hoc/__tests__/mutations/recycled-queries.test.tsx
src/react/hoc/__tests__/queries/errors.test.tsx
src/react/hoc/__tests__/queries/lifecycle.test.tsx
src/react/hoc/__tests__/queries/loading.test.tsx
src/react/hoc/__tests__/queries/skip.test.tsx
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts

Ensures that `useQuery` triggers rerenders faster or at the same time as `useFragment`.
Before this change, `useQuery` used a `useState` setter callback to trigger a
rerender instead of the `useSyncExternalState` `forceRender` callback.
Due to a bug in React (https://github.com/facebook/react/issues/25191), these renders
are not batched together.
That could lead to situations where a child accessing a fragment that was evicted
from the cache would rerender (without data) before a parent `useQuery` component
had a chance to unmount the child.
After this change, `useQuery` and `useFragment` still don't rerender exactly at the same moment
in time - but it is guaranteed that `useQuery` will always rerender before `useFragment` will,
which should fix most problems.
I know, it's late for this, …

Adjust relative timing of `useFragment` and `useQuery`

---

docs/source/api/cache/InMemoryCache.mdx
docs/source/caching/cache-interaction.mdx
docs/source/data/queries.mdx
docs/source/local-state/local-state-management.mdx

This PR replaces uses of "available in version ..." with the new [`<MinVersion>` component](https://apollograph.slack.com/archives/C0721M2F6/p1690243600979049?thread_ts=1690218529.773819&cid=C0721M2F6).
It's likely not comprehensive, but at least replaces previous mentions of versions. (Searched for "available", "version", and "<=" in .mdx files.)

Use MinVersion component

---

docs/shared/useBackgroundQuery-options.mdx
docs/shared/useSuspenseQuery-options.mdx
docs/source/api/react/hooks.mdx
docs/source/data/suspense.mdx

I hope that does it justice - we have no real story behind `skip` itself, the option is kinda hidden - so I had no real pattern to follow here.
Closes #11094

document skipToken

---

docs/source/data/fragments.md

Fixes a broken link for the fragment registry in the useFragment section.
^ n/a for the above

useFragment Docs: Fixing broken link

---

docs/shared/useFragment-options.mdx

`returnPartialData` option of `useFragment` has been deprecated in https://github.com/apollographql/apollo-client/pull/10764, so remove it from the docs as well.
https://github.com/apollographql/apollo-client/pull/10764

Docs: Remove `returnPartialData` from `useFragment` options

---

docs/source/api/link/persisted-queries.mdx

This PR fixes two small language issues in the Persisted Queries docs:
- Removes use of "trusted" to make terminology around the feature more concise
- Names the `generatePersistedQueryIdsFromManifest` function correctly in code sample descriptions. (Code samples use this function, but it was called `generatePersistedQueryIdsAtRuntime`, another utility function in the library)

Correct language

---

.circleci/config.yml
.eslintrc
.git-blame-ignore-revs
docs/source/development-testing/reducing-bundle-size.mdx
package.json
src/core/QueryManager.ts

To ensure we don't accidentally merge unformatted code, this adds a check to ensure prettier formatting is applied. Helpful for external contributors who may or may not have auto formatting in their editor.

Enforce prettier formatting in PRs

---

.changeset/odd-beers-perform.md
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts

Fixes #11184 
Fixes an issue where the wrong result was returned when switching back to initial variables with a cached result before the request for previous changed variables finished.
Prior to [v3.7.11](https://github.com/apollographql/apollo-client/releases/tag/v3.7.11), changing variables would abort a previous request, which meant there was no cache update for the previous variables. This behavior had some edge cases and resulted in some race condition bugs. This was fixed by #10597, but because #10597 no longer aborted requests, the previous request would complete and the cache would be written, but the broadcasted result would be incorrectly associated with the current variables.

Fixes race condition when changing back to initial variables before request finishes

---

docs/source/data/defer.mdx
docs/source/data/directives.mdx
docs/source/data/subscriptions.mdx
docs/source/integrations/react-native.md

Adds missing docs that describe the steps needed to use `@defer` and/or multipart subscriptions over HTTP in a React Native app.

chore: add documentation about polyfills needed to use text streaming in RN

---

.changeset/slow-gorillas-sniff.md
src/core/ApolloClient.ts

This delays devtools registration until after the `ApolloClient` constructor has finished setting up the Apollo Client instance fully. 
As the new registration can happen synchronously if the devtools extension is already loaded at the time the `ApolloClient` instance is created, previously this would add to a `Cannot read properties of undefined` error, as the `ObservableQuery` had not been constructed yet.
Fixes #11192
Can be verified with these CodeSandboxes:
* [Apollo Client 3.8.2](https://mtl279.csb.app/) - [code](https://codesandbox.io/s/11193-mtl279?file=/src/index.mjs)
* [@apollo/client@0.0.0-pr-11193-20230905102117](https://55jyk2.csb.app/) - [code](https://codesandbox.io/s/11193-fixed-55jyk2?file=/src/index.mjs)

Call devtools registration after ApolloClient is fully set up

---

.changeset/tall-otters-wave.md
docs/shared/DisplayClientError.js
src/utilities/globals/invariantWrappers.ts

I noticed that someone shared an error link in the form 
https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.0-rc.2%22%2C%22message%22%3A12%2C%22args%22%3A%5B%5D%7D
which leads to this error page:
I could reproduce a code path that didn't serialize the args correctly.
This PR changes a few things:
* For `invariant.log` etc., error arguments are now serialized correctly in the link to the error page
* The error message is displayed with `lineHeight: "normal", whiteSpace: "pre-wrap"`
* The "condition" is now hidden if it is empty (but not removed - it still takes up space to prevent layout jumping as good as possible)
The generated link now looks like
https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.3%22%2C%22message%22%3A12%2C%22args%22%3A%5B%22fields%22%2C%22User%22%2C%22%22%2C%22Us …

Fix up error message argument wrapping and Error page styling

---

.changeset/shaggy-ears-scream.md
.size-limit.cjs
src/__tests__/client.ts
src/cache/inmemory/__tests__/client.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts
src/react/hooks/__tests__/useQuery.test.tsx

This PR fixes issue #9293 by ensuring all cache-friendly fetch policies (including `cache-{first,only,and-network}` and `network-only` but excluding `no-cache`) return result data after re-reading the data from the cache, even when the data are incomplete (fixing #9293), so any custom `read` functions (or other cache logic) can be applied consistently whether or not the cache data are complete. I've added a new test that exercises all the fetch policies, since test coverage was previously inadequate in this area.
While diagnosing this problem, I noticed `QueryInfo#markResult` previously updated `result.data` using a destructive mutation, which could easily go unnoticed by the caller of `markResult`, so I refactored that code a bit to return a new `result` object instead of modifying the …

Prevent `QueryInfo#markResult` mutation of `result.data` and return cache data consistently whether complete or incomplete

---

.api-reports/api-report-cache.md
.api-reports/api-report-core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/beige-geese-wink.md
.size-limit.cjs
src/__tests__/__snapshots__/exports.ts.snap
src/cache/index.ts
src/cache/inmemory/__tests__/key-extractor.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/object-canon.ts
src/cache/inmemory/policies.ts
src/cache/inmemory/readFromStore.ts
src/cache/inmemory/writeToStore.ts
src/utilities/common/__tests__/canonicalStringify.ts
src/utilities/common/canonicalStringify.ts
src/utilities/graphql/storeUtils.ts
src/utilities/index.ts

Because the [`ObjectCanon`](https://github.com/apollographql/apollo-client/blob/main/src/cache/inmemory/object-canon.ts) happens to produce canonical objects whose keys have been sorted alphabetically/lexicographically, it seemed convenient and efficient for implementing a stable `JSON.stringify` utility (see PR #8222), but the additional memory overhead of fully canonizing (duplicating) the objects was probably not justified, especially since (as this PR suggests) an independent implementation of `canonicalStringify` can be even faster while using much less memory.

Decouple `canonicalStringify` from `ObjectCanon`

---

.changeset/lemon-tigers-promise.md
.size-limit.cjs
src/react/cache/QueryReference.ts
src/react/hooks/__tests__/useSuspenseQuery.test.tsx

Fixes #11270
The `autoDisposeTimeoutMs` configurable value for Suspense hooks was created to ensure components that suspend but never remount would get properly cleaned up after the timeout duration. This works well to cleanup after components that never mount again after initially suspending (such as a user interaction that hides the element while suspended). This timer started when the query ref was initialized and disposed of regardless of whether the initial promise had settled or not. This meant that when the request finished after the configured timeout, the component would suspend indefinitely since nothing was around to resolve/reject the promise leaving it in a pending state forever.
This PR adjusts the start of the dispose timer to wait until the initial promise is settled. This …

Fix some cases where the auto dispose timeout could cause components to suspend indefinitely

---

.changeset/heavy-camels-double.md
src/dev/loadErrorMessageHandler.ts
src/utilities/globals/__tests__/invariantWrappers.test.ts

I call `loadErrorMessages()` but not `loadDevErrorMessages()` on application startup. When a "dev" error code is encountered, I get the following error:
```
| TypeError: Cannot read properties of undefined (reading 'message')
|     at handler (.../node_modules/@apollo/client/dev/dev.cjs:613:41)
|     at getErrorMsg (.../node_modules/@apollo/client/utilities/globals/globals.cjs:85:44)
|     at Function.warn (.../node_modules/@apollo/client/utilities/globals/globals.cjs:48:16)
|     at Object.useSubscription (.../node_modules/@apollo/client/react/hooks/hooks.cjs:550:63)
|     ...
```
It seems reasonable for unloaded error codes revert to the fallback, rather than causing the app to crash.

Don't crash if some (but not all) Error Codes are loaded

---

docs/source/development-testing/testing.mdx
src/testing/react/__tests__/MockedProvider.test.tsx

Fixes #11285.
Also includes two new tests to ensure the proposed way of testing actually works (and keeps working).

Add delay in docs for loading state testing

---

.api-reports/api-report-react.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report.md
.changeset/good-experts-repair.md
src/react/hooks/index.ts
src/react/hooks/useReadQuery.ts

The `useReadQuery` hook currently uses type inference for the return type from the hook. For consistency, I added a `UseReadQueryResult` type that can be used to get a typed return type rather than having to rely on `typeof useReadQuery`, which doesn't allow the use of the generic `TData` type argument.

Add an explicit return type for `useReadQuery`

---

.circleci/config.yml

This updates the version of the circleci-secops-orb used by apollo-client. This change will address ongoing issues with running Gitleaks scans on PRs from forks. 
This PR was open by @peakematt via a second Github account to validate that gitleaks will now run successfully on a pull request from a fork.

update circleci secops orb

---

package.json

Seems CI is failing since it's now using npm 10. Bumping the version.

bump engines field to include npm 10

---

.api-reports/api-report-cache.md
.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/stupid-chairs-wait.md
src/cache/core/types/common.ts

#11206 used the TypeScript syntax `infer X extends Y` that was introduced in TS 4.8.
This caused some problems for some users, so we are rolling back to a more backwars-compatible (albeit slightly less performant) type.

work around TS 4.8-specific `infer X extends Y`

---

docs/source/integrations/react-native.md

Without the `http://` prefix, a "No suitable URL request handler found" error will occur. See https://stackoverflow.com/questions/38099684/no-suitable-url-request-handler-found This really confused me and made me spend a lot of time trying to figure out what went wrong. The other example in the same document already includes this prefix properly.

Fix link to localhost in react-native.md

---

.api-reports/api-report-core.md
.api-reports/api-report-link_batch-http.md
.api-reports/api-report-link_http.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/wild-dolphins-jog.md
.size-limit.cjs
src/cache/inmemory/inMemoryCache.ts
src/utilities/graphql/print.ts

The first of a bunch of small memory-related PRs.

Add `reset` method to `print`, hook up to `InMemoryCache.gc`

---

.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/hot-ducks-burn.md
.size-limit.cjs
src/cache/inmemory/inMemoryCache.ts
src/utilities/graphql/DocumentTransform.ts

An alternative implementation here would be to leave the `reset` method off `DocumentTransform` and just re-create the transform when `.gc` is called.
@jerelmiller what are your thoughts?

Add `reset` method to `DocumentTransform`, hook `InMemoryCache.addTypenameTransform` up to `InMemoryCache.gc`

---

src/tsconfig.json
tsconfig.tests.json

This creates a new `tsconfig.json` in `src` that will be picked up by VSCode and apply the rules of the parent `tsconfig.json` to tests as well - without tooling that relies on the `<root>/tsconfig.json` (e.g. the build steps) having to pick up all the test files.
It should also fix the matcher inclusion problem (`toRerender` in `expect(ProfiledHook).not.toRerender();` being unknown unless another editor window has the `matches/index.d.ts` open).
I'm opening this PR against the `strict: true` PR as that PR fixes a lot of problems we'd otherwise see in our tests.

Introduce IDE-only `tsconfig.json` to check tests too.

---

.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
src/testing/core/mocking/mockLink.ts
src/testing/react/MockedProvider.tsx

Doing this as a PR to check in CI if this fixes up all the type problems we got by merging `main` into `3.9`.
The problem seems to have been introduced by adding the `variableMatcher?: VariableMatcher<TVariables>;` property and also referencing `TVariables` in the `ResultFunction` signature for `result`, both over in #11178.

fix up type in 3.9 branch after merge

---

.api-reports/api-report-cache.md
.api-reports/api-report-core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/thick-mice-collect.md
src/cache/inmemory/entityStore.ts
src/cache/inmemory/readFromStore.ts

This is just a clarification to internal types to make it more apparent where/how `keyMaker` is used.
I don't expect this has been used by anyone outside of the AC core, but in case it was used in other places, I've kept the original "generic" overload, but added a `@deprecated` comment with a note to please use a custom `Trie` instance instead.

Clarify types of `EntityStore.makeCacheKey`

---

docs/source/data/queries.mdx

Hello! I found copy-pasting these bits of code from the docs to be confusing since I would get broken dog images as a result of using it. Turns out it was because refetch was sending `new_dog_breed` as a variable which isn't a dog breed.
Anyways, I think this will hopefully help a future newb like me not spend more time than necessary on this section, chasing an unknown bug. There is also already a more [in-depth explanation](https://www.apollographql.com/docs/react/data/queries/#providing-new-variables-to-refetch) in the docs about how this would work.

Doc update: Remove { breed: 'new_dog_breed' } from queries.mdx

---

.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/quick-hats-marry.md
.size-limits.json
src/core/QueryManager.ts
src/core/__tests__/QueryManager/index.ts

This came up in https://github.com/apollographql/apollo-client-nextjs/issues/103#issuecomment-1823186926 - so far, `defaultContext` was only applied on queries, which was an oversight on my part.

ensure `defaultContext` is also used for mutations and subscriptions

---

.size-limits.json
docs/source/api/link/apollo-link-remove-typename.mdx

We've had a number of complaints that users don't know how to use the [`removeTypenameFromVariables` link](https://www.apollographql.com/docs/react/api/link/apollo-link-remove-typename). For example, in recent feedback from our docs pages:
> Rating: :star: 1/5
> Comment: The topic doesn’t solve the problem. It doesn’t event show the way of using this func
This PR seeks to add some additional example code to clarify that this is meant to be used in the link chain.

Add more documentation on how to use the `removeTypenameFromVariables` link to reduce confusion

---

.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/mighty-coats-check.md
.size-limits.json
docs/shared/mutation-options.mdx
src/__tests__/optimistic.ts
src/cache/core/types/common.ts
src/core/QueryManager.ts
src/core/watchQueryOptions.ts

This PR updates the behaviour of the `optimisticResponse` functional property in mutations to support returning `null`, which will cause the optimistic update to be skipped / bailed out from.
This is useful to support an optimistic response _only_ when certain variables are provided to the mutation. For example, in my use case, I only wish to perform an optimistic update when a specific variable is _not_ included, as I can't reliably compute the result on the client when it is.
Currently, I can workaround this by writing an additional query without an `optimisticResponse` property for mutations which use this variable, and then conditionally calling one of the two mutations based on the input variables. However, this results in duplicate code and I feel this small API change would make …

feat: Allow returning `IGNORE` sentinel from `optimisticResponse` functions to support bailing-out from the optimistic update

---

src/core/ObservableQuery.ts
src/core/QueryInfo.ts
src/react/cache/QueryReference.ts
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx

fixes test "useReadQuery auto-resubscribes the query after its disposed", ~but breaks the next one 😓~ (fixed it 🎉 )
CC @jerelmiller take a look :)

change re-subscription order

---

.changeset/fuzzy-eyes-lick.md

Removes docs changeset created by https://github.com/apollographql/apollo-client/pull/11364. We don't release new client versions for docs-related changes, so I'd like to avoid the changeset here.

Remove docs changeset to avoid patch change

---

.changeset/wise-news-grab.md
.size-limits.json
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/useBackgroundQuery.ts

Thanks to the work in https://github.com/apollographql/apollo-client/pull/11412, we no longer need to `retain` the `queryRef` produced by `useBackgroundQuery` since this is handled in `useReadQuery` for us. This means that a `queryRef` not consumed by `useReadQuery` within the given `autoDisposeTimeoutMs` will now be auto disposed, removing the need for the query to hang out as active while not used. https://github.com/apollographql/apollo-client/pull/11412 enabled the ability to auto resubscribe to a disposed `queryRef`, so when the `queryRef` is consumed after it has been disposed, it will automatically resubscribe.

Remove `retain` call from `useBackgroundQuery` to allow for auto disposal

---

.api-reports/api-report-react_components.md
.api-reports/api-report-react_hoc.md
.changeset/chatty-comics-yawn.md
src/react/components/Mutation.tsx
src/react/components/Query.tsx
src/react/components/Subscription.tsx
src/react/hoc/graphql.tsx
src/react/hoc/mutation-hoc.tsx
src/react/hoc/query-hoc.tsx
src/react/hoc/subscription-hoc.tsx
src/react/hoc/withApollo.tsx

The wording was taken from the docs:
https://www.apollographql.com/docs/react/api/react/hoc/

add deprecation warnings for HOC and Render Prop docblocks

---

.changeset/late-rabbits-protect.md
.size-limits.json
src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/react/hooks/useLoadableQuery.ts

Thanks to the work in https://github.com/apollographql/apollo-client/pull/11412, we no longer need to `retain` the `queryRef` produced by `useLoadableQuery` since this is handled in `useReadQuery` for us. This means that a `queryRef` not consumed by `useReadQuery` within the given `autoDisposeTimeoutMs` will now be auto disposed, removing the need for the query to hang out as active while not used. https://github.com/apollographql/apollo-client/pull/11412 enabled the ability to auto resubscribe to a disposed `queryRef`, so when the `queryRef` is consumed after it has been disposed, it will automatically resubscribe.

Remove `retain` from `useLoadableQuery` to allow for auto disposal

---

docs/source/performance/optimistic-ui.mdx

Adds docs for https://github.com/apollographql/apollo-client/pull/11410.

chore: add docs for skipping an optimistic update via optimisticResponse

---

.changeset/fresh-jeans-retire.md
src/testing/core/mocking/mockLink.ts
src/testing/react/__tests__/MockedProvider.test.tsx

Closes https://github.com/apollographql/apollo-client/issues/11471.
When we [updated the docs](https://github.com/apollographql/apollo-client/pull/11287) to suggest developers use `delay: Infinity` to test loading states, a test was added to verify that this actually works. In the test, the mock response contained neither an `error` or `result` which was triggering an uncaught error in `MockLink` (`Mocked response should contain either result or error`), so the test was lying to us: a mock response with `delay: Infinity` resolves after 1 second[^1] if a result is present.
In the first commit here, a fixed up test fails with `delay: Infinity` but passes with `delay: 30000`.
We can still use `delay: Infinity` value to produce this forever-loading behavior, but we'd have to add an explicit …

fix: behavior of delay: Infinity in a mock response

---

.circleci/config.yml

This PR adds or updates the necessary configuration to enable [Semgrep](https://semgrep.dev/docs/semgrep-code/overview/) to run on PRs on this repo. The Apollo Security team uses Semgrep to test our source for potential security vulnerabilities.
Once this is accepted and merged, the Security team plans to make a passing Semgrep check a requirement for PRs to merge into this repo. This will prevent net-new severe issues from being introduced. The job proposed by this PR runs in a diff-aware mode, so it will only alert if net-new issues are introduced in a branch.
In the event that a severe issue _is_ detected on a PR, the CI job will add a comment to the PR associated with the detection to provide instructions on how to properly resolve the detection. The comment added to PRs will also …

ci: SECOPS-2525 - add semgrep job

---

.api-reports/api-report-utilities.md
.changeset/pink-apricots-yawn.md
.size-limits.json
src/utilities/caching/sizes.ts

Based on some internal testing, we've decided to increase the default memory limits for `inMemoryCache.executeSelectionSet` and `inMemoryCache.executeSelectionSetArray`.

Increase default memory limits

---

.changeset/soft-roses-sit.md
.size-limits.json
src/react/cache/QueryReference.ts
src/react/hooks/__tests__/useSuspenseQuery.test.tsx

This PR resolves a bug where `useSuspenseQuery` with a `cache-and-network` fetch policy does not update its `networkStatus` when there's a concurrent `useReadQuery` with the same fetch policy. 
There is no test code in the cache folder, so I was unable to write a test, please advise if this is necessary.
I am attaching a reproduction of the error instead of the test code.
The expected result is that all networkStatus should be 7 (networkStatus.ready).
[repro codesandbox](https://codesandbox.io/p/devbox/vibrant-banzai-38y7nc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOU …

fix: `networkStatus` update Issue in `useSuspenseQuery` with `cache-and-network` policy

---

.changeset/spotty-bats-march.md
docs/source/caching/cache-configuration.mdx
src/cache/inmemory/__tests__/__snapshots__/writeToStore.ts.snap
src/cache/inmemory/__tests__/writeToStore.ts
src/cache/inmemory/writeToStore.ts

Fixed: https://github.com/apollographql/apollo-client/issues/11482

Fix cache override warning output

---

renovate.json

Since we lint our codebase for formatting violations against `prettier`, updates to that package may result in the need to reformat our codebase. I'm taking this out of the renovate rotation so that we can make this update by hand if/when we are ready to upgrade to the next version, which would include adding an entry to `.git-blame-ignore-revs`.

Ignore `prettier` in renovate PRs

---

.changeset/six-rocks-arrive.md

Adding changeset to bump rc version to include changes from [3.8.10](https://github.com/apollographql/apollo-client/releases/tag/v3.8.10)

Add changeset to bump rc version

---

.github/ISSUE_TEMPLATE/bug.yml

Adds a field to our bug issue template that asks for the apollo client version.

Add field asking for `@apollo/client` version to our bug issue template

---

src/core/ApolloClient.ts

Closes #11506
Adds a doc comment for the `headers` option that mentions that it will be ignored when using the `link` option.

Add doc comment for `headers` property on ApolloClient

---

docs/source/data/error-handling.mdx

console.error also logs the stack trace and the error cause. This will provide a lot more information to what went wrong.
Before this change:
`[Network error]: TypeError: fetch failed`
After this change:
```
[Network error]:  TypeError: fetch failed
at Object.fetch (node:internal/deps/undici/undici:11372:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
cause: Error: getaddrinfo ENOTFOUND xxx.example.com
at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'xxx.example.com'
}
}
```
As you can see, after this change it's very clear that the endpoint is not available.

Change console.log to console.error for network error

---

.api-reports/api-report-react.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_internal.md
.api-reports/api-report.md
.prettierignore
docs/shared/Overrides/UseLoadableQueryResult.js
docs/source/api/react/hooks.mdx
docs/source/api/react/preloading.mdx
docs/source/config.json
src/react/hooks/index.ts
src/react/hooks/useLoadableQuery.ts
src/react/hooks/useQueryRefHandlers.ts
src/react/internal/cache/QueryReference.ts
src/react/query-preloader/createQueryPreloader.ts

This is a continuation of https://github.com/apollographql/apollo-client/pull/11512 that adds the necessary code-level documentation that will be used to document the new APIs in our editors and docs.

Document new React APIs in code - Part 2 of 2

---

docs/shared/ApiDoc/DocBlock.js
docs/shared/ApiDoc/Function.js
docs/shared/ApiDoc/PropertySignatureTable.js
docs/shared/ApiDoc/index.js

Adds a component to our documentation components that will show features marked as alpha/beta with the `<ExperimentalFeature />` component exported by the docs repo.
(NOTE: These screenshots are not of real alpha/beta features. I added some for testing this change)

Add component for API members that are marked as alpha/beta

---

.size-limits.json
docs/source/data/suspense.mdx

Closes https://github.com/apollographql/apollo-client/issues/11491
Closes [#11493](https://github.com/apollographql/apollo-client/issues/11493)
Closes https://github.com/apollographql/apollo-client/issues/11494
Adds new sections to our [suspense docs](https://www.apollographql.com/docs/react/data/suspense) for `useLoadableQuery`, `createQueryPreloader`, and `useQueryRefHandlers`.
NOTE: This only addresses the "guide" part of the documentation. A followup PR to ensure the API documentation for the hook is available (options, return values, etc.). This may require edits to code and will fall in line with the changes in https://github.com/apollographql/apollo-client/pull/11381

Document new React APIs in 3.9 - Part 1 of 2

---

.github/workflows/prerelease.yml

Avoids opening a PR after we've exited prerelease mode and before the release branch has been merged. Example of erroneous PR: https://github.com/apollographql/apollo-client/pull/11538

chore: only open a prerelease version packages PR when still in prerelease mode

---

.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_internal.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.changeset/wet-jars-laugh.md
.size-limits.json
src/core/QueryManager.ts

~Closes https://github.com/apollographql/apollo-client/issues/11543.~
Edit: unrelated to the above issue but still cleanup nonetheless :)

fix: remove error thrown by inFlightLinkObservables

---

docs/shared/ApiDoc/EnumDetails.js
docs/shared/ApiDoc/Function.js
docs/shared/ApiDoc/ParameterTable.js
docs/shared/ApiDoc/PropertySignatureTable.js
docs/shared/ApiDoc/getInterfaceReference.js
docs/shared/ApiDoc/index.js
netlify.toml

Reverts apollographql/apollo-client#11527
Unfortunately there are a few too many cases where we aren't able to parse the nodes due to complex types, so I'm reverting this for now in an effort to ensure docs PRs can continue to be merged.
Here is the log for reference: https://app.netlify.com/sites/apollo-monodocs/deploys/65bae51fbe2f2506e3406166

Revert "Replace Generics in PropertySignatureTable"

---

.changeset/young-dots-breathe.md
src/react/hooks/internal/useLazyRef.ts

Fixes https://github.com/apollographql/apollo-client-nextjs/issues/186
`useLazyRef` was introduced by https://github.com/apollographql/apollo-client/pull/11464 and released in in [`3.8.9`](https://github.com/apollographql/apollo-client/releases/tag/v3.8.9), but the import had not been updated to `rehackt` before our 3.9 release causing some import issues in our experimental package.

Update import to `rehackt` in `useLazyRef`

---

netlify.toml

Now that our docs are generated from docblocks, we should also build a deploy preview when something in src changes.

chore: rebuild docs on src changes

---

.changeset/tiny-vans-draw.md
src/testing/core/mocking/__tests__/mockLink.ts
src/testing/core/mocking/mockLink.ts
src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap

Without the changes in this PR mocks always require a result or an error for a response. However, when an infinite delay is specified, that response is never returned, so it might as well be omitted.
With the changes in this PR omission of `result` and `error` no longer causes an error, when a delay of `Infinity` is specified.
```ts
const mocks = [
{
delay: Infinity
request: {
query: GET_DOG_QUERY,
variables: {
name: "Buck"
}
},
result: {                                             // all of this
data: {                                             // makes no
dog: { id: "1", name: "Buck", breed: "bulldog" }  // sense with
}                                                   // an infinite
}                                                     // delay
}
];
it("renders without error", async …
```

feat(mocking): make response error and result not required when delay is infinite

---

.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.changeset/dirty-insects-return.md
src/testing/core/mocking/__tests__/mockLink.ts
src/testing/core/mocking/mockLink.ts

fix: strengthen MockedResponse.newData type (#11584)

---

docs/shared/useSuspenseQuery-result.mdx

I was re-reading the docs for the first time in a while and noticed this typo. Thanks!

docs: remove errant comma in useSuspenseQuery docs

---

docs/source/data/suspense.mdx

Correct name of query in example. These are supposed to be the same right?
GET_DOG_QUERY_PARTIAL -> PARTIAL_GET_DOG_QUERY

fix(documentation): use correct query names in partial example

---

.changeset/rich-hotels-sniff.md
.size-limits.json
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/internal/cache/QueryReference.ts
src/testing/internal/scenarios/index.ts

Fixes #11315
Due to the mechanics of `fetchMore`, the cache broadcast happens after the concast promise is resolved. This interferes with our [check](https://github.com/apollographql/apollo-client/blob/fc949bb907bf1f3efc5ea102d62de847e4af043c/src/react/internal/cache/QueryReference.ts#L382-L384) on promise resolution to see if we need to emit the result to avoid some situations where the promise might otherwise stay pending forever (#11086). Unfortunately this meant that we emitted a result, then the cache result was broadcasted resulting in an additional re-render.
This fix adds a `setTimeout` around the check to try to allow `QueryInfo.notify` to run first, which is itself run inside a `setTimeout`.

Fix additional re-render when calling `fetchMore` from `useSuspenseQuery` when using `startTransition`.

---

docs/source/data/suspense.mdx

Very minor copyedits on 3.9 docs—mostly breaking up long sentences and paragraphs and making things more concise. (Sorry it took me so long to get to them!)
As a side note, I was able to review the [Cache Sizes doc earlier](https://www.apollographql.com/docs/react/caching/memory-management/#cache-sizes), but am just noticing the double quotations on some of the [cache options](https://www.apollographql.com/docs/react/caching/memory-management/#cache-options). Is this intended?

docs: minor 3.9 docs copyedits

---

.changeset/early-pens-kick.md
.size-limits.json
src/react/hooks/internal/__tests__/useRenderGuard.test.tsx
src/react/hooks/internal/useRenderGuard.ts

Since we don't know what exactly might be change with React 19, this change makes our `useRenderGuard` slightly more resilient, and if it breaks, it does so in a less interrupting way (always return `false` instead of always `true`).
~~It should also save one byte of bundle size ;)~~ But then it gzips 2 bytes bigger 🤦

Make `useRenderGuard` more resilient to changes in React internals.

---

docs/source/performance/optimistic-ui.mdx

This feature is not available in version <3.9.0. This PR updates the docs with a `minVersion`.
After:

chore: add minVersion to docs for bailing out of optimistic updates

---

.changeset/flat-singers-kiss.md
.size-limits.json
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts

Fixes #11688 
Ensures that changing `from` will rerender immediately with the value that matches the updated `from` option. We do have an [existing test](https://github.com/apollographql/apollo-client/blob/9c5a8cee40900125fe5037d573e6daedd619075f/src/react/hooks/__tests__/useFragment.test.tsx#L1216-L1360) for this, but because it uses `waitFor`, we unfortunately didn't catch  the wrong value returned on the render when the options changed. A new test has been added that uses `profileHook` to ensure we are checking renders themselves.

Fix issue with `useFragment` where it returned wrong data when changing the `from` option

---

netlify.toml

As a side effect of https://github.com/apollographql/odyssey/pull/976/files, preview deploys are currently failing (example: https://app.netlify.com/sites/apollo-client-docs/deploys/65f88d0e78880e00084cd36f, see private Slack thread [here](https://apollograph.slack.com/archives/C0721M2F6/p1710521565467909) for more info.)
This PR removes the `NODE_VERSION` specified in `netlify.toml` so it can be set via Netlify GUI.

chore: remove NODE_VERSION from netlify.toml to unblock preview deploys

---

.github/workflows/prerelease.yml

Fixes issue with unreleased changesets from main triggering the versioning step immediately before a new release goes out if the changeset's slug isn't included in `pre.json`.

chore: skip prerelease versioning step if head commit contains version packages commit

---

.changeset/tasty-hotels-press.md
.size-limits.json
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/internal/cache/QueryReference.ts

Fixes #11708
Fixes an issue where setting a default `watchQuery` option in `defaultOptions` on the `ApolloClient` constructor had the potential to break `startTransition`. When using a default option, the [`queryRef.didChangeOptions` check](https://github.com/apollographql/apollo-client/blob/591c2b61e535240a488ba765485d9444ac47c7b8/src/react/hooks/useSuspenseQuery.ts#L225) would always return `true` if the same option were not also passed to the hook directly. Because this returned `true`, we'd use a [different promise](https://github.com/apollographql/apollo-client/blob/591c2b61e535240a488ba765485d9444ac47c7b8/src/react/hooks/useSuspenseQuery.ts#L226) than what React expected for the transition, which ended up showing the Suspense fallback instead of keeping the current UI on screen. …

Fix issue where setting `defaultOptions` would sometimes break `startTransition` for suspense hooks

---

.github/workflows/change-prerelease-tag.yml
.github/workflows/exit-prerelease.yml
.github/workflows/prerelease.yml

Uses github bot token to push to protected branches via workflow dispatch events or push event to protected `release-*` branches for:
* entering prerelease mode
* switching prerelease tags
* exiting prerelease mode

Use bot token in prerelease workflows

---

.github/workflows/prerelease.yml

fix: skip PR creation if no prerelease changesets exist

---

.github/workflows/change-prerelease-tag.yml
.github/workflows/exit-prerelease.yml

`stefanzweifel/git-auto-commit-action` sets the git `author` which appears to break our CLA. Manually setting the git user name and email to the default `github-actions[bot]` values should allow the CLA check to pass.

chore: configure git user directly in prerelease workflows

---

.github/workflows/snapshot-release.yml

Fixes failing snapshot release action with multiple changesets, see https://github.com/apollographql/apollo-client/actions/runs/8510609697/job/23308544668.
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings for docs on using mutli-line strings with `GITHUB_OUTPUT` GHA env variable.

chore: use delimiter in accorance with docs to handle strings with newlines in snapshot release action 

---

.github/workflows/devtools-errorcodes.yml

This is one of those where we won't know if they work until we merge them 😞

Devtools - Trigger Error Code PR after npm Release

---

.api-reports/api-report-react.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_internal.md
.api-reports/api-report.md
.changeset/tiny-bugs-tap.md
.changeset/twelve-apples-vanish.md
docs/source/data/suspense.mdx
src/react/internal/cache/QueryReference.ts
src/react/query-preloader/createQueryPreloader.ts

Removes the `@alpha` designation for `createQueryPreloader` and `queryRef.toPromise()` in preparation for 3.10

Remove alpha designation for query preloading

---

config/FixJSDOMEnvironment.js
src/link/persisted-queries/__tests__/persisted-queries.test.ts

This is a follow-up to #11751 
Using the native `AbortController` previously created a memory leak in our tests, because `mock-fetch` keeps a history of requests - which referenced the `signal` - and the `signal` keeps a reference to the `AbortController`, so the `AbortController` itself was never cleared up, and the `Request` somehow stayed in memory, including a reference to our `ref`.

use native AbortController

---

.changeset/hungry-bobcats-battle.md
.size-limits.json
src/react/hooks/useReadQuery.ts

Prerequisite for https://github.com/apollographql/apollo-client-nextjs/pull/258.
Because in that situation, `useReadQuery` is not called with a real `queryRef`, but with some serializable "transport object", the existing logic crashed when trying to access `undefined["observable"]` (since `transportObject[QUERY_REFERENCE_SYMBOL]` would be `undefined`, as symbol properties cannot be (de)serialized)

Adjust useReadQuery wrapper logic to work with transported objects.

---

.changeset/thick-buttons-juggle.md
.size-limits.json
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/internal/cache/QueryReference.ts

Fixes #11768
#11738 made it possible to dispose of the queryRef synchronously in our suspense hooks which released in 3.9.10. Unfortunately this caused a regression with strict mode where a network request was actually made. This change ensures that `standby` is properly handled in the queryRef `reinitialize` function.
NOTE: This only seemed to affect `useSuspenseQuery`. I've added tests for `useBackgroundQuery` as well to ensure we don't have future regressions, but the bug didn't seem to exhibit itself in this hook.

Fix issue where a network request is made when using `skip`/`skipToken` with `useSuspenseQuery` in strict mode

---

.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.changeset/spotty-garlics-knock.md
.size-limits.json
src/__tests__/__snapshots__/exports.ts.snap
src/testing/core/__tests__/createTestSchema.test.tsx
src/testing/core/createTestSchema.ts
src/testing/index.ts

Closes https://github.com/apollographql/apollo-client/issues/11776. Simplifies usage for developers by adding the mocks in a single pass inside `createTestSchema`.

Call `createMockSchema` inside `createTestSchema`

---

.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.size-limits.json
src/testing/core/__tests__/__snapshots__/createTestSchema.test.tsx.snap
src/testing/core/__tests__/createTestSchema.test.tsx
src/testing/core/createSchemaFetch.ts

@alessbell I'd love to hear your opinion on this:
It is just a thought that I just had when reviewing #11748 - should call `createSchemaFetch` always implicitly mock `window.fetch`?
That could cut down on the usability of the tool in some situations. 
Instead, what I'd suggest would be a `mockGlobal` propery.
So different usages might look like
```diff
using _fetch = createSchemaFetch(schema, {
delay: { min: 10, max: maxDelay },
-    });
+    }).mockGlobal();
```
or
```diff
const { restore } = createSchemaFetch(schema, {
delay: { min: 10, max: maxDelay },
-    });
+    }).mockGlobal();
```
While 
```js
const fetch = createSchemaFetch(schema, {
delay: { min: 10, max: maxDelay },
});
```
would just return a `fetch` function that can be passed around, but won't pollute global scope.
With …

suggestion: mock global `fetch` explicitly

---

.github/workflows/snapshot-release.yml

Upgrades to a version of `alessbell/pull-request-comment-branch` that uses Node 20 to address the github action deprecation warning (previous version was 16). Tested on personal repo ([before](https://github.com/alessbell/good-snow-tire-demo/actions/runs/8710796011)/[after](https://github.com/alessbell/good-snow-tire-demo/actions/runs/8711060211)).

chore: update alessbell/pull-request-comment-branch to v2.1.0

---

docs/source/data/queries.mdx
src/core/__tests__/fetchPolicies.ts

Fixing [documentation](https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy) for `ApolloClient.defaultOptions.watchQuery.nextFetchPolicy` custom function.
Considerations:
- Context that is passed as second argument doesn't provide `initialPolicy`, but `initialFetchPolicy`:
- Type [definition](https://github.com/apollographql/apollo-client/blob/main/src/core/watchQueryOptions.ts#L154) raises error when `initialPolicy` is used 
- Search through code shows [`initialFetchPolicy` is used](https://github.com/search?q=repo%3Aapollographql%2Fapollo-client%20initialFetchPolicy&type=code) in many places 
- `initialPolicy` is obsolete and [not used at all](https://github.com/search?q=repo%3Aapollographql%2Fapollo-client%20initialPolicy&type=code)

fix: initialFetchPolicy instead initialPolicy

---

docs/source/development-testing/static-typing.md

The graphql package is required by the generated files and thus should be included in the initial suggested packages to be installed.

chore: update static-typing.md to add "graphql" as install dependency

---

src/testing/internal/profile/Render.tsx

I am locally getting this error:
> The inferred type of 'withinDOM' cannot be named without a reference to '@testing-library/dom/node_modules/pretty-format'. This is likely not portable. A type annotation is necessary.ts(2742)
So adding that annotation to fix it - I don't believe we need a Changeset for this, as it's purely internal :)

add return type to `withinDOM` implementation

---

docs/source/development-testing/schema-driven-testing.mdx

fix: update link to sandbox in schema-driven testing docs page

---

.api-reports/api-report-react.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_internal.md
.api-reports/api-report.md
package-lock.json
package.json

This updates the API extractor tool and reruns the script. This is an alternative to #11822 which does a manual rename of the type.
cc @phryneas

Update API extractor and regenerate the API report

---

.api-reports/api-report-core.md
.api-reports/api-report-link_http.md
.api-reports/api-report-utilities_subscriptions_urql.md
.api-reports/api-report.md
package-lock.json
package.json

This should be the last blocker for merging in the renovate PRs like https://github.com/apollographql/apollo-client/pull/11766 which are currently failing due to the change in the API report.

Upgrade TypeScript to the latest patch version and regenerate API report

---

.changeset/rich-geese-complain.md
src/cache/inmemory/writeToStore.ts

This is a fix for https://github.com/apollographql/apollo-client/issues/11639
Objects possibly can have null prototypes. This causes them not to have toString() method leading to an error when doing substitution with console.warn() leading to the error "Cannot convert object to primitive value".
The error happens because both `existing` and `incoming` objects do not have `.toString` method. In the Chrome debugger, I saved `incoming` object as `temp1` on the window and these are my observations:
```
console.log('%o', temp1)
> Uncaught TypeError: Cannot convert object to primitive value
```
```
console.log('%o', {...temp1} )
> {__typename: 'Configuration', totalNumber: 10, updatedAt: '2024-05-06T11:10:11.684236649Z' }
```
```
temp1.toString()
> Uncaught TypeError: temp1.toString is not a …
```

Create a new object for console to have a prototype with toString method

---

docs/source/data/mutations.mdx

Since the following url does not match a hash, this fixed it.
https://www.apollographql.com/docs/react/data/mutations#reset
https://www.apollographql.com/docs/react/data/mutations#mutationresult-interface-reset

chore(docs): fix url for reset function

---

.changeset/kind-donkeys-clap.md
src/__tests__/ApolloClient.ts
src/cache/core/cache.ts
src/react/hooks/__tests__/useFragment.test.tsx

Fixes #11785
Uses `equalByQuery` to ensure that when we compare fragment diffs, we respect the `@nonreactive` directive within `cache.watchFragment` and `useFragment`.

Honor `@nonreactive` with `useFragment` and `cache.watchFragment`

---

.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.changeset/nasty-pens-dress.md
.size-limits.json
src/testing/core/mocking/__tests__/mockLink.ts
src/testing/core/mocking/mockLink.ts

Ensure covariant behavior: `MockedResponses<X,Y>` should be assignable to `MockedResponse`

---

.api-reports/api-report-react.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report.md
.changeset/sharp-cats-taste.md
src/react/hooks/useLoadableQuery.ts

This was brought up in https://community.apollographql.com/t/getting-error-ts5084-apollo-client-3-7-4/7267/6 - I don't know why our own type tests don't complain about it.

Add missing name to tuple member (fix TS5084)

---

src/cache/core/cache.ts
src/core/__tests__/masking.test.ts
src/core/masking.ts

Closes https://github.com/apollographql/apollo-client/issues/11671
This adds the other half of data masking which is to mask a fragment document with nested fragments. As such, the `mask` function has been renamed to `maskQuery` and a `maskFragment` function as been added.

[Data masking] Add function to mask fragment data

---

.changeset/brown-bikes-divide.md
.size-limits.json
src/react/hooks/internal/__tests__/useRenderGuard.test.tsx
src/react/hooks/internal/useRenderGuard.ts

This switches `useRenderGuard` to an approach that is not accessing React's internals, and we should even safe some bundle size 🎉

switch `useRenderGuard` to an approach not accessing React's internals

---

.api-reports/api-report-cache.md
.api-reports/api-report-core.md
.api-reports/api-report-react.md
.api-reports/api-report-react_components.md
.api-reports/api-report-react_context.md
.api-reports/api-report-react_hoc.md
.api-reports/api-report-react_hooks.md
.api-reports/api-report-react_internal.md
.api-reports/api-report-react_ssr.md
.api-reports/api-report-testing.md
.api-reports/api-report-testing_core.md
.api-reports/api-report-utilities.md
.api-reports/api-report.md
.size-limits.json
src/__tests__/client.ts
src/cache/core/__tests__/cache.ts
src/cache/core/cache.ts
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx

Closes https://github.com/apollographql/apollo-client/issues/11672
Adds an option to `ApolloClient` that enables data masking. This also adds the implementation to return masked queries from `watchQuery` (i.e. `ObservableQuery`) so that network data and cache updates will be masked.
This work does NOT include any ability to read fragments from the parent objects. This will be done in a followup PR.

[Data masking] Add ability to globally enable data masking for queries

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/breezy-points-carry.md
.size-limits.json
src/cache/core/__tests__/cache.ts
src/cache/core/types/common.ts

Version 3.7.x allowed `undefined` as a valid return value when using `cache.modify`. When doing so, this essentially caused the query to be refetched since the field data was removed. 3.8.x added some more robust types for `cache.modify` with https://github.com/apollographql/apollo-client/pull/10895, but as a result, we lost the ability to return `undefined` from these functions. Since the behavior is identical in > 3.8.x we should still allow this as a valid value since the client handles this correctly.

Allow `undefined` as return value from `cache.modify` modifier function

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.size-limits.json
src/cache/core/__tests__/cache.ts
src/cache/core/cache.ts
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/react/hooks/__tests__/useSuspenseQuery.test.tsx

The interaction between the client and the cache to determine whether the user has enabled data masking is very awkward. The current implementation relies on the client setting a property on the cache after the cache was created. While this works, this feels a bit leaky.
This change removes the property from the cache object and instead does the check in `ObservableQuery` itself before calling `cache.maskDocument` which is a bit more natural since `ObservableQuery` has access to this value.

Move check for whether data masking is enabled to `ObservableQuery`

---

.changeset/nasty-olives-act.md
.size-limits.json
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts

After #11890, I'm fairly confident in this now.
This needs to be reviewed commit-by commit, although a bunch of merges added additional commits at the start and end - I'm really sorry for those! (I believe some of them will disappear here if #11890 gets merged first!)
There might be more PRs to further streamline the result handling, but I think this PR is big enough as it is right now.

refactor useQuery to not use an internal class

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report.api.md
.changeset/angry-ravens-mate.md
.changeset/chilly-dots-shake.md
.changeset/slimy-balloons-cheat.md
.size-limits.json
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
src/react/hooks/useBackgroundQuery.ts
src/react/hooks/useLoadableQuery.ts
src/react/hooks/useQueryRefHandlers.ts
src/react/hooks/useSuspenseQuery.ts

Closes #11818
Adds support for `subscribeToMore` in `useBackgroundQuery`, `useLoadableQuery`, and `useQueryRefHandlers` that was previously missing. This was available in `useSuspenseQuery` but not in the other three hooks.

Add `subscribeToMore` function to `useBackgroundQuery`, `useQueryRefHandlers`, and `useLoadableQuery`

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/clever-bikes-admire.md
.size-limits.json
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/useSubscription.ts

Naming is open for discussion, but I did pretty deliberately select something different from `refetch`:
* `refetch` feels wrong in the case of something long-running like a subscription
* it has very different usage (doesn't accept parameters, doesn't return anything) from existing `refetch` functions.

Add `restart` function to `useSubscription`

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/unlucky-birds-press.md
.size-limits.json
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/useSubscription.ts
src/react/types/types.documentation.ts
src/react/types/types.ts

add `ignoreResults` option to `useSubscription`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/pink-ants-remember.md
.size-limits.json
src/core/ApolloClient.ts

This PR adds the ability to specify a `name` for a client instance for use with devtools. This will be useful for the [multiple clients](https://github.com/apollographql/apollo-client-devtools/pull/1418) feature to be able to more easily identify each client. Without this functionality, a randomly generated ID will be shown instead. Adding a `name` makes this more human-friendly.
As such, I've modified the way devtools is configured with the client by deprecating `connectToDevtools` and added a new `devtools` option:
```ts
new ApolloClient({
devtools: {
enabled: true,
name: 'Apollo Client 1',
}
})
```
This is fully backwards compatible with `connectToDevtools` and will set `enabled` to `true` if the `connectToDevtools` option is set. Structuring the config this way enables us to add …

Add ability to configure a name for the client for use with devtools

---

.github/workflows/prerelease.yml

Reverts apollographql/apollo-client#11729
I'll restore this behavior after we get an initial prerelease out. This change looks like it might be preventing us from releasing changes in our release 3.11 branch since no changesets have been added to `pre.json` yet.

Temporarily revert "fix: skip PR creation if no prerelease changesets exist"

---

.github/workflows/prerelease.yml

Reverts apollographql/apollo-client#11939
Adds back the logic there before. I believe the check for no changesets is preventing any new prerelease PRs from getting created if we haven't yet done a prerelease. We'll need to figure out how best to work around this while ensuring we aren't opening prerelease PRs for changes merged to `main` (which I believe is what this change fixed).

Add back "fix: skip PR creation if no prerelease changesets exist""

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/curly-vans-draw.md
src/cache/core/cache.ts

This removes an unused option from `watchFragment` that was already deprecated, `canonizeResults`.

remove deprecated `watchFragment` option, `canonizeResults`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/pink-flowers-switch.md
src/__tests__/optimistic.ts
src/core/watchQueryOptions.ts

Fixes #11945 
This PR fixes returning the `IGNORE` sentinel object from `optimisticResponse` when inferring the result data of a generic `TypedDocumentNode` mutation.

Fix `optimisticResponse` function return type

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/proud-humans-begin.md
.size-limits.json
src/react/hooks/useQuery.ts
src/react/types/types.ts

This gets rid of `useHandleSkip`, which mutated results during render, among a few other optimizations. Please review Commit by Commit.

optimize `useQuery` result handling

---

docs/source/performance/server-side-rendering.mdx

Updates the note on the SSR docs page about creating a new client instance per-request in a `<Caution />` component.
**Before**
**After**

Wrap note about creating new instance in `Caution`

---

patches/react-dom-19+19.0.0-rc-378b305958-20240710.patch
src/config/jest/setup.ts

For reference: https://github.com/testing-library/react-testing-library/issues/1342
I hope we can get React to accept a PR to make this configurable, but for now this should unclog our CI.

patch React 19 for tests to make FALLBACK_THROTTLE_MS configurable

---

.changeset/early-spoons-attack.md
.size-limits.json
src/core/ApolloClient.ts

Closes #11707
I made an error and incorrectly copied over the [default value](https://github.com/apollographql/apollo-client/pull/11936/files#diff-b156746d5b1aac290dd27cf54cf4713d7ffbe0fce30e5a0dc6114d7b3529ea28L204-L206) to connect to devtools. I forgot the `!` to check if there is already a global client instance 🤦‍♂️.
Regardless, this gives us a chance to re-evaluate the check. Now that Apollo Client Devtools supports multiple clients, we can remove the additional checks for `window.__APOLLO_CLIENT__` when determining how to set the default value. The check will now simply look at `__DEV__` to determine whether to connect the client or not when the option is not specified.

Fix incorrect default devtools config

---

.changeset/famous-berries-remember.md
src/core/ApolloClient.ts

This was mostly already doing this. With https://github.com/apollographql/apollo-client/pull/11969, we removed the check for `typeof window` to set the default value for `devtools.enabled`. The `connectToDevtools` function has some checks for `typeof window` as well, but currently it allows the `setTimeout` to run before it checks for `typeof window`. 
This PR simplifies this by returning early if `typeof window` is `undefined`.

Don't attempt to connect to devtools in non-browser environments

---

.github/workflows/snapshot-release.yml

I noticed the `graphql` package automatically marks one-off "canary" releases that are akin to our snapshot releases as deprecated, which automatically filters them out by default in the "versions" view https://www.npmjs.com/package/graphql?activeTab=versions.
If everyone is on board I'll run a script to deprecate past snapshot releases, but this will take care of them going forward. Already tested this with GraphQL Testing Library, works like a charm: https://www.npmjs.com/package/@apollo/graphql-testing-library?activeTab=versions
The message is inspired by the `graphql` deprecation message but open to suggestions!

chore: mark snapshot releases as deprecated in npm registry

---

.semgrepignore
docs/source/data/subscriptions.mdx

Closes https://github.com/apollographql/apollo-client/issues/10184
Adds `TypeScript` examples to all code blocks on the [subscriptions page](https://www.apollographql.com/docs/react/data/subscriptions).  You'll note that some `<MultiCodeBlock />` components only specify TS and others specify both. The ones that only specify TS will compile and add a JS block as well, but I found some bugs in some places with formatting and spacing so some code blocks specify both TS and JS code blocks to avoid the auto-compilation.
This change assumes that we want `TypedDocumentNode` as the predominant pattern for declaring types on query documents. The [original issue](https://github.com/apollographql/apollo-client/issues/9946) mentions using the generic argument syntax for `subscribeToMore`, but I left …

Add TypeScript examples to all subscriptions page code blocks

---

.changeset/nice-worms-juggle.md
.changeset/pink-horses-pay.md
.changeset/short-scissors-speak.md
.size-limits.json
docs/source/pagination/core-api.mdx
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx
src/testing/internal/scenarios/index.ts

Fixes #11965
This fixes several issues when using `fetchMore` with `no-cache` queries.
* Ensures we don't run multiple network requests unnecessarily
* Does not write the `fetchMore` result to the cache
* Ensures the component is re-rendered using the result of the `updateQuery` function.
**Important**
This PR updates `fetchMore` to force the user to provide an `updateQuery` function when using a query with a `no-cache` fetch policy. Without this, there is no way for the user to determine how to merge the result with the current query data since other mechanisms rely on the cache to perform this functionality. Calling `fetchMore` without an `updateQuery` function will now throw.

Fix `fetchMore` for queries with `no-cache` fetch policies

---

.changeset/fluffy-impalas-cross.md
.size-limits.json
src/core/QueryManager.ts
src/react/hooks/__tests__/useQuery.test.tsx

Fixes #11938
Fixes an issue where multiple fetches might report `data` if the result from the request contained errors. This happened as a result of the logic that checks to see if the value we are emitting was from an old request. We set the `data` property on the value emitted from the observable, but we didn't check to see if we had errors or not. In some cases, the value would be reported with the `data` property set which could leak to the end result.

Fix issue where multiple fetches might report `data` if result contained errors

---

.changeset/pink-guests-vanish.md
.size-limits.json
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/utilities/observables/Concast.ts

Fixes #11988 
Maybe fixes #11846

Fix a potential crash when calling `clearStore` while a query was running.

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/grumpy-pandas-pump.md
.changeset/shaggy-lions-brake.md
src/cache/core/__tests__/cache.ts
src/cache/core/types/common.ts
src/cache/inmemory/entityStore.ts

Fixes an issue with the following type:
```ts
cache.modify<{
union: Array<
| { __typename: "Type1"; a: string }
| { __typename: "Type2"; b: string }
>;
}>({
fields: {
union(field) {
return field.filter((a) => a);
},
},
});
```
This PR also makes it possible to return a `DeepPartial` object for fields that are more complex types and don't query for the whole value:
```ts
cache.modify<{
union: Array<
| { __typename: "Type1"; a: string; c: { foo: string } }
| { __typename: "Type2"; b: string; d: { bar: number } }
>;
}>({
fields: {
union(field) {
return [{ __typename: "Type1", a: "foo" }];
},
},
});
```
This makes it easier to pass a raw server GraphQL parent type to `cache.modify`.
> Caveat: We don't recommend intentionally omitting fields like this example in real app code. This does a …

Fix issue returning arrays from cache.modify modifier functions when the array contains a union type

---

src/__tests__/dataMasking.ts
src/cache/core/cache.ts
src/react/hooks/__tests__/useFragment.test.tsx

Closes #11675
Adds a warning when passing an object to the `from` property that is not identifiable from the cache (i.e. `cache.identify` returns `undefined`). This also adds some tests to check that objects returned from masked queries can be read from `watchFragment` and `useFragment`.

[Data masking] Warn when passing object to `useFragment`/`watchFragment` `from` that is not identifiable

---

src/__tests__/dataMasking.ts

Fixes a failing test after rebasing the `data-masking` branch with `main`.

Fix issue with comparing errors in dataMasking

---

src/core/__tests__/masking.test.ts
src/core/masking.ts

While working on data masking for nested fragments, I stumbled on a potential pitfall with the existing solution; the data masking algorithm only retains exactly whats defined in the selection set. This means that unless `__typename` is defined in the fragment, this property was removed from the returned object. This is mostly ok if you're just working with the query and one level of fragments, but as you introduce nested fragments with data masking, this made it difficult to work with. If you forget to include `__typename` with data masking enabled, this means the `from` option passed to `useFragment`/`watchFragment` was invalid, so the value returned was empty. This _could_ be solved in user-space by adding a `__typename` selection in the fragment, but we don't ask our users to do that …

Always retain `__typename` during data masking

---

.size-limits.json
src/core/__tests__/masking.test.ts
src/core/masking.ts

Because we try and retain object identities as much as possible when running the data masking algorithm, this causes an issue where would-be masked fields are returned in the query when a named fragment selects additional fields on the same child selection as the query.
For example, take this query:
```graphql
query {
user {
profile {
id
}
...UserFields
}
}
fragment UserFields on User {
profile {
id
age
}
}
```
Here the parent asks only for the `id` on the `profile` field while the `UserFields` fragment selects `age` on `profile` as well. Prior to this fix, both `id` and `age` were returned as part of the parent query even though `age` should have been masked. This fix ensures `age` would be masked here as expected.

[Data masking] Fix bug where masked field could be returned in parent query

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/modern-cows-tease.md
src/react/types/types.ts

Type Mutation.reset as an arrow function.
This function doesn't depend on `this`, so it can be safely passed around as value. Typing this as an arrow function makes it clear and plays nicer with https://typescript-eslint.io/rules/unbound-method/

Type `MutationResult.reset` as an arrow function

---

.size-limits.json
src/core/__tests__/masking.test.ts
src/core/masking.ts

Fixes #12035
The data masking algorithm doesn't properly handle `null` when passed as a top-level value (which might happen if there were errors returned in the GraphQL response), as the value of an array item, or as the value of a key with a child selection set. This PR fixes all 3 of these situations.

[Data masking] Ensure masking algorithm properly handles nulls

---

.size-limits.json
src/__tests__/dataMasking.ts
src/core/QueryManager.ts

Masks named fragments returned from `client.query(...)` calls.

[Data masking] Add support for masking `client.query` calls

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.size-limits.json
src/__tests__/dataMasking.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/react/hooks/__tests__/useSubscription.test.tsx

Closes https://github.com/apollographql/apollo-client/issues/12024
Masks data returned from subscriptions. This affects a few places:
* `data` property returned from `useSubscription`
* `data` passed to the `onData` callback in `useSubscription`
* `data` property emitted from `client.subscribe()`
This does _not_ however apply data masking to the `subscriptionData` property passed to `updateQuery` for `observableQuery.subscribeToMore()` as that is used for a cache write.

[Data masking] Mask data returned from subscriptions

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.size-limits.json
src/__tests__/dataMasking.ts
src/core/QueryManager.ts
src/react/hooks/__tests__/useMutation.test.tsx

Closes https://github.com/apollographql/apollo-client/issues/12023
Masks data returned from mutations. This affects a few places:
* `data` returned from `client.mutate()`
* `data` returned from `useMutation`
* `data` passed to `onCompleted` in `useMutation`
This does _not_ however apply data masking to the `update` function passed to `client.mutate` or `useMutation` since this callback is primarily used for cache writes.

[Data masking] Mask data returned from mutations

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/old-ghosts-agree.md
.size-limits.json
src/react/hooks/useSubscription.ts

This PR fixes that the `useSubscription` hook's definition of the recently added (#11927) `restart` function was not cached between rerenders (unlike other functions such as `refetch` and `fetchMore` returned by similar hooks). This made the `restart` unsuitable to be included in the dependency array of `React.useEffect`.
My use case is restarting a subscription when a React Native app is resumed from the background. @phryneas I assume it's evident from the code that `restart` is redefined every render. However, if you would like a reproducible, please let me know.

Fix useSubscription restart was not cached

---

.changeset/forty-news-turn.md
.size-limits.json
src/cache/core/cache.ts
src/react/hooks/__tests__/useFragment.test.tsx

Fixes #12051
#12020 did some refactoring to `useFragment` to be more compatible with [Rules of React](https://react.dev/reference/rules) (specifically not writing to `ref` in render). In the process, `useFragment` now calls `cache.identify` directly to ensure that whole data objects passed to `from` don't trigger rewatches when non key fields change to that object. This change however introduced a regression where invalid identifiers (i.e. `cache.identify` returns `undefined`) would show a warning such as:
```
TypeError: Cannot read properties of undefined (reading '__typename')
```
This was a result of taking that `undefined` and passing it as the value to `cache.watchFragment`, which itself called `cache.identify(undefined)` and this triggered the warning. 
This change ensures that …

Fix obscure warning in `useFragment` when `cache.identify` returns `undefined`

---

.changeset/polite-toys-battle.md
.size-limits.json
src/link/http/selectHttpOptionsAndBody.ts

Fixes #11555
We finally got enough information there that we could fix this on our side with this.

Create `normalizedHeaders` as object with `Object` prototype.

---

docs/source/api/link/community-links.md

Adds `apollo-link-printer` to the community link directory

docs(community-links): add printer link

---

.github/workflows/publish-pr-releases.yml
package-lock.json
package.json

add pkg.pr.new to publish pr releases

---

.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report.api.md
src/core/index.ts
src/masking/index.ts

I forgot to export the data masking types in the core bundle so that they are accessible from `@apollo/client` and not just from `@apollo/client/masking`. This PR updates that import to make it accessible.

Export data mask types in core

---

docs/source/get-started.mdx
docs/source/index.mdx

Removes Summit callouts, unused Gatsby Link import, and an empty page

docs: clean up

---

src/testing/internal/ObservableStream.ts

I learned a thing or two about `ReadableStream` while working on TanStack Start, so I thought we can simplify this here quite a bit.
No changeset since this just changes around a few internals.

`ObservableStream`: use `ReadableStream` instead of iterator

---

.size-limits.json
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx

After merging `main` into the `release-3.12` branch, many of the data masking tests began failing since they were still using the old profiler testing utilities. This PR updates the data masking tests to use the new render stream library instead.

Fix data masking tests that depended on the old profiler utils

---

.changeset/nervous-owls-hear.md
.size-limits.json
src/__tests__/dataMasking.ts
src/core/masking.ts
src/utilities/graphql/transform.ts

Closes #12037
Adds tests to ensure data masking works with `@defer` payloads.

[Data masking] Add tests to ensure deferred payloads are masked

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/early-bobcats-eat.md
.size-limits.json
src/__tests__/dataMasking.ts
src/cache/inmemory/policies.ts
src/core/__tests__/masking.test.ts
src/core/masking.ts

Closes #12043
When passing an unmasked object in migration mode to `cache.identify`, we'd get field accessor warnings even though the end user wasn't accessing them at all. This was due to the fact that `cache.identify` does a spread operation of the result which shallow-copies all the fields, triggering the getters.
This change adds a new `Slot` that we can use to disable field accessor warnings inside Apollo Client core for masked fields. This fixes the `cache.identify` case as this is the only known case of the issue so far. In the future we can use this `Slot` if we encounter other areas of the codebase that prematurely trigger the warnings.

[Data masking] Fix aggressive warnings when using objects marked with `@unmask(mode: "migrate")` with `cache.identify`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.size-limits.json
src/__tests__/__snapshots__/exports.ts.snap
src/__tests__/dataMasking.ts
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/masking.ts
src/utilities/graphql/fragments.ts
src/utilities/index.ts

Closes #11678
Emits a warning when using `no-cache` operations with data masking since `watchFragment` and `useFragment` rely on the cache to read fragment data. This warning will not be emitted when either `dataMasking` is disabled or if the operation already contains `@unmask` for all fragments.

[Data masking] Warn when using data masking with `no-cache` operations

---

.changeset/flat-beans-knock.md
.eslintrc
.size-limits.json
scripts/codemods/data-masking/examples/queries-codegen.ts
scripts/codemods/data-masking/examples/queries-react.tsx
scripts/codemods/data-masking/examples/queries.graphql
scripts/codemods/data-masking/examples/queries.ts
scripts/codemods/data-masking/package-lock.json
scripts/codemods/data-masking/package.json
scripts/codemods/data-masking/tsconfig.json
scripts/codemods/data-masking/unmask.ts

Closes #11676
Adds a codemod that applies the `@unmask` directive to all named fragments in a file. This works for:
* `gql` (or `graphql`) tagged template literals
* `graphql` (or `gql`) functions
* `.graphql` or `.gql` files
To run the codemod, use the following:
```
npx jscodeshift -t scripts/codemods/data-masking/unmask.ts \
--extensions tsx \
--parser tsx \
path/to/file.tsx
```
By default this adds the `@unmask` directive with no arguments. To add it in migrate mode, use the `--mode migrate` option in the CLI:
```
npx jscodeshift -t scripts/codemods/data-masking/unmask.ts \
--extensions tsx \
--parser tsx \
path/to/file.tsx \
--mode migrate
```
You can customize the tag name with the `--tag` option, or use it to only apply to a specific tag name. This defaults to both `gql` and …

[Data masking] Add codemod to apply `@unmask` to all named fragments

---

.changeset/nice-countries-share.md
src/core/__tests__/masking.test.ts
src/core/masking.ts

Fixes #12127
Fixes error thrown when trying to apply accessor warnings to selection sets with inline fragment nodes. I did not previously check the fragment condition before trying to apply the additional selection set, so `data` would be `undefined` in those conditions.

[Data masking] Fix issue applying accessor warnings to interface types

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report.api.md
.changeset/long-zoos-ring.md
.size-limits.json
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/useFragment.ts

While trying out data masking with the [Spotify showcase](https://github.com/apollographql/spotify-showcase), I discovered some cases where it was a bit difficult to adopt data masking without some significant refactors. For example, see https://github.com/apollographql/spotify-showcase/commit/a24c3ed370cf186b5285097aa8d5a42eed2bf7cb. In this component, I had to split out a fallback component and a component that renders the non-null case simply because we can't conditionally render hooks and `null` is not a valid `from` value in `useFragment`. By adding support for `null`, it should make data masking a bit easier to adopt by avoiding these types of refactors where a fallback state is perfectly valid.

[Data masking] Allow `null` as a valid `from` value

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/small-bears-confess.md
src/masking/__tests__/types.test.ts
src/masking/internal/types.ts

The `Unmasked` helper has a bug where unmasking a nullable object would return the object as a non-null type. This PR ensures the `null` is retained in the type.

[Data masking] Ensure `null` is retained when unmasking nullable objects

---

.changeset/gorgeous-zebras-confess.md
.size-limits.json
src/core/__tests__/masking.test.ts
src/core/masking.ts

Fixes an issue where a query selects some fields from an object and warnings are applied to a fragment that selects from the same selection set with more fields. Currently the additional fields are masked accidentally. See the test for a reproduction.

[Data masking] Fix issue with `@unmask(mode: "migrate")` with nested partial objects from parent query

---

netlify.toml

Removes the deploy-preview specific builds for Netlify, as that docs site is no longer used. Now all builds will just emit the typegen info.

[docs] remove all docs deployment except typegen

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/perfect-jobs-flow.md
src/masking/internal/types.ts
src/masking/types.ts

I'm still looking into ways to make this potentially faster, but this should already enable a "safer" option for types that didn't contain fragments in the first place.

skip unmasking for types without fragments

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/clean-turkeys-kick.md
src/masking/internal/types.ts

Found some additional type issues when trying this out with our Studio codebase. Opening this to track changes and try preview builds.
See  https://github.com/apollographql/apollo-client/pull/12150#issuecomment-2489416214 for more info. tl;dr; it was an older version of TypeScript where we see this issue.

Better handle array types when unmasking

---

src/masking/internal/types.ts

API extractor is currently failing on `release-3.12`. This PR fixes it.

Fix tsdoc issue

---

docs/source/data/directives.mdx
docs/source/data/fragments.mdx

Closes #11683
Adds a section on data masking in the fragments doc. This change does NOT include information about TypeScript or how to integrate with GraphQL Codegen. I will create followup PRs that include this information.

Data masking docs

---

README.md

Trying to make it clearer for users to know which version of the GraphQL spec the client is compatible with.

chore: Update readme for GraphQL spec compability

---

src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx

Updates the data masked tests to adjust for changes in the render stream library. 
Related: #12140

Update data masking tests in React hooks to account for changes in render stream library

---

.changeset/giant-pears-learn.md
.size-limits.json
src/masking/types.ts

Fix import extension

---

.changeset/fluffy-worms-fail.md
.changeset/sharp-windows-switch.md
.size-limits.json
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts

Fixes #12008
Errors thrown in `onCompleted` as a result of an error thrown inside `onCompleted` exhibit two behaviors:
* The error becomes the `errors` property on the resolved value from the mutation
* `onError` is also called with the error thrown from `onCompleted`
This is a bit surprising behavior as `onError` is meant to handle errors from the mutation.
This PR moves the error handling from a `.catch` on the promise to the 2nd argument to `.then` so that errors thrown in `onCompleted` aren't handled the same way. This results in the mutation promise throwing that error instead and ensures `onError` is not called as a result.

Don't call `onError` if errors are thrown in `onCompleted`

---

docs/source/development-testing/developer-tooling.md

before this change (yes, it's really so blurry!): 
after: https://www.apollographql.com/docs/deploy-preview/1b53496c8035da7b414e/react/development-testing/developer-tooling
Still not perfect, but way better

docs: adjust screenshot size

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/chilly-icons-shave.md
src/masking/__benches__/types.bench.ts
src/masking/internal/types.ts

prevent infinite recursion of ContainsFragmentsRefs type

---

docs/source/data/fragments.mdx

Reported here: https://discord.com/channels/1022972389463687228/1316737355633135636/1316737355633135636
I have tried this myself and can confirm it works as expected.

Fix incorrect config for data masking for client preset in docs

---

.github/workflows/scheduled-test-canary.yml

Leaving this up for review of the whole action.

canary test adjustments

---

.github/ISSUE_TEMPLATE/question-discussion.md
.github/workflows/lock.yml
README.md

Replace Discord with Discourse links since the Discourse Community Forum there is becoming our focus.

Replace Discord with Discourse links

---

docs/source/get-started.mdx
docs/source/index.mdx
docs/source/why-apollo.mdx

Add meta descriptions and subtitles to help with discoverability

docs: add meta descriptions to top-level pages

---

scripts/codemods/ac2-to-ac3/imports.js

This PR adds the following imports update to the imports.js `ac2-to-ac3` transform:
1. `@apollo/react-common` -> `@apollo/client`
2. `apollo-cache` -> `@apollo/client`
3. `apollo-utilities` -> `@apollo/client/utilities`

Adds @apollo/react-common, apollo-cache, and apollo-utilities to the ac3 imports transform

---

.size-limits.json
src/react/hooks/__tests__/useSubscription.test.tsx

stacked on top of #12233
CI run: https://github.com/apollographql/apollo-client/actions/runs/12394062292

fix timing problems in tests introduced by latest React canary

---

src/__tests__/graphqlSubscriptions.ts
src/__tests__/optimistic.ts
src/__tests__/refetchQueries.ts
src/link/schema/__tests__/schemaLink.ts
src/link/utils/__tests__/toPromise.ts
src/testing/internal/ObservableStream.ts
src/utilities/observables/__tests__/Concast.ts

This PR completes the work to remove `itAsync` from our tests. It is still used by the hoc and component tests, but these will be deleted with 4.0 so we can ignore these for now. `itAsync` will be removed when we remove the query components and hoc on the 4.0 branch.

Remove `itAsync` from remaining relevant tests

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/beige-eggs-nail.md
src/masking/__benches__/types.bench.ts
src/masking/types.ts

Partially fixes #12266
Moves the `ContainsFragmentRefs` check from `MaybeMasked` to the `Unmasked` type to leave `TData` alone when `TData` does not contain fragment refs.
We will still need a solution that works after masked types are generated for situations like #12266.

Leave `TData` alone in `Unmasked` if it does not contain fragment refs

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-masking.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/tiny-ants-bow.md
src/masking/__benches__/types.bench.ts
src/masking/internal/types.ts
src/utilities/index.ts

Related to https://github.com/apollographql/apollo-client/issues/12266
Ensures branded primitive types when used as scalars with the `Unmasked` type.

Handle tagged/branded primitive types when used with `Unmasked`

---

src/react/hooks/__tests__/useLazyQuery.test.tsx
src/testing/matchers/index.d.ts
src/testing/matchers/index.ts
src/testing/matchers/toEqualQueryResult.ts

In preparation for changes to `useLazyQuery` in v4, I'm doing some work to update the `useLazyQuery` test suite. The goals of this refactor are to:
* Switch to render stream checks
* More robust checks on properties returned by the hook (not just the usual `loading`, `data`, etc)

Update `useLazyQuery` tests for robustness

---

src/react/hooks/__tests__/useQuery.test.tsx
src/testing/matchers/index.d.ts
src/testing/matchers/index.ts
src/testing/matchers/toEqualApolloQueryResult.ts

Similar to #12260, this refactors `useQuery` tests to use the new `toEqualQueryResult` matcher. There are many tests in this suite, so this is the first of a series of PRs to make PR review a bit more digestable.

Refactor `useQuery` tests to use `toEqualQueryResult` - Part 1

---

src/react/hooks/__tests__/useQuery.test.tsx

Refactor `useQuery` tests to use `toEqualQueryResult` - Part 2

---

src/react/hooks/__tests__/useQuery.test.tsx

Refactor `useQuery` tests to use `toEqualQueryResult` - Part 3

---

.changeset/lemon-singers-pay.md
package-lock.json
package.json

This came up in #12291 and we don't need to wait for 4.0 to do it.

Remove unused dependency `response-iterator`

---

.changeset/khaki-cars-develop.md
src/react/types/types.ts

From discussion in https://github.com/apollographql/apollo-client/pull/12277
`ignoreResults` is more likely to cause confusion than actually help since the results are always returned.
The option potentially reduces the number of rerenders where the mutation is hooked, but I'm skeptical of the necessity and effectiveness of this.
If there's really a need for performance around state management in `useMutation` then there could be a separate hook more specialized for this that has a clear contract and expected behavior instead of a somewhat unused state that doesn't always gets refreshed
@jerelmiller I was wondering if we want to also deprecate `ignoreResults` in `useSubscription`. I admit I didn't even know that was an option there so I didn't dig

Deprecate ignoreResults in useMutation

---

src/cache/inmemory/__tests__/diffAgainstStore.ts

While working on some things for 4.0, I noticed some room for minor improvements to the `diffAgainstStore` test suite. This PR:
- Adds assertions against the `result` returned from `diffQueryAgainstStore` in tests where appropriate
- Fixes some incorrect test descriptions against their behavior in the test
- Identifies tests that can/should be eliminated in the 4.0 branch for an option that is ignored in the implementation.

Minor tweaks to `diffAgainstStore` tests

---

src/__tests__/client.ts
src/testing/internal/ObservableStream.ts
src/testing/matchers/toEmitAnything.ts

This change introduces two things:
- Adds a `peek` function to `ObservableStream` that lets you peek at the next value "without" consuming the next reader event
- Refactors an existing test that checks that updates to reactive vars will rerender queries.
The `peek` function was necessary due to how these tests operate. Several areas of the refactored test did something like the following:
```ts
// Modify the reactive var to ensure changes are broadcasted
aVar(aVar() + 111)
await expect(aStream).toEmitValue(...)
// ensure that a change unrelated to this query didn't emit a new event
await expect(bStream).not.toEmitAnything()
```
Because `toEmitAnything` consumed a reader event, that meant using `await expect(bStream).toEmitValue(...)` wouldn't quite work as you'd expect since it would be …

Add `peek` to `ObservableStream` and use `ObservableStream` in an existing test

---

.changeset/khaki-cars-develop.md
src/react/types/types.ts

Following-up on discussion in https://github.com/apollographql/apollo-client/pull/12296
Added more information about impact once the option will be removed and possible alternative to retain similar behavior

Add more information about deprecation of useMutation ignoreResults option

---

package-lock.json
package.json
src/link/retry/__tests__/retryLink.ts

I noticed an opportunity to remove a dependency by switching our `RetryLink` tests over to `ObservableStream`.

Remove `wait-for-observables` in favor of `ObservableStream`

---

src/react/hooks/__tests__/useQuery.test.tsx

Tries to fix one of the flaky tests that check for the number of requests by switching to fake timers.

Fix flaky `useQuery` test

---

.api-reports/api-report-core.api.md
.api-reports/api-report-errors.api.md
.api-reports/api-report-link_error.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/curvy-seahorses-walk.md
src/__tests__/__snapshots__/graphqlSubscriptions.ts.snap
src/__tests__/graphqlSubscriptions.ts
src/errors/__tests__/ApolloError.ts
src/errors/index.ts
src/link/error/index.ts

According to the [multipart HTTP subscription protocol](https://www.apollographql.com/docs/graphos/routing/operations/subscriptions/multipart-protocol), fatal tranport errors follow the [GraphQL error format](https://spec.graphql.org/draft/#sec-Errors.Error-Result-Format) which require `extensions` to be a map as its value instead of an array. This PR fixes this by using `GraphQLFormattedError` as its type.

Fix type of `extensions` in `protocolErrors`

---

.api-reports/api-report-testing_react.api.md
knip.config.js
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts

Fixes tests changed by #12327 that now check for the `data` property and not caught when doing the `cache.diff` change in #12304

Fix tests affected by change to cache

---

.changeset/lazy-clocks-sip.md
package-lock.json
package.json

With the [6.0.3 release](https://github.com/enisdenjo/graphql-ws/releases/tag/v6.0.3), the incorrect alternative response format that was introduced on the `Client.prototype.subscribe` `sink` argument in v6 has been removed, so it can now safely be used as a valid `peerDependency`.

Add `graphql-ws` `^6.0.3` as a valid `peerDependency`

---

.changeset/large-timers-lay.md
.size-limits.json
src/react/hooks/useQueryRefHandlers.ts
src/react/hooks/useReadQuery.ts

Up until now the communication from the React team was that it was technically okay to call `useContext` conditionally, but apparently React 19 now warns in dev mode on hook order changes - also for `useContext`.
This should fix that.

`useReadQuery`/`useQueryRefHandlers`: Fix a "hook order" warning that might be emitted in React 19 dev mode.

---

.changeset/quiet-apricots-reply.md
.size-limits.json
src/config/jest/setup.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts

An experiment. This might be required for query streaming with `@defer` and `useSuspenseQuery`.

keep deferred inFlightLinkObservables until the response is finished

---

.circleci/config.yml
.size-limits.json

Removes the security scans run in CircleCI. We have replaced these with a github app implementation that fixes some of the issues we've seen with CCI / fetching credentials for the pipelines. These issues have been especially noticeable on PRs from forks.
The updated scans write output to the "Checks" tab in Github rather than using Github comments. Additionally they run faster.

remove cci-based security scans

---

docs/source/development-testing/testing.mdx

This is a bad practice and we don't encourage this behavior, especially since this means the tests won't reflect the runtime behavior where normalization is applied.
I'm removing this entirely, especially since we are deprecating this option in v4. All examples have been updated to specify `__typename` in the mocks.

Remove `addTypename` setting in testing docs

---

.changeset/curvy-ads-matter.md
.size-limits.json
src/__tests__/fetchMore.ts
src/core/ObservableQuery.ts

I discovered this issue when working on some updates for 4.0. When `fetchMore` is executed for a `no-cache` query, the wrong `networkStatus` and `loading` value is emitted for the final result in the observable. This doesn't currently affect `useQuery` because `useQuery` uses `getCurrentResult()` which returns the right values.

Fix emitted `fetchMore` result from `observableQuery` for no-cache queries

---

.size-limits.json
src/__tests__/fetchMore.ts

Fix failing test added from #12351 due to changes in the `ApolloQueryResult` type in the 4.0 branch.

Fix failing `fetchMore` test added in 3.12.11

---

docs/source/data/fragments.mdx

Adds some documentation for the new `useSuspenseFragment` hook to the Fragments page.

Add documentation for `useSuspenseFragment`

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report.api.md
.changeset/swift-turtles-clap.md
.size-limits.json
src/react/hooks/__tests__/useSuspenseFragment.test.tsx
src/react/hooks/useSuspenseFragment.ts
src/react/query-preloader/createQueryPreloader.ts
src/react/types/types.ts

Discovered this when working in the Next.js streaming package. When the fragment contains required variables, ensure the `variables` option for `useSuspenseFragment` is required as well.

Require `variables` option in `useSuspenseFragment` when there are required variables

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.changeset/curvy-pianos-count.md
src/react/hooks/useMutation.ts
src/react/types/types.ts

Closes #12299
Removes the deprecated `ignoreResults` option from `useMutation`.

Remove deprecated `ignoreResults` option from `useMutation`

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/shiny-sheep-behave.md
.size-limits.json
src/react/hooks/index.ts

This should fix https://github.com/apollographql/apollo-client/actions/runs/13318196502/job/37197223428?pr=12201 in the 4.0 branch. This should have been exported in 3.13.0, but I forgot to include this 🤦‍♂️

Export `UseSuspenseFragmentOptions`

---

docs/source/data/subscriptions.mdx

This is a proposed simplification to the `subscribeToMore` example, to remove a level of indirection that seemed unjustified. If the original approach is more correct, I suggest explaining why the `useEffect` should be in `CommentsPage`, rather than calling it directly in `CommentsPageWithData`.
I am assuming the need to wait until the query data has arrived before executing the subscription.

Docs: simplify subscribeToMore example

---

docs/source/integrations/webpack.md

The current Jest transformer that is linked in this doc doesn't work with the Jest 28+. I've replaced it with the working one which is compatible with the latest jest version.

update webpack.md with a link to working jest transformer

---

.changeset/grumpy-donuts-smoke.md
src/utilities/types/DeepOmit.ts

Linked to issue: [https://github.com/apollographql/apollo-client/issues/12391](https://github.com/apollographql/apollo-client/issues/12391)
Proposed solution to bug in DeepOmit function.
When deep commit is used on a type with optional keys, the optional key(s) is removed and replaced with the orignial type union `undefined`.
This leads to situations like:
```
type OptionalString = {
maybeString?: string;
__typename: 'X-type';
};
```
becoming
```
{
maybeString: string | undefined;
}
```
when DeepOmit is used to remove `___typename`
To solve this I've added logic to deal with Optional and Required keys seperately.

Allowed DeepOmit to support partial

---

docs/source/api/react/testing.md
docs/source/caching/cache-configuration.mdx
docs/source/development-testing/testing.mdx
src/cache/inmemory/helpers.ts

Removing `addTypename` was started in ef892b4dc505, but we still have a few leftovers.

Remove leftover of `addTypename`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-testing_react.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/smart-rats-explode.md
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts
src/core/__tests__/ObservableQuery.ts

Saw a chance for a small bundle size optimization by getting rid of some unused code meant for devtools but unused by them.

Remove unneeded devtools code

---

.api-reports/api-report-utilities.api.md
.changeset/rich-adults-destroy.md
src/testing/core/mocking/__tests__/__snapshots__/mockLink.ts.snap
src/testing/core/mocking/__tests__/mockLink.ts
src/testing/core/mocking/mockLink.ts

Fixes #12403
Better handle `NaN` in the debug messages when a mock cannot be matched.

Show `NaN` in `MockLink` debug messages for unmatched variables

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-testing_react.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/forty-hairs-occur.md
.size-limits.json
src/__tests__/optimistic.ts
src/core/ObservableQuery.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/fetchPolicies.ts
src/react/hooks/__tests__/useQuery.test.tsx

`networkStatus` is really only useful for `ObservableQuery` as all other promise-based APIs will have a final `networkStatus` of either `ready` or `error`. As such, the fine-grained tracking of `networkStatus` has been moved to `ObservableQuery`. This helps us reduce the reliance on `QueryInfo` some more in an effort to one day eliminate it.

[Refactor] Move tracking of `networkStatus` into `ObservableQuery`

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.changeset/empty-rabbits-move.md
.changeset/light-dolphins-taste.md
.changeset/lucky-hats-push.md
.changeset/nice-waves-work.md
.changeset/polite-bees-care.md
.changeset/rich-eagles-cross.md
.changeset/seven-foxes-melt.md
.changeset/soft-mails-clean.md
.changeset/sour-pillows-guess.md
.changeset/strange-seahorses-impress.md
.changeset/twenty-snakes-sort.md
.size-limits.json
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/hooks/useQuery.ts
src/testing/matchers/toEqualLazyQueryResult.ts

Closes #5912
Closes #7484
Closes #9317
Closes #10787
Closes #12100
Partially addresses #12272
Adds the planned breaking changes to `useLazyQuery` planned for 4.0. A summary of the changes described in the changesets:
---
`useLazyQuery` no longer supports SSR environments and will now throw. If you need to run a query in an SSR environment, use `useQuery` instead.
---
The execute function returned from `useLazyQuery` now only supports the `context` and `variables` options. This means that passing options supported by the hook no longer override the hook value.
To change options, rerender the component with new options. These options will take effect with the next query execution.
---
The result resolved from the promise returned from the exeucte function in `useLazyQuery` is now an …

Update `useLazyQuery` with planned breaking changes

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-testing_react.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/purple-lions-cough.md
.changeset/tidy-squids-poke.md
.size-limits.json
src/__tests__/mutationResults.ts
src/__tests__/optimistic.ts
src/core/ObservableQuery.ts
src/core/__tests__/ObservableQuery.ts

Removes the `ObservableQuery.result()` method. This method was not super useful and made it too easy to remove the query from the list of active queries if nothing was subscribed to the observable.
The only other place that used this function was the `setVariables` API. This has been updated to always return a result in the case the variables remain the same or there are no subscribers.

Remove `ObservableQuery.result`

---

.changeset/tidy-squids-poke.md
src/__tests__/mutationResults.ts
src/__tests__/optimistic.ts

As a result of #12432, we can now use `from(observableQuery)` to turn `ObservableQuery` into an RxJS observable which means we can use the `firstValueFrom` as a proper replacement for the removed `result` function (#12430). This PR updates the tests from #12430 to use this pattern and update the changeset with the updated recommendation.

Use `firstValueFrom(from(observableQuery))` where appropriate

---

src/core/__tests__/ApolloClient/general.test.ts

We have a pretty flaky core test that checks against warnings emitted to the console. `MockLink` causes the test to fail from time to time as it is emitting warnings on unmatched mocks. This disables warnings in `MockLink` which don't affect the test anyways.

Disable warnings in mocks to fix flaky test

---

docs/source/_sidebar.yaml
docs/source/data/defer.mdx

Adds the defer page to the sidebar and adds a `minVersion` to the defer page

doc: add defer to sidebar

---

.changeset/little-trainers-compare.md
.size-limits.json
src/core/QueryInfo.ts
src/react/hooks/__tests__/useQuery.test.tsx

Fixes #12458
If a query changed variables and simultaneously skipped a query, `QueryInfo` would get updated with the right `variables`, but the previous `cache.watch` was active. This was a problem when the `fetchPolicy` changed to `standby` as a result of skipping the query while changing variables. If something else cache a cache update during the period while the query was in standby, the diff was updated to the result from the previous variables which meant the next time `queryInfo.getDiff()` was called, it used the already stored wrong result.
This change cancels a `cache.watch` if variables change so that cache updates while a query is skipped don't update `QueryInfo`.

Fix an issue where incorrect results are returned when changing variables and skipping

---

.changeset/shy-dragons-tease.md
.size-limits.json
src/cache/inmemory/inMemoryCache.ts

Move typename transform and fragment cache resets to resetResultCache

---

src/core/ApolloClient.ts
src/react/hooks/__tests__/useMutation.test.tsx
src/testing/matchers/index.d.ts
src/testing/matchers/index.ts
src/testing/matchers/toEqualStrictTyped.ts

While in the process of updating the mutation types, I found it difficult to fully ensure `useMutation` worked as expected since it only checked individual properties. This PR refactors all tests to use snapshot streams and full result matchers to ensure the return values match what is expected. As a result, we've discovered some inconsistencies that we will follow up with later.

Refactor `useMutation` tests to use full result matchers and snapshot streams

---

src/core/__tests__/ApolloClient/general.test.ts

There is a [test flake](https://app.circleci.com/pipelines/github/apollographql/apollo-client/27149/workflows/818a22dc-d2ee-4132-b3ab-444c6cac043e/jobs/240675) that has been plaguing the core tests for some time. I've tried various fixes, but it appears that this flakes out with different queries at different times. I am fairly certain there is a race condition in other tests that happen to conflict with the timing which cause this to fail.
As such, I'm trying this fix to switch from `toHaveBeenLastCalledWith` to `toHaveBeenCalledWith` just to check to make sure that at least one call to the console has been made, that way even if the race condition occurs, this shouldn't happen. This is the only test that checks this specific message, so we shouldn't get any false positives as a result …

Another attempt at fixing test flake

---

src/core/__tests__/ApolloClient/general.test.ts

This one gets a lot of updates with our changes in 4.0, but its super noisy and difficult to trace back errors and logs. This tries to eliminate the warnings emitted from `MockLink` so that its much quieter and easier to debug against.

Reduce console noise in `ApolloClient/general` tests

---

src/react/hooks/useQuery.ts

This is part 1 of a series of small refactors to try and make `useQuery` a bit more sane.
This one focuses on the `createMakeWatchQueryOptions` function to eliminate the need for the curried function. This one is best reviewed by stepping through the commits to see how I got from the starting point to here.

Refactor away `createMakeWatchQueryOptions`

---

src/react/hooks/useQuery.ts
src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap

Part 2 of refactoring `useQuery`.
This one works to remove `getObsQueryOptions` by merging the global defaults right away rather than doing it each time `watchQueryOptions` are about to get used. This simplifies and removes the need for `getObsQueryOptions`.
Best to review this one commit by commit

Refactor away `getObsQueryOptions`

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
package-lock.json
package.json
src/react/hooks/useQuery.ts

This focuses on inlining some of the extracted hooks. This enables additional refactoring where there might have been duplicated logic, or logic that was completely unused in some places.
This one is best to review commit by commit if possible to see the progression.

Refactor `useQuery`: Combine hooks

---

src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/testing/matchers/index.d.ts

This makes sure we are checking all returned values from `useSuspenseQuery` in our tests.

Use `toEqualStrictTyped` in `useSuspenseQuery` tests

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/grumpy-vans-type.md
.changeset/little-spoons-kick.md
.changeset/many-buses-allow.md
.changeset/poor-eels-punch.md
.changeset/tough-rockets-allow.md
.size-limits.json
src/__tests__/ApolloClient.ts
src/__tests__/client.ts
src/__tests__/dataMasking.ts
src/__tests__/mutationResults.ts
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts
src/core/types.ts
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useMutation.ts
src/react/types/types.documentation.ts

Closes #12455
Fixes #9065
Fixes #7167
Partially addresses #12427
Updates `client.mutate` to return a `MutateResult` type instead of a `FetchResult`. `FetchResult` is the raw response type we expect from the link chain. Because of this, we were not able to apply error unification to mutations since there is no `error` property on this type.
This change swaps `errors` for `error` and applies the same error unification behavior to mutations as was done to queries in #12457. Network errors are now subject to the `errorPolicy` and will resolve the mutation promise if the `errorPolicy` is not `none`.
This change also fixes a long-standing bug with `useMutation` where passing an `onError` callback would resolve the promise returned from the mutation when `errorPolicy` was `none`. These errors …

 Unify error behavior of `client.mutate` and update its type

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/forty-shrimps-fry.md
.changeset/real-teachers-peel.md
.changeset/tricky-tables-shave.md
.changeset/warm-ties-sit.md
.size-limits.json
src/__tests__/client.ts
src/__tests__/dataMasking.ts
src/__tests__/graphqlSubscriptions.ts
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/types.ts
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/useSubscription.ts
src/testing/matchers/index.d.ts
src/testing/matchers/index.ts
src/testing/matchers/toEmitStrictTyped.ts
src/testing/matchers/toEqualStrictTyped.ts
src/testing/matchers/utils/getSerializableProperties.ts

Closes #12456
Closes #12422
Closes #12427
Changes the type emitted from subscriptions to a `SubscribeResult`, which uses `error` instead of `errors`. This change also unifies the error behavior between GraphQL errors and network errors so that network errors adhere to the configured `errorPolicy`. This change means that results are no longer emitted when using `errorPolicy: 'ignore'` if there is no associated `data` as well so that we avoid emitting an empty value.
This change also no longer terminates the downstream connection when encountering an error. If the downstream connection closes as a result of the error, a `next` event will be followed by a `complete` event instead. This change essentially means that using the `error` callback is useless and no longer needed. This change …

Unify subscription error behavior and update emitted type

---

.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.changeset/eleven-kangaroos-jump.md
.changeset/slimy-chicken-melt.md
.size-limits.json
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/useSubscription.ts
src/react/types/deprecated.ts
src/react/types/types.documentation.ts

Removes the deprecated `onSubscriptionData`, `onSubscriptionComplete` callbacks from `useSubscription` as well as the returned `variables` value.

Remove deprecated `onSubscriptionData`, `onSubscriptionComplete` callbacks and returned `variables` from `useSubscripton`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/giant-bags-share.md
.size-limits.json
src/__tests__/ApolloClient.ts
src/__tests__/client.ts
src/__tests__/optimistic.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts
src/core/__tests__/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx
src/utilities/caching/__tests__/getMemoryInternals.ts
src/utilities/types/TODO.ts

Closes #12482
Throws an error if a query or mutation does not emit a value before the link chain completes. This is usually a bug in the user's link chain and can have unintended consequences. By throwing, this makes the issue more visible and lets us clean up some areas of the codebase that would otherwise not be able to handle this situation.
This also addresses the issue where issuing a query with a `standby` fetch policy would throw an `EmptyError` and instead will resolve the query with `data: undefined`.

Throw an error if the link chain completes without emitting a value

---

.api-reports/api-report-core.api.md
.api-reports/api-report-errors.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.changeset/nervous-fireants-bow.md
.size-limits.json
src/__tests__/client.ts
src/__tests__/dataMasking.ts
src/__tests__/graphqlSubscriptions.ts
src/__tests__/local-state/general.ts
src/__tests__/mutationResults.ts
src/config/jest/areCombinedGraphQLErrorsEqual.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/equalByQuery.ts
src/errors/CombinedGraphQLErrors.ts
src/link/subscriptions/__tests__/graphqlWsLink.ts
src/link/subscriptions/index.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useSubscription.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
src/react/ssr/__tests__/getDataFromTree.test.tsx
src/testing/experimental/__tests__/createTestSchema.test.tsx

Closes #12483 
Adds a `data` property to `CombinedGraphQLErrors` that captures any partial data returned by the server when `errors` are returned.

Add `data` property to `CombinedGraphQLErrors`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report.api.md
.size-limits.json
src/core/QueryInfo.ts
src/core/QueryManager.ts

In an effort to move toward dismantling `QueryInfo`, this PR removes the `observableQuery` and `lastRequestId` options from `QueryInfo.init`. The `observableQuery` option was only used in one place and was used to call `setObservableQuery` which I just inlined in the one call site. The `lastRequestId` option wasn't used at all so I removed this entirely.

Minor `QueryInfo` refactor

---

src/core/__tests__/ObservableQuery.ts

These were quite noisy and made it difficult to debug.

Fix warnings emitted to console from `ObservableQuery` tests

---

.api-reports/api-report-testing_core.api.md
.api-reports/api-report-testing_internal.api.md
.changeset/ninety-bags-bake.md
.size-limits.json
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
src/react/ssr/__tests__/prerenderStatic.test.tsx
src/testing/core/index.ts
src/testing/core/mocking/__tests__/__snapshots__/mockLink.ts.snap
src/testing/core/mocking/__tests__/mockLink.ts
src/testing/core/mocking/mockLink.ts
src/testing/internal/scenarios/index.ts
src/testing/react/__tests__/MockedProvider.test.tsx
src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap

Combine `variables` and `variableMatcher` by updating `variables` to accept a callback function. This reduces the need to validate that either one or the other option is passed but not both.

Combine `variables` and `variablesMatcher` in `MockLink`

---

.api-reports/api-report-link_core.api.md
.api-reports/api-report.api.md
.changeset/giant-apes-thank.md
.size-limits.json
src/__tests__/mutationResults.ts
src/cache/inmemory/__tests__/policies.ts
src/link/core/ApolloLink.ts
src/react/hooks/__tests__/useQuery.test.tsx
src/testing/core/mocking/mockClient.ts
src/testing/core/mocking/mockLink.ts
src/testing/react/__tests__/MockedProvider.test.tsx
src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap

Closes #12529
Removed the `onError` and `setOnError` methods on `ApolloLink`. These seemed to only be useful to `MockLink` to rewrite the error thrown, but this is undocumented and very confusing. This has been removed with no replacement.

Remove `onError` and `setOnError` from `ApolloLink`

---

.changeset/thin-peas-hear.md
.size-limits.json
src/__tests__/ApolloClient.ts
src/__tests__/client.ts
src/__tests__/dataMasking.ts
src/__tests__/fetchMore.ts
src/__tests__/local-state/export.ts
src/__tests__/local-state/general.ts
src/__tests__/mutationResults.ts
src/__tests__/refetchQueries.ts
src/cache/inmemory/__tests__/policies.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/fetchPolicies.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/react/query-preloader/createQueryPreloader.ts
src/react/types/types.documentation.ts
src/testing/matchers/arrayWithLength.ts
src/testing/matchers/index.d.ts
src/testing/matchers/index.ts

Closes #12505
Changes the default value of `notifyOnNetworkStatusChange` to `true` so that loading states are emitted/rendered by default.

Change `notifyOnNetworkStatusChange` default to `true`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-utilities_internal.api.md
.api-reports/api-report.api.md
.changeset/fair-ways-enjoy.md
.changeset/sixty-meals-travel.md
.changeset/sour-starfishes-pump.md
.size-limits.json
src/__tests__/__snapshots__/exports.ts.snap
src/__tests__/dataMasking.ts
src/__tests__/mutationResults.ts
src/core/ObservableQuery.ts
src/core/QueryInfo.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/core/watchQueryOptions.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/hooks/useLazyQuery.ts
src/utilities/internal/index.ts
src/utilities/internal/normalizeVariables.ts

Fixes the value of `ObservableQuery.variables` to be `undefined` when `variables` are not set. This change means that we treat `{}` and `undefined` as the same variables value, so `variables` are normalized to `undefined` in cases where variables are set to `{}`. This ensure the `TVariables` type better aligns with the `variables` type.
This change also makes it possible to reset variables back to its empty state by calling `reobserve({ variables: undefined })`. Previously this required `reobserve({ variables: {} })` since the `undefined` value was ignored.

Fix value of `ObservableQuery.variables` to be `undefined` when variables are empty

---

.api-reports/api-report-errors.api.md
src/errors/index.ts

I found a rogue import from the recent work merged in that imported from `@apollo/client/core`. This updates the import to `@apollo/client`.

Fix import from `@apollo/client/core`

---

.changeset/hot-kangaroos-eat.md
src/utilities/subscriptions/urql/index.ts

This is a tiny fix to the urql multipart subscription exchange helper so that it closes gracefully when urql attempts to trigger an unsubscribe.
I see that in the 4.0 release [they're slated for removal](https://github.com/apollographql/apollo-client/pull/12428/files), but the spec implemented by the helpers here is not the same as implemented by `urql` (less strict `accept` header, different response structure, no graceful heartbeat handling), hence this small fix while people figure out how to swap.

fix: cancellable in-flight multipart urql subscriptions

---

.size-limits.json
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx

This should make future refactoring easier since the updated tests no longer check calls to internal `QueryManager` methods.

Update tests that check calls to internal `QueryManager` methods

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report.api.md
.changeset/small-poems-rest.md
.size-limits.json
src/__tests__/refetchQueries.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts

Closes #10291
Don't `broadcastQueries` when a query is torn down. This should save a bit on performance by avoiding potentially lots of notifications to other queries purely because a query was removed.

Don't call `broadcastQueries` when a query is stopped

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report.api.md
.changeset/brave-moons-juggle.md
.size-limits.json
src/core/ApolloClient.ts

Closes #12584
Removes the `typeDefs` option from `ApolloClient`. This option was not used anywhere besides setting a property inside the `ApolloClient` instance.

Remove `typeDefs` option

---

.api-reports/api-report-core.api.md
.api-reports/api-report-link_core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/short-tomatoes-attend.md
.size-limits.json
src/core/ApolloClient.ts
src/core/QueryManager.ts
src/core/types.ts
src/core/watchQueryOptions.ts
src/link/core/types.ts
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/useMutation.ts
src/react/types/deprecated.ts
src/utilities/common/mergeOptions.ts

Closes #12582
With https://github.com/apollographql/apollo-client/pull/12576 in place, we prefer to use the `DefaultContext` type as the type used for `context` options throughout the client. `context` is global and shared with the link chain, so the existing `TContext` arg can be a detriment to the DX, especially if you're not careful to align the type in multiple places.
This change should help avoid those footguns and make it easier to work with a single context type throughout the client.

Remove `TContext` generic argument

---

.changeset/funny-boats-wink.md
.changeset/strong-rivers-fry.md

We removed `rootValue` in favor of `context` but I forgot to update the changesets so this corrects them before we release the next alpha.

Fix incorrect local state changets

---

.changeset/slimy-ants-bake.md
src/react/hooks/__tests__/useMutation.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

This feels like a logical next step after the changes in #12631, but arguments could be made in both the direction of the previous behaviour and the new one - I wanted to put up this PR for discussion, but we don't need to do this. (but if we wanted to, it would be breaking)

`useQuery`: only advance `previousData` if `data` changed

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report.api.md
.changeset/kind-crews-warn.md
.size-limits.json
src/core/ApolloClient.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts

This is a logical next step after #12647 and saves another 100 bytes, but I didn't want to add it to that PR, so I'm opening it separately.

remove `ObservableQuery.queryId`, return `Set` from `getObservableQueries`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report.api.md
.changeset/beige-kings-grow.md
.size-limits.json
src/__tests__/dataMasking.ts
src/__tests__/fetchMore.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts
src/core/__tests__/ObservableQuery.ts
src/core/networkStatus.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx

Fixes #12653
Adds `NetworkStatus.streaming` and sets `loading` to `true` when a `@defer` response is waiting for more chunks.

`loading` is now `true `when a response is still streaming. Adds `NetworkStatus.streaming`

---

src/core/__tests__/ObservableQuery.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx

Closes #12551
It appears this bug was fixed between now and `4.0.0-alpha.8` which exhibited the buggy behavior. Since this bug is already fixed, this PR adds tests to ensure we don't have any regressions for this behavior in future changes.

Add test for changing variables with error returned with `notifyOnNetworkStatusChange: false`

---

.changeset/great-scissors-jam.md
.size-limits.json
src/__tests__/local-state/resolvers.ts
src/core/ObservableQuery.ts
src/core/__tests__/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx

Supersedes #12021
Sets the initial `loading` state to `false` for a `cache-only` query when no data is in the cache.

Set `loading: false` with `cache-only` queries with no data in the cache

---

.api-reports/api-report-link_error.api.md
.api-reports/api-report-link_persisted-queries.api.md
.changeset/sharp-glasses-sneeze.md
.changeset/stupid-paws-jam.md
src/link/error/__tests__/index.ts
src/link/error/index.ts
src/link/persisted-queries/__tests__/persisted-queries.test.ts
src/link/persisted-queries/__tests__/react.test.tsx
src/link/persisted-queries/index.ts

Closes #12569
Updates `createPersistedQueryLink` to combine `graphQLErrors` and `networkError` properties into a single `error` property to match the rest of the client. `error` is of type `ErrorLike`.
The `response` property has also been removed in favor of accessing `data` from the `CombinedGraphQLErrors` instance.

Update persisted query link error handling to match the rest of the client

---

.size-limits.json
src/core/ObservableQuery.ts
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

As I was playing around with trying to use `observable.getCurrentResult` inside `useSyncExternalStore`, I found a couple places that could use a small bit of improvement. This is the result of those changes which reduces some bundle size in the process.

Minor improvements to `useQuery`/`ObservableQuery`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report.api.md
.changeset/mighty-carrots-bathe.md
.changeset/old-melons-double.md
.changeset/sixty-bears-bathe.md
.size-limits.json
src/__tests__/fetchMore.ts
src/core/ObservableQuery.ts
src/core/index.ts
src/core/watchQueryOptions.ts
src/react/hooks/useBackgroundQuery.ts
src/react/hooks/useLazyQuery.ts
src/react/hooks/useLoadableQuery.ts
src/react/hooks/useQuery.ts
src/react/hooks/useQueryRefHandlers.ts
src/react/internal/cache/QueryReference.ts
src/react/internal/types.ts

rework options & option handling for `ObservableQuery.fetchMore`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report.api.md
.changeset/clever-islands-talk.md
.changeset/four-tables-cheat.md
.changeset/lemon-pans-sit.md
.changeset/stupid-eagles-fetch.md
.size-limits.json
src/__tests__/fetchMore.ts
src/__tests__/refetchQueries.ts
src/core/ObservableQuery.ts
src/core/QueryManager.ts
src/core/__tests__/ApolloClient/general.test.ts
src/core/__tests__/ObservableQuery.ts
src/core/__tests__/fetchPolicies.ts
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useLazyQuery.ts

Fixes #11997
Throws an error when `fetchMore` is called on a `cache-only` query. Additionally a warning will be emitted when setting a poll interval on a `cache-only` query and polling will be cancelled.
`cache-only` queries are now excluded from `refetchQueries` when using `include: 'all' | 'active'` and when listed as a query in `include`.
`cache-only` queries are also excluded from `client.reFetchObservableQueries` when `includeStandby` is `true`.

Don't allow `fetchMore` or updates to polling for `cache-only` queries and exclude from `client.refetchQueries`

---

src/react/hooks/__tests__/useQuery.test.tsx

Supercedes https://github.com/apollographql/apollo-client/pull/12230
This will likely be solved by https://github.com/apollographql/apollo-client/pull/12556 so we'll add this test case to the test suite once #12556 is merged.

Add test for changing variables with `network-only` fetch policy

---

.changeset/tough-olives-fry.md
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/useQuery.ts

Fixes #11328
The core fixed this issue when we emitted a value after a `refetch` even when deep equal, but `useQuery` prevented that render from happening. Since we didn't rerender, the `variables` value returned from the hook was incorrect. This PR ensures that a `refetch` with a deep equal result when `notifyOnNetworkStatusChange` is `false` will rerender if variables have changed.

Ensure a `refetch` that changes variables and returns deep equal results rerenders

---

.changeset/kind-taxis-thank.md
.size-limits.json
src/__tests__/local-state/general.ts
src/local-state/LocalState.ts
src/local-state/__tests__/LocalState/base.test.ts
src/local-state/__tests__/LocalState/cache.test.ts

Fixes #12730
Remove the warning for a missing resolver when encountering an `@client` field that does not have a cache value. This is less confusing when `@client` fields are managed by `read` functions since local resolvers aren't required in order to use `@client` fields.

Don't warn for missing resolvers

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_components.api.md
.api-reports/api-report-react_context.api.md
.api-reports/api-report-react_hoc.api.md
.api-reports/api-report-react_hooks.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report-react_ssr.api.md
.api-reports/api-report-testing.api.md
.api-reports/api-report-testing_core.api.md
.api-reports/api-report-utilities.api.md
.api-reports/api-report.api.md
.changeset/popular-waves-drop.md
.size-limits.json
src/__tests__/dataMasking.ts
src/core/ApolloClient.ts
src/react/hooks/__tests__/useFragment.test.tsx
src/testing/react/MockedProvider.tsx

Adds `@deprecated` tags to options and methods on the `ApolloClient` constructor that are no longer supported. Adds runtime warnings for other change.

Add deprecations and warnings to `ApolloClient` options and methods

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report.api.md
.changeset/proud-walls-shave.md
integration-tests/pnpm-lock.yaml
integration-tests/vite/package.json
integration-tests/vite/src/App.tsx
integration-tests/vite/src/enhanceDataStates.ts
src/__tests__/ApolloClient.ts
src/cache/core/types/DataProxy.ts
src/core/QueryInfo.ts
src/core/index.ts
src/core/types.ts
src/react/hooks/__tests__/useBackgroundQuery.test.tsx
src/react/hooks/__tests__/useLazyQuery.test.tsx
src/react/hooks/__tests__/useLoadableQuery.test.tsx
src/react/hooks/__tests__/useQuery.test.tsx
src/react/hooks/__tests__/useSuspenseQuery.test.tsx
src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
src/testing/internal/markAsStreaming.ts

I first thought that we would be okay with only a `Streaming` override, but in the end we don't know what certain codegen setups might create, so we probably also need a `Complete` and `Partial` override.
That would also be an escape hatch for use cases like #12738, allowing users to introduce `DeepReadonly` themselves.
Since `Partial` is already a TS builtin and `PartialData` felt weird, I opted for a namespace that exports all three - the name `TData` is very much up for debate here.

also allow Complete and Partial datastate type overrides

---

.changeset/great-peaches-design.md
.size-limits.json
src/__tests__/ApolloClient.ts
src/__tests__/client.ts
src/core/ApolloClient.ts
src/react/hooks/__tests__/useFragment.test.tsx
src/react/hooks/__tests__/useSuspenseFragment.test.tsx
src/react/hooks/useFragment.ts
src/react/internal/cache/FragmentReference.ts

Closes #12745
Applies document transforms to `client.readQuery`, `client.readFragment`, `client.watchFragment`, `useFragment`, and `useSuspenseFragment`.

Apply document transforms on `client.read*` APIs

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-utilities_internal.api.md
.api-reports/api-report.api.md
.changeset/late-bottles-add.md
.size-limits.json
src/cache/inmemory/__tests__/entityStore.ts
src/cache/inmemory/entityStore.ts
src/cache/inmemory/inMemoryCache.ts
src/cache/inmemory/types.ts
src/utilities/internal/getStoreKeyName.ts

`InMemoryCache`: store fields with an empty object of optional arguments the same as fields without arguments

---

.api-reports/api-report-react.api.md
.changeset/heavy-ways-call.md
src/react/hooks/useMutation.ts

I discovered this when looking doing a pass through the docs.

Disallow `mutation` option in `mutate` callback returned from `useMutation`

---

.api-reports/api-report-link_http.api.md
.api-reports/api-report.api.md
.changeset/purple-eyes-divide.md
.size-limits.json
src/link/batch-http/__tests__/batchHttpLink.ts
src/link/http/HttpLink.ts
src/link/http/__tests__/HttpLink.ts

Discovered while working on #12819

Update `HttpLink` types for `fetchOptions` and `credentials`

---

docs/source/data/queries.mdx
docs/source/get-started.mdx
src/react/hooks/__tests__/useLazyQuery.test.tsx

Most of the work in this PR makes the documentation for `useLazyQuery` much more robust. Previously the section included a paragraph and a single example for using it. I've instead framed the hook as a way to execute queries in response to user interaction. I've also added more subsections that describe the capabilities of `useLazyQuery` much more in depth.
I also tweaks a couple things in the get started guide for accuracy.

Misc get started tweaks and more robust `useLazyQuery` documentation

---

.changeset/brave-pandas-battle.md
scripts/codemods/ac3-to-ac4/README.md
scripts/codemods/ac3-to-ac4/src/__tests__/imports.test.ts
scripts/codemods/ac3-to-ac4/src/__tests__/legacyEntryPoints.test.ts
scripts/codemods/ac3-to-ac4/src/index.ts
scripts/codemods/ac3-to-ac4/src/legacyEntrypoints.ts
scripts/codemods/ac3-to-ac4/src/util/entryPointAliases.ts
scripts/codemods/ac3-to-ac4/src/util/findImportDeclarationFor.ts
scripts/codemods/ac3-to-ac4/src/util/handleModuleRename.ts

Add a new `legacyEntryPoints` codemod transformation step.

---

CHANGELOG.md

Hi, while migrating from 3.14 to 4 and following the guide, I noticed the command was incorrect. 
fixes
```
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/apollo-client-codemod-migrate-3-to-4 - Not found
npm error 404
npm error 404  'apollo-client-codemod-migrate-3-to-4@*' is not in this registry.
```

docs: fix npx codemod command for Apollo Client migration

---

.changeset/hip-badgers-reply.md
.size-limits.json
src/cache/core/cache.ts
src/core/ApolloClient.ts
src/link/core/ApolloLink.ts

This should do it... look at the build output diff :)

restore `getMemoryInternals` access in dev builds

---

docs/source/migrating/apollo-client-4-migration.mdx

This was missing in the migration guide

Add section on change to `preloadQuery`

---

.api-reports/api-report-core.api.md
.api-reports/api-report-react.api.md
.api-reports/api-report-react_internal.api.md
.api-reports/api-report.api.md
.changeset/hip-mangos-hope.md
src/core/index.ts
src/react/hooks/internal/wrapHook.ts
src/react/index.ts
src/react/internal/index.ts

fix `local-rules/import-from-inside-other-export` where `/react/internals` imported directly from `/react`
This caused `react` to be pulled into a RSC bundle, resulting in apollographql/apollo-client-integrations#499

Fix accidental deep re-export from `/react` out of `/react/internals`

---

.api-reports/api-report-core.api.md
.api-reports/api-report.api.md
docs/source/api/core/ApolloClient.mdx
src/core/ApolloClient.ts
src/utilities/caching/sizes.ts

Found this while working on https://github.com/apollographql/apollo-client-devtools/pull/1607

Remove outdated information in doc blocks

---

src/react/hooks/useReactiveVar.ts

update docs for `useReactiveVar` import

---

.api-reports/api-report-cache.api.md
.api-reports/api-report-local-state.api.md
.api-reports/api-report.api.md
.changeset/flat-worms-notice.md
.changeset/perfect-crabs-smile.md
.changeset/shaggy-islands-yell.md
.changeset/unlucky-cooks-rhyme.md
.size-limits.json
src/__tests__/local-state/general.ts
src/cache/core/cache.ts
src/cache/inmemory/inMemoryCache.ts
src/core/QueryManager.ts
src/local-state/LocalState.ts
src/local-state/__tests__/LocalState/aliases.test.ts
src/local-state/__tests__/LocalState/async.test.ts
src/local-state/__tests__/LocalState/base.test.ts
src/local-state/__tests__/LocalState/cache.test.ts
src/local-state/__tests__/LocalState/context.test.ts
src/local-state/__tests__/LocalState/errors.test.ts
src/local-state/__tests__/LocalState/forcedResolvers.test.ts
src/local-state/__tests__/LocalState/fragments.test.ts
src/local-state/__tests__/LocalState/partialData.test.ts
src/local-state/__tests__/LocalState/rootValue.test.ts
src/local-state/__tests__/LocalState/subscriptions.test.ts
src/local-state/__tests__/LocalState/testUtils.ts

Closes #12930.
Better detect whether the cache can handle resolving a client field and warn if neither a local resolver or read function is defined. If a `read` function is defined, don't set a default value of `null` for the field to allow for the `read` function to set the value. This allows default parameters to work again.
This also adds a check for `no-cache` fetch policies and will warn if used with a `@client` field since the cache is not read. This fixes an issue where using a `no-cache` fetch policy would read from the cache to get the cache `diff` to resolve the field.

More robust handling of local state default value when read function is defined

---

.changeset/healthy-jokes-sing.md
src/link/subscriptions/__tests__/graphqlWsLink.ts
src/link/subscriptions/index.ts

Fixes #12946
Removes the `operationType` key in the payload sent by `GraphQLWsLink` which was causing issues with HotChocolate.

Filter `operationType` in payload of `GraphQLWsLink`

---

src/react/types/types.documentation.ts

Remove `ignoreResults` from MutationOptionsDocumentation and MutationResultDocumentation

---

docs/source/migrating/apollo-client-4-migration.mdx

@glasser pointed this out when upgrading an application to v4 which already had v3 installed.

Update npm install command for Apollo Client 4
